// Reklama: kdo z toho má užitek? – co po nás reklama chce, kdo ji zaplatil
// a jaké triky používá (známá postava, „jen dnes!“, „zdarma*“ s malým
// písmem, „9 z 10“, hračka natočená zblízka…). Na vyšších úrovních placená
// doporučení a reklamy ve hrách. Všechny značky a postavy jsou vymyšlené.
// Vysvětlení je zajímavost (ukáže se i po správné odpovědi).

import type { Spec } from '../../core/bank';
import type { Visual } from '../../core/types';
import { pevne, q, text } from './kriticke-common';

/** Tlačítka u otázek „Je to reklama, zpráva, nebo pohádka?“. */
const DRUHY = ['Reklama', 'Zpráva', 'Pohádka'];
const ASK_DRUH = 'Je to reklama, zpráva, nebo pohádka?';

function druh(key: string, ukazka: string, correct: 0 | 1 | 2, hints: string[], explain: string): Spec {
  return pevne(key, `„${ukazka}“ ${ASK_DRUH}`, DRUHY, correct, hints, explain, { speak: `${ukazka} ${ASK_DRUH}` });
}

// Vymyšlené reklamy (vizuál „reading“).
const LUPINKY: Visual = text('Jiskrolupínky', 'Nové Jiskrolupínky! Každé ráno plné energie. Křupou tak hlasitě, že probudí i draka. Kupte je ještě dnes!');
const MED: Visual = text('Na trhu', 'Knut prodává na trhu med. Volá na lidi: „Můj med je nejlepší na celém trhu! Kupte si sklenici!“');
const ROBODRAK: Visual = text('Robodrak 3000', 'Robodrak 3000 létá, svítí a mluví! Jen dnes za skvělou cenu. Kdo nemá Robodraka, přichází o zábavu!');
const VITAMINKY: Visual = text('Vitamínky Drakovitky', 'Slavná zpěvačka Lili Duhová říká: „Já jím každý den vitamínky Drakovitky. Proto zpívám tak krásně!“');
const MLZACEK: Visual = text('Plyšový drak Mlžáček', 'V reklamě sedí Mlžáček na posteli a je větší než polštář. V obchodě je krabice s Mlžáčkem jen o trochu větší než tvoje dlaň.');
const BUBLINATOR: Visual = text('Žvýkačka Bublinátor', 'Největší bubliny na světě!*\n*Podle našich zaměstnanců.');
const BARVOHRAD: Visual = text('Pastelky Barvohrad', '9 z 10 dětí kreslí nejraději pastelkami Barvohrad!*\n*Zeptali jsme se 10 dětí na naší kreslicí soutěži.');
const RYCHLOSKOKY: Visual = text('Boty Rychloskoky', 'S botami Rychloskoky poběžíš rychleji než vítr! Teď v nových barvách.');
const KOMETA: Visual = text('Hvězdné kuličky', 'Kapitán Kometa z tvého oblíbeného seriálu jí každé ráno Hvězdné kuličky. Buď {silná|silný} jako on!');
const LIMONADA: Visual = text('Limonáda Vikingský šum', 'Limonáda Vikingský šum má jahodovou příchuť. Láhev má 1 litr a stojí 35 Kč. Chutná skvěle, má krásnou barvu a je nejlepší na léto!');
const KULISACI: Visual = text('Sýrové kuličky Kulišáci', 'V každém balíčku najdeš jednu z 30 sběratelských kartiček! Sesbírej je všechny!');
const KOSTKOS_SLEVA: Visual = text('Stavebnice Kostkoš', 'Velký výprodej! Slevy až 70 %!');
const TICHOSLAP: Visual = text('Video: Hanka Hvězdička', 'Hanka ve videu ukazuje sluchátka Tichošlap: „Tahle sluchátka jsou nejlepší! Kupte si je přes můj odkaz.“\nPod videem: Spolupráce se značkou Tichošlap.');
const OVCI_OSTROV: Visual = text('Hra Ovčí ostrov', 'Hraj zdarma! Tvoje ovečky rostou pomalu? Kup si balíček 100 zlatých vajec jen za 199 Kč a porostou hned!');
const USMEVNIK: Visual = text('Zubní pasta Úsměvník', 'Doporučuje 9 z 10 zubařů!*\n*Průzkum mezi 20 zubaři, kteří s naší firmou spolupracují.');
const DZUS: Visual = text('Džus Slunoplod', '100 % přírodní chuť! Osvěží celou rodinu.');
const PRASEK: Visual = text('Prací prášek Jiskroprášek', 'Nový Jiskroprášek pere o 30 % bělejší!');
const KOSTKOS_ZDARMA: Visual = text('Stavebnice Kostkoš', 'Stavebnice Kostkoš zdarma!*\n*Při nákupu nad dva tisíce korun.');
const DRAHOKAMY: Visual = text('Obchod ve hře', 'Balíček 500 drahokamů: 249 Kč.\nKouzelný kůň: 400 drahokamů.');
const ODPOCET: Visual = text('Nabídka ve hře', 'Nabídka končí za 9:59… 9:58… 9:57…\nKup si teď Dračí brnění za 99 drahokamů!');
const MLZACEK_SLEVA: Visual = text('Plyšový drak Mlžáček', 'Původně 1200 Kč, teď jen 599 Kč! Takovou slevu už neuvidíš!');
const LIZATKA: Visual = text('Lízátka Duhomlsek', 'Malé balení: 3 lízátka za 30 Kč.\nVelké balení: 10 lízátek za 120 Kč.');
const PREDPLATNE: Visual = text('Aplikace Dračí příběhy', 'První týden zdarma! Potom 149 Kč každý měsíc, dokud předplatné nezrušíš.');
const HEBKOS: Visual = text('Krém Hebkoš', 'Vědecky ověřeno! S krémem Hebkoš máš hebké ruce celý den.');
const KOMETA_ZDARMA: Visual = text('Hvězdné kuličky', 'Kapitán Kometa volá: „Jen dnes! Hvězdné kuličky zdarma!* Rychle, než dojdou!“\n*Při nákupu tří balíčků.');

// ---------------------------------------------------------------------------
// L2 – co reklama chce, kdo ji platí a kdo má z chvály užitek

const L2: Spec[] = [
  q('lupinky-chce', 'Co chce reklama, abys {udělala|udělal}?', 'Koupit Jiskrolupínky',
    ['Sníst víc zeleniny', 'Jít dřív spát', 'Probudit draka'],
    ['Co se v reklamě nabízí?'],
    'Každá reklama chce, abychom něco koupili nebo udělali – tahle, abys {koupila|koupil} Jiskrolupínky. Hlasité křupání v ní má probudit chuť, i když zrovna nemáš hlad.',
    { visual: LUPINKY }),
  q('lupinky-zaplatil', 'Kdo tuhle reklamu nejspíš zaplatil?', 'Firma, která lupínky vyrábí',
    ['Paní učitelka', 'Tvoji rodiče', 'Knihovna'],
    ['Komu pomůže, když se lupínky budou prodávat?'],
    'Reklamu platí ten, kdo chce něco prodat. Když lidé lupínky koupí, vydělá firma, která je vyrábí – a část peněz z prodeje pak dá na další reklamy.',
    { visual: LUPINKY }),
  q('med-uzitek', 'Kdo má užitek z toho, že Knut svůj med chválí?', 'Knut, protože ho chce prodat',
    ['Včely', 'Ostatní prodavači', 'Nikdo'],
    ['Kdo dostane peníze, když si med koupíš?'],
    'Knut chválí svůj med, protože ho chce prodat. Když prodavač chválí vlastní zboží, nemusí to být pravda – ale nemusí to být ani lež. Proto se vyplatí ověřovat.',
    { visual: MED }),
  q('med-overit', 'Jak zjistíš, jestli je Knutův med opravdu dobrý?', 'Ochutnám ho a porovnám s jiným',
    ['Uvěřím Knutovi', 'Hned koupím všechen', 'Zeptám se Knuta ještě jednou'],
    ['Co můžeš udělat {sama|sám}?'],
    'Chválu od prodavače je dobré ověřit: ochutnat a porovnat s medem od jiných včelařů. Jak med chutná, záleží i na tom, z jakých květů ho včely nosily.',
    { visual: MED }),
  q('robodrak-dnes', 'Proč reklama říká „jen dnes“?', 'Aby lidé nakoupili hned, bez přemýšlení',
    ['Protože zítra hračky nebudou', 'Protože je dnes svátek', 'Aby ho nikdo nekoupil'],
    ['Jak se cítíš, když něco musíš stihnout hned?'],
    '„Jen dnes“ je trik: když spěcháš, méně přemýšlíš, jestli věc opravdu potřebuješ. Pomáhá jednoduché pravidlo – s nákupem počkat do zítřka.',
    { visual: ROBODRAK }),
  q('robodrak-zabava', 'Reklama tvrdí: „Kdo nemá Robodraka, přichází o zábavu.“ Je to pravda?', 'Ne, zábava jde mít i bez něj',
    ['Ano, bez Robodraka nic nebaví', 'Ano, v reklamě je vždy pravda', 'Ano, když je drahý'],
    ['Bavíš se někdy i bez nových hraček?'],
    'Reklama chce, aby sis {myslela|myslel}, že bez hračky budeš {smutná|smutný}. Zábava ale jde mít i bez ní – třeba venku s kamarády.',
    { visual: ROBODRAK }),
  q('vitaminky-zpevacka', 'Proč je v reklamě slavná zpěvačka?', 'Aby se ti výrobek víc líbil',
    ['Protože vitamínky vymyslela', 'Protože je lékařka', 'Aby byla reklama kratší'],
    ['Rozumí zpěvačka vitamínům?'],
    'Firma zpěvačce zaplatila, aby výrobek chválila. Lidé ji mají rádi, a tak se jim zalíbí i to, co ukazuje – odbornice na vitamíny ale není.',
    { visual: VITAMINKY }),
  q('vitaminky-zpev', 'Zpívá Lili Duhová krásně kvůli vitamínkům?', 'To se z reklamy nepozná',
    ['Ano, sama to řekla', 'Ano, vitamínky zlepšují hlas', 'Ano, jinak by to neříkala'],
    ['Co musela Lili dělat, aby se naučila zpívat?'],
    'Zpěvačky se zpívat učí dlouho a pilně. Že Lili pomohly vitamínky, jen říká v placené reklamě – důkaz to není.',
    { visual: VITAMINKY }),
  q('reklama-hudba', 'Proč v reklamách často hraje veselá hudba?', 'Aby se nám líbila a zůstala v hlavě',
    ['Aby byla reklama pravdivější', 'Aby se výrobek zlevnil', 'Protože bez hudby reklama nejde'],
    ['Pamatuješ si nějakou písničku z reklamy?'],
    'Veselá hudba nám zlepší náladu a krátká písnička z reklamy, znělka, se dobře pamatuje. Na tom, jestli je výrobek dobrý, ale nic nemění.'),
  q('mlzacek-velky', 'Proč vypadal Mlžáček v reklamě mnohem větší?', 'Natočili ho zblízka vedle malých věcí',
    ['V krabici se scvrkl', 'V obchodě je jiný drak', 'Televize všechno zvětší'],
    ['Jak vypadá věc, když ji natočíš hodně zblízka?'],
    'Hračky se v reklamách natáčejí zblízka a vedle malých věcí, aby vypadaly velké. V obchodě se proto vyplatí podívat, jak je hračka velká doopravdy.',
    { visual: MLZACEK }),
  q('reklama-kde', 'Kde všude můžeš potkat reklamu?', 'V televizi, na ulici i v mobilu',
    ['Jen v televizi', 'Jen v novinách', 'Nikde'],
    ['Rozhlédni se cestou do školy.'],
    'Reklamy jsou na plakátech, v televizi, v časopisech, v mobilu i ve hrách. Najdeš je i na tramvajích, na dresech sportovců nebo na obalech.'),
  q('proc-plati', 'Proč firmy platí za reklamu?', 'Aby lidé kupovali jejich výrobky',
    ['Aby lidem rozdávaly peníze', 'Aby lidé měli méně věcí', 'Protože to firmy musejí'],
    ['Co firma chce, aby lidé udělali?'],
    'Reklama stojí hodně peněz a firmy ji platí, protože doufají, že díky ní prodají víc. Z peněz za reklamy žije i spousta televizí a webů.'),
  q('hracka-chci', 'V reklamě uvidíš hračku a hned ji chceš. Co je dobré udělat?', 'Počkat a promyslet, jestli ji potřebuju',
    ['Hned ji chtít koupit', 'Utratit za ni všechny úspory', 'Věřit všemu z reklamy'],
    ['{Chtěla|Chtěl} bys ji i za týden?'],
    'Reklama umí přání rychle probudit. Když počkáš pár dní, poznáš, jestli hračku chceš opravdu, nebo jen kvůli reklamě.'),
  druh('druh-boty', 'Nové boty Rychloskoky! S nimi budeš nejrychlejší ve třídě.', 0,
    ['Chce ten text, abys něco {koupila|koupil}?'],
    'Text chválí boty a chce, abys je {koupila|koupil} – to dělá reklama. Slib, že budeš nejrychlejší ve třídě, ale žádné boty splnit nemůžou.'),
  druh('druh-snih', 'Včera v Brně napadlo deset centimetrů sněhu. Silničáři celou noc sypali silnice.', 1,
    ['Dozvíš se, co se opravdu stalo?'],
    'Text říká, co se stalo, kde a kdy, nic neprodává a nic si nevymýšlí – je to zpráva. Právě na otázky co, kde a kdy odpovídá každá dobrá zpráva.'),
  druh('druh-jablka', 'Byl jednou jeden drak, který spal na hromádce zlatých jablek.', 2,
    ['Jak začínají pohádky?'],
    '„Byl jednou jeden…“ je typický začátek pohádky. Zlatá jablka a drak jsou z příběhu.'),
  druh('druh-limonada', 'Limonáda Vikingský šum osvěží i draka! Teď ve velké láhvi.', 0,
    ['Chválí text nějaký výrobek?'],
    'Text chválí limonádu a láká, abys ji {koupila|koupil} – je to reklama. „Osvěží i draka“ je nadsázka, slib, který se nedá ověřit.'),
  druh('druh-tucnaci', 'V zoo se narodila dvě mláďata tučňáků. Zatím zůstávají s rodiči v pavilonu.', 1,
    ['Stalo se to opravdu?'],
    'Text popisuje skutečnou událost a nic neprodává – je to zpráva. Takové zprávy o mláďatech zoo často píše i na svém webu.'),
  druh('druh-princezna', 'Za sedmero horami žila princezna, která uměla mluvit s rybami.', 2,
    ['Umějí lidé mluvit s rybami?'],
    '„Za sedmero horami“ a mluvení s rybami patří do pohádky.'),
];

// ---------------------------------------------------------------------------
// L3 – hvězdička a malé písmo, „9 z 10“, „až“, sbírání a fakt × názor

const L3: Spec[] = [
  q('bublinator-pismo', 'Co prozrazuje malé písmo pod hvězdičkou?', 'Že to tvrdí jen lidé z firmy',
    ['Že to změřili vědci', 'Že bubliny jsou zdravé', 'Že to platí na celém světě'],
    ['Přečti si pozorně řádek s hvězdičkou.'],
    'Malé písmo prozradí, že „největší bubliny“ nikdo nezměřil – jen to tvrdí lidé, kteří pro firmu pracují.',
    { visual: BUBLINATOR }),
  q('bublinator-dukaz', 'Proč tvrzení zaměstnanců firmy není dobrý důkaz?', 'Chtějí, aby se žvýkačka prodávala',
    ['Neumějí dělat bubliny', 'Nikdy žvýkačku neviděli', 'Je jich moc'],
    ['Kdo má užitek z toho, když se žvýkačka prodá?'],
    'Zaměstnanci mají užitek z toho, když se žvýkačka prodává, a tak nejsou nestranní. Lepší důkaz by bylo porovnání bublin měřením.',
    { visual: BUBLINATOR }),
  q('barvohrad-deset', 'Proč „9 z 10 dětí“ v této reklamě moc neznamená?', 'Ptali se jen 10 dětí z vlastní soutěže',
    ['Protože 9 je malé číslo', 'Protože děti neumějí kreslit', 'Protože pastelky nejsou barevné'],
    ['Kolika dětí se ptali a kde?'],
    'Deset dětí z vlastní soutěže je malá a vybraná skupina. Z toho se nedá poznat, co mají rády děti v celé zemi.',
    { visual: BARVOHRAD }),
  q('barvohrad-test', 'Jak by se dalo poctivě zjistit, kterými pastelkami se kreslí nejlépe?', 'Dát mnoha dětem vyzkoušet různé pastelky',
    ['Uvěřit reklamě', 'Zeptat se prodavače Barvohradu', 'Koupit nejdražší'],
    ['Jak se dělá férové porovnání?'],
    'Poctivé porovnání: mnoho dětí vyzkouší různé pastelky a řekne, které se jim nejlépe kreslilo. Ještě férovější je, když děti nevědí, které pastelky jsou od koho.',
    { visual: BARVOHRAD }),
  q('rychloskoky-vitr', 'Je pravda, že v Rychloskocích poběžíš rychleji než vítr?', 'Ne, reklama přehání',
    ['Ano, jinak by to nenapsali', 'Ano, boty mají motor', 'Ano, když je obuješ naopak'],
    ['Jak rychle umí běžet člověk a jak rychle fouká vichr?'],
    'Reklamy často přehánějí, aby výrobek zněl úžasně. Žádné boty z tebe neudělají vichr – ten fouká rychleji, než jede auto ve městě.',
    { visual: RYCHLOSKOKY }),
  q('kometa-proc', 'Proč reklama ukazuje hrdinu z oblíbeného seriálu?', 'Aby děti chtěly být jako on',
    ['Protože kuličky vymyslel', 'Protože kuličky jsou z vesmíru', 'Aby byla reklama kratší'],
    ['Co by děti udělaly, aby byly jako jejich hrdina?'],
    'Děti mají Kapitána Kometu rády a chtějí být jako on. Reklama doufá, že si proto koupí i jeho kuličky.',
    { visual: KOMETA }),
  q('kometa-silna', 'Budeš po Hvězdných kuličkách {silná|silný} jako Kapitán Kometa?', 'Ne, to reklama jen slibuje',
    ['Ano, hrdinové nelžou', 'Ano, když jich sníš hodně', 'Ano, kuličky jsou kouzelné'],
    ['Je Kapitán Kometa skutečný člověk?'],
    'Kapitán Kometa je postava ze seriálu a silný je díky příběhu. Sílu dává pohyb, spánek a pestré jídlo, ne jedny kuličky.',
    { visual: KOMETA }),
  q('limonada-fakt', 'Co z reklamy je fakt?', 'Stojí 35 Kč',
    ['Chutná skvěle', 'Má krásnou barvu', 'Je nejlepší na léto'],
    ['Co se dá ověřit na cenovce?'],
    'Cenu může ověřit každý. „Chutná skvěle“, „krásná barva“ a „nejlepší na léto“ jsou názory, které mají lákat.',
    { visual: LIMONADA }),
  q('limonada-nazor', 'Co z reklamy je názor?', 'Chutná skvěle',
    ['Láhev má 1 litr', 'Stojí 35 Kč', 'Má jahodovou příchuť'],
    ['Co by každý mohl vidět jinak?'],
    'Jestli limonáda chutná skvěle, posoudí každý sám. Objem, cena a příchuť se dají ověřit.',
    { visual: LIMONADA }),
  q('kulisaci-proc', 'Proč firma dává do balíčků sběratelské kartičky?', 'Aby lidé kupovali víc balíčků',
    ['Aby byly kuličky zdravější', 'Aby děti uměly počítat do třiceti', 'Protože kartičky nic nestojí'],
    ['Co musíš udělat, abys {měla|měl} všechny kartičky?'],
    'Kdo chce mít všechny kartičky, musí kupovat další a další balíčky. A to je přesně to, co firma chce.',
    { visual: KULISACI }),
  q('kulisaci-kolik', 'Kolik balíčků musíš koupit, abys {měla|měl} jistě všech 30 kartiček?', 'Nedá se to říct, kartičky se opakují',
    ['Přesně 30', 'Přesně 10', 'Jen jeden'],
    ['Může ti padnout stejná kartička dvakrát?'],
    'Kartičky se v balíčcích opakují, takže 30 balíčků jistě nestačí. Matematici spočítali, že když má každá kartička stejnou šanci, je potřeba v průměru asi 120 balíčků.',
    { visual: KULISACI }),
  q('kostkos-az', 'Co znamená slovo „až“ v nápisu „Slevy až 70 %“?', 'Jen něco je o 70 % levnější',
    ['Všechno je o 70 % levnější', 'Všechno je zdarma', 'Sleva začne až zítra'],
    ['Znamená „až“ u všeho, nebo jen u něčeho?'],
    '„Až 70 %“ znamená, že tak velkou slevu má jen něco – často jen pár věcí. Ostatní věci jsou zlevněné méně, nebo vůbec ne.',
    { visual: KOSTKOS_SLEVA }),
  q('male-pismo', 'Proč bývá důležitá informace v reklamě napsaná malým písmem?', 'Aby si jí lidé nevšimli',
    ['Protože je nepodstatná', 'Aby ji lidé hned uviděli', 'Aby se lépe četla'],
    ['Co by se stalo, kdyby byla napsaná velkými písmeny?'],
    'Malým písmem se píše to, co by lidi mohlo od nákupu odradit. Proto se ho vyplatí přečíst.'),
  druh('druh-hasici', 'Hasiči v neděli snesli ze stromu kočku, která se bála slézt dolů.', 1,
    ['Prodává ten text něco?'],
    'Text popisuje, co se stalo, a nic neprodává – je to zpráva. Kočky na strom vylezou snadno, ale dolů hlavou napřed lézt neumějí, a tak někdy potřebují pomoc.'),
  druh('druh-pekarna', 'Pekárna U Vikinga dnes otevřela novou prodejnu. Přijďte ochutnat naše skvělé rohlíky!', 0,
    ['Přečti pozorně druhou větu.'],
    'Začátek zní jako zpráva, ale pak text láká na „naše skvělé rohlíky“. Pekárna chce prodávat – je to reklama.'),
  druh('druh-brokolice', 'Kouzelná brokolice splnila chlapci přání a odnesla ho na obláček.', 2,
    ['Umějí brokolice kouzlit?'],
    'Kouzelná brokolice a let na obláčku jsou z pohádky.'),
  druh('druh-bourky', 'Meteorologové varují: zítra odpoledne přijdou silné bouřky.', 1,
    ['Kdo to říká a proč?'],
    'Meteorologové oznamují, co naměřili a předpověděli. Nic neprodávají – je to zpráva.'),
  druh('druh-usmevnik', 'Podle vědců je naše zubní pasta Úsměvník nejlepší. Kupte si ji v každé drogerii!', 0,
    ['Kdo asi ten text napsal a co chce?'],
    'Text napsala firma o své pastě a chce ji prodat. I když se odvolává na vědce, je to reklama – a neříká, kteří vědci to byli.'),
];

// ---------------------------------------------------------------------------
// L4 – placená doporučení, reklamy ve hrách, průzkumy a slova bez obsahu

const L4: Spec[] = [
  q('hanka-spoluprace', 'Co znamená nápis „Spolupráce se značkou Tichošlap“?', 'Firma Hance za video zaplatila',
    ['Hanka sluchátka vyrobila', 'Hanka si je koupila sama', 'Video je zpráva z novin'],
    ['Proč by firma s Hankou spolupracovala?'],
    'Spolupráce znamená, že firma Hance zaplatila nebo jí dala sluchátka, aby je ve videu ukázala. Je to reklama.',
    { visual: TICHOSLAP }),
  q('hanka-odkaz', 'Proč chce Hanka, abys {kupovala|kupoval} přes její odkaz?', 'Dostane z každého nákupu peníze',
    ['Aby byl nákup levnější', 'Protože jiný obchod není', 'Aby se sluchátka nerozbila'],
    ['Kdo pozná, že nákup přišel přes Hančin odkaz?'],
    'Obchod pozná, že nákup přišel přes Hančin odkaz, a zaplatí jí za něj. Proto má Hanka užitek z toho, když sluchátka chválí.',
    { visual: TICHOSLAP }),
  q('hanka-verit', 'Komu bys nejvíc {věřila|věřil}, že jsou sluchátka dobrá?', 'Nezávislému testu více sluchátek',
    ['Hance, protože je slavná', 'Reklamě firmy Tichošlap', 'Tomu, kdo nejvíc křičí'],
    ['Kdo nemá užitek z toho, jestli se sluchátka prodají?'],
    'Nezávislý test porovná víc sluchátek a nikdo ho neplatí za chválu. Hanka i firma mají z prodeje užitek.',
    { visual: TICHOSLAP }),
  q('placene-oznaceni', 'Proč má být placené video označené slovem „reklama“ nebo „spolupráce“?', 'Aby diváci věděli, že je zaplacené',
    ['Aby bylo video delší', 'Aby se líbilo víc lidem', 'Aby ho nikdo neviděl'],
    ['{Věřila|Věřil} bys videu stejně, kdybys {věděla|věděl}, že je zaplacené?'],
    'Diváci mají vědět, že jde o reklamu, a ne o obyčejný názor. Pak se sami rozhodnou, jak moc chvále věřit.'),
  q('ovce-zdarma', 'Je hra Ovčí ostrov opravdu úplně zdarma?', 'Stáhnout jde zdarma, ale prodává věci',
    ['Ano, nic v ní nestojí peníze', 'Ne, stažení stojí 199 Kč', 'Ano, zlatá vejce jsou jen ozdoba'],
    ['Co ti hra nabízí za 199 Kč?'],
    'Hru stáhneš zdarma, ale uvnitř ti nabízí zlatá vejce za skutečné peníze. Tak si hra na sebe vydělává.',
    { visual: OVCI_OSTROV }),
  q('ovce-pomalu', 'Proč ve hře ovečky rostou schválně pomalu?', 'Aby hráči chtěli koupit zlatá vejce',
    ['Protože rychleji to hra neumí', 'Protože je hra rozbitá', 'Aby hráči hru rychle dohráli'],
    ['Co reklama nabízí, aby ovečky rostly rychleji?'],
    'Tvůrci hry nastavili pomalý růst schválně. Čekání tě má otrávit natolik, abys {zaplatila|zaplatil} za zrychlení.',
    { visual: OVCI_OSTROV }),
  q('hra-reklama-odmena', 'Hra ti nabízí: „Podívej se na reklamu a dostaneš 5 drahokamů.“ Proč to dělá?', 'Firma hře platí za tvé sledování',
    ['Hra tě má prostě ráda', 'Drahokamy nic nestojí', 'Aby tě hra nudila'],
    ['Kdo platí za to, že reklamu uvidíš?'],
    'Firma z reklamy platí hře za každé zhlédnutí. Drahokamy jsou odměna, abys reklamu {sledovala|sledoval}.'),
  q('usmevnik-pruzkum', 'Co je na průzkumu mezi zubaři podezřelé?', 'Zubaři s firmou spolupracují',
    ['Zubaři nerozumějí zubům', 'Devět je víc než deset', 'Pasta má hezkou barvu'],
    ['Přečti si malé písmo.'],
    'Zubaři, kteří s firmou spolupracují, mají z prodeje užitek. Poctivý průzkum by se ptal mnoha náhodně vybraných zubařů.',
    { visual: USMEVNIK }),
  q('dzus-prirodni', 'Znamená „100 % přírodní chuť“, že je džus jen z ovoce?', 'To se z reklamy poznat nedá',
    ['Ano, určitě je jen z ovoce', 'Ano, v reklamě to tak stojí', 'Ano, protože je žlutý'],
    ['Píše se tam, z čeho je džus, nebo jak chutná?'],
    'Slova „přírodní chuť“ znějí dobře, ale nic přesného neříkají. Co v džusu opravdu je, prozradí složení na obalu.',
    { visual: DZUS }),
  q('slozeni', 'Kde se dozvíš, co je v džusu opravdu?', 'Ve složení na obalu',
    ['V reklamě', 'Na plakátu s džusem', 'V písničce z reklamy'],
    ['Co musí být podle pravidel napsané na každém obalu?'],
    'Na obalu musí být složení – seznam všeho, co v džusu je. Je seřazené podle toho, čeho je ve výrobku nejvíc, takže první věc v seznamu je v něm hlavní.'),
  q('prasek-srovnani', 'Co v reklamě chybí?', 'S čím se prášek porovnává',
    ['Jméno prášku', 'Slovo „nový“', 'Údaj o bělosti'],
    ['Bělejší než co?'],
    '„O 30 % bělejší“ nic neznamená, když nevíme, s čím se prášek srovnává. Se starým práškem, s jiným, nebo s praním bez prášku? Takové tvrzení se nedá ověřit.',
    { visual: PRASEK }),
  q('kostkos-zdarma', 'Je stavebnice Kostkoš opravdu zdarma?', 'Ne, musíš nejdřív hodně utratit',
    ['Ano, každý ji dostane', 'Ano, hvězdička nic neznamená', 'Ne, stojí přesně dva tisíce'],
    ['Přečti si malé písmo pod hvězdičkou.'],
    'Stavebnici dostaneš jen tehdy, když nakoupíš za víc než dva tisíce korun. „Zdarma“ s hvězdičkou často zdarma není.',
    { visual: KOSTKOS_ZDARMA }),
  q('cena-99', 'Proč je cena 99 Kč, a ne 100 Kč?', 'Aby se zdála menší',
    ['Protože stokoruna neexistuje', 'Protože 99 je hezčí číslo', 'Aby prodavač dostal víc'],
    ['Čím začíná číslo 99 a čím 100?'],
    'Rozdíl je jen koruna, ale 99 začíná devítkou, a tak se cena zdá „pod stovkou“. U nás se takovým cenám říká baťovské – podle obuvníka Tomáše Bati, který je rád používal.'),
  q('reklama-sleduje', 'Po hledání bot na internetu ti začnou chodit reklamy na boty. Proč?', 'Reklamní firmy sledují, co hledáš',
    ['Je to náhoda', 'Boty tě hledají', 'Počítač se nudí'],
    ['Co o tobě internet ví, když něco hledáš?'],
    'Reklamní firmy zaznamenávají, co hledáš a na co klikáš. Pak ti ukazují reklamy, na které nejspíš klikneš.'),
  q('otazky-reklama', 'Na co je dobré se zeptat, když vidíš reklamu?', 'Kdo ji zaplatil a co po mně chce',
    ['Jakou má barvu', 'Jak dlouho trvá', 'Kolik v ní hraje lidí'],
    ['Na co se ptá Hádankář mlžný?'],
    'Kdo reklamu zaplatil a co po tobě chce – tyhle dvě otázky odhalí většinu reklamních triků.'),
  druh('druh-clanek', 'Pět důvodů, proč jsou boty Rychloskoky nejlepší. Článek vznikl ve spolupráci s firmou Rychloskoky.', 0,
    ['Kdo se na článku podílel?'],
    'Vypadá to jako článek, ale připravila ho firma, která boty prodává. Je to reklama převlečená za článek.'),
  druh('druh-voda', 'Obec oznamuje, že v úterý nepoteče voda od 8 do 12 hodin kvůli opravě potrubí.', 1,
    ['Chce ten text něco prodat?'],
    'Obec oznamuje, co se stane a proč. Nic neprodává – je to zpráva.'),
  druh('druh-soutez', 'Napiš nám, proč máš {ráda|rád} lízátka Duhomlsek, a vyhraj roční zásobu!', 0,
    ['Kdo soutěž pořádá a proč?'],
    'Soutěž pořádá firma, aby lidé mysleli na její lízátka a mluvili o nich. I soutěž může být reklama.'),
];

// ---------------------------------------------------------------------------
// L5 – triky ve hrách a na internetu, cena za kus, předplatné a údaje

const L5: Spec[] = [
  q('drahokamy-koruny', 'Proč hra neukazuje cenu koně rovnou v korunách?', 'Aby nebylo vidět, kolik to stojí',
    ['Protože koně se v korunách neprodávají', 'Protože drahokamy jsou zdarma', 'Aby byla hra kratší'],
    ['Kolik korun stojí jeden drahokam?'],
    'Drahokamy zakryjí, že platíš skutečnými penězi. Kůň za 400 drahokamů zní levněji, než kdyby hra napsala, že stojí skoro 200 Kč.',
    { visual: DRAHOKAMY }),
  q('drahokamy-zbytek', 'Kolik drahokamů ti zbude, když koupíš balíček a za něj koně?', '100 drahokamů',
    ['Žádný', '400 drahokamů', '500 drahokamů'],
    ['Kolik drahokamů koupíš a kolik zaplatíš za koně?'],
    '500 − 400 = 100. Na dalšího koně ti zbytek nestačí, a tak tě láká koupit další balíček. I to je trik.',
    { visual: DRAHOKAMY }),
  q('odpocet', 'Proč hra ukazuje odpočítávání?', 'Aby hráč nakoupil ve spěchu',
    ['Aby hráč věděl, kolik je hodin', 'Aby se hra hrála rychleji', 'Protože hra šetří čas'],
    ['Jak se rozhoduješ, když na tebe tlačí čas?'],
    'Odpočítávání vyvolá pocit, že musíš jednat hned. Ve spěchu se hůř přemýšlí, jestli věc opravdu chceš.',
    { visual: ODPOCET }),
  q('posledni-kusy', 'E-shop píše: „Poslední 3 kusy! Právě si je prohlíží 12 lidí.“ Co tím chce?', 'Aby ses {bála|bál}, že ti to uteče',
    ['Aby ti řekl přesný počet lidí', 'Aby tě od nákupu odradil', 'Aby ti dal slevu na zítra'],
    ['Jak se cítíš, když něčeho zbývá málo?'],
    'Když něčeho „zbývá málo“, bojíme se, že o to přijdeme, a kupujeme bez rozmýšlení. Jestli je to pravda, navíc nemůžeš ověřit.'),
  q('puvodni-cena', 'Co bys {měla|měl} ověřit, než uvěříš, že je to velká sleva?', 'Za kolik se drak dřív opravdu prodával',
    ['Jakou barvu má cenovka', 'Jestli je drak plyšový', 'Jestli je 599 menší než 1200'],
    ['Může být „původní cena“ vymyšlená?'],
    'Obchod může napsat vysokou „původní“ cenu, za kterou se drak nikdy neprodával. Porovnej ceny v jiných obchodech a dřívější ceny.',
    { visual: MLZACEK_SLEVA }),
  q('lizatka-vyhodnejsi', 'Které balení lízátek je výhodnější?', 'Malé balení',
    ['Velké balení', 'Obě stejně', 'To se spočítat nedá'],
    ['Kolik stojí jedno lízátko v každém balení?'],
    'V malém balení stojí lízátko 30 : 3 = 10 Kč, ve velkém 120 : 10 = 12 Kč. Větší balení nemusí být výhodnější – vyplatí se to spočítat.',
    { visual: LIZATKA }),
  q('predplatne-zapomenes', 'Co se stane, když na zrušení předplatného zapomeneš?', 'Každý měsíc se zaplatí 149 Kč',
    ['Aplikace se sama smaže', 'Nic, pořád je zdarma', 'Zaplatí se jen jednou'],
    ['Přečti si druhou větu.'],
    'Zkušební týden zdarma se sám změní v placené předplatné. Firmy počítají s tím, že lidé na zrušení zapomenou.',
    { visual: PREDPLATNE }),
  q('aplikace-kdo-plati', 'Aplikace je zdarma, ale ukazuje hodně reklam. Kdo její tvůrce platí?', 'Firmy, které v ní mají reklamy',
    ['Nikdo, tvůrci pracují zdarma', 'Stát', 'Hráči za každé spuštění'],
    ['Z čeho mají tvůrci peníze, když aplikace nic nestojí?'],
    'Tvůrcům platí firmy za reklamy, které v aplikaci uvidíš. Tvoje pozornost je vlastně to, co se prodává.'),
  q('hebkos-overeno', 'Na co by ses {měla|měl} zeptat, když reklama píše „vědecky ověřeno“?', 'Kdo to ověřil a jak',
    ['Jakou barvu má krém', 'Jestli krém voní', 'Kolik stojí doprava'],
    ['Stačí napsat „vědecky“, aby to byla pravda?'],
    'Slova „vědecky ověřeno“ může napsat kdokoli. Důležité je, kdo ověření dělal, jak a jestli ho nezaplatila sama firma.',
    { visual: HEBKOS }),
  q('vsichni-maji', 'Reklama říká: „Všechny děti už Robodraka mají. Nezůstaň pozadu!“ Jaký trik používá?', 'Hraje na strach, že budeš {jiná|jiný}',
    ['Říká přesný počet dětí', 'Vysvětluje, jak hračka funguje', 'Porovnává cenu s jinými'],
    ['Je pravda, že ho mají úplně všechny děti?'],
    'Reklama hraje na strach, že budeš mezi kamarády {jiná|jiný}. Přitom ho určitě nemají všechny děti – a nevadí to.'),
  q('sponzorovano', 'Při hledání „nejlepší pastelky“ má první odkaz nálepku Sponzorováno. Co to znamená?', 'Firma zaplatila, aby byla první',
    ['Je to nejlepší výsledek', 'Vybrali ho učitelé', 'Je to náhoda'],
    ['Co znamená slovo „sponzor“?'],
    'Sponzorovaný odkaz je reklama – firma zaplatila, aby se ukázala nahoře. Nejlepší být nemusí.'),
  q('hodnoceni', 'E-shop ukazuje u hračky jen samá nejlepší hodnocení. Proč být {opatrná|opatrný}?', 'Prodejce je mohl vybrat nebo napsat',
    ['Pět hvězd je málo', 'Hodnocení píšou jen děti', 'Hvězdičky se nedají přečíst'],
    ['Kdo má užitek z toho, že hodnocení jsou hezká?'],
    'Prodejce může horší hodnocení schovat nebo si hezká nechat napsat. Pomůže přečíst si recenze i jinde.'),
  q('kometa-trik', 'Který trik tahle reklama NEPOUŽÍVÁ?', 'Porovnání s jinými výrobky',
    ['Známou postavu', 'Spěch', 'Zdarma s hvězdičkou'],
    ['Najdi v reklamě všechny triky, které znáš.'],
    'Reklama má známou postavu, spěch („jen dnes“, „než dojdou“) i „zdarma“ s hvězdičkou. S jinými výrobky nic neporovnává.',
    { visual: KOMETA_ZDARMA, speak: 'Který trik tahle reklama nepoužívá?' }),
  q('minihra', 'Ve hře se objeví mini-hra „Pomoz medvídkovi najít Jiskrolupínky!“ Co to je?', 'Reklama převlečená za hru',
    ['Nová úroveň bez reklamy', 'Zpráva od kamarádky', 'Pohádka'],
    ['Co je v mini-hře hlavní věc, kterou hledáš?'],
    'Mini-hra s lupínky je reklama: při hraní si jméno výrobku zapamatuješ, i když si toho ani nevšimneš.'),
  q('soutez-udaje', 'Soutěž o tablet chce tvoje jméno, adresu a telefon rodičů. Co uděláš?', 'Nejdřív se zeptám rodičů',
    ['Hned všechno vyplním', 'Vyplním údaje kamarádky', 'Pošlu i svou fotku'],
    ['Komu tvoje údaje dáváš?'],
    'Údaje o tobě mají cenu – firmy je sbírají a využívají. Než je někam napíšeš, poraď se s rodiči.'),
  q('tajemna-truhla', 'Ve hře prodávají tajemnou truhlu. Může v ní být vzácný drak, nebo jen kamínek. Proč je to nevýhodné?', 'Utratíš hodně a dostaneš obyčejné věci',
    ['Truhly jsou vždycky prázdné', 'Vzácného draka dostane každý', 'Truhla se nedá otevřít'],
    ['Víš předem, co za své peníze dostaneš?'],
    'Za truhlu zaplatíš, ale nevíš, co v ní bude. Vzácné věci padají málokdy, a tak lidé kupují další a další truhly.'),
  q('kolo-vyber', 'Jak nejlépe vybrat nové kolo, aby tě reklama neoklamala?', 'Porovnat víc kol a nezávislé testy',
    ['Vybrat to z nejveselejší reklamy', 'Vybrat to, co chválí fotbalista', 'Koupit nejdražší'],
    ['Kdo nemá užitek z toho, které kolo si koupíš?'],
    'Nejlépe pomůže porovnání a testy od lidí, kteří z prodeje nic nemají. Veselá reklama ani slavná tvář o kvalitě nic neřeknou.'),
  q('zeleny-obal', 'Obal je zelený a má na sobě lístečky. Znamená to, že je výrobek šetrný k přírodě?', 'Ne, barva obalu nic nedokazuje',
    ['Ano, zelená znamená přírodu', 'Ano, lístečky to dokazují', 'Ano, když je obal hezký'],
    ['Může mít zelený obal kdokoli?'],
    'Zelenou barvu a lístečky může na obal dát kdokoli. Jestli je výrobek šetrný k přírodě, se pozná podle ověřených značek a složení.'),
];

export const reklamaBanks = { 2: L2, 3: L3, 4: L4, 5: L5 };
