// Fakt, nebo názor? – fakt se dá ověřit a platí, názor říká, co si někdo
// myslí nebo co se mu líbí (nejlepší, krásný, nudný, super…). Nepravdivá
// ověřitelná tvrzení sem nepatří – ta jsou v „Mýtus, nebo pravda?“.
// L3–L4: věty, ve kterých je fakt i názor, a slova, která názor prozrazují.

import type { Spec } from '../../core/bank';
import { fakt, q } from './kriticke-common';

/** Možnosti u otázek „Která část věty…?“ – celá věta. */
const CELA_FAKT = 'Celá věta je fakt';
const CELA_NAZOR = 'Celá věta je názor';

// ---------------------------------------------------------------------------
// L1 – jasná fakta a názory se slovy jako nejlepší, nejhezčí, nudný

const L1: Spec[] = [
  fakt('pes-nohy', 'Pes má čtyři nohy.', true,
    ['Dá se to spočítat?'],
    'Dá se to ověřit – stačí se na psa podívat a nohy spočítat.'),
  fakt('tyden-dny', 'Týden má sedm dní.', true,
    ['Podívej se do kalendáře.'],
    'Ověříš to v kalendáři: pondělí, úterý, středa, čtvrtek, pátek, sobota a neděle.'),
  fakt('snih-taje', 'Když je nad nulou, sníh taje.', true,
    ['Dá se to vyzkoušet s teploměrem a miskou sněhu?'],
    'Dá se to pozorovat venku i v kuchyni: když teploměr ukazuje víc než nula stupňů, sníh se mění ve vodu. Každému to dopadne stejně.'),
  fakt('ryby-voda', 'Ryby žijí ve vodě.', true,
    ['Kde ryby potkáš?'],
    'Dá se to pozorovat v rybníce, v řece, v moři i v akváriu.'),
  fakt('citron-kysely', 'Citron je kyselý.', true,
    ['Dá se to ověřit ochutnáním?'],
    'Ověříš to ochutnáním a chemici by to změřili – v citronu je kyselina citronová. Kyselý je pro každého, i pro toho, kdo ho má rád.'),
  fakt('rok-mesice', 'Rok má dvanáct měsíců.', true,
    ['Spočítej měsíce od ledna do prosince.'],
    'Ověříš to v kalendáři: od ledna do prosince je to dvanáct měsíců.'),
  fakt('led-voda', 'Led je zmrzlá voda.', true,
    ['Co se stane, když dáš vodu do mrazáku?'],
    'Dá se to vyzkoušet: voda v mrazáku zmrzne na led a led v teple zase roztaje na vodu.'),
  fakt('kolo-dve', 'Jízdní kolo má dvě kola.', true,
    ['Spočítej kola na kole.'],
    'Stačí se podívat a spočítat. Proto se mu říká i bicykl – „bi“ znamená dva.'),
  fakt('kravy-mleko', 'Krávy dávají mléko.', true,
    ['Kde se bere mléko v obchodě?'],
    'Ověříš to na statku: krávy se dojí a jejich mléko pak koupíš v obchodě.'),
  fakt('vcely-med', 'Včely vyrábějí med.', true,
    ['Zeptej se včelaře.'],
    'Ověříš to u včelaře: med vytáčí z plástů, které naplnily včely.'),
  fakt('hrebik-pericko', 'Železný hřebík je těžší než peříčko.', true,
    ['Dá se to zvážit?'],
    'Dá se to ověřit na váze nebo v dlaních. Na tom, co se komu víc líbí, to nezáleží.'),
  fakt('tucnaci-plavou', 'Tučňáci umějí plavat.', true,
    ['Viděla jsi tučňáky v zoo?'],
    'Dá se to pozorovat v zoo i ve filmech z přírody: tučňáci pod vodou rychle plavou.'),
  fakt('jahody-nejlepsi', 'Jahody jsou nejlepší ovoce.', false,
    ['Mají všichni nejraději stejné ovoce?'],
    'Slovo „nejlepší“ prozrazuje, co si někdo myslí. Jeden má nejraději jahody, druhý banány – a oba mají právo na svůj názor.'),
  fakt('zima-nejhezci', 'Zima je nejhezčí roční období.', false,
    ['Dá se změřit, co je nejhezčí?'],
    'Co je nejhezčí, si každý myslí jinak. Někdo miluje sníh, jiný léto. Změřit se to nedá.'),
  fakt('psi-nejlepsi', 'Psi jsou nejlepší zvířata.', false,
    ['Co by řekl kamarád, který má kočku?'],
    'Kamarád s kočkou by řekl něco jiného. Slovo „nejlepší“ vyjadřuje názor.'),
  fakt('modra-krasna', 'Modrá je nejkrásnější barva.', false,
    ['Má každý rád stejnou barvu?'],
    'Krása se nedá změřit. Každý má rád jinou barvu, a tak je to názor.'),
  fakt('kresleni-zabava', 'Kreslení je větší zábava než zpívání.', false,
    ['Baví všechny stejné věci?'],
    'Co koho baví, je názor. Někdo raději kreslí, jiný zpívá.'),
  fakt('polevka-vyborna', 'Rajská polévka je výborná.', false,
    ['Chutná všem stejné jídlo?'],
    'Chuť má každý jinou. Slovo „výborná“ říká, co si myslí ten, kdo to říká.'),
  fakt('pohadka-nudna', 'Tahle pohádka je nudná.', false,
    ['Nudí se u pohádky všichni stejně?'],
    'Jednoho pohádka nudí a druhého baví. „Nudná“ je názor.'),
  fakt('kotata-roztomila', 'Koťátka jsou nejroztomilejší zvířátka.', false,
    ['Dá se roztomilost spočítat?'],
    'Roztomilost se nedá změřit ani spočítat. Je to názor – i když ho má hodně lidí.'),
  fakt('dest-otravny', 'Déšť je otravný.', false,
    ['Co by na déšť řekl zahrádkář nebo žába?'],
    'Někomu déšť vadí, ale zahrádkář nebo žába se z něj radují. Je to názor.'),
  fakt('lode-krasne', 'Vikingské lodě jsou krásné.', false,
    ['Líbí se všem stejné věci?'],
    'Co je krásné, posoudí každý po svém. Krása se nedá změřit.'),
];

// ---------------------------------------------------------------------------
// L2 – fakta z kalendáře, mapy a přírody, názory bez slova „nej“

const L2: Spec[] = [
  fakt('praha-hlavni', 'Praha je hlavní město České republiky.', true,
    ['Dá se to najít v atlase?'],
    'Ověříš to v atlase, v učebnici nebo na mapě. Platí to pro všechny, ať se jim Praha líbí, nebo ne.'),
  fakt('hodina-minuty', 'Hodina má šedesát minut.', true,
    ['Podívej se na hodiny.'],
    'Ověříš to na hodinách: velká ručička oběhne za hodinu celý ciferník a projde šedesát minut.'),
  fakt('sovy-noc', 'Většina sov se vydává za potravou v noci.', true,
    ['Kdo sovy pozoroval?'],
    'Přírodovědci sovy pozorovali: většina z nich hledá potravu za šera a v noci. Dá se to ověřit.'),
  fakt('brokolice-zelenina', 'Brokolice je zelenina.', true,
    ['Kde brokolice leží v obchodě?'],
    'Najdeš to v každé knize o zelenině. Jestli ti brokolice chutná, to už je názor.'),
  fakt('mrkev-zem', 'Mrkev roste pod zemí.', true,
    ['Viděla jsi mrkev na zahradě?'],
    'Ověříš to na zahradě: nad zemí je vidět jen zelená nať, oranžový kořen je schovaný v hlíně.'),
  fakt('mesic-ve-dne', 'Měsíc je někdy vidět i ve dne.', true,
    ['Dá se to pozorovat?'],
    'Dá se to pozorovat: za jasného počasí často uvidíš Měsíc i odpoledne na modré obloze.'),
  fakt('lipa-strom', 'Lípa je strom.', true,
    ['Jak vypadá lípa v parku?'],
    'Ověříš to v atlase rostlin i na procházce – lípa má kmen, větve a korunu.'),
  fakt('kocky-predou', 'Kočky umějí příst.', true,
    ['Poslouchala jsi někdy spokojenou kočku?'],
    'Stačí pohladit spokojenou kočku a poslouchat. Tohle se dá ověřit.'),
  fakt('duben-dny', 'Duben má třicet dní.', true,
    ['Podívej se do kalendáře.'],
    'Ověříš to v kalendáři – po 30. dubnu přijde hned 1. května.'),
  fakt('snezenky', 'Sněženky kvetou mezi prvními květinami v roce.', true,
    ['Kdy jsi viděla sněženky?'],
    'Dá se to pozorovat: sněženky vykvetou, když ještě místy leží sníh a jiné květiny teprve raší.'),
  fakt('brokolice-horsi', 'Brokolice chutná hůř než mrkev.', false,
    ['Chutná všem stejně?'],
    'Chuť je věc názoru. Někomu brokolice chutná víc než mrkev a jinému naopak.'),
  fakt('praha-nejkrasnejsi', 'Praha je nejkrásnější město na světě.', false,
    ['Líbí se všem stejné město?'],
    'Mnoho lidí to tak cítí, ale jiní milují jiná města. „Nejkrásnější“ je názor.'),
  fakt('cekani-dlouhe', 'Hodina čekání u lékaře je strašně dlouhá.', false,
    ['Hodina má pořád stejně minut. Co je tedy „strašně dlouhá“?'],
    'Hodina má vždycky šedesát minut. Jak dlouhá se zdá, je pocit – tedy názor.'),
  fakt('sovy-krasne', 'Sovy jsou nejkrásnější ptáci.', false,
    ['Dá se krása změřit?'],
    'Někomu se nejvíc líbí sovy, jinému papoušci. Krása je názor.'),
  fakt('lipa-vune', 'Lípa voní nejlépe ze všech stromů.', false,
    ['Líbí se všem stejná vůně?'],
    'Vůně se každému líbí jiná. „Nejlépe“ tu vyjadřuje názor.'),
  fakt('fotbal-super', 'Fotbal je super hra.', false,
    ['Baví fotbal úplně každého?'],
    'Slovo „super“ říká, co se komu líbí. Někoho fotbal baví a jiného ne.'),
  fakt('pisnicka-hezka', 'Tahle písnička je moc hezká.', false,
    ['Líbí se všem stejné písničky?'],
    'Jestli je písnička hezká, posoudí každý po svém. Je to názor.'),
  fakt('leto-lepsi', 'Léto je lepší než zima.', false,
    ['Mají všichni rádi stejné roční období?'],
    'Lyžař by řekl, že lepší je zima. Co je „lepší“, je názor.'),
  fakt('uplnek-kouzelny', 'Měsíc v úplňku vypadá kouzelně.', false,
    ['Vypadá Měsíc pro každého stejně kouzelně?'],
    'Úplněk se dá pozorovat, ale jestli vypadá kouzelně, je pocit – tedy názor.'),
  fakt('ukoly-zabavne', 'Úkoly z matematiky jsou zábavné.', false,
    ['Baví všechny děti stejné věci?'],
    'Někoho úkoly z matematiky baví a jiného ne. „Zábavné“ je názor.'),
];

// ---------------------------------------------------------------------------
// L3 – fakta s čísly a světem, názory převlečené za jistotu, věty s obojím

const L3: Spec[] = [
  fakt('everest-nejvyssi', 'Nejvyšší hora světa je Mount Everest.', true,
    ['Dá se hora změřit?'],
    'Měřiči horu mnohokrát změřili, naposledy i pomocí družic. Měří skoro devět kilometrů nad mořem.'),
  fakt('vltava-nejdelsi', 'Vltava je nejdelší řeka v Česku.', true,
    ['Jak se dá zjistit délka řeky?'],
    'Délku řek změřili zeměměřiči podle map. Vltava měří asi 430 kilometrů. Labe je sice celé delší, ale většina jeho toku leží v Německu.'),
  fakt('kilogram-gramy', 'Kilogram je tisíc gramů.', true,
    ['Jak se převádějí jednotky?'],
    'Je to pravidlo měření, které platí všude. Ověříš ho v učebnici i na kuchyňské váze.'),
  fakt('kytara-struny', 'Obyčejná kytara má šest strun.', true,
    ['Dají se struny spočítat?'],
    'Stačí struny spočítat. Existují i kytary s dvanácti strunami, ale obyčejná jich má šest.'),
  fakt('antarktida-led', 'Většinu Antarktidy pokrývá led.', true,
    ['Jak to mohli vědci zjistit?'],
    'Vědci to vidí na snímcích z družic a změřili to na výpravách do Antarktidy.'),
  fakt('slunce-vychod', 'Slunce vychází na východní straně oblohy.', true,
    ['Dá se to pozorovat každé ráno?'],
    'Dá se to pozorovat každé ráno. Podle toho se lidé odedávna orientují v krajině.'),
  fakt('kone-trava', 'Koně se živí hlavně trávou a senem.', true,
    ['Kdo se o koně stará a ví, co jedí?'],
    'Chovatelé a veterináři to vědí z pozorování – koně jsou býložravci.'),
  fakt('uplnek-29', 'Od jednoho úplňku do dalšího uplyne asi 29 dní.', true,
    ['Dá se to spočítat v kalendáři?'],
    'Lidé to pozorují odedávna a dá se to spočítat v kalendáři – vyjde to asi na 29 a půl dne. I slovo „měsíc“ v kalendáři má jméno podle Měsíce.'),
  fakt('kocky-chytrejsi', 'Všichni přece vědí, že kočky jsou chytřejší než psi.', false,
    ['Dokazují něco slova „všichni přece vědí“?'],
    'Věta zní jistě, ale slova „všichni přece vědí“ nic nedokazují. A co znamená „chytřejší“, si každý představí jinak.'),
  fakt('sachy-nejchytrejsi', 'Šachy jsou nejchytřejší hra na světě.', false,
    ['Dá se změřit, která hra je nejchytřejší?'],
    'Nejchytřejší hru nejde změřit. Milovník šachů to tak cítí, jiný by jmenoval jinou hru.'),
  fakt('hory-lepsi', 'Na horách je to lepší než u moře.', false,
    ['Jezdí všichni na dovolenou na stejné místo?'],
    'Někdo miluje hory, jiný moře. „Lepší“ je názor.'),
  fakt('kytara-hezci', 'Kytara má hezčí zvuk než klavír.', false,
    ['Líbí se všem stejná hudba?'],
    'Zvuk se dá změřit, ale „hezčí“ je pocit. Klavíristka by nejspíš řekla opak.'),
  fakt('podzim-smutny', 'Podzim je smutné roční období.', false,
    ['Je podzim smutný pro každého?'],
    'Někomu je na podzim smutno, jiný se těší na barevné listí a pouštění draků. Je to názor.'),
  fakt('vareni-zabavnejsi', 'Vaření je zábavnější než uklízení.', false,
    ['Baví všechny stejné věci?'],
    'Co je zábavnější, posoudí každý po svém. Je to názor, i když s ním hodně lidí souhlasí.'),
  fakt('olympiada-jasne', 'Je jasné, že zimní olympiáda je zajímavější než letní.', false,
    ['Promění slova „je jasné“ názor ve fakt?'],
    'Slova „je jasné“ mají přesvědčit, ale „zajímavější“ je pořád jen názor.'),
  q('cast-snih', '„Včera napadlo deset centimetrů sněhu a byl to nejkrásnější den zimy.“ Která část věty je názor?', 'Byl to nejkrásnější den zimy',
    ['Napadlo deset centimetrů sněhu', CELA_FAKT, CELA_NAZOR],
    ['Která část se dá změřit?', 'Hledej slovo „nej…“.'],
    'Výška sněhu se dá změřit, to je fakt. „Nejkrásnější den“ je názor – pro jiného mohl být nejkrásnější jiný den.'),
  q('cast-kolo', '„Moje kolo má dvacet jedna převodů a je to nejlepší kolo na světě.“ Která část věty je názor?', 'Je to nejlepší kolo na světě',
    ['Kolo má dvacet jedna převodů', CELA_FAKT, CELA_NAZOR],
    ['Která část se dá spočítat?'],
    'Převody se dají spočítat, to je fakt. „Nejlepší kolo na světě“ je názor majitele.'),
  q('cast-karlstejn', '„Karlštejn postavili před více než šesti sty lety a je to nejhezčí hrad v Česku.“ Která část věty je názor?', 'Je to nejhezčí hrad v Česku',
    ['Postavili ho před více než 600 lety', CELA_FAKT, CELA_NAZOR],
    ['Která část se dá najít v historické knize?'],
    'Kdy hrad postavili, zjistili historici ze starých listin – to je fakt. Který hrad je nejhezčí, je názor.'),
  q('cast-plejtvak', '„Plejtvák obrovský je největší zvíře na Zemi a je úžasně krásný.“ Která část věty je názor?', 'Je úžasně krásný',
    ['Je největší zvíře na Zemi', CELA_FAKT, CELA_NAZOR],
    ['Co se dá změřit a zvážit?'],
    'Velikost vědci změřili, to je fakt. Jestli je krásný, posoudí každý po svém.'),
  q('cast-palacinky', '„Palačinky se dělají z mouky, mléka a vajec a nejlepší jsou s marmeládou.“ Která část věty je názor?', 'Nejlepší jsou s marmeládou',
    ['Dělají se z mouky, mléka a vajec', CELA_FAKT, CELA_NAZOR],
    ['Co najdeš v receptu a co je věc chuti?'],
    'Z čeho se palačinky dělají, najdeš v receptu – to je fakt. S čím jsou nejlepší, je věc chuti.'),
  q('cast-brno', '„Brno je druhé největší město v Česku a má nejhezčí náměstí.“ Která část věty je názor?', 'Má nejhezčí náměstí',
    ['Je druhé největší město v Česku', CELA_FAKT, CELA_NAZOR],
    ['Co se dá spočítat?'],
    'Kolik lidí ve městě žije, se dá spočítat – to je fakt. Které náměstí je nejhezčí, je názor.'),
  q('ktera-fakt-jahody', 'Která věta je fakt?', 'Jahody rostou na zahradě i v lese.',
    ['Jahody jsou nejchutnější ovoce.', 'Jahody jsou krásně červené.', 'Jahodová zmrzlina je nejlepší.'],
    ['Která věta se dá ověřit na procházce?'],
    'Kde jahody rostou, se dá ověřit pozorováním. Ostatní věty obsahují slova jako „nejchutnější“, „krásně“ a „nejlepší“ – to jsou názory.'),
  q('ktera-nazor-more', 'Která věta je názor?', 'Moře je nejkrásnější v létě.',
    ['Mořská voda je slaná.', 'V moři žijí ryby.', 'Moře je větší než rybník.'],
    ['Hledej slovo, které hodnotí.'],
    '„Nejkrásnější“ je hodnocení – názor. Slanost, ryby i velikost moře se dají ověřit pozorováním a měřením.'),
];

// ---------------------------------------------------------------------------
// L4 – čísla × pocity, fakta o názorech, slova, která názor prozrazují

const L4: Spec[] = [
  fakt('teplomer-bazen', 'Teploměr ukazuje, že voda v bazénu má 24 stupňů.', true,
    ['Dá se to přečíst na přístroji?'],
    'Teplota se dá změřit a každý si ji na teploměru přečte. Jestli je voda „studená“, by už byl názor.'),
  fakt('vaha-taska', 'Váha ukázala, že Leifova taška váží tři kilogramy.', true,
    ['Dá se to zvážit znovu?'],
    'Hmotnost se dá změřit a kdykoli ověřit znovu. Jestli je taška „těžká“, to už je pocit.'),
  fakt('film-dve-hodiny', 'Film trval dvě hodiny.', true,
    ['Dá se to změřit hodinami?'],
    'Délka filmu se dá změřit hodinami nebo najít v programu kina.'),
  fakt('tove-rekla', 'Tove řekla, že má nejraději zimu.', true,
    ['Neptáme se, jestli je zima nejlepší. Ptáme se, jestli to Tove řekla.'],
    'Že to Tove řekla, se dá ověřit – slyšeli to ostatní a Tove to potvrdí. Názor je až to, co si Tove o zimě myslí.',
    { difficulty: 0.4 }),
  fakt('anketa-pizza', 'V anketě napsalo dvanáct dětí z naší třídy, že mají nejraději pizzu.', true,
    ['Dají se hlasy v anketě spočítat?'],
    'Výsledek ankety se dá ověřit – stačí spočítat lístky. Věta „pizza je nejlepší“ by byla názor, ale počet hlasů je fakt.',
    { difficulty: 0.3 }),
  fakt('spanek-lekari', 'Lékaři doporučují dětem ve tvém věku spát devět až dvanáct hodin denně.', true,
    ['Dá se doporučení lékařů najít a přečíst?'],
    'Doporučení lékařů je sepsané a dá se najít. Lékaři ho určili podle výzkumů spánku.'),
  fakt('everest-snezka', 'Mount Everest je vyšší než Sněžka.', true,
    ['Obě hory jsou změřené.'],
    'Obě hory jsou změřené: Everest měří skoro devět kilometrů, Sněžka něco přes jeden a půl kilometru.'),
  fakt('bazen-studena', 'Voda v bazénu je moc studená.', false,
    ['Je voda studená pro každého stejně?'],
    'Jestli je voda „moc studená“, je pocit. Otužilec by řekl, že je příjemná. Teplotu by rozhodl teploměr, ne pocit.'),
  fakt('taska-tezka', 'Leifova taška je moc těžká.', false,
    ['Je taška stejně těžká pro dítě i pro dospělého?'],
    'Pro Leifa může být těžká, pro dospělého lehká. „Moc těžká“ je pocit – fakt by byl údaj z váhy.'),
  fakt('film-dlouhy', 'Film byl moc dlouhý.', false,
    ['Nudil se u filmu každý?'],
    'Jak dlouhý se film zdá, je pocit. Komu se líbil, tomu uběhl rychle.'),
  fakt('podle-me-cteni', 'Podle mě je čtení zábavnější než televize.', false,
    ['Čí je to myšlenka?'],
    'Slova „podle mě“ přímo říkají, že jde o názor.'),
  fakt('deset-minut', 'Deset minut čtení denně je málo.', false,
    ['Deset minut je číslo. A co slovo „málo“?'],
    'Deset minut se dá změřit, ale „málo“ je hodnocení. Pro někoho je to hodně, pro jiného málo.',
    { difficulty: 0.3 }),
  fakt('drahe-boty', 'Boty za tisíc korun jsou drahé.', false,
    ['Cena je číslo. A co slovo „drahé“?'],
    'Cena tisíc korun je fakt, ale jestli je to „drahé“, posoudí každý podle sebe.',
    { difficulty: 0.2 }),
  fakt('vstavani-brzo', 'Vstávat v sedm hodin je moc brzo.', false,
    ['Vstávají všichni rádi ve stejnou dobu?'],
    'Sedm hodin je čas na hodinách, ale „moc brzo“ je názor. Ranní ptáče to vidí jinak.'),
  q('slovo-malebna', '„Vltava protéká Prahou a je to nejmalebnější česká řeka.“ Které slovo prozrazuje názor?', 'Nejmalebnější',
    ['Protéká', 'Prahou', 'Řeka'],
    ['Hledej slovo, které hodnotí.'],
    '„Nejmalebnější“ znamená nejkrásnější na pohled – to je názor. Že Vltava protéká Prahou, se dá ověřit na mapě.'),
  q('slovo-uzasny', '„Včera ve tři hodiny odpoledne začal na náměstí úžasný koncert.“ Které slovo prozrazuje názor?', 'Úžasný',
    ['Včera', 'Odpoledne', 'Koncert'],
    ['Které slovo říká, jak se to někomu líbilo?'],
    '„Úžasný“ je hodnocení. Kdy a kde koncert začal, se dá ověřit.'),
  q('slovo-roztomile', '„V zoo se narodilo roztomilé mládě slona.“ Které slovo prozrazuje názor?', 'Roztomilé',
    ['Narodilo', 'Mládě', 'Slona'],
    ['Které slovo by jiný člověk mohl vidět jinak?'],
    '„Roztomilé“ je názor. Že se v zoo narodilo slůně, je fakt, který zoo zveřejnila.'),
  q('cast-fakt-varan', '„Komodský varan je nejhezčí ještěr a žije na ostrovech v Indonésii.“ Která část věty je fakt?', 'Žije na ostrovech v Indonésii',
    ['Je nejhezčí ještěr', CELA_FAKT, CELA_NAZOR],
    ['Která část se dá ověřit v atlase zvířat?'],
    'Kde varan žije, zjistili přírodovědci pozorováním – to je fakt. „Nejhezčí ještěr“ je názor.'),
  q('cast-fakt-mozart', '„Mozart složil přes šest set skladeb a jeho hudba je ze všech nejkrásnější.“ Která část věty je fakt?', 'Složil přes šest set skladeb',
    ['Jeho hudba je nejkrásnější', CELA_FAKT, CELA_NAZOR],
    ['Co se dá spočítat?'],
    'Hudební vědci Mozartovy skladby sepsali a spočítali – to je fakt. Nejkrásnější hudba je názor.'),
  q('cast-fakt-duby', '„Duby se dožívají stovek let a jsou to nejvznešenější stromy.“ Která část věty je fakt?', 'Dožívají se stovek let',
    ['Jsou to nejvznešenější stromy', CELA_FAKT, CELA_NAZOR],
    ['Co se dá zjistit z letokruhů?'],
    'Stáří stromů zjistí vědci třeba podle letokruhů – to je fakt. „Nejvznešenější“ je názor.'),
  q('cast-nazor-darek', '„Tohle kolo stojí pět tisíc korun, je modré a je to nejlepší dárek.“ Která část věty je názor?', 'Je to nejlepší dárek',
    ['Stojí pět tisíc korun', 'Je modré', CELA_FAKT],
    ['Věta má tři části. Dvě se dají ověřit.'],
    'Cenu i barvu může ověřit každý. „Nejlepší dárek“ je názor – někdo by si přál něco jiného.'),
  q('dva-nazory', 'Ve které větě jsou dva názory?', 'Zima je krásná a sáňkování je nejlepší.',
    ['Zima začíná v prosinci a je krásná.', 'Leden má 31 dní a v zimě sněží.', 'V zimě bývají noci dlouhé.'],
    ['Hledej dvě hodnoticí slova v jedné větě.'],
    '„Krásná“ i „nejlepší“ jsou hodnocení. Ostatní věty mají nejvýš jeden názor, nebo žádný.',
    { difficulty: 0.3 }),
];

export const faktBanks = { 1: L1, 2: L2, 3: L3, 4: L4 };
