// Mýtus, nebo pravda? – rozšířené omyly a překvapivé pravdy o zvířatech,
// přírodě a světě. Vysvětlení je zajímavost (ukáže se i po správné odpovědi):
// nejdřív JAK se to zjistilo (pozorování, měření, pokus, přístroj, odborník),
// pak jeden navazující detail. Draci z pohádek a příběhů jsou jasně oddělení
// od skutečných zvířat. O lidském těle je „Fakt, nebo pohádka?“ na Ostrově
// těla – jeho tvrzení se tu neopakují.

import type { Spec } from '../../core/bank';
import { mytus } from './kriticke-common';

// ---------------------------------------------------------------------------
// L1 – zvířata a příroda kolem nás, jednoduché pokusy

const L1: Spec[] = [
  mytus('pstros-nelita', 'Pštros neumí létat, ale rychle běhá.', true,
    ['{Viděla|Viděl} jsi pštrosa v zoo?'],
    'Přírodovědci pštrosům měřili rychlost: běží až kolem 70 kilometrů za hodinu, rychleji než auto ve městě. Vzlétnout ale nedokážou – na svá malá křídla jsou moc těžcí.'),
  mytus('slon-nejvetsi', 'Slon je největší zvíře, které žije na souši.', true,
    ['Vědci zvířata měřili a vážili.'],
    'Vědci zvířata měřili a vážili: africký slon je největší a nejtěžší zvíře na souši. Žirafa je sice vyšší, ale slon váží několikrát víc – velký sameček kolem šesti tun.'),
  mytus('jezek-zima', 'Ježek v zimě spí.', true,
    ['Potkáš ježka v zimě na zahradě?'],
    'Přírodovědci ježky sledovali: na zimu si v listí udělají pelíšek a většinu zimy prospí. Srdce jim při tom zpomalí z asi 190 úderů za minutu na pouhých 20.'),
  mytus('more-slane', 'Voda v moři je slaná.', true,
    ['{Ochutnala|Ochutnal} jsi někdy mořskou vodu?'],
    'Kdo u moře ochutnal vodu, ví to. Vědci navíc změřili, že v litru mořské vody je asi 35 gramů soli – proto se nedá pít, žízeň by jen zhoršila.'),
  mytus('pavouk-osm', 'Pavouk má osm nohou.', true,
    ['Dají se nohy spočítat?'],
    'Stačí pavouka pozorovat a nohy spočítat: má jich osm. Proto pavouk nepatří k hmyzu – hmyz má nohou jen šest.'),
  mytus('led-plave', 'Kostka ledu plave na vodě.', true,
    ['Dá se to vyzkoušet se sklenicí vody.'],
    'Dá se to vyzkoušet pokusem: kostka ledu zůstane ve sklenici nahoře, protože led je lehčí než stejně velký kousek vody. Proto rybníky zamrzají odshora a ryby pod ledem přečkají zimu.'),
  mytus('dracek-letavy', 'Dráček létavý je skutečná ještěrka.', true,
    ['Existují skutečná zvířata, která se jmenují po dracích?'],
    'Přírodovědci ho pozorovali v pralesích jihovýchodní Asie. Po stranách těla má kožní blány, které vypadají jako malá dračí křídla – odtud jméno. Oheň ale nechrlí.'),
  mytus('pulec-zaba', 'Z pulce vyroste žába.', true,
    ['Kde žijí pulci?'],
    'Dá se to pozorovat v rybníce: pulcům nejdřív narostou zadní nohy, pak přední a ocásek se postupně ztratí. Z pulce, který dýchal pod vodou žábrami, je nakonec žába, která dýchá vzduch.'),
  mytus('housenka-motyl', 'Z housenky se stane motýl.', true,
    ['Co se děje v kukle?'],
    'Dá se to pozorovat: housenka se zakuklí a po čase se z kukly vylíhne motýl. Uvnitř kukly se mezitím celé její tělo přestaví a narostou mu křídla.'),
  mytus('delfin-nadech', 'Delfín se musí vynořit, aby se nadechl.', true,
    ['Je delfín ryba, nebo savec?'],
    'Dá se to pozorovat: delfín vystrčí hlavu nad vodu a nadechne se otvorem na temeni. Je to savec a dýchá plícemi jako my – pod vodou bez nadechnutí vydrží jen několik minut.'),
  mytus('tucnak-leta', 'Tučňák umí létat ve vzduchu jako vrabec.', false,
    ['{Viděla|Viděl} jsi tučňáka letět?'],
    'Přírodovědci tučňáky dlouho pozorovali: ve vzduchu nelétají. Křídla jim slouží jako ploutve, se kterými pod vodou rychle plavou, jako by létali.'),
  mytus('velryba-ryba', 'Velryba je ryba.', false,
    ['Jak velryba dýchá?'],
    'Vědci pozorovali, že velryby dýchají vzduch a mláďata krmí mlékem – jsou to savci, i když žijí ve vodě. Poznáš to i podle ocasu: velryba má ocasní ploutev naležato, ryba nastojato.'),
  mytus('netopyr-ptak', 'Netopýr je pták.', false,
    ['Má netopýr peří?'],
    'Přírodovědci pozorovali, že netopýr má srst a mláďata krmí mlékem. Je to savec, který umí létat: křídlo mu tvoří kůže napjatá mezi velmi dlouhými prsty.'),
  mytus('jezek-jablka', 'Ježek si nosí jablka napíchnutá na bodlinách.', false,
    ['Čím se ježek živí?'],
    'Přírodovědci ježky dlouho pozorovali: jablka na bodlinách nenosí. Živí se hlavně brouky, žížalami a slimáky, a tak zahrádkářům pomáhají.'),
  mytus('mesic-syr', 'Měsíc je z velkého kusu sýra.', false,
    ['Byl někdo na Měsíci?'],
    'Astronauti na Měsíci chodili a přivezli odtud kameny – dohromady asi 382 kilogramů. Vědci je zkoumali: je to hornina, žádný sýr.'),
  mytus('varan-ohen', 'Komodský varan chrlí oheň.', false,
    ['Je komodský varan drak z pohádky, nebo skutečné zvíře?'],
    'Přírodovědci komodské varany pozorují už přes sto let: je to velký ještěr a oheň nechrlí. Říká se mu i komodský drak, ale ohniví draci jsou jen z příběhů.'),
  mytus('dinosauri-vymysleni', 'Dinosauři jsou vymyšlení jako draci z pohádek.', false,
    ['Co vystavují v přírodovědném muzeu?'],
    'Vědci vykopali tisíce zkamenělých dinosauřích kostí i vajec. Dinosauři opravdu žili – jen tak dávno, že je žádný člověk nikdy neviděl.'),
  mytus('duha-poklad', 'Na konci duhy je schovaný hrnec zlata.', false,
    ['Dá se konec duhy doběhnout?'],
    'Duhu nejde doběhnout – když se pohneš, posune se s tebou, jak pozorují všichni, kdo to zkusili. Z letadla bývá duha vidět i jako celý kruh, takže žádný konec s hrncem zlata nemá.'),
  mytus('slunce-zhasne', 'V noci Slunce zhasne a ráno se zase rozsvítí.', false,
    ['Kam se Slunce v noci schová?'],
    'Astronauti z vesmíru vidí, že Slunce svítí pořád. Noc máme, když se Země otočí a my jsme na její straně odvrácené od Slunce – na druhé straně Země je zrovna den.'),
  mytus('snek-ulita', 'Šnek si může ulitu sundat a spát bez ní.', false,
    ['Roste ulita spolu se šnekem?'],
    'Přírodovědci pozorovali, že ulita ke šnekovi pevně přirůstá a roste spolu s ním – nové kousky přibývají na jejím okraji. Sundat ji nejde, je to jeho domeček na celý život.'),
];

// ---------------------------------------------------------------------------
// L2 – slavné omyly o zvířatech a překvapivé pravdy

const L2: Spec[] = [
  mytus('pstros-vejce', 'Pštros snáší největší vejce ze všech žijících ptáků.', true,
    ['Který pták je ze všech největší?'],
    'Vědci vejce vážili: jedno pštrosí vejce váží víc než dvacet slepičích. V noci na vejcích sedí a zahřívá je tatínek pštros.'),
  mytus('kukacka', 'Kukačka obecná si nestaví hnízdo a vejce klade do hnízd jiných ptáků.', true,
    ['Ornitologové kukačky dlouho pozorovali.'],
    'Ornitologové to pozorovali a natočili: kukačka snese vejce do cizího hnízda a mládě pak krmí jiní ptáci. Její vejce se navíc často barvou podobá vejcím v tom hnízdě.'),
  mytus('slunce-hvezda', 'Slunce je hvězda.', true,
    ['Proč je Slunce tak velké a jasné?'],
    'Astronomové zkoumali světlo Slunce i hvězd přístroji: jsou to tělesa stejného druhu, jen Slunce je k nám mnohem blíž. Kdyby bylo Slunce dutá koule, vešel by se do něj víc než milion Zemí.'),
  mytus('snezka', 'Sněžka je nejvyšší hora v Česku.', true,
    ['Hory se dají změřit.'],
    'Zeměměřiči ji změřili: měří 1603 metrů a žádná česká hora není vyšší. Přes její vrchol vede hranice, takže nahoře stojíš napůl v Česku a napůl v Polsku.'),
  mytus('panda-bambus', 'Panda velká se živí hlavně bambusem.', true,
    ['Kdo pandy pozoroval?'],
    'Přírodovědci pandy pozorovali v horských lesích Číny: bambus tvoří skoro celou jejich potravu. Spořádají ho tolik, že jídlem tráví většinu dne.'),
  mytus('gepard', 'Gepard je nejrychlejší zvíře na souši.', true,
    ['Vědci zvířatům měřili rychlost.'],
    'Vědci gepardům měřili rychlost: v krátkém sprintu běží rychleji než auto ve městě. Tak rychle ale vydrží běžet jen chvilku, asi půl minuty.'),
  mytus('hrom-blesk', 'Hrom vzniká při blesku.', true,
    ['Co slyšíš po blesku?'],
    'Vědci to zkoumali přístroji: blesk prudce ohřeje vzduch a ten se rozepne s hlasitým zahřměním. Světlo blesku k nám doletí hned, zvuk až po chvíli – proto nejdřív zableskne a pak zahřmí.'),
  mytus('rostliny-svetlo', 'Pokojové rostliny se naklánějí ke světlu.', true,
    ['Podívej se na květiny na okně.'],
    'Dá se to pozorovat: rostlina na okně se nakloní ke sklu. Stonek víc roste na stinné straně, a tak se ohne ke světlu – když květináč otočíš, za pár dní se natočí zpátky.'),
  mytus('ledni-medved-plave', 'Lední medvěd umí v moři uplavat velký kus cesty.', true,
    ['Vědci medvědy sledovali pomocí vysílaček.'],
    'Vědci dali medvědicím obojky s vysílačkou a zjistili, že některé uplavaly v kuse i přes sto kilometrů. Obojky nosí jen medvědice – samci mají krk širší než hlavu a obojek by jim sklouzl.'),
  mytus('jelen-parohy', 'Jelenům každý rok opadají parohy a narostou nové.', true,
    ['Co občas najdou myslivci v lese?'],
    'Myslivci a přírodovědci to pozorují: koncem zimy najdou v lese shozené parohy a jelenům pak rostou nové. Parohy patří k nejrychleji rostoucím částem zvířecího těla – za pár měsíců jsou celé.'),
  mytus('pstros-hlava', 'Když se pštros bojí, strčí hlavu do písku.', false,
    ['Co udělá pštros, když uvidí nebezpečí?'],
    'Přírodovědci pštrosy pozorovali: při nebezpečí utíkají, nebo si lehnou a přitisknou krk k zemi. Z dálky to vypadá, jako by hlavu schovali – v písku ji ale nemají.'),
  mytus('netopyri-slepi', 'Netopýři jsou slepí.', false,
    ['Vědci to zkoumali pokusy.'],
    'Vědci zjistili pokusy, že netopýři vidí. Ve tmě se navíc orientují podle ozvěny svého volání, které je tak vysoké, že ho většinou neslyšíme.'),
  mytus('velbloud-voda', 'Velbloud má v hrbu zásobu vody.', false,
    ['Vědci zkoumali, z čeho je hrb.'],
    'Vědci zkoumali, z čeho je hrb: je z tuku. Z něj velbloud čerpá sílu, když dlouho nejí – hrb pak splaskne a povisne na stranu.'),
  mytus('slepys-slepy', 'Slepýš je slepý.', false,
    ['{Všimla|Všiml} sis někdy, jaké oči má slepýš?'],
    'Kdo slepýše pozoroval, viděl, že má oči a umí mrkat. Jméno dostal nejspíš kvůli malým očím – slepý ale není.'),
  mytus('mysi-syr', 'Myši mají ze všeho nejraději sýr.', false,
    ['Co jedí myši venku v přírodě?'],
    'Přírodovědci a chovatelé pozorovali, že myši nejraději jedí zrní, semínka a sladké věci. Sýr taky snědí, ale nejraději ho nemají – to je jen z pohádek a kreslených filmů.'),
  mytus('hadi-slizci', 'Hadi jsou slizcí.', false,
    ['Jakou kůži mají hadi?'],
    'Zoologové a chovatelé drží hady v rukou každý den a vědí, že had má suchou kůži se šupinami. Slizký jen vypadá, protože se jeho šupiny lesknou.'),
  mytus('koala-medved', 'Koala je medvěd.', false,
    ['Kde koala nosí mládě?'],
    'Přírodovědci pozorovali, že koala nosí mládě ve vaku jako klokan. Patří mezi vačnatce – medvídkem se jí říká jen kvůli huňatému kožíšku.'),
  mytus('tucnaci-sever', 'Tučňáci žijí na severním pólu.', false,
    ['Na severním pólu žijí lední medvědi. A kde žijí tučňáci?'],
    'Výpravy vědců zjistily, že tučňáci žijí na jihu, nejvíc kolem Antarktidy – na severním pólu žádní nejsou. Tam místo nich žijí lední medvědi, takže se tučňák s ledním medvědem v přírodě nikdy nepotká.'),
  mytus('ptaci-odletaji', 'Všichni ptáci odlétají na zimu do teplých krajin.', false,
    ['Kdo chodí v zimě na krmítko?'],
    'Stačí v zimě pozorovat krmítko: sýkorky, vrabci i kosi u nás zůstávají. Odlétají hlavně ptáci, kteří jedí létající hmyz, třeba vlaštovky – v zimě by tu potravu nenašly.'),
  mytus('hvezdy-male', 'Hvězdy jsou malá světýlka, jen o trochu větší než lampička.', false,
    ['Proč se nám hvězdy zdají malé?'],
    'Astronomové změřili, že hvězdy jsou obrovské koule, mnohé větší než Slunce. Malé se zdají, protože jsou nesmírně daleko – světlo z nejbližší hvězdy po Slunci k nám letí přes čtyři roky.'),
  mytus('draci-muzeum', 'V muzeu vystavují kostry draků chrlících oheň.', false,
    ['Čí kostry vědci opravdu vykopali?'],
    'V muzeích jsou kostry dinosaurů, které vědci vykopali. Kosti ohnivých draků nikdo nikdy nenašel – takoví draci jsou z příběhů, třeba i z naší hry.'),
];

// ---------------------------------------------------------------------------
// L3 – blesky, Měsíc, ještěři a rostliny, které se hýbou

const L3: Spec[] = [
  mytus('varan-nejvetsi', 'Komodský varan je největší žijící ještěr na světě.', true,
    ['Vědci ještěry měřili.'],
    'Vědci varany měřili a vážili: dorostou asi do tří metrů a žijí na několika ostrovech v Indonésii. Krokodýli bývají větší, ale ti mezi ještěry nepatří.'),
  mytus('dracek-plachti', 'Dráček létavý umí plachtit ze stromu na strom.', true,
    ['Přírodovědci ho natáčeli v pralese.'],
    'Přírodovědci ho natáčeli v pralese: roztáhne kožní blány po stranách těla a klouže vzduchem jako kluzák. Tak přeletí ze stromu na strom i přes deset metrů, aniž by slezl na zem.'),
  mytus('morsky-konik', 'Mořský koník je ryba.', true,
    ['Čím mořský koník dýchá?'],
    'Vědci zkoumali jeho tělo: má žábry a ploutvičky a dýchá pod vodou jako jiné ryby. Jen plave vzpřímeně a ocasem se drží mořských rostlin, aby ho neodnesl proud.'),
  mytus('hvezdy-ve-dne', 'Hvězdy jsou na obloze i ve dne, jen je nevidíme.', true,
    ['Co se stane při úplném zatmění Slunce?'],
    'Při úplném zatmění Slunce se uprostřed dne setmí a lidé hvězdy uvidí. Astronomové jasné hvězdy pozorují dalekohledy i ve dne – pouhým okem je přes světlou oblohu nevidíme.'),
  mytus('bourka-sekundy', 'Když mezi bleskem a hromem napočítáš tři sekundy, je bouřka asi kilometr daleko.', true,
    ['Co je rychlejší – světlo, nebo zvuk?'],
    'Vědci změřili, že zvuk uletí asi kilometr za tři sekundy, kdežto světlo blesku k nám dorazí skoro hned. Napočítané sekundy vyděl třemi a víš, kolik kilometrů je bouřka daleko.'),
  mytus('citlivka', 'Existuje rostlina, která při dotyku sklopí lístky.', true,
    ['Dá se to ověřit v květinářství.'],
    'Dá se to pozorovat u citlivky stydlivé: když se jí dotkneš, lístky se během chvilky složí. Když ji pak necháš být, za čas je zase roztáhne.'),
  mytus('vazka-pozpatku', 'Vážka umí ve vzduchu stát na místě i letět pozpátku.', true,
    ['Vědci vážky natáčeli rychlou kamerou.'],
    'Vědci vážky natáčeli rychlou kamerou: každé ze čtyř křídel umí mávat jinak. Proto vážka zvládne stát na místě i letět pozpátku a za letu chytá komáry.'),
  mytus('kolibrik-maly', 'Nejmenší pták na světě měří jen asi pět centimetrů.', true,
    ['Vědci ptáky měřili.'],
    'Vědci změřili kolibříka kubánského: je dlouhý asi jako malíček a váží asi dva gramy. Jeho vajíčko je velké zhruba jako hrášek.'),
  mytus('chobotnice-srdce', 'Chobotnice má tři srdce.', true,
    ['Vědci zkoumali stavbu jejího těla.'],
    'Vědci zkoumali stavbu jejího těla a našli tři srdce: dvě menší pohánějí žábry a jedno velké zbytek těla. Přísavkami na osmi ramenou chobotnice dokonce ochutnává.'),
  mytus('ptaci-kosti', 'Mnoho ptáků má uvnitř duté kosti.', true,
    ['Co ptákům pomáhá, aby byli při létání lehcí?'],
    'Zoologové zkoumali ptačí kostry: kosti mají uvnitř prázdné prostory se vzpěrami, takže jsou lehké a přitom pevné. Kostra fregatky dokonce váží méně než její peří.'),
  mytus('blesk-jednou', 'Blesk nikdy neuhodí dvakrát do stejného místa.', false,
    ['Vědci měří údery blesku přístroji na věžích.'],
    'Vědci měří údery blesku přístroji na vysokých věžích. Blesk nejčastěji uhodí do nejvyššího místa v okolí, a proto do některých mrakodrapů uhodí i mnohokrát za rok.'),
  mytus('sova-dokola', 'Sova umí otočit hlavu úplně dokola.', false,
    ['Vědci to změřili.'],
    'Vědci to změřili: sova otočí hlavu asi o tři čtvrtě kruhu. Otáčet musí celou hlavou, protože očima v hlavě hýbat nedokáže.'),
  mytus('zeme-placata', 'Země je placatá jako talíř.', false,
    ['Jak vypadá Země na fotkách z vesmíru?'],
    'Astronauti Zemi vyfotili z vesmíru a je kulatá. Už dávno si lidé všimli, že lodě mizí za obzorem odspodu a že stín Země na Měsíci je při zatmění kulatý.'),
  mytus('mesic-sviti', 'Měsíc svítí vlastním světlem.', false,
    ['Proč vidíme někdy jen kousek Měsíce?'],
    'Astronomové pozorují, že Měsíc jen odráží světlo Slunce – a přitom je jeho povrch tmavý asi jako asfalt. Proto vidíme jen tu část Měsíce, na kterou Slunce svítí.'),
  mytus('slon-brcko', 'Slon pije chobotem jako brčkem.', false,
    ['Kam slon vodu z chobotu dá?'],
    'Přírodovědci pozorovali, že slon nasaje vodu do chobotu a pak si ji vystříkne do tlamy. Do chobotu se mu najednou vejde asi osm litrů.'),
  mytus('sopky-teplo', 'Sopky jsou jen v teplých krajinách.', false,
    ['Znáš studenou zemi se sopkami?'],
    'Vědci pozorují činné sopky i na studeném Islandu, a dokonce v Antarktidě. V kráteru sopky Erebus v Antarktidě je jezero žhavé lávy, i když kolem je všude led.'),
  mytus('lide-dinosauri', 'Pravěcí lidé jezdili na dinosaurech.', false,
    ['Jak staré jsou kosti dinosaurů?'],
    'Vědci určili stáří zkamenělin: velcí dinosauři zmizeli přes šedesát milionů let předtím, než se objevili první lidé. Lidé a dinosauři se tedy nikdy nepotkali.'),
  mytus('slepys-had', 'Slepýš je had.', false,
    ['Umí slepýš mrkat?'],
    'Přírodovědci zkoumali jeho tělo: slepýš má víčka a umí mrkat, což hadi neumějí. Je to beznohá ještěrka – a když ho něco chytí za ocas, umí ho odhodit jako jiné ještěrky.'),
  mytus('kralik-mrkev', 'Králík by měl jíst hlavně mrkev.', false,
    ['Zeptej se veterinářky.'],
    'Veterináři radí, že králík potřebuje hlavně seno a trávu – ty mu obrušují zuby, které mu pořád dorůstají. Mrkev je pro něj jen pamlsek, protože je v ní hodně cukru.'),
  mytus('byk-cervena', 'Býka rozzuří červená barva.', false,
    ['Vědci s býky zkoušeli látky různých barev.'],
    'Vědci zkoumali býčí oči a zjistili, že červenou od zelené skoro nerozeznají. Při pokusech běžel býk za látkou, která se hýbala, ať měla jakoukoli barvu.'),
];

// ---------------------------------------------------------------------------
// L4 – smysly zvířat, Měsíc, sever a jih a důkazy ze zkamenělin

const L4: Spec[] = [
  mytus('vcely-barvy', 'Včely rozeznávají barvy.', true,
    ['Vědec to ověřil pokusem s barevnými kartičkami.'],
    'Vědec Karl von Frisch to ověřil pokusem: včely se naučily létat na modrou kartičku se sladkou vodou a našly ji i mezi šedými. Včely vidí i ultrafialovou barvu, kterou my nevidíme.'),
  mytus('motyl-nohy', 'Motýli ochutnávají nohama.', true,
    ['Co udělá motýl, když stoupne na sladkou kapku?'],
    'Vědci pozorovali, že když motýl stoupne na sladkou kapku, hned rozvine sosák – chuťové buňky má na nohou. Samička tak nohama ochutná i list, jestli se hodí pro její housenky.'),
  mytus('cvrcek-usi', 'Cvrček má uši na předních nohou.', true,
    ['Přírodovědci cvrčky zkoumali pod lupou.'],
    'Přírodovědci je našli pod lupou: na předních nohách má cvrček tenké blanky, kterými slyší. Tak zaslechne cvrlikání ostatních cvrčků, které samečci vydávají třením křídel.'),
  mytus('stopy-mesic', 'Stopy astronautů jsou na Měsíci pořád.', true,
    ['Fouká na Měsíci vítr?'],
    'Na Měsíci nefouká vítr ani neprší, takže stopy nic nesmaže. Vesmírná sonda vyfotila cestičky, které tam astronauti vyšlapali – ti poslední tam byli v roce 1972.'),
  mytus('mesic-skok', 'Na Měsíci bys {vyskočila|vyskočil} mnohem výš než na Zemi.', true,
    ['Astronauti to vyzkoušeli.'],
    'Astronauti to vyzkoušeli a natočili: Měsíc přitahuje věci asi šestkrát slaběji než Země. Proto tam astronauti i v těžkých skafandrech poskakovali jako klokani.'),
  mytus('praha-more', 'Kdysi dávno bylo na místě dnešní Prahy moře.', true,
    ['Co vědci našli v kamenech kolem Prahy?'],
    'Víme to ze zkamenělin: v kamenech kolem Prahy vědci našli spoustu pravěkých mořských živočichů, třeba trilobitů. To moře tu bylo před stovkami milionů let, dávno před dinosaury.'),
  mytus('konik-tatinek', 'U mořských koníků nosí mláďata tatínek.', true,
    ['Mořští koníci se chovají i v akváriích.'],
    'Přírodovědci to pozorovali v moři i v akváriích: sameček má na bříšku vak, do kterého samička naklade vajíčka. Mláďata se v něm vylíhnou a pak z vaku vyplavou.'),
  mytus('sokol', 'Sokol stěhovavý je při střemhlavém letu rychlejší než auto na dálnici.', true,
    ['Vědci mu rychlost změřili přístroji.'],
    'Vědci a sokolníci mu rychlost měřili přístroji: střemhlav letí i přes 300 kilometrů za hodinu. Auto jezdí po dálnici nejvýš kolem 130 kilometrů za hodinu, tedy víc než dvakrát pomaleji.'),
  mytus('mesta-z-vesmiru', 'Z vesmírné stanice jsou v noci vidět světla velkých měst.', true,
    ['Astronauti fotí Zemi z oběžné dráhy.'],
    'Astronauti je fotí z vesmírné stanice: velká města v noci svítí jako třpytivé skvrny. Stanice obletí Zemi asi za hodinu a půl, takže astronauti vidí východ Slunce šestnáctkrát za den.'),
  mytus('houba-podzemi', 'Hřib, který najdeš v lese, je jen malá část celé houby.', true,
    ['Co je pod hřibem v zemi?'],
    'Odborníci na houby zjistili, že houba má pod zemí dlouhá tenká vlákna – podhoubí. Hřib je jen její plodnice a podhoubí jedné houby může prorůst velký kus lesa.'),
  mytus('ledni-medved', 'Lední medvěd má pod bílou srstí černou kůži.', true,
    ['Zoologové zkoumali medvědí kůži.'],
    'Zoologové zkoumali medvědí kůži zblízka: je černá. Chlupy jsou průhledné a světlo se v nich rozptýlí tak, že se nám srst zdá bílá.'),
  mytus('psi-cernobile', 'Psi vidí svět jen černobíle.', false,
    ['Vědci to zkoumali pokusy s barevnými kartičkami.'],
    'Vědci to zkoumali pokusy: psi se naučili rozlišovat barevné kartičky. Vidí hlavně modrou a žlutou, červenou od zelené skoro nerozeznají – červený míček v zelené trávě jim proto splývá.'),
  mytus('cinska-zed', 'Velká čínská zeď je vidět z Měsíce pouhým okem.', false,
    ['Co říkali astronauti, kteří byli na Měsíci?'],
    'Astronauti, kteří byli na Měsíci, řekli, že odtud žádná stavba vidět není – jen oceány, pevniny a mraky. Zeď je dlouhá, ale úzká, a ani první čínský astronaut ji z vesmírné lodi neviděl.'),
  mytus('svetr-hreje', 'Svetr sám vyrábí teplo.', false,
    ['Co se stane s teploměrem zabaleným do svetru?'],
    'Vyzkoušej pokus: zabal teploměr do svetru. Teplota nestoupne, protože svetr teplo nevyrábí – jen drží teplo tvého těla. Teplo drží hlavně vzduch uvězněný mezi vlákny.'),
  mytus('poust-noc', 'Na poušti je vždycky horko, ve dne i v noci.', false,
    ['Meteorologové na pouštích měří teplotu.'],
    'Meteorologové měří teplotu na pouštích: v noci se tam často rychle ochladí, někdy až k nule nebo i pod ni. Suchý vzduch bez mraků totiž teplo z písku rychle pustí k obloze.'),
  mytus('kachna-ozvena', 'Kachní kvákání nedělá ozvěnu.', false,
    ['Vědci to vyzkoušeli s nahrávkou.'],
    'Vědci to vyzkoušeli: nahráli kvákání kachny v místnosti s ozvěnou a ozvěnu naměřili. Jen je tichá a splyne s koncem kvákání, a tak se snadno přeslechne.'),
  mytus('ropucha-bradavice', 'Když vezmeš do ruky ropuchu, naskočí ti bradavice.', false,
    ['Co bradavice způsobuje, zjistili lékaři.'],
    'Lékaři zjistili, že bradavice způsobují drobounké viry, které se přenášejí mezi lidmi. Hrbolky na kůži ropuchy jsou jen její žlázy a bradavice nikomu nepřenesou.'),
  mytus('stonozka-sto', 'Stonožka má vždycky přesně sto nohou.', false,
    ['Vědci stonožkám nohy spočítali.'],
    'Vědci stonožkám nohy počítali: podle druhu mají od třiceti do víc než tří set nohou. Přesně sto nenašli u žádné – sto nohou je 50 párů, ale párů nohou mají stonožky skoro vždycky lichý počet.'),
  mytus('vlci-mesic', 'Vlci vyjí na Měsíc.', false,
    ['Proč si vlci dávají znamení?'],
    'Přírodovědci vlky pozorovali: vytím si dávají znamení se smečkou. Vyjí i za noci bez Měsíce a hlavu zvedají, aby je bylo slyšet dál – i na několik kilometrů.'),
  mytus('pavouk-sit', 'Pavouk se zamotá do své vlastní sítě.', false,
    ['Po kterých vláknech pavouk chodí?'],
    'Přírodovědci pavouky zkoumali pod mikroskopem: chodí hlavně po vláknech, která nelepí, a jejich nohy se k lepkavým vláknům skoro nepřichytí. Starou síť pavouk často sní a upřede novou.'),
];

// ---------------------------------------------------------------------------
// L5 – fyzika, vesmír a příbuzenství živých tvorů; i vědci měnili názor

const L5: Spec[] = [
  mytus('blesk-slunce', 'Blesk je teplejší než povrch Slunce.', true,
    ['Vědci zkoumali světlo blesku přístroji.'],
    'Vědci zkoumali světlo blesku přístroji: vzduch v něm se na okamžik rozpálí asi na třicet tisíc stupňů. Povrch Slunce má asi pět a půl tisíce stupňů, takže blesk je víc než pětkrát teplejší.'),
  mytus('pirko-kladivko', 'Na Měsíci padá kladívko a pírko stejně rychle.', true,
    ['Astronaut to na Měsíci vyzkoušel před kamerou.'],
    'Astronaut David Scott to v roce 1971 na Měsíci vyzkoušel před kamerou: kladívko a sokolí pírko dopadly současně. Na Zemi pírko brzdí vzduch, na Měsíci žádný vzduch není.'),
  mytus('zvuk-vzduch', 'Ve vzduchoprázdnu se zvuk nešíří.', true,
    ['Vědci dali zvonek pod skleněný zvon a odsávali vzduch.'],
    'Vědci to ukázali pokusem: dali zvonek pod skleněný zvon a odsávali vzduch. Zvonek dál zvonil, ale čím méně vzduchu tam bylo, tím hůř ho bylo slyšet. Proto astronauti venku ve vesmíru mluví vysílačkou.'),
  mytus('venuse', 'Nejteplejší planetou není Merkur, i když je nejblíž Slunci.', true,
    ['Sondy měřily teplotu na planetách.'],
    'Sondy naměřily, že na Venuši je přes 400 stupňů – víc než na Merkuru. Hustá atmosféra tam drží teplo jako peřina a je tam tak horko, že by se roztavilo i olovo.'),
  mytus('slunce-osm-minut', 'Světlo ze Slunce k nám letí asi osm minut.', true,
    ['Astronomové změřili vzdálenost Slunce i rychlost světla.'],
    'Astronomové změřili vzdálenost Slunce i rychlost světla a vyšlo jim, že paprsek letí na Zemi něco přes osm minut. Slunce na obloze tedy vidíme takové, jaké bylo před osmi minutami.'),
  mytus('zelvusky', 'Drobní živočichové želvušky vydrželi deset dní venku ve vesmíru.', true,
    ['Vědci je vynesli do vesmíru na družici.'],
    'Vědci to vyzkoušeli pokusem: v roce 2007 vynesli vysušené želvušky na družici a nechali je deset dní venku ve vesmíru. Mnohé se pak na Zemi ve vodě probraly – a přitom bývají menší než milimetr.'),
  mytus('ptaci-dinosauri', 'Ptáci jsou potomci dinosaurů.', true,
    ['Porovnej kostru ptáka a malého dinosaura.'],
    'Vědci porovnávali kostry ptáků a dinosaurů a našli zkameněliny dinosaurů s peřím. Nejbližšími žijícími příbuznými tyranosaura jsou tak vlastně ptáci – třeba i slepice.'),
  mytus('houby-zvirata', 'Houby mají blíž ke zvířatům než k rostlinám.', true,
    ['Vědci porovnávali dědičnou informaci.'],
    'Vědci porovnali dědičnou informaci hub, rostlin a zvířat a houby vyšly příbuznější zvířatům. Jako zvířata si totiž neumějí vyrobit potravu ze světla – musí ji získat odjinud.'),
  mytus('jahoda-plody', 'Zrníčka na povrchu jahody jsou ve skutečnosti malé plody.', true,
    ['Botanici zkoumali, jak jahoda roste.'],
    'Botanici zkoumali, jak jahoda roste: každé zrníčko je malý plod se semínkem uvnitř. Na jedné jahodě jich bývá kolem dvou set a červená dužina je zduřelá část květu.'),
  mytus('kov-drevo', 'Kovová lžíce a dřevěná vařečka vedle sebe mají stejnou teplotu, i když lžíce víc studí.', true,
    ['Změř je teploměrem.'],
    'Teploměr to ukáže: obě mají teplotu místnosti. Kov jen rychleji odvádí teplo z ruky, a proto se zdá studenější – stejně jako dlažba v koupelně vedle koberce.'),
  mytus('delfin-spanek', 'Delfín umí spát tak, že jedna polovina mozku odpočívá a druhá hlídá.', true,
    ['Vědci měřili činnost mozku přístroji.'],
    'Vědci to změřili přístroji, které sledují činnost mozku. Delfín tak může spát a přitom plavat a vynořovat se k nadechnutí – jedno oko má při tom otevřené.'),
  mytus('sklo-tece', 'Sklo ve starých oknech za stovky let pomalu steklo dolů.', false,
    ['Vědci spočítali, jak rychle by sklo teklo.'],
    'Vědci spočítali, že by sklo stékalo déle, než existuje vesmír. Staré tabule bývají dole tlustší proto, že byly nerovné už od výroby a sklenáři je dávali tlustší stranou dolů.'),
  mytus('umyvadlo', 'Voda v umyvadle se na jižní polovině Země točí vždycky opačně než u nás.', false,
    ['Vědci měřili, jak silně působí otáčení Země.'],
    'Vědci změřili, že otáčení Země působí na tak malé množství vody jen nepatrně. Směr víru v umyvadle určí hlavně jeho tvar a to, jak voda natekla – točí se na obě strany všude na světě.'),
  mytus('pluto', 'Pluto je devátá planeta Sluneční soustavy.', false,
    ['Co astronomové objevili za Neptunem?'],
    'Astronomové objevili za Neptunem mnoho podobných těles. V roce 2006 se proto na sjezdu v Praze dohodli, že Pluto je trpasličí planeta – a učebnice se opravily podle nových objevů.'),
  mytus('tezsi-rychleji', 'Těžší věci padají vždycky rychleji než lehčí.', false,
    ['Vědci pouštěli koule stejné velikosti, ale různé váhy.'],
    'Pokusy ukázaly, že těžká a lehká koule stejné velikosti puštěné zároveň dopadnou skoro současně. Rozdíl dělá hlavně vzduch: zmačkaný papír spadne rychleji než stejný papír rozložený, i když váží stejně.'),
  mytus('auto-pneumatiky', 'Před bleskem chrání lidi v autě gumové pneumatiky.', false,
    ['Vědci zkoušeli pokusy s umělým bleskem.'],
    'Vědci to zkoumali pokusy s umělým bleskem: proud projde kovovou karoserií kolem lidí do země. V autě s plechovou střechou jsi při bouřce opravdu v bezpečí – díky kovu, ne díky gumě.'),
  mytus('odvracena-strana', 'Odvrácená strana Měsíce je pořád ve tmě.', false,
    ['Svítí Slunce na celý Měsíc?'],
    'Astronomové vědí, že na odvrácenou stranu svítí Slunce stejně často jako na přivrácenou. Jen ji ze Země nevidíme – poprvé ji vyfotila až sonda Luna 3 v roce 1959.'),
  mytus('mesic-u-obzoru', 'Měsíc nízko nad obzorem je doopravdy větší než vysoko na obloze.', false,
    ['Jak by se dala velikost Měsíce porovnat?'],
    'Když Měsíc vyfotíš nízko nad obzorem i vysoko na obloze a fotky porovnáš, je stejně velký. Větší se jen zdá, protože nás oklame mozek – u obzoru je Měsíc od nás dokonce o kousek dál.'),
  mytus('pes-sedm-let', 'Jeden psí rok je vždycky přesně jako sedm lidských.', false,
    ['Veterináři porovnávali, jak psi dospívají.'],
    'Veterináři porovnávali, jak psi dospívají: za první rok pes dospěje asi tolik jako člověk za patnáct let. Velcí psi pak stárnou rychleji než malí, takže pravidlo „krát sedm“ je jen hrubý odhad.'),
  mytus('dinosauri-zaroven', 'Všichni dinosauři žili ve stejnou dobu.', false,
    ['Vědci určovali stáří zkamenělin.'],
    'Vědci určili stáří zkamenělin: dinosauři žili přes 150 milionů let a mnoho druhů se nikdy nepotkalo. Tyranosaurus žil časově blíž k nám než ke stegosaurovi.'),
  mytus('kompas-pol', 'Střelka kompasu ukazuje přesně k severnímu pólu.', false,
    ['Vědci změřili, kde je magnetický pól.'],
    'Vědci změřili, že střelka ukazuje k severnímu magnetickému pólu, a ne přesně k zeměpisnému. Magnetický pól je od něj kus vzdálený a každý rok se o desítky kilometrů posune.'),
];

export const mytusBanks = { 1: L1, 2: L2, 3: L3, 4: L4, 5: L5 };
