// Dračí detektivka – krátké útulné záhady (3–8 vět) bez zločinu a násilí:
// kdo snědl koláč, čí stopy vedou ke stodole, kde je ztracený klíč. Otázky:
// kdo to byl, která stopa to prozradila, co víme jistě a co jen tušíme.
// Ze stop vždy vyplývá právě jedna odpověď; ostatní podezřelé stopy vyřadí.
// Vysvětlení je zajímavost (ukáže se i po správné odpovědi): úvaha nad
// stopami a k ní navazující detail o stopách nebo o detektivní práci.

import type { Spec } from '../../core/bank';
import type { Visual } from '../../core/types';
import { q, text } from './kriticke-common';

// ---------------------------------------------------------------------------
// L2 – jedna jasná stopa, podezřelí s jasnou výmluvou

const KOLAC: Visual = text('Kdo ochutnal koláč?', 'Babička Sigrid upekla borůvkový koláč a dala ho na okno vychladnout. Za chvíli z něj chyběl kousek. Kočka Mína celou dobu spala na peci. Na parapetu zůstaly fialové otisky malých dračích tlapek. Dráček Kamínek měl fialovou pusu.');
const KLIC: Visual = text('Kde je klíč od kůlny?', 'Dědeček Knut hledá klíč od kůlny. Ráno ho dal do kapsy zahradnické zástěry. Pak zaléval záhony a zástěru pověsil na věšák v předsíni. Kapsy kalhot i bundy už prohledal. Klíč nikde.');
const STOPY_SNIH: Visual = text('Stopy ve sněhu', 'Od domu ke stodole vedou ve sněhu malé stopy. Každá má čtyři kulaté polštářky a nejsou na ní vidět drápy. Pes Brok leží celé ráno u kamen. Koza Béta je zavřená v chlívku a dědeček je od rána v dílně. Kočka Micka se právě vrací ze stodoly se sněhem na tlapkách.');
const RYBICKY: Visual = text('Kdo nakrmil rybičky?', 'Tove ráno zjistila, že v akváriu plavou kousky krmení. Maminka je od rána v práci. Tatínek ještě spí. U akvária stojí otevřená krabička s krmením a vedle ní leží Tomova čepice. Tom se usmívá: „Rybičky měly hlad.“');
const PONOZKA: Visual = text('Kam zmizela ponožka?', 'Liv pověsila na šňůru pět ponožek. Večer tam visely jen čtyři. Pod šňůrou ležel v trávě kolíček. Pes Brok měl v pelíšku něco pruhovaného a vesele vrtěl ocasem.');
const SNEHULAK: Visual = text('Kdo postavil sněhuláka?', 'Večer byla zahrada ještě prázdná. V osm ráno na ní stál sněhulák s mrkví místo nosu. Tatínek odjel na hory už včera odpoledne. Ivar spal až do devíti. Runa vstala brzy a teď má mokré rukavice. Z lednice chybí jedna mrkev.');
const RYBA: Visual = text('Který dráček vzal rybu?', 'Rybář Leif nechal na molu košík s rybami. Když se vrátil, jedna ryba chyběla. Na molu byly mokré stopy, které vedly k jezeru. Dráček Jiskra se celé odpoledne vyhříval na skále a je úplně suchý. Dráček Mech spal v jeskyni a chrápal. Dráček Vlnka právě vylezl z vody.');
const KYTKY: Visual = text('Kdo zalil kytky?', 'Maja odjela na týden k babičce a prosila, ať jí někdo zalévá kytky. Když se vrátila, hlína v květináčích byla vlhká. Bo byl celý týden nemocný v posteli. Erik má na teniskách hlínu a v kapse klíč od Majina bytu.');
const KNIHA: Visual = text('Kde je kniha o hvězdách?', 'Ingrid si půjčila z knihovny knihu o hvězdách. Večer si v ní četla na zahradě pod dekou. Ráno knihu nemohla najít v pokoji. Na zahradě leží složená deka a pod ní něco hranatého.');

const L2: Spec[] = [
  q('kolac-kdo', 'Kdo ochutnal koláč?', 'Dráček Kamínek',
    ['Kočka Mína', 'Babička Sigrid', 'Nikdo, koláč se zmenšil sám'],
    ['Čí otisky zůstaly na parapetu?'],
    'Na parapetu byly otisky dračích tlapek a Kamínek měl fialovou pusu od borůvek. Kočka Mína celou dobu spala na peci, takže to být nemohla.',
    { visual: KOLAC }),
  q('kolac-stopa', 'Která stopa prozradila, kdo to byl?', 'Otisky dračích tlapek',
    ['Koláč na okně', 'Kočka na peci', 'Borůvky v koláči'],
    ['Která stopa ukazuje na draka?'],
    'Otisky tlapek prozradily, že na okně byl dráček, a fialová pusa, že to byl právě Kamínek. Koláč ani spící kočka nikoho neprozradí.',
    { visual: KOLAC }),
  q('klic-kde', 'Kde by měl dědeček hledat nejdřív?', 'V kapse zástěry na věšáku',
    ['V kapse kalhot', 'V kapse bundy', 'Na dně studny'],
    ['Kam dědeček klíč ráno dal?'],
    'Ráno dal dědeček klíč do zástěry a ta teď visí v předsíni. Kalhoty i bundu už prohledal – a ztracenou věc je nejlepší hledat tam, kde byla naposledy.',
    { visual: KLIC }),
  q('klic-jiste', 'Co o klíči víme jistě?', 'Ráno byl v kapse zástěry',
    ['Teď je v kapse zástěry', 'Někdo si ho vzal', 'Spadl do záhonu'],
    ['Co se v příběhu opravdu stalo a co jen tušíme?'],
    'Jistě víme jen to, že ráno byl klíč v zástěře. Jestli tam je i teď, zatím jen tušíme – mohl vypadnout třeba při zalévání.',
    { visual: KLIC }),
  q('stopy-kdo', 'Čí stopy vedou ke stodole?', 'Kočky Micky',
    ['Psa Broka', 'Kozy Béty', 'Dědečkovy'],
    ['Kdo se právě vrací ze stodoly?'],
    'Micka se vrací ze stodoly se sněhem na tlapkách a kočičí stopy nemají otisky drápů – kočka je při chůzi schovává. Brok leží u kamen, Béta je zavřená a dědeček je v dílně.',
    { visual: STOPY_SNIH }),
  q('stopy-dukaz', 'Který důkaz nejvíc ukazuje na Micku?', 'Má sníh na tlapkách',
    ['Ráno bylo zima', 'Stodola je velká', 'Micka je zrzavá'],
    ['Čím se Micka liší od ostatních v příběhu?'],
    'Sníh na tlapkách prozrazuje, že Micka právě chodila venku. Zima ani velikost stodoly nikoho neprozradí – platí pro všechny stejně.',
    { visual: STOPY_SNIH }),
  q('rybicky-kdo', 'Kdo rybičky nakrmil?', 'Tom',
    ['Maminka', 'Tatínek', 'Tove'],
    ['Čí věc leží u krabičky s krmením?'],
    'U krmení leží Tomova čepice a Tom sám řekl, že rybičky měly hlad. Maminka je v práci a tatínek spí – dvě stopy dohromady ukazují na Toma.',
    { visual: RYBICKY }),
  q('rybicky-maminka', 'Proč to nebyla maminka?', 'Je od rána v práci',
    ['Nemá ráda rybičky', 'Neumí otevřít krabičku', 'Je moc vysoká'],
    ['Kde je maminka?'],
    'Maminka je od rána v práci, takže rybičky krmit nemohla – detektivové tomu říkají alibi. Ostatní důvody se v příběhu vůbec nepíšou.',
    { visual: RYBICKY }),
  q('ponozka-kde', 'Kde je nejspíš ztracená ponožka?', 'V pelíšku u Broka',
    ['Na šňůře', 'V pračce', 'Odletěla za mraky'],
    ['Co pruhovaného měl Brok v pelíšku?'],
    'V Brokově pelíšku je něco pruhovaného a Brok vesele vrtí ocasem. Nejspíš si ponožku odnesl na hraní – psi rádi nosí věci, které voní jejich lidmi.',
    { visual: PONOZKA }),
  q('ponozka-jiste', 'Co víme jistě?', 'Na šňůře chybí jedna ponožka',
    ['Brok ponožku roztrhal', 'Ponožku odnesl vítr', 'Je to Livina nejoblíbenější'],
    ['Co Liv viděla na vlastní oči?'],
    'Jistě víme, že z pěti ponožek zbyly čtyři. Že je ponožka u Broka, zatím jen tušíme – ověří se to, až se Liv podívá do pelíšku.',
    { visual: PONOZKA }),
  q('snehulak-kdo', 'Kdo postavil sněhuláka?', 'Runa',
    ['Ivar', 'Tatínek', 'Sněhulák se postavil sám'],
    ['Kdo mohl být v osm ráno na zahradě?', 'Kdo má mokré rukavice?'],
    'Runa vstala brzy a má mokré rukavice od sněhu. Ivar v osm ještě spal a tatínek odjel už odpoledne, kdy byla zahrada ještě prázdná.',
    { visual: SNEHULAK }),
  q('snehulak-stopa', 'Která stopa ukazuje na Runu?', 'Má mokré rukavice',
    ['Sněhulák má nos z mrkve', 'Je zima', 'Zahrada je velká'],
    ['Co má Runa jinak než ostatní?'],
    'Mokré rukavice prozrazují, že Runa pracovala se sněhem. Chybějící mrkev ukazuje jen na to, že někdo sahal do lednice.',
    { visual: SNEHULAK }),
  q('ryba-kdo', 'Který dráček vzal rybu?', 'Vlnka',
    ['Jiskra', 'Mech', 'Rybář Leif'],
    ['Kam vedly mokré stopy?'],
    'Mokré stopy vedly k jezeru a Vlnka právě vylezl z vody. Jiskra je úplně suchý a Mech spal v jeskyni.',
    { visual: RYBA }),
  q('ryba-jiskra', 'Proč to nebyl Jiskra?', 'Je úplně suchý',
    ['Nemá rád ryby', 'Je moc malý', 'Neumí chodit'],
    ['Jaké byly stopy na molu?'],
    'Stopy byly mokré a vedly k jezeru, ale Jiskra se celé odpoledne vyhříval na skále a je suchý. Ze suchého draka mokré stopy nezůstanou.',
    { visual: RYBA }),
  q('kytky-kdo', 'Kdo nejspíš kytky zaléval?', 'Erik',
    ['Bo', 'Maja', 'Kytky se zalévaly samy'],
    ['Kdo se mohl dostat do bytu?'],
    'Erik má klíč od Majina bytu a na teniskách hlínu. Bo byl celý týden nemocný a Maja byla u babičky.',
    { visual: KYTKY }),
  q('kytky-jiste', 'Co víme jistě?', 'Hlína v květináčích je vlhká',
    ['Erik zaléval každý den', 'Bo nemá rád kytky', 'Kytky vyrostly'],
    ['Co Maja viděla na vlastní oči?'],
    'Vlhkou hlínu Maja viděla. Že Erik zaléval každý den, jen tušíme – mohl zalít jednou pořádně.',
    { visual: KYTKY }),
  q('kniha-kde', 'Kde je kniha nejspíš?', 'Pod dekou na zahradě',
    ['V knihovně', 'Na poličce v pokoji', 'U kamarádky'],
    ['Kde si Ingrid večer četla?'],
    'Ingrid četla na zahradě pod dekou a pod složenou dekou je něco hranatého – přesně jako kniha.',
    { visual: KNIHA }),
  q('kniha-overit', 'Jak si to Ingrid nejrychleji ověří?', 'Podívá se pod deku',
    ['Zeptá se hvězd', 'Půjčí si jinou knihu', 'Bude čekat'],
    ['Stopa leží přímo na zahradě.'],
    'Nejrychlejší je podívat se pod deku. Dobrý detektiv tip vždycky ověří, než řekne, že záhadu vyřešil.',
    { visual: KNIHA }),
];

// ---------------------------------------------------------------------------
// L3 – víc podezřelých, výmluvy a otázka „co víme jistě?“

const MOUKA: Visual = text('Stopy v mouce', 'V pekárně někdo v noci ochutnal perník. Pekař Dag ráno našel na podlaze rozsypanou mouku a v ní otisky malých kopýtek. Kočka z pekárny spala zavřená v kanceláři. Dráček Uhlík spal celou noc u Daga doma. Sousedova koza Líza večer utekla z ohrady.');
const DESTNIK: Visual = text('Čí je deštník?', 'Po besídce zůstal ve třídě zapomenutý deštník. Je malý, žlutý a má na rukojeti samolepku s lodičkou. Anna nosí jen zelené věci. Knut má deštník modrý. Petr říká, že deštník nikdy nemá. Liv má na penále stejnou samolepku s lodičkou.');
const DAREK: Visual = text('Tajemný dárek', 'Na Frejině lavici ležel ráno balíček s mašlí. Na přáníčku stálo jen: „Pro Freju.“ Písmena byla napsaná modrým perem. Jonas píše jen tužkou. Tom je od včerejška nemocný doma. Maja má modré pero a včera kupovala mašle.');
const PUDA: Visual = text('Dupání na půdě', 'Ivar slyšel brzy ráno na půdě dupání. Pak tam našel rozkousané žaludy a na trámu malé stopy. Kočka byla v tu dobu zavřená v kuchyni. V okénku na půdu je díra a v ní se zachytil chomáček rezavé srsti.');
const MRKVE: Visual = text('Záhada ze zahrady', 'Ze záhonu zmizely tři mrkve. Kolem záhonu je plot a pod ním je vyhrabaná malá díra. V díře uvízlo pár šedých chlupů. Pes Brok je velký a pod plot se nevejde. Zrzavá kočka Mína mrkve nejí. Králík Ušák od sousedů má šedou srst.');
const KOUPELNA: Visual = text('Mokrá koupelna', 'V koupelně je mokrá podlaha a na ní stopy bosých nohou. Stopy jsou malé, mnohem menší než tatínkova bota. Tatínek je v práci. Erik se právě vrátil z plavání a má mokré vlasy. Sigrid ještě spí.');
const OBRAZEK: Visual = text('Kdo namaloval draka?', 'Na nástěnce visí obrázek draka bez podpisu. Je namalovaný vodovkami a v rohu je fialový otisk palce. Tove maluje jen pastelkami. Alva kreslí jen fixami. Knut byl celý den na výletě. Leif měl ráno na palci fialovou skvrnu.');
const LUCERNA: Visual = text('Světlo v zahradním domku', 'V noci se v zahradním domku rozsvítila lucerna na baterky. Ráno v domku ležela otevřená kniha o hvězdách a dalekohled. Večer si dalekohled půjčovala Ingrid, protože chtěla pozorovat Měsíc. Bo se bojí tmy a v noci z domu nechodí. Tatínek celou noc spal a chrápal.');
const HOLINKY: Visual = text('Cizí holínky', 'V předsíni stojí cizí mokré holínky velikosti 30. Leif nosí boty velikosti 34. Maminka nosí velikost 38. Dag má jen tenisky. Runa přišla na návštěvu v dešti a sedí v kuchyni v ponožkách.');

const L3: Spec[] = [
  q('mouka-kdo', 'Kdo ochutnal perník?', 'Koza Líza',
    ['Kočka z pekárny', 'Dráček Uhlík', 'Pekař Dag'],
    ['Jaké otisky zůstaly v mouce?'],
    'Otisky kopýtek patří koze a koza Líza večer utekla z ohrady. Kočka byla zavřená v kanceláři a Uhlík spal u Daga doma.',
    { visual: MOUKA }),
  q('mouka-stopa', 'Která stopa ukazuje přímo na kozu?', 'Otisky kopýtek v mouce',
    ['Rozsypaná mouka', 'Chybějící perník', 'Kočka v kanceláři'],
    ['Kdo z podezřelých má kopýtka?'],
    'Kopýtka má jen koza – kočka i drak mají tlapky. Rozsypaná mouka a chybějící perník jen ukazují, že tu někdo byl.',
    { visual: MOUKA }),
  q('destnik-kdo', 'Čí je deštník nejspíš?', 'Livin',
    ['Annin', 'Petrův', 'Knutův'],
    ['Vyřaď nejdřív ty, kterým deštník patřit nemůže.', 'Kdo má stejnou samolepku?'],
    'Liv má stejnou samolepku s lodičkou jako deštník. Anna nosí jen zelené věci, Knutův deštník je modrý a Petr deštník nemá.',
    { visual: DESTNIK }),
  q('destnik-overit', 'Jak se dá jistě ověřit, že je deštník Livin?', 'Zeptat se Liv, jestli ho poznává',
    ['Podívat se na počasí', 'Zeptat se Petra', 'Schovat ho do skříně'],
    ['Stejná samolepka je silná stopa, ale ne jistota.'],
    'Samolepka je silná stopa, ale stejnou může mít i někdo jiný. Jistotu dá až Liv, když deštník pozná.',
    { visual: DESTNIK }),
  q('darek-kdo', 'Kdo nejspíš nechal dárek?', 'Maja',
    ['Jonas', 'Tom', 'Freja'],
    ['Čím bylo napsané přáníčko?'],
    'Přáníčko je psané modrým perem a Maja ho má. Navíc včera kupovala mašle. Jonas píše tužkou a Tom je od včerejška nemocný doma.',
    { visual: DAREK }),
  q('darek-jiste', 'Co z toho víme jistě?', 'Přáníčko je psané modře',
    ['Dárek koupila Maja', 'Maja má Freju nejraději', 'Jonas nemá rád dárky'],
    ['Co je v příběhu opravdu vidět?'],
    'Modré písmo vidí každý. Že dárek dala Maja, je zatím jen silné tušení – modré pero může mít i někdo další.',
    { visual: DAREK }),
  q('puda-kdo', 'Kdo nejspíš dupal na půdě?', 'Veverka',
    ['Kočka', 'Vítr', 'Ivar'],
    ['Kdo má rezavou srst a rád jí žaludy?'],
    'Rezavá srst a rozkousané žaludy ukazují na veverku – ta si žaludy a oříšky schovává na zimu. Kočka byla zavřená v kuchyni a vítr žaludy nekouše.',
    { visual: PUDA }),
  q('puda-kocka', 'Proč to nebyla kočka?', 'Byla zavřená v kuchyni',
    ['Nemá chlupy', 'Neumí dupat', 'Bojí se tmy'],
    ['Kde byla kočka, když se ozývalo dupání?'],
    'Kočka byla v tu dobu zavřená v kuchyni, takže na půdě být nemohla. Detektivové tomu říkají alibi.',
    { visual: PUDA }),
  q('mrkve-kdo', 'Kdo nejspíš snědl mrkve?', 'Králík Ušák',
    ['Pes Brok', 'Kočka Mína', 'Kos'],
    ['Jaké chlupy uvízly v díře pod plotem?'],
    'Pod plotem je malá díra se šedými chlupy a Ušák má šedou srst. Brok se pod plot nevejde, Mína je zrzavá a mrkve nejí a kos chlupy nemá.',
    { visual: MRKVE }),
  q('mrkve-stopa', 'Která stopa ukazuje na Ušáka?', 'Šedé chlupy v díře',
    ['Chybějí tři mrkve', 'Kolem záhonu je plot', 'Brok je velký'],
    ['Která stopa se hodí jen k Ušákovi?'],
    'Šedé chlupy se hodí k Ušákovi. Chybějící mrkve a plot jen ukazují, co se stalo a kudy.',
    { visual: MRKVE }),
  q('koupelna-jiste', 'Co víme jistě?', 'V koupelně chodil někdo bosý',
    ['Byl to určitě Erik', 'Sigrid se sprchovala', 'Tatínek zapomněl ručník'],
    ['Co je v koupelně opravdu vidět?'],
    'Jistě víme, že v koupelně chodil bosý někdo s malýma nohama. Kdo to byl, zatím jen tušíme.',
    { visual: KOUPELNA }),
  q('koupelna-vlasy', 'Proč Erikovy mokré vlasy nejsou jistý důkaz?', 'Mohl je mít mokré z plavání',
    ['Vlasy nikdy nejsou mokré', 'Erik nemá vlasy', 'Protože Erik je malý'],
    ['Odkud se Erik právě vrátil?'],
    'Erik se vrátil z plavání, takže vlasy mohl mít mokré odtamtud. Stopa, která má víc vysvětlení, není jistý důkaz.',
    { visual: KOUPELNA }),
  q('obrazek-kdo', 'Kdo nejspíš namaloval draka?', 'Leif',
    ['Tove', 'Knut', 'Alva'],
    ['Co zůstalo v rohu obrázku?', 'Kdo měl na palci fialovou skvrnu?'],
    'V rohu obrázku je fialový otisk palce a Leif měl na palci fialovou skvrnu. Tove maluje pastelkami, Alva kreslí fixami a Knut byl na výletě.',
    { visual: OBRAZEK }),
  q('obrazek-overit', 'Jak by se dalo ověřit, že obrázek je Leifův?', 'Porovnat otisk s Leifovým palcem',
    ['Zeptat se Knuta', 'Změřit nástěnku', 'Podívat se na počasí'],
    ['Otisky prstů má každý jiné.'],
    'Otisky prstů má každý jiné, dokonce i dvojčata, která vypadají úplně stejně. Když se otisk na obrázku shoduje s Leifovým palcem, je to silný důkaz.',
    { visual: OBRAZEK }),
  q('lucerna-kdo', 'Kdo byl v noci v zahradním domku?', 'Ingrid',
    ['Bo', 'Tatínek', 'Nikdo, lucerna se rozsvítila sama'],
    ['Čí věc zůstala v domku?'],
    'V domku zůstal dalekohled, který si půjčovala Ingrid, a kniha o hvězdách. Bo v noci z domu nechodí a tatínek spal.',
    { visual: LUCERNA }),
  q('lucerna-jiste', 'Co víme jistě?', 'V noci v domku svítila lucerna',
    ['Ingrid viděla Měsíc', 'Bo spal celou noc', 'Tatínek nic neslyšel'],
    ['Co se v noci opravdu stalo?'],
    'Světlo v domku bylo vidět. Jestli Ingrid Měsíc opravdu viděla, nevíme – mohlo být zataženo.',
    { visual: LUCERNA }),
  q('holinky-kdo', 'Čí jsou holínky nejspíš?', 'Runy',
    ['Leifovy', 'Dagovy', 'Maminčiny'],
    ['Komu by holínky velikosti 30 mohly padnout?', 'Kdo přišel v dešti a teď je v ponožkách?'],
    'Runa přišla v dešti a teď sedí v ponožkách, takže si boty zula. Leif i maminka mají větší nohu a Dag nosí tenisky.',
    { visual: HOLINKY }),
  q('detektiv-postup', 'Co udělá dobrý detektiv, když má podezření?', 'Hledá další stopy, než někoho obviní',
    ['Hned obviní prvního, koho vidí', 'Věří tomu, kdo nejvíc křičí', 'Stopy si nezapisuje'],
    ['Stačí jedno podezření?'],
    'Podezření je jen začátek. Dobrý detektiv sbírá další stopy a obviní někoho, až když do sebe všechno zapadá.'),
];

// ---------------------------------------------------------------------------
// L4 – čas, výmluvy (alibi), víc stop dohromady a vyřazování podezřelých

const MEDOVNIK: Visual = text('Poslední kousek medovníku', 'Babička dala poslední kousek medovníku na talíř v kuchyni ve dvě hodiny. Ve tři hodiny už byl talíř prázdný. Petr hrál od jedné do čtyř fotbal na hřišti. Pes Brok byl celé odpoledne s dědečkem na procházce. Jonas přijel na návštěvu až v pět. Alva říká, že celé odpoledne malovala v pokoji, ale na jejím obrázku jsou drobky.');
const KURNIK: Visual = text('Otevřený kurník', 'Ráno byla dvířka kurníku otevřená a slepice se procházely po zahradě. Dvířka mají háček, který zvenku otevře jen člověk. Tove večer viděla v kurníku Dagovu zapomenutou čepici. Pak Erik kurník zavřel a háček zapnul. Dag ráno běžel ke kurníku jako první a teď má čepici na hlavě.');
const PRSTYNEK: Visual = text('Ztracený prstýnek', 'Babička Sigrid sázela tulipány a pak zjistila, že nemá prstýnek. Při mytí nádobí po snídani ho ještě měla na ruce. Na zahradě měla rukavice a sundala si je jen jednou – když zalévala. U konve se v trávě něco zalesklo.');
const VZKAZ: Visual = text('Vzkaz na tabuli', 'Ráno se na tabuli objevil vzkaz: „Zítra přineste lepidlo!“ Je napsaný zelenou křídou a písmena jsou nakloněná doleva. Zelenou křídu mají jen paní učitelka a Ingrid, Petr má jen bílou. Paní učitelka píše písmena úplně rovně. Ingrid píše levou rukou a písmena naklání doleva.');
const SALA: Visual = text('Šála na lavičce', 'Na lavičce v parku zůstala pletená šála. Je modrá a dlouhá. Ingrid má šálu červenou. Knut šálu nikdy nenosí. Freja i Liv mají modré šály, ale Liv má tu svou právě na krku.');
const BLATO: Visual = text('Otisky v blátě', 'Před domem jsou v blátě otisky úzkých kol a vedle nich stopy bot. Pošťák jezdí autem se širokými pneumatikami. Dědeček chodí pěšky o holi. Tove k nám vždycky přijíždí na kole a u branky z něj sesedne.');
const NOS: Visual = text('Sněhulák bez nosu', 'Včera večer měl sněhulák na zahradě mrkev místo nosu. Ráno mrkev chyběla. Od sněhuláka k lesu vedly skupinky po čtyřech stopách – dvě kulaté a dvě protáhlé, jako by zvíře skákalo. Pes Brok spal celou noc v domě. Sousedův kocour mrkev nejí.');
const KLAVIR: Visual = text('Kdo hrál na klavír?', 'Odpoledne se z obýváku ozývala písnička Skákal pes. Hrála se pomalu a na konci s chybami. Maminka hraje na klavír výborně a bez chyb. Tatínek je v práci. Anna na klavír nehraje, jen ráda zpívá. Bo se na klavír učí teprve týden a zatím umí jen Skákal pes.');

const L4: Spec[] = [
  q('medovnik-kdo', 'Kdo nejspíš snědl medovník?', 'Alva',
    ['Petr', 'Jonas', 'Pes Brok'],
    ['Kdo byl odpoledne doma?', 'Co je na obrázku?'],
    'Petr byl na hřišti, Brok na procházce a Jonas přijel až v pět. Alva byla doma a na jejím obrázku jsou drobky.',
    { visual: MEDOVNIK }),
  q('medovnik-jonas', 'Proč to nemohl být Jonas?', 'Přijel, až když byl talíř prázdný',
    ['Nemá rád medovník', 'Byl na fotbale', 'Je moc malý'],
    ['Kdy zmizel medovník a kdy Jonas přijel?'],
    'Medovník zmizel mezi druhou a třetí hodinou. Jonas přijel až v pět, takže má výmluvu, která platí – alibi.',
    { visual: MEDOVNIK }),
  q('medovnik-stopa', 'Která stopa je proti Alvě nejsilnější?', 'Drobky na jejím obrázku',
    ['Maluje v pokoji', 'Petr hrál fotbal', 'Talíř stál v kuchyni'],
    ['Co by tam nemělo být, kdyby Alva jen malovala?'],
    'Drobky na obrázku by tam nebyly, kdyby Alva jen malovala. Ostatní věci o Alvě nic neprozrazují.',
    { visual: MEDOVNIK }),
  q('kurnik-kdo', 'Kdo nejspíš nechal kurník otevřený?', 'Dag',
    ['Erik', 'Tove', 'Liška'],
    ['Kdo byl u kurníku ráno a proč?'],
    'Večer Erik kurník zavřel a v kurníku zůstala Dagova čepice. Ráno běžel ke kurníku jako první Dag – a čepici má teď na hlavě. Liška háček zvenku neotevře.',
    { visual: KURNIK }),
  q('kurnik-stopa', 'Který důkaz ukazuje na Daga?', 'Má zase svou čepici',
    ['Slepice jsou na zahradě', 'Erik zavíral večer', 'Dvířka mají háček'],
    ['Kde byla čepice večer a kde je teď?'],
    'Večer byla čepice zavřená v kurníku. Když ji má Dag teď na hlavě, musel kurník otevřít – nikdo jiný tam ráno nebyl dřív.',
    { visual: KURNIK }),
  q('prstynek-kde', 'Kde je prstýnek nejspíš?', 'V trávě u konve',
    ['V kuchyni u nádobí', 'V záhonu s tulipány', 'Na stole od snídaně'],
    ['Kdy měla babička ruce bez rukavic?'],
    'Po mytí nádobí prstýnek ještě měla. Na zahradě ho chránily rukavice, sundala si je jen u konve – a právě tam se něco leskne.',
    { visual: PRSTYNEK }),
  q('prstynek-jiste', 'Co zatím víme jistě?', 'U konve se něco leskne',
    ['Prstýnek leží u konve', 'Prstýnek odnesla straka', 'Babička ho ztratila v kuchyni'],
    ['Co babička opravdu viděla?'],
    'Jistě víme jen to, že se u konve něco leskne. Že je to prstýnek, je silné tušení – ověří se, až se babička podívá.',
    { visual: PRSTYNEK }),
  q('vzkaz-kdo', 'Kdo napsal vzkaz?', 'Ingrid',
    ['Paní učitelka', 'Petr', 'Školník'],
    ['Kdo má zelenou křídu?', 'Kdo z nich píše písmena nakloněná doleva?'],
    'Zelenou křídu mají jen paní učitelka a Ingrid. Paní učitelka píše rovně, Ingrid naklání písmena doleva – i podle rukopisu se dá poznat, kdo psal.',
    { visual: VZKAZ }),
  q('vzkaz-stopy', 'Které dvě stopy dohromady ukazují na Ingrid?', 'Zelená křída a písmo nakloněné doleva',
    ['Velká písmena a lepidlo', 'Tabule a zítřek', 'Vykřičník a tabule'],
    ['Jedna stopa vyřadí ostatní děti, druhá paní učitelku.'],
    'Zelená křída zúží podezřelé na dvě. Písmo nakloněné doleva pak vyřadí paní učitelku. Teprve obě stopy dohromady ukážou na Ingrid.',
    { visual: VZKAZ }),
  q('sala-kdo', 'Čí je šála nejspíš?', 'Frejina',
    ['Ingridina', 'Knutova', 'Livina'],
    ['Kdo má modrou šálu a nemá ji u sebe?'],
    'Modrou šálu mají Freja a Liv. Liv má svou na krku, takže zapomenutá šála je nejspíš Frejina.',
    { visual: SALA }),
  q('sala-liv', 'Proč to není Livina šála?', 'Liv má svou šálu na krku',
    ['Liv nemá ráda modrou', 'Liv nechodí do parku', 'Liv je moc malá'],
    ['Kde je teď Livina šála?'],
    'Liv má svou modrou šálu právě na krku, takže ta na lavičce jí nepatří.',
    { visual: SALA }),
  q('blato-kdo', 'Kdo nejspíš přijel?', 'Tove',
    ['Pošťák', 'Dědeček', 'Nikdo'],
    ['Jaká kola nechávají úzké otisky?'],
    'Úzké otisky kol a stopy bot vedle nich sedí na kolo, ze kterého někdo sesedl. Tak přijíždí Tove. Pošťákovo auto má široká kola a dědeček chodí pěšky.',
    { visual: BLATO }),
  q('blato-jiste', 'Co víme jistě?', 'Že tu jelo něco s úzkými koly',
    ['Že přijela Tove', 'Že pošťák nepřijel', 'Že dědeček je doma'],
    ['Co je v blátě opravdu vidět?'],
    'Otisky úzkých kol vidíme. Že přijela Tove, je jen silné tušení – na kole mohl přijet i někdo jiný.',
    { visual: BLATO }),
  q('nos-kdo', 'Kdo nejspíš vzal mrkev?', 'Zajíc',
    ['Pes Brok', 'Sousedův kocour', 'Nikdo, mrkev roztála'],
    ['Které zvíře skáče, žije u lesa a má rádo mrkev?'],
    'Skupinky po čtyřech stopách nechává skákající zajíc – zadní nohy při skoku dopadnou před přední. Stopy vedly do lesa, Brok spal doma, kocour mrkev nejí a mrkev netaje.',
    { visual: NOS }),
  q('nos-brok', 'Proč to nebyl Brok?', 'Spal celou noc v domě',
    ['Nemá rád mrkev', 'Je moc malý', 'Neumí skákat'],
    ['Kde byl Brok v noci?'],
    'Brok spal celou noc v domě, takže na zahradě být nemohl. To je jeho alibi.',
    { visual: NOS }),
  q('klavir-kdo', 'Kdo nejspíš hrál na klavír?', 'Bo',
    ['Maminka', 'Tatínek', 'Anna'],
    ['Jak písnička zněla?', 'Kdo se na klavír teprve učí?'],
    'Písnička zněla pomalu a s chybami. Maminka hraje bez chyb, tatínek je v práci a Anna nehraje. Bo se učí týden a umí právě Skákal pes.',
    { visual: KLAVIR }),
  q('klavir-stopa', 'Která stopa pomohla nejvíc?', 'Hrálo se pomalu a s chybami',
    ['Klavír je v obýváku', 'Anna ráda zpívá', 'Bylo odpoledne'],
    ['Co vyřadilo maminku?'],
    'Pomalé hraní s chybami se hodí k začátečníkovi, a ne k mamince. Ostatní věci nikoho neprozradí.',
    { visual: KLAVIR }),
  q('alibi', 'Co je alibi?', 'Důkaz, že podezřelý byl jinde',
    ['Jméno detektiva', 'Stopa v blátě', 'Druh lupy'],
    ['Vzpomeň si na Jonase a medovník.'],
    'Alibi je důkaz, že podezřelý byl v tu dobu jinde – třeba že Jonas přijel až v pět. Slovo alibi pochází z latiny a znamená „jinde“.'),
];

// ---------------------------------------------------------------------------
// L5 – logické vyřazování, časová osa, hra na lháře a spory v nápovědách

const LED: Visual = text('Srdce v ledu', 'Ráno se v ledu na zamrzlém jezeře objevila roztátá díra ve tvaru srdce. Led roztál teplem, takže to udělal drak, který chrlí oheň. Na ledu zůstaly stopy se čtyřmi drápy.\nOhnivec chrlí oheň a má tři drápy.\nJiskřička chrlí oheň a má čtyři drápy.\nMlhoun má čtyři drápy, ale chrlí jen mlhu.\nUhlík chrlí oheň a má čtyři drápy, ale celou noc spal v jeskyni a Liv ho hlídala.');
const ATLAS: Visual = text('Písek v atlase', 'Knihovnice Runa našla ve středu ráno v atlase hub písek. V knihovním sešitu má zapsáno: Ivar si atlas půjčil v pondělí a vrátil ho v úterý večer. Maja si ho půjčila až ve středu odpoledne. Ivar byl v pondělí odpoledne se sestrou na pískovišti.');
const LHARI: Visual = text('Hra na lháře', 'Děti hrají hru na lháře: dvě z nich schválně mluví nepravdu a jedno říká pravdu. Jedno z nich snědlo poslední palačinku.\nTom říká: „Snědla ji Alva.“\nAlva říká: „Já ne.“\nPetr říká: „Já ne.“');
const SATKY: Visual = text('Zapomenutý šátek', 'Po návštěvě zůstal na věšáku zelený šátek. Na návštěvě byly tři dračice: Hvězdička, Kapka a Perla. Každá přišla v šátku jiné barvy: jedna v červeném, jedna v modrém a jedna v zeleném. Kapka nosí jen modrou. Hvězdička zelený šátek nemá.');
const KOLO: Visual = text('Kolo na hodinu', 'Tatínkovo kolo zmizelo z garáže a za hodinu bylo zpátky. Zámek na kole má číselný kód, který znají jen tatínek, Dag a Liv. Tatínek byl celou dobu na schůzce. Dag byl celou hodinu na tréninku plavání. Sedátko je teď nastavené nízko, přesně jak ho má ráda Liv.');
const POKLAD: Visual = text('Hledání pokladu', 'Jonas schoval pro sestru poklad a nechal jí tři nápovědy.\n1. Poklad není u jabloně.\n2. Poklad je blíž k domu než k plotu.\n3. Poklad není v kůlně.\nNa zahradě jsou čtyři místa: jabloň, kůlna a pískoviště jsou u domu, lavička je u plotu.');
const KOSIK: Visual = text('Košík s jahodami', 'Někdo nechal u dveří košík s jahodami, zazvonil a schoval se. Sousedka Freja viděla odbíhat holku v červené bundě. Bo zahlédl dlouhý cop. Ingrid má modrou bundu a dlouhý cop. Maja má červenou bundu a krátké vlasy. Runa má červenou bundu a dlouhý cop.');

const L5: Spec[] = [
  q('led-kdo', 'Který drak roztavil v ledu srdce?', 'Jiskřička',
    ['Ohnivec', 'Mlhoun', 'Uhlík'],
    ['Vyřaď draky, kteří nechrlí oheň nebo nemají čtyři drápy.', 'Kdo má výmluvu, která platí?'],
    'Ohnivec má tři drápy a Mlhoun nechrlí oheň. Uhlík by se hodil, ale Liv ho celou noc hlídala. Zbývá Jiskřička.',
    { visual: LED }),
  q('led-uhlik', 'Proč to nebyl Uhlík, i když chrlí oheň a má čtyři drápy?', 'Má alibi, Liv ho hlídala',
    ['Neumí létat', 'Má jen tři drápy', 'Nechrlí oheň'],
    ['Kde byl Uhlík v noci?'],
    'Uhlík by se ke stopám hodil, ale celou noc spal v jeskyni a Liv ho hlídala. To je jeho alibi.',
    { visual: LED }),
  q('led-bez-alibi', 'Kdyby Uhlíka nikdo nehlídal, kolik draků by bylo podezřelých?', 'Dva',
    ['Jeden', 'Tři', 'Čtyři'],
    ['Kteří draci chrlí oheň a zároveň mají čtyři drápy?'],
    'Oheň a čtyři drápy mají Jiskřička i Uhlík. Bez alibi by byli podezřelí oba a detektiv by potřeboval další stopu.',
    { visual: LED }),
  q('atlas-kdo', 'Kdo mohl do atlasu zanést písek?', 'Ivar',
    ['Maja', 'Kdo si ho půjčí ve čtvrtek', 'Oba stejně'],
    ['Seřaď si, co se stalo v pondělí, v úterý a ve středu.'],
    'Písek našla Runa ve středu ráno. Do té doby měl atlas jen Ivar – a ten byl v pondělí na pískovišti. Maja si atlas půjčila až potom.',
    { visual: ATLAS }),
  q('atlas-maja', 'Proč to nemohla být Maja?', 'Písek tam byl dřív, než si atlas půjčila',
    ['Maja nemá ráda písek', 'Maja atlas nevrátila', 'Maja si ho půjčila v pondělí'],
    ['Kdy Runa písek našla a kdy si Maja atlas půjčila?'],
    'Runa našla písek ve středu ráno a Maja si atlas půjčila až ve středu odpoledne. Časová osa Maju vyřadí – co se stalo později, nemůže způsobit to, co bylo dřív.',
    { visual: ATLAS }),
  q('lhari-kdo', 'Kdo snědl palačinku?', 'Petr',
    ['Tom', 'Alva', 'Nikdo'],
    ['Zkus postupně každé dítě: co kdyby palačinku snědlo právě ono?', 'U každé možnosti spočítej, kolik dětí by mluvilo pravdu.'],
    'Kdyby to byla Alva, mluvili by pravdu Tom i Petr. Kdyby to byl Tom, mluvili by pravdu Alva i Petr. Jen když to byl Petr, mluví pravdu jediné dítě – Alva.',
    { visual: LHARI }),
  q('lhari-pravda', 'Kdo z dětí mluví pravdu?', 'Alva',
    ['Tom', 'Petr', 'Všechny tři'],
    ['Nejdřív zjisti, kdo palačinku snědl.'],
    'Palačinku snědl Petr. Pravdu tedy mluví jen Alva, když říká „Já ne“. Tom i Petr mluví nepravdu, jak to hra vyžaduje.',
    { visual: LHARI }),
  q('satky-kdo', 'Která dračice přišla v zeleném šátku?', 'Perla',
    ['Hvězdička', 'Kapka', 'To se nedá zjistit'],
    ['Kdo nosí jen modrou?', 'Kdo zelený šátek nemá?'],
    'Kapka nosí modrou a Hvězdička zelený šátek nemá. Zelený šátek tedy patří Perle.',
    { visual: SATKY }),
  q('satky-hvezdicka', 'V jakém šátku přišla Hvězdička?', 'V červeném',
    ['V modrém', 'V zeleném', 'To se nedá zjistit'],
    ['Modrý má Kapka. Který zbývá?'],
    'Modrý šátek má Kapka a zelený Hvězdička nemá. Na Hvězdičku zbývá červený.',
    { visual: SATKY }),
  q('kolo-kdo', 'Kdo si kolo půjčil?', 'Liv',
    ['Tatínek', 'Dag', 'Soused'],
    ['Kdo zná kód zámku?', 'Kdo z nich má výmluvu, která platí?'],
    'Kód znají jen tři. Tatínek byl na schůzce a Dag na tréninku. Zbývá Liv – a sedátko je nastavené tak, jak ho má ráda.',
    { visual: KOLO }),
  q('kolo-dve', 'Které dvě věci dohromady ukazují na Liv?', 'Zná kód a sedátko je nízko',
    ['Kolo zmizelo na hodinu', 'Garáž má dveře', 'Tatínek má schůzky'],
    ['Hledej stopy, které se týkají přímo Liv.'],
    'Kód znají jen tři lidé a nízké sedátko sedí právě na Liv. Obě stopy dohromady jsou silnější než každá zvlášť.',
    { visual: KOLO }),
  q('kolo-jiste', 'Co víme jistě?', 'Kolo bylo hodinu pryč',
    ['Liv jela k babičce', 'Dag nezná kód', 'Tatínek kolo hledal'],
    ['Co se opravdu stalo a co si jen domýšlíme?'],
    'Jistě víme, že kolo bylo hodinu pryč. Kam s ním Liv jela, nevíme. A Dag kód zná.',
    { visual: KOLO }),
  q('poklad-kde', 'Kde je poklad?', 'V pískovišti',
    ['U jabloně', 'V kůlně', 'U lavičky'],
    ['Vyřaď místa podle každé nápovědy zvlášť.'],
    'První nápověda vyřadí jabloň, třetí kůlnu a druhá lavičku u plotu. Zbývá pískoviště.',
    { visual: POKLAD }),
  q('poklad-lavicka', 'Která nápověda vyřadila lavičku?', 'Druhá',
    ['První', 'Třetí', 'Žádná'],
    ['Kde lavička stojí?'],
    'Lavička stojí u plotu, ale druhá nápověda říká, že poklad je blíž k domu než k plotu.',
    { visual: POKLAD }),
  q('poklad-spor', 'Co kdyby Jonas přidal čtvrtou nápovědu: „Poklad není v pískovišti“?', 'Žádné místo by nesedělo',
    ['Poklad by byl u lavičky', 'Poklad by byl v kůlně', 'Poklad by byl u jabloně'],
    ['Které místo by zůstalo po všech čtyřech nápovědách?'],
    'Všechna čtyři místa by byla vyřazená. Nápovědy by si odporovaly a jedna z nich by musela být chybná.',
    { visual: POKLAD }),
  q('kosik-kdo', 'Kdo nechal košík s jahodami?', 'Runa',
    ['Ingrid', 'Maja', 'Freja'],
    ['Co přesně viděla Freja a co Bo?', 'Kdo má červenou bundu i dlouhý cop?'],
    'Červenou bundu mají Maja a Runa, dlouhý cop Ingrid a Runa. Obě stopy sedí jen na Runu. Freja košík nenechala, ta odbíhající holku viděla.',
    { visual: KOSIK }),
  q('kosik-jedna-stopa', 'Proč nestačí jen jedna ze stop?', 'Každá stopa sedí na dvě holky',
    ['Svědci se vždycky pletou', 'Košík byl moc těžký', 'Jahody nenechávají stopy'],
    ['Na koho sedí červená bunda a na koho cop?'],
    'Červená bunda sedí na Maju i Runu, dlouhý cop na Ingrid i Runu. Jen dohromady ukážou na jednu holku.',
    { visual: KOSIK }),
  q('dva-podezreli', 'Detektiv má dva podezřelé a jednu stopu, která sedí na oba. Co udělá?', 'Hledá další stopu, která je odliší',
    ['Vybere toho, kdo je mu méně milý', 'Obviní oba', 'Hodí si mincí'],
    ['Pomůže stopa, která sedí na oba?'],
    'Stopa, která sedí na oba, mezi nimi nerozhodne. Detektiv hledá další stopu, dokud nezbude jen jedna možnost.'),
];

export const detektivBanks = { 2: L2, 3: L3, 4: L4, 5: L5 };
