// Jak to víme? – způsoby poznání: pozoruju, změřím, spočítám, vyzkouším
// pokusem, zeptám se odborníka, najdu ve spolehlivé knize × „jen jsem to
// slyšel/a“. Vyšší úrovně: férový pokus, co víme jistě a co jen tušíme,
// proč pokus opakovat a proč vědci mění názor. Vysvětlení je zajímavost
// (ukáže se i po správné odpovědi): nejdřív proč, pak navazující detail.

import type { Spec } from '../../core/bank';
import { poradi, q } from './kriticke-common';

// ---------------------------------------------------------------------------
// L1 – jak se co zjistí a kdo to ví nejlépe (jasné případy)

const L1: Spec[] = [
  q('okno-prsi', 'Jak nejlépe zjistíš, jestli venku prší?', 'Podívám se z okna',
    ['Zkusím hádat', 'Zeptám se plyšáka', 'Počkám do zítřka'],
    ['Co můžeš udělat hned teď?'],
    'Stačí se podívat – tomu se říká pozorování. Meteorologové mají na déšť i přístroj srážkoměr, který ukáže, kolik vody napršelo.'),
  q('vyska-metr', 'Jak zjistíš, kolik měříš?', 'Změřím se metrem',
    ['Budu hádat podle bot', 'Podívám se do zrcadla', 'Zeptám se, kolik měří kamarádka'],
    ['Čím se měří délka?'],
    'Výšku zjistíš měřením – metrem nebo podle značek na zdi. Ráno jsi přitom o kousek vyšší než večer, protože se tělo přes den trochu stlačí.'),
  q('cukr-voda', 'Jak zjistíš, jestli se cukr rozpustí ve vodě?', 'Vyzkouším to ve sklenici',
    ['Zeptám se kočky', 'Nakreslím si to', 'Budu hádat'],
    ['Dá se to udělat doma v kuchyni?'],
    'Nejlepší je pokus: nasypat lžičku cukru do sklenice vody, zamíchat a pozorovat. V teplé vodě se cukr rozpustí rychleji než ve studené – i to si můžeš vyzkoušet.'),
  q('zub-boli', 'Kdo nejlépe pozná, proč tě bolí zub?', 'Zubařka',
    ['Kadeřnice', 'Pekař', 'Spolužák'],
    ['Kdo se o zubech dlouho učil?'],
    'Zubařka se o zubech dlouho učila. Podívá se do pusy zrcátkem a na rentgenovém snímku uvidí i zuby, které ti teprve rostou schované v čelisti.'),
  q('pes-nemocny', 'Pejsek je nemocný. Kdo nejlépe pozná, co mu je?', 'Veterinářka',
    ['Prodavač v hračkářství', 'Pošťák', 'Soused, který psa nemá'],
    ['Existují lékaři i pro zvířata.'],
    'Veterinářka je lékařka pro zvířata a umí zvíře vyšetřit i léčit. Musí se vyznat v tělech mnoha různých zvířat – od křečka až po koně.'),
  q('pocasi-zitra', 'Kdo nejlépe předpoví, jaké bude zítra počasí?', 'Meteorolog',
    ['Kuchař', 'Hasič', 'Řidič autobusu'],
    ['Kdo měří teplotu a vítr a sleduje mraky?'],
    'Meteorologové měří teplotu, vítr a tlak vzduchu a sledují mraky na snímcích z družic. Z těch čísel pak velké počítače spočítají, jaké bude počasí.'),
  q('zirafa-kniha', 'Kde zjistíš, čím se živí žirafa?', 'V knize o zvířatech',
    ['V kuchařce', 'V jízdním řádu', 'V pohádce o drakovi'],
    ['Která kniha je o zvířatech?'],
    'Knihy o zvířatech píšou lidé, kteří zvířata dlouho pozorovali. Dozvíš se v nich třeba, že žirafa okusuje listy stromů jazykem dlouhým skoro půl metru.'),
  q('zmrzlina-zdarma', 'Leif ti řekl, co slyšel od kamaráda: zítra bude ve škole zmrzlina zdarma. Víš to jistě?', 'Ne, jen jsem to {slyšela|slyšel}',
    ['Ano, určitě', 'Ano, zmrzlina je dobrá', 'Ano, říkal to kamarád'],
    ['Viděl to někdo z nich na vlastní oči?'],
    'Zpráva šla od jednoho k druhému a cestou se mohla změnit – jako při hře na tichou poštu. Jistě to budeš vědět, až se zeptáš paní učitelky.'),
  q('teplomer', 'Jak zjistíš, jak je venku teplo?', 'Podívám se na teploměr',
    ['Podívám se do kalendáře', 'Budu hádat', 'Zeptám se rybiček'],
    ['Který přístroj měří teplotu?'],
    'Teploměr teplotu změří, odhad se snadno splete. Meteorologové mají teploměry ve stínu – na slunci by ukazovaly víc, než kolik opravdu je.'),
  q('ptacci-pocet', 'Jak zjistíš, kolik ptáčků sedí na krmítku?', 'Spočítám je',
    ['Tipnu si', 'Zeptám se kočky', 'Podívám se do knihy'],
    ['Ptáčci jsou přímo před tebou.'],
    'Když ptáčky spočítáš, víš to jistě – tip může být vedle. Ptáky na krmítkách takhle každou zimu počítají ornitologové a přidat se k nim můžou i děti.'),
  q('jablko-chut', 'Jak zjistíš, jestli je jablko sladké, nebo kyselé?', 'Ochutnám ho',
    ['Změřím ho metrem', 'Zvážím ho', 'Podívám se na strom'],
    ['Který smysl pozná chuť?'],
    'Chuť zjistíme ochutnáním. Jablko ochutnat můžeš, ale neznámé bobule a houby nikdy neochutnáváme – mohou být jedovaté.'),
  q('taska-vaha', 'Jak zjistíš, kolik váží tvoje taška?', 'Zvážím ji na váze',
    ['Změřím ji pravítkem', 'Podívám se na ni', 'Zeptám se tašky'],
    ['Který přístroj ukazuje kilogramy?'],
    'Kolik co váží, ukáže váha – pravítko měří délku. Lékaři radí, aby školní taška vážila nejvýš asi desetinu toho, co vážíš ty.'),
  q('magnet-lzicka', 'Jak zjistíš, jestli magnet přitáhne lžičku?', 'Vyzkouším to',
    ['Podívám se na barvu lžičky', 'Budu hádat', 'Zeptám se lžičky'],
    ['Máš magnet i lžičku po ruce.'],
    'Pokus ukáže víc než hádání. Některé lžičky magnet přitáhne a jiné ne, i když vypadají stejně – záleží na tom, z jakého kovu jsou.'),
  q('kaminek-voda', 'Jak zjistíš, jestli kamínek plave, nebo se potopí?', 'Dám ho do misky s vodou',
    ['Zvážím ho na dlani', 'Zeptám se kamínku', 'Nakreslím si ho'],
    ['Dá se to zkusit hned.'],
    'Stačí malý pokus: dát kamínek do vody a pozorovat. Většina kamenů se potopí, ale sopečná pemza plave – je plná vzduchových bublinek.'),
  q('dinosauri-muzeum', 'Kde se dozvíš, jak vypadali dinosauři?', 'V knize o dinosaurech nebo v muzeu',
    ['Ve snu', 'V pohádce o drakovi', 'Na obalu od jogurtu'],
    ['Kde se vystavují staré kosti?'],
    'Vědci vykopali zkamenělé kosti dinosaurů a poskládali z nich kostry, které uvidíš v muzeu. Jakou barvu dinosauři měli, se ale z kostí většinou poznat nedá.'),
  q('vlak-rad', 'Kde zjistíš, kdy jede vlak?', 'V jízdním řádu',
    ['V kuchařce', 'V pohádkové knize', 'Na krabici od bot'],
    ['Je to tabulka s časy odjezdů.'],
    'V jízdním řádu jsou časy, kdy vlaky odjíždějí – najdeš ho na nádraží i v mobilu. Podle něj se dá celá cesta naplánovat dopředu, i s přestupy.'),
  q('nejjisteji', 'Co víš nejjistěji?', 'Co jsem {viděla|viděl} na vlastní oči',
    ['Co řekl kamarád kamaráda', 'Co se mi zdálo', 'Co si myslí můj plyšák'],
    ['Čemu se dá nejvíc věřit?'],
    'Co jsi {viděla|viděl} a {ověřila|ověřil} na vlastní oči, víš nejjistěji. Doslech se cestou snadno změní a sen si mozek vymýšlí.'),
  q('zmrzlina-tepla', 'Jak zjistíš, jestli zmrzlina v teple roztaje?', 'Dám kousek na talířek a pozoruju ho',
    ['Zeptám se ledničky', 'Budu hádat', 'Nakreslím zmrzlinu'],
    ['Dá se to vyzkoušet v kuchyni.'],
    'Malý pokus: dát kousek zmrzliny na talířek a dívat se, co se s ní děje. Když roztátou zmrzlinu znovu zmrazíš, ztuhne, ale už nebude tak nadýchaná.'),
  q('kasel-lekarka', 'Kdo nejlépe pozná, proč dlouho kašleš?', 'Lékařka',
    ['Kamarádka ze třídy', 'Prodavačka bonbonů', 'Pekařka'],
    ['Kdo tě poslouchá fonendoskopem?'],
    'Lékařka tě vyšetří: fonendoskopem poslouchá, jak dýcháš, a podívá se ti do krku. Podle zvuku dechu pozná, jestli jsou plíce v pořádku.'),
  q('pozar-rady', 'Kdo ti nejlépe poradí, jak se chovat při požáru?', 'Hasič',
    ['Cukrář', 'Malíř', 'Zpěvák'],
    ['Kdo hasí oheň?'],
    'Hasiči se o ohni a požárech učí a mají s nimi zkušenosti. Radí zapamatovat si číslo 150 – nebo 112, které platí po celé Evropě.'),
  q('knihovnice', 'Kdo ti nejlépe pomůže najít knížku o koních?', 'Knihovnice',
    ['Automechanik', 'Popelář', 'Zmrzlinář'],
    ['Kdo se stará o knihy?'],
    'Knihovnice ví, kde v knihovně jaké knihy stojí. Knihy jsou tam seřazené podle témat, a tak ti rychle najde i další knihy o koních.'),
];

// ---------------------------------------------------------------------------
// L2 – čím to změřím, kdo je odborník, co je důkaz a jak ověřit zprávu

const L2: Spec[] = [
  q('nastroj-teplota', 'Čím zjistíš, jestli je voda v bazénu dost teplá?', 'Teploměrem',
    ['Pravítkem', 'Váhou', 'Hodinami', 'Lupou'],
    ['Hledáš přístroj na teplotu.'],
    'Teplotu vody změří teploměr. Ruka se může splést – když jdeš z horka, zdá se ti voda studenější, než opravdu je.'),
  q('nastroj-cas', 'Čím změříš, jak dlouho ti trvá doběhnout k plotu?', 'Stopkami',
    ['Teploměrem', 'Metrem', 'Váhou'],
    ['Měříš čas.'],
    'Čas změří stopky, třeba v mobilu – metr měří délku a váha hmotnost. Na závodech se čas měří dokonce na setiny sekundy, tak malý rozdíl by oko nepoznalo.'),
  q('nastroj-lupa', 'Čím si nejlépe prohlédneš nožičky mravence?', 'Lupou',
    ['Dalekohledem', 'Teploměrem', 'Váhou', 'Metrem'],
    ['Mravenec je malý a blízko.'],
    'Lupa zvětší malé věci, které jsou blízko – dalekohled je na věci daleko. Pod lupou uvidíš, že mravenec má šest nohou a na hlavě dvě tykadla.'),
  q('nastroj-dalekohled', 'Čím si nejlépe prohlédneš krátery na Měsíci?', 'Dalekohledem',
    ['Lupou', 'Mikroskopem', 'Teploměrem'],
    ['Měsíc je hodně daleko.'],
    'Dalekohled přiblíží věci, které jsou daleko – lupa a mikroskop zvětšují věci zblízka. Krátery vznikly, když na Měsíc dopadly kameny z vesmíru, a spoustu jich uvidíš už malým dalekohledem.'),
  q('jablon-zahradnice', 'Kdo ti nejlépe poradí, jak se starat o mladou jabloň?', 'Zahradnice',
    ['Kominík', 'Pilotka', 'Prodavač bot'],
    ['Kdo se stará o stromy každý den?'],
    'Zahradnice se o stromy stará každý den a ví, kdy je zalévat, stříhat a hnojit. Jabloně se nejčastěji stříhají koncem zimy, než začnou rašit.'),
  q('hvezdy-astronom', 'Kdo ví nejvíc o hvězdách a planetách?', 'Astronom',
    ['Zahradník', 'Kominík', 'Hasič'],
    ['Kdo se dívá dalekohledem na noční oblohu?'],
    'Astronomové zkoumají vesmír velkými dalekohledy a přístroji na družicích. Největší dalekohledy stojí vysoko v horách, kde je vzduch čistý a suchý.'),
  q('hrad-historik', 'Kdo zjistí, jak se žilo na hradě před stovkami let?', 'Historik',
    ['Kuchařka', 'Řidič autobusu', 'Prodavač hraček'],
    ['Kdo čte staré listiny a kroniky?'],
    'Historici čtou staré listiny a kroniky a porovnávají je. Pomáhají jim i archeologové, kteří na hradech vykopou třeba staré střepy nebo mince.'),
  q('fazole-dukaz', 'Co nejlépe dokáže, že je tvoje fazole vyšší než Tovina?', 'Měření pravítkem',
    ['Kamarádka si to myslí', 'Moje fazole je hezčí', 'Zdálo se mi to'],
    ['Čím se dá výška přesně zjistit?'],
    'Měření je důkaz, dojem se může plést. Pravítko ukáže přesné číslo a stejné měření si může zopakovat kdokoli další.'),
  q('pes-tlapka', 'Ivar tvrdí, že jeho pes umí podat tlapku. Co je nejlepší důkaz?', 'Pes to před námi předvede',
    ['Ivar to řekne dvakrát', 'Ivar má psa moc rád', 'Pes má velké tlapky'],
    ['Co bys {chtěla|chtěl} vidět na vlastní oči?'],
    'Nejlepší důkaz je vidět to na vlastní oči – když se něco jen opakuje, pravdivější to není. Proto i vědci své pokusy ukazují ostatním.'),
  q('zavod', 'Liv a Bo se hádají, kdo rychleji doběhne ke stromu. Jak to rozhodnou?', 'Poběží a změří si čas',
    ['Kdo křičí hlasitěji, má pravdu', 'Kdo je starší, je rychlejší', 'Hodí si mincí'],
    ['Jak se to dá zjistit doopravdy?'],
    'Spor se nejlépe rozhodne pokusem a měřením: oba poběží a stopky ukážou, kdo byl rychlejší. Aby to bylo férové, musí oba vyběhnout ze stejného místa.'),
  q('pastelky-obchod', 'Anna říká, že v obchodě mají nové pastelky. Jak to nejlépe ověříš?', 'Půjdu se tam podívat',
    ['Budu tomu věřit, když to řekne znovu', 'Řeknu to hned všem', 'Nakreslím si pastelky'],
    ['Kde se to dá zjistit?'],
    'Ověřit zprávu znamená podívat se, jak to je doopravdy. Opakováním se zpráva pravdivější nestane – a když ji hned pošleš dál, můžeš šířit omyl.'),
  q('pavouk-encyklopedie', 'Kde spolehlivě zjistíš, kolik nohou má pavouk?', 'V encyklopedii zvířat',
    ['V reklamě na sprej', 'V pohádce o pavoučkovi', 'Na obalu od sušenek'],
    ['Kdo píše knihy o zvířatech?'],
    'Encyklopedii psali odborníci, kteří zvířata zkoumali. Reklama chce hlavně prodávat a pohádka vyprávět příběh.'),
  q('rericha-svetlo', 'Jak zjistíš, jestli řeřicha potřebuje k růstu světlo?', 'Jednu misku na okno, druhou do skříně',
    ['Obě misky dám na okno', 'Přestanu řeřichu zalévat', 'Zeptám se řeřichy'],
    ['Musíš něco porovnat.'],
    'Porovnáš řeřichu na světle a ve tmě a obě misky zaléváš stejně, aby rozdíl udělalo jen světlo. Řeřicha ve skříni vyroste bledá a vytáhlá, jak se natahuje za světlem.'),
  q('snih-tani', 'Jak zjistíš, jestli sníh roztaje rychleji v kuchyni, nebo na balkoně?', 'Dám hrnek sněhu na obě místa',
    ['Dám hrnek sněhu jen do kuchyně', 'Zeptám se sněhuláka', 'Budu to hádat'],
    ['Potřebuješ porovnat dvě místa.'],
    'Pokus s porovnáním: stejně velké hrnky sněhu na dvou místech. Pak pozoruješ, kde sníh zmizí dřív – a teploměr ti prozradí proč.'),
  q('stul-delka', 'Jak nejpřesněji zjistíš, jak dlouhý je stůl?', 'Změřím ho metrem',
    ['Odhadnu to okem', 'Zeptám se, jak dlouhý stůl mají sousedé', 'Budu hádat'],
    ['Odhad, nebo měření?'],
    'Metr ukáže přesné číslo, odhad může být vedle. Truhláři proto říkají: dvakrát měř, jednou řež.'),
  q('snezenka-park', 'Dag slyšel, že v parku už kvete první sněženka. Jak to nejlépe ověří?', 'Půjde se do parku podívat',
    ['Počká, až mu to řekne ještě někdo', 'Zeptá se kočky', 'Najde sněženku v kuchařce'],
    ['Kde sněženka roste?'],
    'Nejjistější je podívat se na vlastní oči – pozorování je důkaz, doslech ne. Sněženky kvetou brzy, někdy už v únoru, takže zpráva pravdivá být může.'),
  q('stopy-atlas', 'Na sněhu jsou stopy zvířete. Jak zjistíš, čí jsou?', 'Porovnám je s obrázky v atlasu stop',
    ['Hodím si kostkou', 'Počkám, až roztají', 'Zeptám se sněhuláka'],
    ['V jaké knize jsou nakreslené stopy zvířat?'],
    'V atlasu stop jsou obrázky stop různých zvířat a porovnáváním najdeš ty nejpodobnější. Myslivci poznají zvíře i podle toho, jak jdou stopy za sebou.'),
  q('horecka-rada', 'Kdo ti nejlépe poradí, jaký lék je vhodný na horečku?', 'Lékařka nebo lékárnice',
    ['Reklama v televizi', 'Kamarád ze třídy', 'Prodavač hraček'],
    ['Kdo se o lécích učil?'],
    'O lécích nejlépe poradí lékařka nebo lékárnice – léky pro děti se dávkují jinak než pro dospělé. Reklama chce hlavně prodat a kamarád se v lécích nevyzná.'),
  q('kocici-oci', 'Freja slyšela, že kočky vidí i v úplné tmě. Jak to ověří?', 'Najde si to v knize o kočkách',
    ['Uvěří tomu hned', 'Pošle to všem kamarádům', 'Zeptá se plyšové kočky'],
    ['Kdo o kočkách opravdu něco ví?'],
    'Ve spolehlivé knize by zjistila, že kočky vidí v šeru mnohem lépe než my, ale v úplné tmě nevidí ani ony. Oči jim ve tmě svítí, protože mají vzadu v oku vrstvu, která odráží světlo.'),
  q('slunce-stin', 'Jak zjistíš, jestli je tvůj stín ráno delší než v poledne?', 'Změřím ho ráno i v poledne',
    ['Změřím ho jen ráno', 'Zeptám se stínu', 'Budu to hádat'],
    ['Musíš měřit dvakrát.'],
    'Když stín změříš ráno i v poledne, můžeš délky porovnat – ráno je delší. V poledne je Slunce na obloze nejvýš, a proto je stín nejkratší.'),
];

// ---------------------------------------------------------------------------
// L3 – férový pokus, co víme jistě a co jen tušíme, spolehlivé zdroje

const L3: Spec[] = [
  q('ferovy-kvetinac', 'Tom chce zjistit, jestli fazole roste lépe v hlíně, nebo v písku. Co musí mít oba květináče stejné?', 'Světlo a množství vody',
    ['Hlínu', 'Nic, na tom nezáleží', 'Jiné semínko v každém'],
    ['Co Tom zkoumá? To se lišit musí.', 'Všechno ostatní má být stejné.'],
    'Tom zkoumá hlínu a písek, takže jen v tom se květináče liší. Světlo a voda musí být stejné, jinak by nevěděl, co rozdíl způsobilo.'),
  q('ferove-vlastovky', 'Maja zkouší, která papírová vlaštovka doletí nejdál. Kdy bude pokus férový?', 'Když je hodí stejně a z jednoho místa',
    ['Když každou hodí odjinud', 'Když nejhezčí hodí nejsilněji', 'Když některé hodí po větru'],
    ['Co má být u všech vlaštovek stejné?'],
    'Férový pokus mění jen jednu věc – tady tvar vlaštovky. Hod, místo i vítr mají být pro všechny stejné, a nejlepší je hodit každou víckrát.'),
  q('jedna-zmena', 'Kolik věcí najednou měníme při férovém pokusu?', 'Jen jednu',
    ['Všechny najednou', 'Žádnou', 'Tolik, kolik chceme'],
    ['Jak jinak poznáš, co způsobilo rozdíl?'],
    'Když změníš jen jednu věc, víš, že rozdíl způsobila právě ona. Při více změnách najednou se to pozná těžko.'),
  q('co-se-lisi', 'Knut zalévá jednu rostlinu vodou a druhou slabým čajem. Co má být u obou rostlin jiné?', 'Jen to, čím je zalévá',
    ['Světlo', 'Velikost květináče', 'Všechno'],
    ['Co Knut zkoumá?'],
    'Knut zkoumá, jestli čaj rostlinám pomáhá, nebo škodí. Proto se smějí lišit jen tím, čím je zalévá – světlo i květináče mají mít stejné.'),
  q('sovy-zdroj', 'Který zdroj o sovách je nejspolehlivější?', 'Kniha od odborníka na ptáky',
    ['Komentář neznámého člověka', 'Reklama na krmivo pro ptáky', 'Pohádka o moudré sově'],
    ['Kdo sovy opravdu zkoumal?'],
    'Odborník na ptáky sovy dlouho pozoroval a zkoumal. Neznámý člověk se může plést, reklama chce prodávat a pohádka vymýšlí.'),
  q('ornitolog', 'Kdo je odborník na ptáky?', 'Ornitolog',
    ['Geolog', 'Astronom', 'Meteorolog'],
    ['Slovo „ornis“ znamená řecky pták.'],
    'Ornitolog zkoumá ptáky, geolog kameny, astronom vesmír a meteorolog počasí. Ornitologové dávají ptákům na nohu lehký kroužek s číslem – podle něj pak zjistí, kam ptáci létají.'),
  q('kamen-geolog', '{Našla|Našel} jsi zvláštní lesklý kámen. Kdo ti nejlépe řekne, co je to za kámen?', 'Geoložka',
    ['Ornitoložka', 'Astronomka', 'Meteoroložka'],
    ['Kdo zkoumá horniny a nerosty?'],
    'Geologové zkoumají horniny a nerosty a poznají je podle barvy, lesku a tvrdosti. Tvrdost zkoušejí i rýpáním: tvrdý nerost udělá do skla rýhu.'),
  q('archeolog', 'Kdo zkoumá předměty, které lidé dávno ztratili nebo zakopali v zemi?', 'Archeolog',
    ['Astronom', 'Ornitolog', 'Meteorolog'],
    ['Pracuje s lopatkou a štětečkem.'],
    'Archeologové opatrně kopou v zemi a hledají staré předměty. Každý nález si zapíšou i s místem, kde ležel – i to prozradí, jak lidé dřív žili.'),
  q('pozorovani-tip', 'Co z toho je pozorování, a ne jen tip?', 'Na krmítku teď sedí pět sýkorek.',
    ['Zítra asi přiletí víc sýkorek.', 'Sýkorky mají určitě rády slunečnice.', 'Sýkorky se asi nebojí zimy.'],
    ['Co se opravdu děje a co si jen myslíme?'],
    'Pozorování je to, co vidíš nebo spočítáš. Ostatní věty jsou jen tipy, které by se musely ověřit – třeba zapisováním sýkorek celou zimu.'),
  q('mokra-trava', 'Ráno je na zahradě mokrá tráva. Co víš jistě?', 'Tráva je mokrá',
    ['V noci pršelo', 'Někdo zaléval zahradu', 'Zítra bude zase mokrá'],
    ['Co vidíš a co si jen domýšlíš?'],
    'Jistě víš jen to, co vidíš: tráva je mokrá. Proč, zatím jen tušíš – mohlo pršet, mohla to být ranní rosa, nebo zalévání.'),
  q('vune-kolace', 'Z kuchyně voní koláč. Co víš jistě?', 'V kuchyni něco voní jako koláč',
    ['Babička upekla borůvkový koláč', 'Koláč je pro mě', 'Koláč už je upečený'],
    ['Co ti opravdu říká nos?'],
    'Nos ti řekne jen to, že něco voní jako koláč. Kdo peče, jaký koláč to je a jestli je hotový, zatím jen tušíš.'),
  poradi('kroky-badani', 'Seřaď kroky bádání, jak jdou za sebou.',
    ['Položím si otázku', 'Tipnu si, co se stane', 'Udělám pokus', 'Zapíšu, co vidím', 'Porovnám to se svým tipem'],
    ['Na začátku je vždycky otázka.', 'Tip si dáš dřív, než zkoušíš.'],
    'Bádání začíná otázkou. Pak si tipneš, uděláš pokus, zapíšeš, co vidíš, a porovnáš to s tipem – když tip nevyjde, i to je objev.'),
  poradi('kroky-led', 'Seřaď kroky pokusu s kostkou ledu.',
    ['Naleju do sklenice vodu', 'Vložím do ní kostku ledu', 'Pozoruju, co led udělá', 'Zapíšu, co jsem {viděla|viděl}'],
    ['Co musí být ve sklenici nejdřív?'],
    'Nejdřív voda, pak led, potom pozorování a nakonec zápis. Zapisuje se až to, co jsi opravdu {viděla|viděl}.'),
  q('anketa-zvire', 'Chceš zjistit, jaké zvíře má tvoje třída nejraději. Co uděláš?', 'Zeptám se všech a zapíšu si to',
    ['Zeptám se jen nejlepší kamarádky', 'Napíšu tam své oblíbené zvíře', 'Budu hádat'],
    ['Na koho se musíš zeptat?'],
    'Taková anketa je sbírání dat. Když se zeptáš všech a odpovědi si zapíšeš, výsledek je spolehlivý – a můžeš z něj nakreslit i graf.'),
  q('veverky-internet', 'Neznámý člověk na internetu píše, že veverka vždycky najde všechny oříšky, které zahrabala. Co uděláš?', 'Ověřím si to v knize nebo u odborníka',
    ['Hned tomu uvěřím', 'Pošlu to všem kamarádům', 'Napíšu mu, že má pravdu'],
    ['Víš, kdo to píše a jak to ví?'],
    'Než něčemu uvěříš, ověř si to. Přírodovědci pozorovali, že veverky spoustu oříšků najdou, ale některé ne – a z nich pak vyrostou nové stromy.'),
  q('tri-kocky', 'Bo viděl v parku tři bílé kočky. Může říct, že všechny kočky jsou bílé?', 'Ne, viděl jich moc málo',
    ['Ano, tři kočky stačí', 'Ano, když je viděl dvakrát', 'Ano, bílá je hezká barva'],
    ['Znáš i kočky jiných barev?'],
    'Ze tří koček se nedá usoudit nic o všech kočkách. Stačí jedna černá kočka a pravidlo neplatí.'),
  q('proc-zapis', 'Proč si vědci zapisují, co pozorují?', 'Aby nic nezapomněli a mohli to porovnat',
    ['Aby měli hodně papírů', 'Aby to nikdo nepřečetl', 'Protože se to hodí na kreslení'],
    ['Pamatuješ si přesně, co jsi {viděla|viděl} před týdnem?'],
    'Paměť se plete. Zápis pomůže porovnat, co se dělo včera a dnes, a ukázat to i ostatním. V pražském Klementinu si teplotu zapisují každý den už přes 200 let.'),
  q('dve-knihy', 'Dvě knihy píšou o stejném zvířeti něco jiného. Co uděláš?', 'Najdu další spolehlivý zdroj',
    ['Věřím té s hezčími obrázky', 'Věřím té tlustší', 'Nebudu věřit ničemu'],
    ['Jak se dá spor rozhodnout?'],
    'Když se zdroje neshodnou, hledej další spolehlivé zdroje nebo se zeptej odborníka. Obrázky ani tloušťka knihy nic nedokazují – a pomůže i to, která kniha je novější.'),
  q('astronom-astrolog', 'Kdo zkoumá planety pomocí dalekohledů a měření?', 'Astronom',
    ['Astrolog', 'Kouzelník', 'Ornitolog'],
    ['Jedno z podobných slov patří vědci.'],
    'Astronom je vědec, který vesmír měří a pozoruje. Astrolog jen tvrdí, že hvězdy předpovídají osud, a to se pokusy nepotvrdilo.'),
];

// ---------------------------------------------------------------------------
// L4 – proč pokusy opakovat, náhoda, malá anketa, porovnání a nové důkazy

const L4: Spec[] = [
  q('opakovani-proc', 'Proč vědci opakují stejný pokus víckrát?', 'Aby měli jistotu, že to nebyla náhoda',
    ['Protože je první pokus bavil', 'Aby jim to trvalo déle', 'Aby vyšlo pokaždé něco jiného'],
    ['Co když se napoprvé něco pokazilo?'],
    'Jeden pokus může dopadnout náhodou nebo chybou. Když vyjde stejně i podruhé a potřetí, je výsledek spolehlivý.'),
  q('kostka-sestky', 'Runa hodila třikrát kostkou a dvakrát padla šestka. Je kostka falešná?', 'Ze tří hodů se to poznat nedá',
    ['Ano, určitě', 'Ne, falešné kostky neexistují', 'Ano, šestka padá vždycky'],
    ['Tři hody jsou hodně, nebo málo?'],
    'Dvě šestky ze tří hodů se klidně stanou náhodou. U poctivé kostky padá šestka zhruba v každém šestém hodu – podezřelé by bylo, kdyby padala mnohem častěji i po stovce hodů.'),
  q('stastne-ponozky', 'Jonas měl dvakrát modré ponožky a jeho tým vyhrál. Myslí si, že nosí štěstí. Jak to ověří?', 'Zapíše si hodně zápasů s nimi i bez nich',
    ['Bude je nosit pořád', 'Zeptá se ponožek', 'Koupí si další modré ponožky'],
    ['Stačí dva zápasy, aby to poznal?', 'S čím by zápasy v modrých ponožkách porovnal?'],
    'Dva zápasy jsou málo a výhra mohla mít jiné důvody. Teprve porovnání mnoha zápasů s ponožkami a bez nich by něco ukázalo.'),
  q('mala-anketa', 'Alva se zeptala dvou kamarádek a obě mají rády brokolici. Platí to pro všechny děti?', 'To se ze dvou odpovědí poznat nedá',
    ['Ano, dvě kamarádky stačí', 'Ano, brokolice je zdravá', 'Ano, když to napíše do novin'],
    ['Kolika dětí se zeptala?'],
    'Dvě kamarádky jsou moc malá skupina a navíc si mohou být podobné. Proto se výzkumníci při průzkumech ptají stovek i tisíců různých lidí.'),
  q('mereni-rozdil', 'Leif změřil lavici dvakrát. Poprvé mu vyšlo 120 cm, podruhé 124 cm. Co udělá?', 'Změří ji znovu a pečlivě',
    ['Uvěří prvnímu měření', 'Vybere číslo, které se mu líbí', 'Přestane měřit'],
    ['Když se dvě měření liší, co to znamená?'],
    'Rozdíl prozrazuje chybu v měření. Leif má měřit znovu a pečlivě, s metrem přiloženým přesně na začátek lavice.'),
  q('vedkyne-omyl', 'Co udělá dobrá vědkyně, když nový pokus ukáže, že se mýlila?', 'Změní názor a opraví to',
    ['Výsledek schová', 'Bude dál tvrdit to své', 'Přestane dělat pokusy'],
    ['Co je ve vědě důležitější – mít pravdu, nebo najít pravdu?'],
    'Věda se opravuje podle důkazů a přiznat omyl není ostuda. Tak třeba astronomové v roce 2006 přestali počítat Pluto mezi planety.'),
  q('limonada-naslepo', 'Tove tvrdí, že pozná drahou limonádu od levné. Jak to nejlépe ověříte?', 'Dáme jí ochutnat naslepo',
    ['Ukážeme jí obě láhve', 'Uvěříme jí, když to říká', 'Koupíme dražší limonádu'],
    ['Co by ji mohlo ovlivnit, když láhve uvidí?'],
    'Když Tove vidí láhev nebo cenu, může ji to ovlivnit. Ochutnávka naslepo ukáže, jestli limonády pozná jen podle chuti – takhle naslepo zkoušejí vědci i nové léky.'),
  q('hnojivo-porovnani', 'Freja zkoumá, jestli hnojivo pomáhá rajčatům. Co potřebuje kromě rajčat s hnojivem?', 'Stejná rajčata bez hnojiva',
    ['Víc hnojiva', 'Rajčata jiného druhu jinde', 'Nic dalšího'],
    ['S čím výsledek porovná?'],
    'Bez porovnání by Freja nevěděla, jestli by rajčata nevyrostla stejně i bez hnojiva. Vědci takovým rostlinám bez hnojiva říkají kontrolní skupina.'),
  q('vic-seminek', 'Proč je při pokusu lepší zasadit víc semínek, a ne jen jedno?', 'Jedno semínko může být náhodou slabé',
    ['Aby bylo víc práce', 'Jedno semínko nikdy nevyroste', 'Aby se nevešla do květináče'],
    ['Jsou všechna semínka úplně stejná?'],
    'Semínka se od sebe trochu liší a některá nevyklíčí. Když jich zasadíš víc, náhoda výsledek tolik nezkazí.'),
  q('video-lajky', 'Video tvrdí, že kočkám prospívá kravské mléko. Má hodně lajků. Je to důkaz?', 'Ne, lajky nejsou důkaz',
    ['Ano, tolik lidí se nemůže mýlit', 'Ano, videa jsou vždycky pravdivá', 'Ano, když je video vtipné'],
    ['Co vlastně říká počet lajků?'],
    'Lajky jen ukazují, kolika lidem se video líbilo. Veterináři přitom vědí, že dospělým kočkám kravské mléko často nedělá dobře.'),
  q('krmitko-mraz', 'Maja si všimla, že když mrzne, chodí na krmítko víc ptáků. Jak to ověří?', 'Celou zimu bude zapisovat mráz a ptáky',
    ['Zeptá se jednoho ptáka', 'Podívá se jen jednou', 'Nakreslí si sýkorku'],
    ['Stačí jedno pozorování?'],
    'Jedno pozorování může být náhoda. Když si Maja bude každý den zapisovat teplotu i počet ptáků, uvidí, jestli to platí.'),
  q('overeni-jinymi', 'Proč vědci chtějí, aby jejich pokus zopakovali i jiní vědci?', 'Aby se ukázalo, že to vyjde i jim',
    ['Aby měli méně práce', 'Aby se proslavili', 'Aby se chyba neprozradila'],
    ['Co když se první vědci někde spletli?'],
    'Když pokus vyjde stejně i v jiné laboratoři, je mnohem jistější, že nejde o chybu nebo náhodu jedné skupiny.'),
  q('dva-svedci', 'Knut a Petr viděli stejnou věc, ale každý ji vypráví trochu jinak. Proč?', 'Každý si všiml něčeho jiného',
    ['Jeden z nich určitě lže', 'Oba to jen vymysleli', 'To se nikdy nestává'],
    ['Díváš se na věci stejně jako tvoje kamarádka?'],
    'Každý si všimne něčeho jiného a paměť se plete. Proto se vyplatí porovnat víc svědků – a ještě lépe mít fotku nebo záznam.'),
  q('buky-duby', 'Dag tvrdí, že v lese roste víc buků než dubů. Jak to nejlépe ověří?', 'Na kousku lesa spočítá buky i duby',
    ['Spočítá jen buky', 'Zeptá se veverky', 'Podívá se na jeden strom'],
    ['Co musí spočítat, aby mohl porovnávat?'],
    'Aby mohl porovnat, musí spočítat oba druhy stromů na stejném kousku lesa. Z počtu jen jednoho druhu se nic nepozná.'),
  poradi('kroky-rericha', 'Seřaď kroky férového pokusu s řeřichou.',
    ['Nasypu semínka do dvou misek', 'Jednu dám na světlo, druhou do tmy', 'Týden obě stejně zalévám', 'Po týdnu je porovnám'],
    ['Co musíš udělat jako první?', 'Porovnává se až na konci.'],
    'Nejdřív zasadíš semínka, pak misky rozdělíš, týden je stejně zaléváš a nakonec porovnáš, jak řeřicha vyrostla.'),
  q('tip-overitelny', 'Který tip se dá ověřit pokusem?', 'Ve tmě semínka klíčí pomaleji',
    ['Modrá je nejhezčí barva', 'Zítra bude nejlepší den', 'Kočky jsou roztomilejší než psi'],
    ['Který tip se dá změřit nebo vyzkoušet?'],
    'Tip o semínkách jde vyzkoušet: zasadit je na světlo i do tmy a porovnat. Pokus ho může i vyvrátit – semínka v zemi přece klíčí potmě. Ostatní věty jsou názory, ty pokus nerozhodne.'),
  q('dinosauri-peri', 'Vědci si dlouho mysleli, že dinosauři měli jen šupiny. Pak našli zkameněliny s otisky peří. Co udělali?', 'Změnili názor podle důkazu',
    ['Zkameněliny schovali', 'Řekli, že je to omyl', 'Přestali dinosaury zkoumat'],
    ['Co dělá dobrý vědec s novým důkazem?'],
    'Nový důkaz vědce přesvědčil: dnes víme, že mnoho dinosaurů mělo peří. Tak se kniha poznání opravuje.'),
  q('kontrola-teplomer', 'Zdá se ti, že teploměr za oknem ukazuje moc vysokou teplotu. Jak to ověříš?', 'Porovnám ho s jiným teploměrem',
    ['Budu mu věřit', 'Vyhodím ho', 'Zeptám se, kolik stupňů bylo včera'],
    ['S čím můžeš teploměr porovnat?'],
    'Přístroj se dá ověřit porovnáním s jiným přístrojem. Když se liší, jeden z nich měří špatně – třeba proto, že na něj svítí slunce.'),
  q('nahoda-vyhra', 'Ivar třikrát za sebou uhodl, jestli padne panna, nebo orel. Umí věštit?', 'Ne, mohla to být náhoda',
    ['Ano, třikrát je důkaz', 'Ano, když je šikovný', 'Ano, mince ho poslouchá'],
    ['Jak často se to může stát jen tak?'],
    'Uhodnout třikrát za sebou se podaří zhruba jednou z osmi pokusů – tedy docela často. Věštění by se muselo prokázat mnohem víc pokusy.'),
  q('zapis-mereni', 'Proč je lepší zapsat si naměřená čísla hned, a ne až večer?', 'Aby se čísla v paměti nepopletla',
    ['Aby se čísla změnila', 'Protože večer se nepíše', 'Aby nikdo nevěděl výsledky'],
    ['Pamatuješ si přesně čísla z rána?'],
    'Paměť čísla snadno poplete. Zápis hned po měření je přesný a můžeš se k němu kdykoli vrátit.'),
];

export const jakBanks = { 1: L1, 2: L2, 3: L3, 4: L4 };
