// Rostliny a houby: části rostliny a k čemu jsou, co rostlina potřebuje,
// stromy listnaté × jehličnaté, strom × keř × bylina, ovoce × zelenina (jen
// jednoznačné případy), bezpečí u hub a bobulí, fotosyntéza jednoduše a proč
// houby nejsou rostliny.

import { bankSkill, type Spec } from '../../core/bank';
import { capitalize } from '../../core/czech';
import type { Rng } from '../../core/rng';
import type { KnowledgeCard } from '../../core/types';
import { fixed, ord, pickSome, q, slug } from './common';

const ID = 'svet.rostliny';

// ---------------------------------------------------------------------------
// L1 – části rostliny, co potřebuje, stromy, bezpečí

const L1: Spec[] = [
  q('koren', 'Která část rostliny je v zemi a saje vodu?', 'Kořen',
    ['List', 'Květ', 'Plod'],
    ['Tahle část není vidět, schovává se v hlíně.'],
    'Kořen drží rostlinu v zemi a saje z půdy vodu a živiny.'),
  q('semenko', 'Z čeho vyroste nová rostlinka?', 'Ze semínka',
    ['Z kamínku', 'Z písku', 'Z kapky rosy'],
    ['Co zahradník na jaře zasévá do hlíny?'],
    'Nová rostlinka vyroste ze semínka. Když má vodu a teplo, semínko vyklíčí.'),
  q('potrebuje', 'Co potřebuje rostlina, aby rostla?', 'Vodu a světlo',
    ['Tmu a sucho', 'Sladkou limonádu', 'Hodně soli'],
    ['Proč dáváme květiny k oknu a zaléváme je?'],
    'Rostlina potřebuje vodu, světlo, vzduch a teplo. Živiny bere z půdy.'),
  q('jehlicnaty', 'Který strom je jehličnatý?', 'Smrk',
    ['Dub', 'Lípa', 'Bříza', 'Buk'],
    ['Hledej strom, který má místo listů jehlice.'],
    'Smrk má jehlice a šišky, je to jehličnatý strom. Dub, lípa, bříza i buk jsou listnaté.'),
  q('listnaty', 'Který strom je listnatý?', 'Dub',
    ['Smrk', 'Borovice', 'Jedle'],
    ['Hledej strom, který na podzim shazuje listí.'],
    'Dub má listy, které na podzim opadají – je to listnatý strom. Smrk, borovice i jedle jsou jehličnaté.'),
  q('zaludy', 'Na kterém stromě rostou žaludy?', 'Na dubu',
    ['Na smrku', 'Na bříze', 'Na lípě', 'Na jabloni'],
    ['Žaludy mají na sobě malou čepičku.'],
    'Žaludy jsou plody dubu. Rády je mají veverky, sojky i divoká prasata.'),
  q('sisky', 'Na kterém stromě rostou šišky?', 'Na smrku',
    ['Na dubu', 'Na lípě', 'Na buku', 'Na jabloni'],
    ['Šišky mají jehličnaté stromy.'],
    'Šišky rostou na jehličnatých stromech, třeba na smrku nebo borovici. Ve šiškách jsou schovaná semena.'),
  q('houba-les', 'Najdeš v lese hezkou houbu. Co uděláš?', 'Nechám ji být a řeknu dospělému',
    ['Hned ji ochutnám', 'Utrhnu ji a sním doma', 'Dám ji ochutnat kamarádce'],
    ['Umíš jedlou houbu bezpečně poznat?'],
    'Houby nikdy nesbíráme ani nejíme bez dospělého, který se v nich vyzná. Některé jedovaté houby vypadají skoro stejně jako jedlé.'),
  q('kmen', 'Jak se jmenuje silná dřevěná část stromu, která drží korunu?', 'Kmen',
    ['Kořen', 'List', 'Plod'],
    ['Pokrývá ji kůra.'],
    'Kmen je silný a dřevěný. Nese korunu s větvemi a listy a vede vodu od kořenů nahoru.'),
  q('mrkev', 'Kterou část mrkve jíme?', 'Kořen',
    ['List', 'Květ', 'Semínko'],
    ['Mrkev se vytahuje ze země.'],
    'Oranžová mrkev je kořen. Zelená nať nahoře, to jsou listy.'),
  q('salat', 'Kterou část salátu jíme?', 'Listy',
    ['Kořen', 'Květ', 'Semínka'],
    ['Salát je zelený a křupavý.'],
    'U salátu jíme listy. Kořen zůstává v zemi nebo ho odřízneme.'),
  q('jablko-cast', 'Která část jabloně je jablko?', 'Plod',
    ['Kořen', 'List', 'Kmen'],
    ['Uvnitř jablka najdeš semínka.'],
    'Jablko je plod jabloně. Chrání semínka, ze kterých může vyrůst nová jabloň.'),
  q('zalevani', 'Kdy zaliješ pokojovou květinu?', 'Když má suchou hlínu',
    ['Každou hodinu', 'Nikdy', 'Jen když kvete'],
    ['Sáhni prstem do hlíny v květináči.'],
    'Květinu zaléváme, když je hlína suchá. Když je v květináči pořád mokro, kořenům to škodí.'),
  q('okno', 'Proč dáváme květinu v květináči k oknu?', 'Aby měla světlo',
    ['Aby jí byla zima', 'Aby ji viděli sousedé', 'Aby nemusela pít'],
    ['Co rostlina potřebuje kromě vody?'],
    'Rostliny potřebují světlo. Bez něj nemohou v listech vyrábět potravu.'),
  q('vcely-kvety', 'Proč na květy létají včely?', 'Sbírají nektar a pyl',
    ['Schovávají se před deštěm', 'Hledají tam jehličí', 'Staví si v nich hnízda'],
    ['Co vyrábějí včely v úlu?'],
    'Včely sbírají v květech sladký nektar a pyl. Z nektaru vyrábějí med a přitom přenášejí pyl z květu na květ.'),
  q('bobule', 'Najdeš v lese neznámé bobule. Co s nimi uděláš?', 'Nejím je a zeptám se dospělého',
    ['Ochutnám jednu', 'Nasbírám je na svačinu', 'Dám je ochutnat bráškovi'],
    ['Víš jistě, co to je?'],
    'Některé bobule jsou jedovaté. Jíme jen to, co dospělý bezpečně pozná.'),
  q('rybiz', 'Na čem roste rybíz?', 'Na keři',
    ['Na vysokém stromě', 'Pod zemí', 'Ve vodě'],
    ['Rybíz trháme vestoje, bez žebříku.'],
    'Rybíz roste na keři. Keř má víc tenkých dřevnatých stonků, které rostou hned od země.'),
  q('pampeliska', 'Co se stane s květem pampelišky, když odkvete?', 'Změní se v chmýří se semínky',
    ['Promění se v jablko', 'Zčervená a ztvrdne', 'Schová se pod zem'],
    ['Když na něj foukneš, rozletí se.'],
    'Z odkvetlé pampelišky je chmýří. Každé chmýříčko nese jedno semínko a vítr ho odnese daleko.'),
  q('kvet', 'Která část rostliny láká včely barvou a vůní?', 'Květ',
    ['Kořen', 'Stonek', 'Semínko'],
    ['Tuhle část dáváme do vázy.'],
    'Květy lákají hmyz barvou a vůní. Hmyz přenáší pyl a z květu pak vyroste plod.'),
  q('strom-casti', 'Co z toho strom nemá?', 'Ploutve',
    ['Kořeny', 'Kmen', 'Větve'],
    ['Tři z možností najdeš na každém stromě.'],
    'Strom má kořeny, kmen, větve a listy nebo jehlice. Ploutve mají ryby.'),
];

/** Ovoce a zelenina – jen jednoznačné případy (žádné rajče, okurka, dýně). */
const OVOCE_ZELENINA: [string, boolean, string][] = [
  ['jablko', true, 'Jablko je ovoce. Roste na jabloni a je sladké a šťavnaté.'],
  ['hruška', true, 'Hruška je ovoce. Roste na stromě hrušni.'],
  ['švestka', true, 'Švestka je ovoce. Roste na stromě a uvnitř má pecku.'],
  ['třešeň', true, 'Třešeň je ovoce. Sladké třešně rostou na stromě a mají pecku.'],
  ['meruňka', true, 'Meruňka je ovoce. Je sladká a uvnitř má pecku.'],
  ['broskev', true, 'Broskev je ovoce. Má sametovou slupku a uvnitř pecku.'],
  ['pomeranč', true, 'Pomeranč je ovoce. Roste na stromech v teplých krajích.'],
  ['banán', true, 'Banán je ovoce. Roste v teplých krajích ve velkých trsech.'],
  ['citron', true, 'Citron je ovoce, i když je kyselý. Roste na stromech v teplých krajích.'],
  ['hroznové víno', true, 'Hroznové víno je ovoce. Roste na vinné révě.'],
  ['malina', true, 'Malina je ovoce. Roste na keři maliníku.'],
  ['jahoda', true, 'Jahoda je ovoce. Roste na nízké rostlině jahodníku.'],
  ['mrkev', false, 'Mrkev je zelenina. Jíme její oranžový kořen.'],
  ['petržel', false, 'Petržel je zelenina. Jíme kořen i zelenou nať.'],
  ['cibule', false, 'Cibule je zelenina. Roste v zemi a při krájení štípe do očí.'],
  ['česnek', false, 'Česnek je zelenina. Jeho stroužky rostou v zemi.'],
  ['salát', false, 'Salát je zelenina. Jíme jeho listy.'],
  ['zelí', false, 'Zelí je zelenina. Z jeho listů se dělá i kysané zelí.'],
  ['kedluben', false, 'Kedluben je zelenina. Jíme jeho ztloustlý stonek.'],
  ['ředkvička', false, 'Ředkvička je zelenina. Jíme její červenou bulvičku.'],
  ['špenát', false, 'Špenát je zelenina. Jíme jeho listy.'],
  ['celer', false, 'Celer je zelenina. Jíme jeho bulvu nebo řapíky.'],
  ['květák', false, 'Květák je zelenina. Jíme jeho nerozvité květy.'],
  ['pórek', false, 'Pórek je zelenina. Je příbuzný cibule.'],
];

function ovoceNeboZelenina(rng: Rng): Spec {
  const [name, ovoce, explain] = rng.pick(OVOCE_ZELENINA);
  return fixed(`ovoce-${slug(name)}`, `Je ${name} ovoce, nebo zelenina?`, ['Ovoce', 'Zelenina'], ovoce ? 0 : 1,
    ['Ovoce bývá sladké a často roste na stromech a keřích.', 'Zelenina se častěji vaří nebo dává do salátu.'],
    explain);
}

// ---------------------------------------------------------------------------
// L2 – strom × keř × bylina, části rostliny a k čemu jsou, šíření semen

const L2: Spec[] = [
  q('ker-kdo', 'Která z těchto rostlin je keř?', 'Rybíz',
    ['Dub', 'Smrk', 'Lípa', 'Pampeliška'],
    ['Keř má víc dřevnatých stonků hned od země.'],
    'Rybíz je keř – od země mu roste víc dřevnatých stonků. Dub, smrk a lípa jsou stromy, pampeliška je bylina.'),
  q('bylina-kdo', 'Která z těchto rostlin je bylina?', 'Pampeliška',
    ['Dub', 'Smrk', 'Líska', 'Rybíz'],
    ['Bylina má měkký zelený stonek, ne dřevo.'],
    'Pampeliška je bylina s měkkým stonkem. Dub a smrk jsou stromy, líska a rybíz keře.'),
  q('strom-ker', 'Čím se strom liší od keře?', 'Strom má jeden silný kmen',
    ['Strom nemá listy', 'Strom roste jen v lese', 'Strom nikdy nekvete'],
    ['Podívej se, kolik stonků roste ze země.'],
    'Strom má jeden silný kmen, keř má víc tenčích dřevnatých stonků hned od země.'),
  q('byliny-co', 'Co platí o bylinách?', 'Mají měkký zelený stonek',
    ['Mají tvrdý dřevěný kmen', 'Rostou vyšší než stromy', 'Nikdy nekvetou'],
    ['Vzpomeň si na pampelišku nebo kopretinu.'],
    'Byliny mají měkký zelený stonek, který nedřevnatí. Patří sem třeba pampeliška, kopretina nebo tulipán.'),
  q('list-k-cemu', 'K čemu jsou rostlině listy?', 'Na světle vyrábějí potravu',
    ['Sají vodu ze země', 'Drží rostlinu v zemi', 'Lákají včely vůní'],
    ['Proč listy potřebují slunce?'],
    'Listy na světle vyrábějí pro rostlinu potravu. Vodu sají kořeny a včely lákají květy.'),
  q('koren-k-cemu', 'K čemu jsou rostlině kořeny?', 'Sají vodu a drží rostlinu v zemi',
    ['Vyrábějí semínka', 'Lákají včely', 'Zachycují sluneční světlo'],
    ['Co by se stalo s rostlinou bez kořenů ve větru?'],
    'Kořeny drží rostlinu v zemi a sají z půdy vodu se živinami.'),
  q('stonek-k-cemu', 'Co dělá stonek?', 'Vede vodu od kořenů k listům',
    ['Vyrábí semena', 'Saje vodu ze země', 'Chrání semínka v plodu'],
    ['Stonek je jako trubka mezi kořenem a listy.'],
    'Stonek nese listy a květy a vede vodu od kořenů nahoru. Z listů zase rozvádí potravu.'),
  q('kvet-k-cemu', 'K čemu je rostlině květ?', 'Vyroste z něj plod se semeny',
    ['Saje vodu', 'Drží rostlinu ve větru', 'Vyrábí hlínu'],
    ['Co najdeš na jabloni, když odkvete?'],
    'Když hmyz nebo vítr přenese pyl, vyroste z květu plod se semeny. Z nich pak rostou nové rostliny.'),
  ord('cesta-vody', 'Seřaď cestu vody rostlinou. Začni v zemi.', ['Hlína', 'Kořen', 'Stonek', 'List'],
    ['Co saje vodu jako první?'],
    'Voda z hlíny vstoupí do kořene, stonkem vystoupá nahoru a dojde až do listů.'),
  ord('fazole', 'Seřaď, jak roste fazole. Začni semínkem.', ['Semínko', 'Klíček', 'Mladá rostlinka', 'Kvetoucí rostlina', 'Lusk se semínky'],
    ['Co vyroste ze semínka jako první?'],
    'Ze semínka vyraší klíček, vyroste mladá rostlinka, ta pokvete a z květů vyrostou lusky s novými semínky.'),
  q('modrin', 'Který jehličnatý strom na zimu shazuje jehličí?', 'Modřín',
    ['Smrk', 'Borovice', 'Jedle'],
    ['Na podzim jeho jehličí zezlátne.'],
    'Modřín je jehličnatý strom, ale na zimu shodí jehlice, podobně jako listnaté stromy listí. Na jaře mu narostou nové.'),
  q('sisky-semena', 'Kde mají jehličnaté stromy semena?', 'Ve šiškách',
    ['V žaludech', 'V jablkách', 'V kaštanech'],
    ['Najdeš je v lese pod smrkem.'],
    'Semena smrku, borovice nebo jedle jsou schovaná ve šiškách. Rády je vyloupávají veverky a ptáci.'),
  q('ker-ovoce', 'Které ovoce roste na keři?', 'Angrešt',
    ['Jablko', 'Hruška', 'Třešeň', 'Švestka'],
    ['Ostatní ovoce roste na stromech.'],
    'Angrešt roste na nízkém keři s trny. Jablka, hrušky, třešně i švestky rostou na stromech.'),
  q('opylovani', 'Kdo přenáší pyl z květu na květ?', 'Včely a čmeláci',
    ['Žížaly', 'Krtci', 'Ryby'],
    ['Kdo létá z květu na květ?'],
    'Včely, čmeláci a další hmyz nosí pyl z květu na květ. Díky tomu mohou vyrůst plody.'),
  q('pampeliska-vitr', 'Jak se šíří semínka pampelišky?', 'Odnáší je vítr',
    ['Zakopou je krtci', 'Odnesou je ryby', 'Rozkutálejí se'],
    ['Každé semínko má svůj malý padáček.'],
    'Semínka pampelišky mají chmýří jako padáček a vítr je odnese daleko.'),
  q('bez-vody', 'Co se stane s květinou, kterou dlouho nezaléváš?', 'Zvadne',
    ['Rozkvete víc', 'Vyroste rychleji', 'Zmodrá'],
    ['Co rostlina potřebuje, aby mohla růst?'],
    'Bez vody rostlina zvadne – listy a stonek ochabnou a svěsí se. Když ji včas zaliješ, často se vzpamatuje.'),
  q('houby-kdy', 'Kdy chodíme nejčastěji na houby?', 'V létě a na podzim',
    ['V zimě', 'Jen na jaře', 'Jen v prosinci'],
    ['Houbám se daří, když je teplo a vlhko.'],
    'Houby rostou nejvíc v létě a na podzim, když je teplo a po dešti vlhko.'),
  q('houby-proc-dospely', 'Proč smíš houby sbírat jen s dospělým?', 'Jedovatá houba může vypadat jako jedlá',
    ['Houby rostou jen v noci', 'Houby jsou moc těžké', 'Houby se sbírají jen v rukavicích'],
    ['Poznáš každou houbu bezpečně?'],
    'Některé jedovaté houby jsou jedlým velmi podobné. Proto houby sbíráme jen s dospělým, který je bezpečně pozná.'),
  q('tulipan', 'Z čeho na jaře vyroste tulipán?', 'Z cibulky',
    ['Ze šišky', 'Ze žaludu', 'Z kaštanu'],
    ['Zahradníci ho sázejí na podzim do země.'],
    'Tulipán roste z cibulky. Na podzim ji zasadíme a na jaře z ní vyroste květina.'),
  q('smrk-zima', 'Proč jsou smrky v zimě zelené?', 'Jehlice na zimu neopadávají',
    ['Natírají je lesníci', 'V zimě jim rostou listy', 'Pod sněhem zezelenají'],
    ['Co se na podzim děje s jehlicemi smrku?'],
    'Smrk si jehlice nechává i přes zimu. Každá jehlice vydrží několik let, pak opadne a naroste nová.'),
];

type Druh = 'strom' | 'ker' | 'bylina';
const DRUHY: [string, Druh][] = [
  ['dub', 'strom'], ['buk', 'strom'], ['lípa', 'strom'], ['bříza', 'strom'], ['javor', 'strom'],
  ['smrk', 'strom'], ['borovice', 'strom'], ['jedle', 'strom'], ['modřín', 'strom'], ['jabloň', 'strom'],
  ['rybíz', 'ker'], ['angrešt', 'ker'], ['líska', 'ker'], ['šípková růže', 'ker'],
  ['pampeliška', 'bylina'], ['sedmikráska', 'bylina'], ['kopretina', 'bylina'], ['mák', 'bylina'],
  ['tulipán', 'bylina'], ['sněženka', 'bylina'], ['kopřiva', 'bylina'], ['heřmánek', 'bylina'], ['jahodník', 'bylina'],
];
const DRUH_POPIS: Record<Druh, string> = {
  strom: 'je strom – má jeden silný dřevnatý kmen a korunu.',
  ker: 'je keř – od země mu roste víc dřevnatých stonků.',
  bylina: 'je bylina – má měkký zelený stonek, který nedřevnatí.',
};

function stromKerBylina(rng: Rng): Spec {
  const [name, druh] = rng.pick(DRUHY);
  return fixed(`druh-${slug(name)}`, `Je ${name} strom, keř, nebo bylina?`, ['Strom', 'Keř', 'Bylina'], ['strom', 'ker', 'bylina'].indexOf(druh),
    ['Má dřevnatý kmen, víc dřevnatých stonků, nebo měkký zelený stonek?'],
    `${capitalize(name)} ${DRUH_POPIS[druh]}`);
}

// ---------------------------------------------------------------------------
// L3 – šíření semen, světlo, houby, jedovaté rostliny, jak to víme

const L3: Spec[] = [
  q('letokruhy', 'Jak poznáš, kolik let bylo pokácenému stromu?', 'Spočítám letokruhy',
    ['Změřím délku listů', 'Spočítám šišky', 'Podle barvy kůry'],
    ['Podívej se na pařez.'],
    'Každý rok přiroste stromu jedna vrstva dřeva – letokruh. Kolik letokruhů, tolik let.'),
  q('listi-proc', 'Proč listnaté stromy na zimu shazují listí?', 'V zimě by listy jen ztrácely vodu',
    ['Aby měla zvířata co jíst', 'Aby na ně lépe svítilo slunce', 'Aby mohly v zimě kvést'],
    ['V zimě je voda v zemi zmrzlá.'],
    'Když je zem zmrzlá, strom nenasaje dost vody. Listy by ji odpařovaly, a tak je strom na podzim shodí.'),
  q('tresen', 'Jak se dostanou semena třešně daleko od stromu?', 'Roznesou je ptáci',
    ['Odnese je vítr', 'Samy odskáčou', 'Odplavou po řece'],
    ['Kdo má rád sladké třešně?'],
    'Ptáci se živí třešněmi a pecky se semeny pak upustí na jiném místě. Tak se třešně šíří.'),
  q('lopuch', 'Jak se dostanou semena lopuchu daleko od rostliny?', 'Zachytí se na srsti zvířat',
    ['Odnese je vítr jako padáček', 'Vystřelí je rostlina', 'Plavou po vodě'],
    ['Plody lopuchu se drží i na oblečení.'],
    'Semena lopuchu jsou schovaná v kulatých plodech s háčky. Ty se zachytí na srsti nebo oblečení a zvíře je odnese daleko. Podle nich vynálezce vymyslel suchý zip.'),
  q('javor', 'Jak létají semena javoru?', 'Točí se jako vrtulka',
    ['Skáčou jako žába', 'Plavou jako loďka', 'Kutálejí se jako míček'],
    ['Každé semeno má tenké křidélko.'],
    'Semena javoru mají křidélka. Když padají, točí se jako vrtulka a vítr je odnese dál od stromu.'),
  q('kvety-barvy', 'Proč jsou květy barevné a voní?', 'Lákají hmyz, který přenáší pyl',
    ['Aby se líbily lidem', 'Aby odháněly déšť', 'Aby je nesnědla zvířata'],
    ['Kdo létá z květu na květ?'],
    'Barva a vůně lákají včely, čmeláky a motýly. Hmyz se napije nektaru a přenese pyl na další květ.'),
  q('tma', 'Rostlina roste ve tmavé skříni. Co se s ní stane?', 'Zbledne a zeslábne',
    ['Víc zezelená', 'Rozkvete', 'Nic, světlo nepotřebuje'],
    ['Co rostlina bez světla nedokáže vyrobit?'],
    'Bez světla rostlina nevyrobí potravu ani zelené barvivo. Zbledne, vytáhne se a zeslábne.'),
  q('za-svetlem', 'Proč se květina na okně naklání ke sklu?', 'Roste za světlem',
    ['Chce vidět ven', 'Utíká před vodou', 'Je jí zima'],
    ['Odkud jde do pokoje nejvíc světla?'],
    'Rostliny rostou směrem ke světlu. Když květináč pootočíš, za pár dní se rostlina natočí zase k oknu.'),
  q('podhoubi', 'Kde je schovaná největší část houby?', 'Pod zemí jako podhoubí',
    ['V klobouku', 'Ve třeni', 'V plodnici nad zemí'],
    ['To, co vidíme nad zemí, je jen malá část houby.'],
    'Houba je hlavně podhoubí – tenká vlákna v půdě nebo ve dřevě. Nad zem vyrůstá jen plodnice s kloboukem a třeněm.'),
  q('mech', 'Jak mech pomáhá lesu?', 'Zadržuje vodu jako houba na nádobí',
    ['Vyrábí med', 'Odhání komáry', 'Svítí v noci'],
    ['Zmáčkni v lese mech po dešti.'],
    'Mech nasaje hodně vody a pomalu ji pouští. Les díky němu tolik nevysychá.'),
  q('konvalinka', 'Která z těchto rostlin je jedovatá?', 'Konvalinka',
    ['Máta', 'Sedmikráska', 'Jahodník'],
    ['Kvete bílými zvonečky a krásně voní.'],
    'Konvalinka je jedovatá, i když krásně voní. Neznámé rostliny proto nikdy neochutnáváme.'),
  q('kopriva', 'Proč kopřiva pálí?', 'Má žahavé chloupky',
    ['Je horká od slunce', 'Má ostré trny jako růže', 'Pálí jen v noci'],
    ['Podívej se na list zblízka lupou.'],
    'Na listech a stonku kopřivy jsou drobné žahavé chloupky. Když se jich dotkneš, ulomí se a pálí.'),
  q('kastany', 'Na podzim sbíráme lesklé kaštany. Na kterém stromě rostou?', 'Na jírovci',
    ['Na dubu', 'Na buku', 'Na lípě'],
    ['Jeho velké listy vypadají jako rozevřená dlaň s prsty.'],
    'Lesklé kaštany na hraní rostou na jírovci maďalu, kterému se často říká kaštan. Jedlé kaštany jsou z jiného stromu, kaštanovníku.'),
  q('jmeli', 'Kde roste jmelí?', 'Na větvích stromů',
    ['Na dně rybníka', 'Na skalách v horách', 'Pod zemí'],
    ['V zimě ho uvidíš jako zelené koule v holých korunách.'],
    'Jmelí roste na větvích stromů a bere si od nich vodu. V zimě je vidět jako zelené koule v korunách.'),
  q('jahoda-semena', 'Kde má jahoda semínka?', 'Na povrchu',
    ['Uvnitř v pecce', 'Ve slupce pod zemí', 'Nemá žádná'],
    ['Prohlédni si jahodu zblízka.'],
    'Jahoda má drobná semínka na povrchu. Každá tečka na jahodě je jedno semínko.'),
  q('jablko-semena', 'Kde má jablko semínka?', 'Uprostřed v jádřinci',
    ['Na povrchu slupky', 'V řapíku', 'Nemá žádná'],
    ['Rozkroj jablko napříč.'],
    'Semínka jablka jsou uprostřed v jádřinci. Když jablko rozkrojíš napříč, uvidíš hvězdičku.'),
  q('kyslik', 'Co dávají rostliny do vzduchu, když na ně svítí slunce?', 'Kyslík',
    ['Kouř', 'Prach', 'Sůl'],
    ['Co potřebujeme k dýchání?'],
    'Na světle rostliny vyrábějí potravu a přitom do vzduchu uvolňují kyslík, který dýcháme.'),
  q('brambora', 'Co je brambora, kterou jíme?', 'Hlíza pod zemí',
    ['Kořen', 'Plod', 'List'],
    ['Rostlina si v ní ukládá zásoby na příští rok.'],
    'Brambora je hlíza – podzemní zásobárna rostliny. Plody brambor jsou malé zelené kuličky a jsou jedovaté.'),
  q('opyleni', 'Co se stane s květem, na který včela přinese pyl?', 'Může z něj vyrůst plod',
    ['Hned uvadne a zmizí', 'Změní se v listy', 'Začne víc vonět'],
    ['Co roste na jabloni po odkvětu?'],
    'Když se pyl dostane na správné místo v květu, květ je opylený. Pak z něj může vyrůst plod se semeny.'),
];

/** „Kterou část rostliny jíme u…?“ */
const CASTI = ['Kořen', 'Stonek', 'Listy', 'Květy', 'Plod', 'Semena'] as const;
type Cast = (typeof CASTI)[number];
/** [u čeho (2. pád), jíme, vysvětlení, části, které se jedí také, a proto nesmí být chybnou možností].
 *  Bez ředkvičky: její bulva je z větší části ztloustlý stonek pod děložními lístky, ne čistý kořen. */
const JIDLA: [string, Cast, string, Cast[]?][] = [
  ['mrkve', 'Kořen', 'Mrkev je kořen. Zelená nať nahoře, to jsou listy.'],
  ['salátu', 'Listy', 'U salátu jíme listy.'],
  ['špenátu', 'Listy', 'U špenátu jíme listy.'],
  ['zelí', 'Listy', 'Hlávka zelí je z listů, které se těsně překrývají.'],
  ['jabloně', 'Plod', 'U jabloně jíme plod – jablko. Uvnitř má semínka.'],
  ['rajčete', 'Plod', 'Rajče je plod – uvnitř najdeš semínka.', ['Semena']],
  ['okurky', 'Plod', 'Okurka je plod – uvnitř má semínka.', ['Semena']],
  ['papriky', 'Plod', 'Paprika je plod – uvnitř má semínka.'],
  ['hrášku', 'Semena', 'Kuličky hrášku jsou semena. Rostou v luscích.', ['Plod']],
  ['brokolice', 'Květy', 'U brokolice jíme nerozvitá poupata květů. Když ji necháš růst, rozkvete žlutě.', ['Stonek']],
  ['květáku', 'Květy', 'U květáku jíme nerozvité květy, jak napovídá i jeho jméno.', ['Stonek']],
  ['kedlubnu', 'Stonek', 'Kedluben je ztloustlý stonek. Listy z něj rostou do stran.', ['Listy']],
  ['chřestu', 'Stonek', 'U chřestu jíme mladé stonky, které vyrůstají ze země.', ['Listy']],
];

function kteraCast(rng: Rng): Spec {
  const [name, cast, explain, also = []] = rng.pick(JIDLA);
  return q(`cast-${slug(name)}`, `Kterou část rostliny jíme u ${name}?`, cast, pickSome(rng, CASTI, 3, [cast, ...also]),
    ['Vzpomeň si, z jakých částí se rostlina skládá.', 'Kde tahle část roste – v zemi, nahoře, nebo v plodu?'],
    explain);
}

// ---------------------------------------------------------------------------
// L4 – fotosyntéza jednoduše, houby jsou samostatná říše, pokusy s rostlinami

const L4: Spec[] = [
  q('fotosynteza', 'Z čeho si list vyrábí potravu?', 'Z vody a vzduchu pomocí světla',
    ['Z hlíny, kterou sní', 'Z pylu od včel', 'Z hnojiva ve tmě'],
    ['Co list potřebuje ze vzduchu a co od Slunce?'],
    'List vyrábí cukr z vody a oxidu uhličitého ze vzduchu. Energii mu dává světlo. Říká se tomu fotosyntéza.'),
  q('fotosynteza-kyslik', 'Co vzniká v listu na světle kromě cukru?', 'Kyslík',
    ['Oxid uhličitý', 'Pyl', 'Sůl'],
    ['Co dýcháme?'],
    'Při fotosyntéze vzniká cukr a kyslík. Kyslík rostlina pouští do vzduchu a my ho dýcháme.'),
  q('fotosynteza-vzduch', 'Kterou část vzduchu list potřebuje k výrobě potravy?', 'Oxid uhličitý',
    ['Kyslík', 'Dusík', 'Vodní páru'],
    ['Je to plyn, který vydechujeme.'],
    'List bere ze vzduchu oxid uhličitý a z něj a z vody vyrábí cukr. Kyslík přitom vzniká.'),
  q('chlorofyl', 'Proč jsou listy zelené?', 'Mají zelené barvivo chlorofyl',
    ['Odrážejí modrou oblohu', 'Pijí zelenou vodu', 'Natírá je rosa'],
    ['V listu je barvivo, které zachycuje světlo.'],
    'Listy obsahují zelené barvivo chlorofyl. Pomocí něj zachycují světlo a vyrábějí potravu.'),
  q('houby-nejsou-rostliny', 'Proč houby nepatří mezi rostliny?', 'Nemají chlorofyl a potravu si nevyrobí',
    ['Rostou v lese', 'Mají klobouk', 'Jsou jedovaté'],
    ['Umí houba vyrábět potravu pomocí světla?'],
    'Houby nemají zelené barvivo a potravu si samy nevyrobí. Tvoří samostatnou říši – nejsou rostliny ani živočichové.'),
  q('vytrusy', 'Čím se houby rozmnožují?', 'Výtrusy',
    ['Semínky z květů', 'Šiškami', 'Pylem'],
    ['Houby nemají květy ani semena.'],
    'Houby se rozmnožují drobnými výtrusy. Jsou tak malé, že je vítr roznese jako prach. Z výtrusu pak vyroste nové podhoubí.'),
  q('houby-prace', 'Jakou práci dělají mnohé houby v lese?', 'Rozkládají spadané listí a dřevo',
    ['Vyrábějí kyslík jako listy', 'Opylují květy', 'Vyrábějí med'],
    ['Proč v lese nejsou metrové vrstvy listí z minulých let?'],
    'Houby rozkládají spadané listí a staré dřevo na živiny, které pak využijí rostliny.'),
  q('mykorhiza', 'Jak si pomáhají houby a stromy?', 'Houba dává stromu vodu, strom houbě cukr',
    ['Strom houbu chrání před deštěm', 'Houba stromu přináší pyl', 'Nijak, houby stromům jen škodí'],
    ['Proč hřiby rostou jen pod některými stromy?'],
    'Vlákna mnoha hub obalují kořeny stromů. Houba stromu podává vodu a živiny a strom jí dává cukr. Proto roste hřib často pod smrkem nebo břízou.'),
  q('dychani', 'Dýchají rostliny?', 'Ano, ve dne i v noci',
    ['Ne, nikdy', 'Jen v zimě', 'Jen když kvetou'],
    ['Potřebuje každá živá buňka energii?'],
    'Rostliny dýchají pořád, ve dne i v noci. Ve dne ale na světle vyrobí víc kyslíku, než spotřebují.'),
  q('lisejnik', 'Co je lišejník?', 'Houba a řasa, které žijí spolu',
    ['Mladý mech', 'Nemocná kůra stromu', 'Plíseň po dešti'],
    ['Jsou to dva různé organismy v jednom.'],
    'Lišejník je soužití houby a řasy, někdy sinice. Řasa vyrábí potravu, houba ji chrání a drží vodu. Proto roste i na holých kamenech.'),
  ord('fotosynteza-kroky', 'Seřaď, jak rostlina vyrábí a rozvádí potravu.',
    ['Kořen nasaje vodu', 'Voda stoupá stonkem do listu', 'List na světle vyrobí cukr', 'Cukr putuje do celé rostliny'],
    ['Kde začíná cesta vody?', 'Z čeho list vyrábí cukr?'],
    'Kořen nasaje vodu a ta stoupá stonkem do listu. List z ní a z oxidu uhličitého ze vzduchu na světle vyrobí cukr. Ten pak putuje do celé rostliny.'),
  ord('od-kvetu', 'Seřaď od květu k nové rostlině.', ['Květ', 'Opylení', 'Plod se semeny', 'Semeno v zemi', 'Klíček'],
    ['Co se musí stát s květem, aby vyrostl plod?'],
    'Květ je opylen, vyroste z něj plod se semeny, semeno se dostane do země a vyklíčí z něj nová rostlina.'),
  q('pokus-svetlo', 'Tom zasadil dvě fazole do kelímků. Jeden dal na okno, druhý do tmavé skříně. Co zjišťuje?', 'Jestli fazole potřebuje světlo',
    ['Jestli fazole potřebuje vodu', 'Jak rychle roste skříň', 'Jestli fazole potřebuje hnojivo'],
    ['Čím se oba kelímky liší?'],
    'Kelímky se liší jen světlem. Když fazole ve skříni zbledne a zeslábne, víme, že světlo potřebuje.'),
  q('karafiat', 'Bílý karafiát postavíš do vody s modrým barvivem. Co uvidíš za den?', 'Květ zmodrá',
    ['Nic se nestane', 'Voda zbělá', 'Květ zčervená'],
    ['Kam putuje voda ze stonku?'],
    'Stonek vede vodu až do květu. Barvivo jde s vodou a obarví lístky květu. Tímhle pokusem se dá cesta vody ukázat.'),
  q('rosnatka', 'Rosnatka roste na chudé rašelině. Jak si přilepší?', 'Živí se i hmyzem',
    ['Pije mléko', 'Živí se kamínky', 'Odejde jinam'],
    ['Na jejích lepkavých listech ulpívají mušky.'],
    'Rosnatka má na listech lepkavé kapky. Mušky se na ně přilepí a rostlina z nich získá živiny, které v rašelině chybějí.'),
  q('letokruhy-proc', 'Proč má strom letokruhy?', 'Každý rok přiroste vrstva dřeva',
    ['Kmen se každý rok přebarví', 'Na kmeni se usadí prach', 'Datel do stromu vyklove kroužky'],
    ['Kdy strom roste rychle a kdy pomalu?'],
    'Na jaře dřevo přirůstá rychle a je světlé, koncem léta pomalu a je tmavší. V zimě strom neroste. Tak vzniká každý rok jeden letokruh.'),
  q('jehlice-proc', 'Proč smrk nemusí na zimu shazovat jehlice?', 'Jehlice ztrácejí jen málo vody',
    ['Jehlice v zimě hřejí', 'Smrk v zimě roste nejrychleji', 'Jehlice sníh odrážejí pryč'],
    ['Porovnej úzkou jehlici a široký list.'],
    'Jehlice jsou úzké a pokryté voskem, a tak ztrácejí jen málo vody. Proto je smrk v zimě nemusí shazovat.'),
  q('energie', 'Odkud má rostlina energii na růst?', 'Ze slunečního světla',
    ['Z hlíny', 'Z hnojiva', 'Z deště'],
    ['Proč rostliny ve tmě slábnou?'],
    'Energii dává rostlině sluneční světlo. Z půdy bere rostlina vodu a živiny, ale energii ne.'),
  q('rise', 'Kdo tvoří samostatnou říši vedle rostlin a živočichů?', 'Houby',
    ['Stromy', 'Mechy', 'Kapradiny'],
    ['Nemají zelené barvivo, a přesto nejsou živočichové.'],
    'Houby jsou samostatná říše. Stromy, mechy i kapradiny jsou rostliny – mají chlorofyl.'),
  q('semeno-zasoba', 'Proč má semínko fazole uvnitř zásobu potravy?', 'Klíček z ní žije, než mu narostou listy',
    ['Aby chutnalo lidem', 'Aby bylo těžší', 'Aby ho vítr neodnesl'],
    ['Může malý klíček pod zemí vyrábět potravu pomocí světla?'],
    'Než klíček vyroste nad zem a narostou mu listy, žije ze zásob v semínku.'),
];

export const rostliny = bankSkill({
  id: ID,
  island: 'svet',
  name: 'Rostliny a houby',
  description: 'Stavba a potřeby rostlin, stromy, keře a byliny, ovoce a zelenina, bezpečí u hub a jednoduchá fotosyntéza.',
  rvp: {
    1: ['ČJS-3-4-02'],
    2: ['ČJS-3-4-02'],
    3: ['ČJS-3-4-02'],
    4: ['ČJS-5-4-04'],
  },
  ability: 'znalosti',
  testLike: 'vedomosti',
  banks: { 1: L1, 2: L2, 3: L3, 4: L4 },
  gen: {
    1: ovoceNeboZelenina,
    2: stromKerBylina,
    3: kteraCast,
  },
  genShare: 0.4,
});

export const rostlinyCards: KnowledgeCard[] = [
  {
    id: `${ID}.letokruhy`,
    skillId: ID,
    level: 2,
    emoji: '🌳',
    title: 'Strom si píše deník',
    text: 'Každý rok stromu přiroste jedna vrstva dřeva – letokruh. Když je spočítáš na pařezu, zjistíš, kolik bylo stromu let.',
  },
  {
    id: `${ID}.suchy-zip`,
    skillId: ID,
    level: 3,
    emoji: '🌿',
    title: 'Suchý zip podle lopuchu',
    text: 'Švýcarský vynálezce George de Mestral si v roce 1941 všiml, jak se mu plody lopuchu chytají na oblečení i na psí srst. Pod mikroskopem na nich uviděl drobné háčky a podle nich vymyslel suchý zip.',
  },
  {
    id: `${ID}.houby`,
    skillId: ID,
    level: 4,
    emoji: '🍄',
    title: 'Houby nejsou rostliny',
    text: 'Houby nemají zelené barvivo a potravu si samy nevyrobí. Tvoří samostatnou říši a v něčem mají blíž ke zvířatům než k rostlinám.',
    fix: {
      before: 'Dlouho se houby učily jako zvláštní rostliny bez květů.',
      evidence: 'Vědci zkoumali pod mikroskopem jejich stavbu a porovnali jejich dědičnou informaci. Ukázalo se, že houby jsou samostatná říše.',
    },
  },
];
