// Země a vesmír: Slunce je hvězda, den a noc, rok, Měsíc a jeho fáze, osm
// planet v pořadí od Slunce, Pluto jako trpasličí planeta, zatmění, sklon
// zemské osy a roční období, rychlost světla. Vysvětlení říkají, jak to víme.
//
// Vysvětlení se ukazuje i po správné odpovědi jako zajímavost (showFact):
// nejdřív hlavní důvod, pak jeden navazující detail.

import { bankSkill, type Spec } from '../../core/bank';
import type { Rng } from '../../core/rng';
import type { KnowledgeCard } from '../../core/types';
import { num, ord, pickSome, q, slug } from './common';

const ID = 'svet.vesmir';

/** Planety v pořadí od Slunce. */
export const PLANETY = ['Merkur', 'Venuše', 'Země', 'Mars', 'Jupiter', 'Saturn', 'Uran', 'Neptun'];
/** 7. pád: „mezi Merkurem a Zemí“. */
const PLANETY_7 = ['Merkurem', 'Venuší', 'Zemí', 'Marsem', 'Jupiterem', 'Saturnem', 'Uranem', 'Neptunem'];
const PORADI = ['první', 'druhá', 'třetí', 'čtvrtá', 'pátá', 'šestá', 'sedmá', 'osmá'];
/** Zajímavost o každé planetě (v pořadí od Slunce). */
const PLANETA_FAKT = [
  'Merkur oběhne Slunce za pouhých 88 dní.',
  'Venuše je nejteplejší planeta – na jejím povrchu je přes 400 °C.',
  'Země je jediná planeta, o které víme, že na ní je život.',
  'Mars je rudý, protože jeho povrch pokrývá rezavý prach.',
  'Jupiter je největší planeta – vešlo by se do něj přes tisíc Zemí.',
  'Saturn má nejnápadnější prstence z kousků ledu a kamení.',
  'Uran obíhá Slunce skoro položený na boku.',
  'Na Neptunu fouká nejsilnější vítr ve Sluneční soustavě.',
];

const VSECHNY = `Od Slunce jdou planety takto: ${PLANETY.join(', ')}.`;

function ntaPlaneta(rng: Rng): Spec {
  const i = rng.int(0, 7);
  const wrong = [i - 1, i + 1, i + 2, i - 2].filter((j) => j >= 0 && j < 8).map((j) => PLANETY[j]);
  return q(`poradi-${i + 1}`, `Která planeta je ${PORADI[i]} od Slunce?`, PLANETY[i], wrong,
    ['Vyjmenuj planety popořadě od Slunce a počítej je na prstech.'],
    `${VSECHNY} Na ${i + 1}. místě je ${PLANETY[i]}. ${PLANETA_FAKT[i]}`);
}

function mezi(rng: Rng): Spec {
  const i = rng.int(1, 6);
  const wrong = pickSome(rng, PLANETY.filter((_, j) => Math.abs(j - i) > 1), 3);
  return q(`mezi-${slug(PLANETY[i])}`, `Která planeta obíhá mezi ${PLANETY_7[i - 1]} a ${PLANETY_7[i + 1]}?`, PLANETY[i], wrong,
    ['Vyjmenuj planety popořadě od Slunce.'],
    `${VSECHNY} Mezi ${PLANETY_7[i - 1]} a ${PLANETY_7[i + 1]} je tedy ${PLANETY[i]}. ${PLANETA_FAKT[i]}`);
}

function seradPlanety(n: number) {
  return (rng: Rng): Spec => {
    const idx = rng.shuffle([...Array(8).keys()]).slice(0, n).sort((a, b) => a - b);
    return ord(`planety-${idx.map((i) => i + 1).join('-')}`, 'Seřaď planety od Slunce.', idx.map((i) => PLANETY[i]),
      ['Která z nich je nejblíž Slunci?', 'Vyjmenuj všech osm planet popořadě.'],
      `${VSECHNY} Čtyři planety nejblíž Slunci jsou kamenné, čtyři vzdálenější jsou obři z plynu a ledu.`);
  };
}

// ---------------------------------------------------------------------------
// L2 – Slunce, den a noc, Měsíc, hvězdy

const L2: Spec[] = [
  q('slunce-hvezda', 'Co je Slunce?', 'Hvězda',
    ['Planeta', 'Měsíc', 'Kometa'],
    ['Svítí samo a hřeje.'],
    'Slunce je hvězda – obrovská koule horkého plynu, která sama svítí a hřeje. Je nám nejblíž ze všech hvězd.'),
  q('den-noc', 'Proč se střídá den a noc?', 'Země se otáčí',
    ['Slunce na noc zhasne', 'Měsíc zakryje Slunce', 'Slunce odletí za hory'],
    ['Zkus posvítit baterkou na míč a pomalu s ním otáčet.'],
    'Země se otáčí kolem své osy. Strana otočená ke Slunci má den, odvrácená strana noc.'),
  q('rok', 'Za jak dlouho oběhne Země kolem Slunce?', 'Za rok',
    ['Za den', 'Za týden', 'Za měsíc'],
    ['Mezi dvěma tvými narozeninami oběhne Země Slunce jednou.'],
    'Země oběhne Slunce jednou za rok, tedy asi za 365 dní. Letí přitom rychlostí asi 30 kilometrů za sekundu.'),
  q('otoceni', 'Za jak dlouho se Země jednou otočí kolem své osy?', 'Za den',
    ['Za hodinu', 'Za rok', 'Za týden'],
    ['Kolikrát se za tu dobu vystřídá den a noc?'],
    'Země se otočí jednou za den, asi za 24 hodin. Proto se den a noc střídají každý den.'),
  q('mesic-kolem', 'Kolem čeho obíhá Měsíc?', 'Kolem Země',
    ['Kolem Marsu', 'Kolem Polárky', 'Nikam, stojí na místě'],
    ['Měsíc je náš nejbližší soused ve vesmíru.'],
    'Měsíc obíhá kolem Země a jeden oběh mu trvá asi měsíc. Právě podle Měsíce dostal jméno i měsíc v kalendáři.'),
  q('mesic-sviti', 'Proč Měsíc v noci svítí?', 'Odráží světlo Slunce',
    ['Uvnitř hoří oheň', 'Je to hvězda', 'Svítí na něj světla měst'],
    ['Svítí Měsíc sám, nebo ho něco osvětluje?'],
    'Měsíc sám nesvítí. Odráží světlo Slunce, podobně jako zeď, na kterou svítíš baterkou. Proto vidíme jen jeho osvětlenou část.'),
  q('hvezdy-ve-dne', 'Jsou hvězdy na obloze i ve dne?', 'Ano, ale Slunce je přezáří',
    ['Ne, ráno zhasnou', 'Ne, ve dne odletí', 'Ne, schovají se za mraky'],
    ['Uvidíš ve dne na slunci rozsvícenou baterku?'],
    'Hvězdy jsou na obloze pořád. Ve dne je ale Slunce tak jasné, že slabé světlo hvězd nevidíme.'),
  q('nejblizsi-hvezda', 'Která hvězda je Zemi nejblíž?', 'Slunce',
    ['Polárka', 'Měsíc', 'Večernice'],
    ['Je vidět hlavně ve dne.'],
    'Nejbližší hvězda je Slunce. Měsíc není hvězda a Večernice je planeta Venuše.'),
  q('tvar-mesice', 'Proč vidíme Měsíc někdy jako srpek a jindy jako kulatý?', 'Vidíme různě velkou osvětlenou část',
    ['Kousky mu odpadávají', 'Zakrývají ho mraky', 'Nafukuje se a splaskává'],
    ['Měsíc osvětluje Slunce jen z jedné strany.'],
    'Slunce osvětluje vždy půlku Měsíce. Jak Měsíc obíhá Zemi, vidíme z té osvětlené půlky jednou víc a jindy méně.'),
  q('planeta', 'Na které planetě žijeme?', 'Na Zemi',
    ['Na Marsu', 'Na Měsíci', 'Na Slunci'],
    ['Je to třetí planeta od Slunce.'],
    'Žijeme na planetě Zemi. Je jediná, o které víme, že na ní je život.'),
  q('slunce-velke', 'Je Slunce větší než Země?', 'Ano, mnohem větší',
    ['Ne, je menší', 'Jsou stejně velké', 'Je velké jako Měsíc'],
    ['Proč se nám asi zdá malé?'],
    'Slunce je obrovské – vešlo by se do něj přes milion Zemí. Malé se nám zdá jen proto, že je hodně daleko.'),
  q('slunce-oci', 'Proč se nikdy nedíváme přímo do Slunce?', 'Poškodilo by nám to oči',
    ['Slunce by se urazilo', 'Slunce by zhaslo', 'Uviděli bychom tmu'],
    ['Slunce svítí velmi silně.'],
    'Sluneční světlo je tak silné, že by nám poškodilo oči. Do Slunce se nikdy nedíváme, a už vůbec ne dalekohledem.'),
  q('tvar-zeme', 'Jaký tvar má Země?', 'Koule',
    ['Placka', 'Krychle', 'Válec'],
    ['Podívej se na glóbus.'],
    'Země je obrovská koule. Víme to z fotek z vesmíru a lidé to poznali už dávno podle kulatého stínu Země na Měsíci.'),
  q('druha-strana', 'Když je u nás noc, co je na druhé straně Země?', 'Den',
    ['Také noc', 'Všude je večer', 'Tam není nic'],
    ['Na kterou stranu Země zrovna svítí Slunce?'],
    'Slunce vždy osvětluje jen půlku Země. Když je u nás noc, na druhé straně Země je den.'),
  q('astronaut', 'Jak se jmenuje člověk, který letí do vesmíru?', 'Astronaut',
    ['Pilot letadla', 'Potápěč', 'Horolezec'],
    ['Obléká si skafandr.'],
    'Astronaut, u nás se říká i kosmonaut, letí do vesmíru v raketě a mimo loď nosí skafandr. První Čech ve vesmíru byl Vladimír Remek v roce 1978.'),
  q('mesic-vzduch', 'Je na Měsíci vzduch k dýchání?', 'Ne, astronauti potřebují skafandr',
    ['Ano, jako na Zemi', 'Ano, ale jen v noci', 'Ano, na vrcholcích hor'],
    ['Proč mají astronauti na Měsíci helmu?'],
    'Na Měsíci vzduch není. Astronauti si proto nosí vzduch s sebou ve skafandru.'),
  q('mesic-ve-dne', 'Dá se Měsíc někdy vidět i ve dne?', 'Ano, často',
    ['Nikdy', 'Jen o Vánocích', 'Jen v zimě'],
    ['Podívej se odpoledne na oblohu.'],
    'Měsíc bývá na obloze často i ve dne, třeba odpoledne nebo ráno. Je jasný, a tak ho Slunce nepřezáří.'),
  q('dalekohled', 'Čím si lidé prohlížejí vzdálené hvězdy a planety?', 'Dalekohledem',
    ['Mikroskopem', 'Lupou', 'Teploměrem'],
    ['Mikroskop je na malé věci zblízka. A na vzdálené?'],
    'Dalekohled přiblíží vzdálené věci. Hvězdáři se jím dívají na planety, Měsíc a hvězdy.'),
  q('hvezdy-tecky', 'Proč vypadají hvězdy jako malé tečky?', 'Jsou nesmírně daleko',
    ['Jsou opravdu malinké', 'Jsou to jiskry z ohně', 'Jsou nalepené na obloze'],
    ['Proč se nám zdá malé i Slunce?'],
    'Mnohé hvězdy jsou ještě větší než Slunce, ale jsou tak daleko, že je vidíme jen jako tečky.'),
  num('pocet-planet', 'Kolik planet obíhá kolem Slunce?', 8,
    ['Zkus je vyjmenovat a počítej na prstech.'],
    'Kolem Slunce obíhá osm planet: Merkur, Venuše, Země, Mars, Jupiter, Saturn, Uran a Neptun.',
    { difficulty: 0.3 }),
];

// ---------------------------------------------------------------------------
// L3 – planety, fáze Měsíce, Pluto, galaxie

const L3: Spec[] = [
  q('nejblize', 'Která planeta je nejblíž Slunci?', 'Merkur',
    ['Venuše', 'Země', 'Mars', 'Neptun'],
    ['Je to nejmenší planeta.'],
    'Merkur je nejblíž Slunci a je také nejmenší z osmi planet. Oběhne Slunce za pouhých 88 dní.'),
  q('nejdal', 'Která planeta je od Slunce nejdál?', 'Neptun',
    ['Uran', 'Saturn', 'Pluto', 'Jupiter'],
    ['Pozor, Pluto už planeta není.'],
    'Nejdál od Slunce je Neptun. Pluto obíhá ještě dál, ale od roku 2006 je trpasličí planeta.'),
  q('nejvetsi', 'Která planeta je největší?', 'Jupiter',
    ['Saturn', 'Země', 'Neptun', 'Mars'],
    ['Je to pátá planeta od Slunce.'],
    'Největší planeta je Jupiter. Je to obr z plynu a vešlo by se do něj přes tisíc Zemí.'),
  q('ruda', 'Která planeta se nazývá Rudá planeta?', 'Mars',
    ['Venuše', 'Jupiter', 'Merkur', 'Saturn'],
    ['Obíhá hned za Zemí.'],
    'Mars je načervenalý, protože jeho povrch pokrývá rezavý prach. Proto se mu říká Rudá planeta.'),
  q('prstence', 'Která planeta má nejnápadnější prstence?', 'Saturn',
    ['Mars', 'Venuše', 'Merkur', 'Země'],
    ['Prstence jsou z kousků ledu a kamení.'],
    'Saturn má velké a jasné prstence z kousků ledu a kamení. Slabší prstence mají i Jupiter, Uran a Neptun.'),
  q('pluto', 'Čím je Pluto od roku 2006?', 'Trpasličí planetou',
    ['Devátou planetou', 'Hvězdou', 'Měsícem Země'],
    ['Astronomové ho přeřadili do nové skupiny.'],
    'Od roku 2006 je Pluto trpasličí planeta. Je menší než náš Měsíc a za Neptunem obíhá s dalšími podobnými tělesy.'),
  q('faze-proc', 'Proč vidíme Měsíc jednou jako srpek a jindy jako kulatý?', 'Vidíme různou část jeho osvětlené strany',
    ['Zakrývá ho stín Země', 'Mraky ho ořezávají', 'Měsíc se zmenšuje'],
    ['Měsíc obíhá Zemi a Slunce ho osvětluje z jedné strany.'],
    'Slunce osvětluje vždy půlku Měsíce. Podle toho, kde Měsíc na své cestě kolem Země je, vidíme z osvětlené půlky větší nebo menší kus. Stín Země to není – ten Měsíc zakryje jen při zatmění.'),
  ord('faze', 'Seřaď fáze Měsíce. Začni novem.', ['Nov', 'První čtvrť', 'Úplněk', 'Poslední čtvrť'],
    ['Po novu Měsíc dorůstá.', 'Úplněk je, když svítí celý.'],
    'Po novu Měsíc dorůstá do první čtvrti, pak je úplněk, potom couvá do poslední čtvrti a zase je nov. Trvá to asi měsíc.'),
  q('uplnek', 'Jak se jmenuje fáze, kdy Měsíc svítí jako celý kulatý?', 'Úplněk',
    ['Nov', 'První čtvrť', 'Poslední čtvrť'],
    ['Měsíc je tehdy celý, úplný.'],
    'Úplněk je, když vidíme celou osvětlenou stranu Měsíce. Bývá asi dva týdny po novu.'),
  q('nov', 'Jak se jmenuje fáze, kdy Měsíc skoro vůbec nevidíme?', 'Nov',
    ['Úplněk', 'První čtvrť', 'Poslední čtvrť'],
    ['Měsíc je tehdy mezi Zemí a Sluncem.'],
    'Při novu je Měsíc mezi Zemí a Sluncem a k nám míří jeho neosvětlená strana. Proto ho skoro nevidíme.'),
  q('mesic-obeh', 'Za jak dlouho oběhne Měsíc kolem Země?', 'Asi za měsíc',
    ['Za jeden den', 'Za rok', 'Za hodinu'],
    ['Podle Měsíce dostal jméno kus kalendáře.'],
    'Měsíc oběhne Zemi asi za 27 dní a jeho fáze se vystřídají asi za 29 a půl dne. Podle Měsíce se jmenuje i měsíc v kalendáři.'),
  q('zivot', 'Na které planetě víme o životě?', 'Jen na Zemi',
    ['Na Marsu', 'Na Venuši', 'Na Jupiteru'],
    ['Vědci hledají život i jinde, zatím ale bez úspěchu.'],
    'Zatím víme o životě jen na Zemi. Vědci ho hledají třeba na Marsu, ale dosud ho nikde jinde neprokázali.'),
  q('soustava', 'Jak se jmenuje Slunce se vším, co kolem něj obíhá?', 'Sluneční soustava',
    ['Mléčná dráha', 'Souhvězdí', 'Velký vůz'],
    ['Patří do ní planety, měsíce i komety.'],
    'Slunce, osm planet, jejich měsíce, trpasličí planety, planetky a komety tvoří Sluneční soustavu.'),
  q('mlecna-draha', 'Jak se jmenuje naše galaxie?', 'Mléčná dráha',
    ['Sluneční soustava', 'Velký vůz', 'Polárka'],
    ['Za tmavé noci ji uvidíš jako bělavý pruh na obloze.'],
    'Naše galaxie je Mléčná dráha – obrovské hvězdné město s miliardami hvězd. Slunce je jedna z nich.'),
  q('velky-vuz', 'Co je Velký vůz?', 'Skupina hvězd na obloze',
    ['Planeta', 'Kometa', 'Měsíc Jupiteru'],
    ['Najdeš ho na severní obloze.'],
    'Velký vůz je sedm jasných hvězd, které tvoří tvar vozu. Pomůže ti najít Polárku.'),
  q('vecernice', 'Jak se říká Venuši, když jasně svítí večer po západu Slunce?', 'Večernice',
    ['Polárka', 'Kometa', 'Jitřenka'],
    ['Ráno se jí říká jinak než večer.'],
    'Venuše je po Měsíci nejjasnější těleso noční oblohy. Večer se jí říká Večernice, ráno Jitřenka.'),
  q('zatmeni-slunce', 'Co se děje při zatmění Slunce?', 'Měsíc zakryje Slunce',
    ['Země zakryje Slunce', 'Slunce zhasne', 'Mraky zakryjí Slunce'],
    ['Co se může dostat mezi Slunce a Zemi?'],
    'Při zatmění Slunce se Měsíc dostane přesně mezi Slunce a Zemi a zakryje ho. Dívat se na to smíme jen s dospělým a jen přes speciální brýle na zatmění.'),
  q('padajici-hvezda', 'Co je padající hvězda?', 'Kamínek, který shoří ve vzduchu',
    ['Hvězda, která spadla', 'Letadlo v noci', 'Jiskra z Měsíce'],
    ['Hvězdy jsou obrovské a daleko. Co tedy může „spadnout“?'],
    'Padající hvězda je kamínek z vesmíru, který vletí do vzduchu nad Zemí a rozžhaví se. Odborně se jí říká meteor.'),
  q('kometa', 'Co je kometa?', 'Těleso z ledu a prachu s ohonem',
    ['Hvězda, která padá', 'Měsíc Marsu', 'Planeta s prstenci'],
    ['Když se přiblíží ke Slunci, začne se odpařovat.'],
    'Kometa je hrouda ledu a prachu. Když se přiblíží ke Slunci, led se odpařuje a vznikne dlouhý svítící ohon.'),
];

// ---------------------------------------------------------------------------
// L4 – jak jsme poznali vesmír, lety do vesmíru, planety zblízka

const L4: Spec[] = [
  q('venuse-teplo', 'Která planeta je nejteplejší?', 'Venuše',
    ['Merkur', 'Mars', 'Jupiter'],
    ['Není to ta nejbližší ke Slunci!'],
    'Nejteplejší je Venuše. Má hustou vrstvu plynů, která drží teplo jako peřina. Sondy tam naměřily přes 400 °C.'),
  q('galileo', 'Kdo první uviděl dalekohledem měsíce Jupiteru?', 'Galileo Galilei',
    ['Mikuláš Koperník', 'Isaac Newton', 'Albert Einstein'],
    ['Byl to italský vědec, který si sám postavil dalekohled.'],
    'Galileo Galilei v roce 1610 uviděl dalekohledem čtyři měsíce, které obíhají Jupiter. Byl to důkaz, že ne všechno obíhá Zemi.'),
  q('kopernik', 'Co tvrdil Mikuláš Koperník?', 'Země obíhá kolem Slunce',
    ['Slunce obíhá kolem Země', 'Země je placatá', 'Měsíc je hvězda'],
    ['Kdo je uprostřed: Slunce, nebo Země?'],
    'Mikuláš Koperník v knize z roku 1543 popsal, že uprostřed je Slunce a Země i ostatní planety kolem něj obíhají. Tehdy tomu mnoho lidí nevěřilo.'),
  q('stopy', 'Proč stopy astronautů na Měsíci vydrží mnoho let?', 'Na Měsíci nefouká vítr ani neprší',
    ['Astronauti je zalili', 'Měsíc je z betonu', 'Hlídají je roboti'],
    ['Co na Zemi smaže stopy v písku?'],
    'Na Měsíci není vzduch, takže tam nefouká vítr ani neprší. Stopy astronautů tam zůstanou velmi dlouho.'),
  q('prvni-na-mesici', 'Ve kterém roce poprvé přistáli lidé na Měsíci?', 'V roce 1969',
    ['V roce 1869', 'V roce 1999', 'V roce 2019'],
    ['Bylo to před více než padesáti lety.'],
    'V roce 1969 přistála na Měsíci posádka lodi Apollo 11. Neil Armstrong jako první vstoupil na jeho povrch.'),
  q('gagarin', 'Kdo byl první člověk ve vesmíru?', 'Jurij Gagarin',
    ['Neil Armstrong', 'Galileo Galilei', 'Mikuláš Koperník'],
    ['Letěl v roce 1961.'],
    'Jurij Gagarin v roce 1961 jako první člověk obletěl Zemi v kosmické lodi. Celý let trval necelé dvě hodiny.'),
  q('armstrong', 'Kdo jako první vstoupil na Měsíc?', 'Neil Armstrong',
    ['Jurij Gagarin', 'Galileo Galilei', 'Isaac Newton'],
    ['Stalo se to v roce 1969.'],
    'Neil Armstrong vystoupil na Měsíc v roce 1969. Řekl, že je to malý krok pro člověka, ale obrovský skok pro lidstvo.'),
  q('polarka', 'Proč je Polárka důležitá pro cestovatele?', 'Ukazuje směr k severu',
    ['Je nejjasnější hvězda', 'Svítí jen v zimě', 'Ukazuje, kolik je hodin'],
    ['Polárka stojí na obloze skoro pořád na stejném místě.'],
    'Polárka stojí skoro přesně nad severem a v noci se téměř nehýbe. Námořníci podle ní odedávna hledali sever. Nejjasnější hvězda to ale není.'),
  q('kamenne', 'Které planety jsou kamenné, s pevným povrchem?', 'Merkur, Venuše, Země a Mars',
    ['Jupiter, Saturn, Uran a Neptun', 'Jen Země', 'Všech osm'],
    ['Jsou to čtyři planety nejblíž Slunci.'],
    'Merkur, Venuše, Země a Mars jsou kamenné. Jupiter a Saturn jsou obři z plynu, Uran a Neptun obři z ledu a plynu.'),
  q('pas-planetek', 'Co obíhá Slunce mezi Marsem a Jupiterem?', 'Pás planetek',
    ['Pluto', 'Země', 'Měsíc'],
    ['Je tam obrovské množství kamenných těles menších než planety.'],
    'Mezi Marsem a Jupiterem obíhá pás planetek – spousta kamenných těles různé velikosti.'),
  q('uplnek-svetlo', 'Proč je noc za úplňku světlejší?', 'Měsíc k nám odráží nejvíc světla',
    ['Hvězdy svítí víc', 'Slunce v noci svítí přímo', 'Lampy svítí víc'],
    ['Kolik z osvětlené strany Měsíce vidíme při úplňku?'],
    'Při úplňku vidíme celou osvětlenou stranu Měsíce. Odráží k nám nejvíc slunečního světla, a tak je noc světlejší.'),
  q('lod-obzor', 'Loď odplouvá k obzoru. Co z ní zmizí jako první?', 'Spodní část lodi',
    ['Špička stěžně', 'Celá najednou', 'Vlajka nahoře'],
    ['Země je kulatá a loď „zapadá“ za její oblinu.'],
    'Loď mizí za oblinou Země: nejdřív zmizí trup a nakonec špička stěžně. Tak lidé už dávno poznali, že Země je kulatá.'),
  q('rok-mars', 'Proč je rok na Marsu delší než na Zemi?', 'Mars je dál od Slunce a oběh trvá déle',
    ['Mars se točí pomaleji', 'Na Marsu je zima', 'Mars je menší'],
    ['Která dráha je delší – ta blíž Slunci, nebo dál?'],
    'Mars obíhá dál od Slunce, jeho dráha je delší a letí pomaleji. Jeden oběh mu trvá skoro dva naše roky.'),
  q('merkur-rok', 'Na které planetě je rok nejkratší?', 'Na Merkuru',
    ['Na Neptunu', 'Na Zemi', 'Na Jupiteru'],
    ['Která planeta má ke Slunci nejblíž?'],
    'Merkur je nejblíž Slunci a oběhne ho za pouhých 88 dní. Rok na Merkuru je tedy nejkratší.'),
  q('putovani-slunce', 'Proč Slunce během dne putuje po obloze od východu k západu?', 'Země se otáčí',
    ['Slunce obíhá kolem Země', 'Vítr Slunce posouvá', 'Mraky ho táhnou'],
    ['Pohybuje se opravdu Slunce, nebo my?'],
    'Slunce jen vypadá, že se pohybuje. Ve skutečnosti se otáčí Země se všemi, kdo na ní jsou.'),
  ord('faze-6', 'Seřaď fáze Měsíce. Začni novem.',
    ['Nov', 'Dorůstající srpek', 'První čtvrť', 'Úplněk', 'Poslední čtvrť', 'Couvající srpek'],
    ['Po novu Měsíc dorůstá.', 'Srpek těsně před novem couvá.'],
    'Nov, dorůstající srpek, první čtvrť, úplněk, poslední čtvrť a couvající srpek. Pak je zase nov.'),
  q('zatmeni-mesice', 'Co se děje při zatmění Měsíce?', 'Měsíc vstoupí do stínu Země',
    ['Měsíc zakryje Slunce', 'Měsíc zhasne', 'Mraky zakryjí Měsíc'],
    ['Co je při zatmění Měsíce mezi Sluncem a Měsícem?'],
    'Při zatmění Měsíce je Země mezi Sluncem a Měsícem a vrhá na Měsíc svůj stín. Měsíc pak bývá načervenalý.'),
  q('iss', 'Co je Mezinárodní vesmírná stanice?', 'Laboratoř, která obíhá Zemi',
    ['Planeta s lidmi', 'Letiště na Měsíci', 'Hvězda s anténou'],
    ['Astronauti na ní žijí a pracují celé měsíce.'],
    'Mezinárodní vesmírná stanice obíhá Zemi asi 400 km nad námi. Astronauti z různých zemí na ní žijí a dělají pokusy.'),
  q('mesic-skoky', 'Proč astronauti na Měsíci skákali tak vysoko?', 'Měsíc je přitahuje slaběji než Země',
    ['Měli pružiny v botách', 'Na Měsíci fouká silný vítr', 'Povrch Měsíce pruží jako trampolína'],
    ['Měsíc je mnohem menší než Země.'],
    'Měsíc je menší a přitahuje věci asi šestkrát slaběji než Země. Proto tam astronauti vyskočili mnohem výš.'),
];

// ---------------------------------------------------------------------------
// L5 – Měsíc a světlo, Galileo, planety zblízka, velikosti a vzdálenosti

const L5: Spec[] = [
  q('mesic-strana', 'Proč vidíme ze Země pořád stejnou stranu Měsíce?', 'Otočí se jednou za každý oběh',
    ['Měsíc se vůbec neotáčí', 'Druhá strana je pořád ve tmě', 'Druhou stranu zakrývá Země'],
    ['Za jak dlouho se Měsíc otočí a za jak dlouho oběhne Zemi?'],
    'Měsíc se otočí kolem své osy za stejnou dobu, za jakou oběhne Zemi. Proto k nám míří pořád stejnou stranou. Odvrácená strana ale tmavá není – svítí na ni Slunce, když je u nás nov.'),
  q('faze-cyklus', 'Za jak dlouho se vystřídají všechny fáze Měsíce?', 'Asi za 29 a půl dne',
    ['Asi za 7 dní', 'Asi za 365 dní', 'Přesně za 24 hodin'],
    ['Je to skoro celý měsíc.'],
    'Od novu do dalšího novu uplyne asi 29 a půl dne. Podle Měsíce se dřív počítaly měsíce v kalendáři.'),
  q('dorusta', 'Měsíc svítí zprava a má tvar písmene D. Co dělá?', 'Dorůstá',
    ['Couvá', 'Je v úplňku', 'Je v novu'],
    ['Za pár dní bude osvětlené části víc, nebo méně?'],
    'Při pohledu z Česka platí: Měsíc osvětlený zprava jako D dorůstá, osvětlený zleva jako C couvá. Na jižní polokouli je to obráceně.'),
  q('couva', 'Měsíc svítí zleva a má tvar písmene C. Co dělá?', 'Couvá',
    ['Dorůstá', 'Je v úplňku', 'Je v novu'],
    ['Pomůže ti písmeno, které tvar připomíná.'],
    'Při pohledu z Česka platí: Měsíc jako C couvá, jako D dorůstá. Stačí si zapamatovat první písmena.'),
  q('venuse-faze', 'Co uviděl Galileo dalekohledem na Venuši?', 'Že má fáze jako Měsíc',
    ['Že má prstence', 'Že na ní rostou lesy', 'Že je placatá'],
    ['Venuši, stejně jako Měsíc, osvětluje Slunce.'],
    'Galileo uviděl, že Venuše má fáze – jednou je jako tenký srpek, jindy skoro celá. Takové fáze může mít, jen když obíhá kolem Slunce.'),
  q('mars-cerveny', 'Proč je Mars červený?', 'Povrch pokrývá rezavý prach',
    ['Je rozžhavený', 'Odráží červené Slunce', 'Je pokrytý lávou'],
    ['Co se stane se železem, když zrezaví?'],
    'Na povrchu Marsu je hodně železa, které zrezavělo. Rezavý prach barví Mars do červena.'),
  q('mars-jak-vime', 'Jak víme, jak vypadá povrch Marsu zblízka?', 'Jezdí po něm vozítka s kamerami',
    ['Byli tam lidé', 'Je vidět pouhým okem', 'Jen to hádáme'],
    ['Kdo nebo co odtud posílá fotky?'],
    'Po Marsu jezdí robotická vozítka s kamerami a přístroji. Posílají na Zemi fotky a měření. Lidé tam zatím nebyli.'),
  q('jupiter-zeme', 'Kolik Zemí by se vešlo do Jupiteru?', 'Přes tisíc',
    ['Asi deset', 'Jen dvě', 'Ani jedna'],
    ['Jupiter je největší planeta.'],
    'Jupiter je obrovský – vešlo by se do něj přes 1 300 Zemí.'),
  q('slunce-zeme', 'Kolik Zemí by se vešlo do Slunce?', 'Přes milion',
    ['Asi sto', 'Asi deset', 'Asi tisíc'],
    ['Slunce je mnohem větší i než Jupiter.'],
    'Slunce je tak velké, že by se do něj vešlo přes milion Zemí. Přesto existují hvězdy, které jsou ještě mnohem větší.'),
  q('hvezdy-sviti', 'Proč hvězdy svítí?', 'Jsou to horká slunce, která sama září',
    ['Odrážejí světlo Měsíce', 'Jsou to lampy na obloze', 'Odrážejí světlo Země'],
    ['Svítí Slunce samo?'],
    'Hvězdy jsou obrovské horké koule plynu jako Slunce. Září samy, na rozdíl od planet a Měsíce, které světlo jen odrážejí.'),
  q('stred', 'Co je uprostřed Sluneční soustavy?', 'Slunce',
    ['Země', 'Měsíc', 'Jupiter'],
    ['Podle čeho má soustava jméno?'],
    'Uprostřed Sluneční soustavy je Slunce. Planety, planetky i komety obíhají kolem něj.'),
  ord('vzdalenosti', 'Seřaď od nejbližšího k Zemi po nejvzdálenější.', ['Měsíc', 'Slunce', 'Neptun', 'Polárka'],
    ['Co obíhá přímo kolem Země?', 'Polárka je hvězda daleko za Sluneční soustavou.'],
    'Měsíc je nejblíž, Slunce asi 400krát dál, Neptun ještě mnohem dál a Polárka je hvězda daleko za Sluneční soustavou.'),
  q('hvezdy-toci', 'Proč se hvězdy během noci pomalu točí kolem Polárky?', 'Země se otáčí a osa míří k Polárce',
    ['Hvězdy obíhají Polárku', 'Vítr hvězdy roztáčí', 'Polárka hvězdy přitahuje'],
    ['Kdo se ve skutečnosti otáčí – hvězdy, nebo my?'],
    'Otáčí se Země a její osa míří skoro přesně k Polárce. Proto se zdá, že se celá obloha točí kolem ní.'),
  q('meteorit', 'Jak se říká kamenu z vesmíru, který dopadl na Zemi?', 'Meteorit',
    ['Meteor', 'Kometa', 'Planeta'],
    ['Padající hvězda na obloze je meteor. A když kámen dopadne?'],
    'Meteor je svítící stopa na obloze. Když kousek kamene nebo železa nevyhoří a dopadne na zem, je to meteorit.'),
  q('odvracena-strana', 'Jak víme, jak vypadá odvrácená strana Měsíce?', 'Vyfotografovaly ji sondy',
    ['Je vidět ze Země', 'Namalovali ji malíři', 'Nikdo to neví'],
    ['Ze Země ji nikdy neuvidíme. Kdo tedy mohl?'],
    'Odvrácenou stranu Měsíce poprvé vyfotila sonda v roce 1959. Dnes ji známe z mnoha snímků.'),
];

// ---------------------------------------------------------------------------
// L6 – sklon osy, světlo, důkazy a výpočty (nad rámec 1. stupně)

const L6: Spec[] = [
  q('osa', 'Proč se u nás střídají roční období?', 'Zemská osa je skloněná',
    ['Země je v létě blíž Slunci', 'Slunce v zimě méně hoří', 'Měsíc v zimě zakrývá Slunce'],
    ['Kdyby šlo o vzdálenost, bylo by léto na celé Zemi najednou?'],
    'Zemská osa je skloněná. Během roku je ke Slunci přikloněná jednou severní a jednou jižní polokoule. Ta přikloněná má léto.'),
  q('perihelium', 'Kdy je Země nejblíž Slunci?', 'Začátkem ledna',
    ['V červenci', 'Na jaře', 'Koncem září'],
    ['Pozor, není to v létě!'],
    'Země je Slunci nejblíž začátkem ledna – a u nás je přitom zima. Roční období tedy nezpůsobuje vzdálenost od Slunce.'),
  q('svetlo-slunce', 'Jak dlouho letí světlo ze Slunce na Zemi?', 'Asi 8 minut',
    ['Asi 8 sekund', 'Asi 8 hodin', 'Asi 8 dní'],
    ['Světlo je nejrychlejší, ale Slunce je opravdu daleko.'],
    'Sluneční světlo k nám letí asi 8 minut. Slunce na obloze tedy vidíme takové, jaké bylo před osmi minutami.'),
  q('svetlo-mesic', 'Jak dlouho letí světlo z Měsíce na Zemi?', 'Něco přes 1 sekundu',
    ['Asi 8 minut', 'Asi hodinu', 'Asi den'],
    ['Měsíc je asi 400krát blíž než Slunce.'],
    'Měsíc je asi 400krát blíž než Slunce, a tak jeho světlo k nám letí jen něco přes sekundu.'),
  q('minulost', 'Když se v noci díváš na vzdálenou hvězdu, co vlastně vidíš?', 'Světlo, které k nám letělo mnoho let',
    ['Hvězdu přesně teď', 'Odraz Měsíce', 'Lampu na obloze'],
    ['Jak dlouho letí světlo i z blízkého Slunce?'],
    'Světlo ze vzdálených hvězd k nám letí roky, i tisíce let. Díváme se tedy do minulosti.'),
  q('australie', 'V prosinci je u nás zima. Jaké období je v Austrálii a proč?', 'Léto – je natočená ke Slunci',
    ['Zima – je daleko', 'Léto – je blíž Slunci', 'Jaro – je na jihu'],
    ['Která polokoule je v prosinci přikloněná ke Slunci?'],
    'V prosinci je ke Slunci přikloněná jižní polokoule, a proto je v Austrálii léto. Vzdálenost od Slunce tu nehraje roli.'),
  q('eratosthenes', 'Jak změřil Eratosthenés už před více než 2 000 lety velikost Země?', 'Porovnal stíny ve dvou městech',
    ['Obešel celou Zemi', 'Podíval se z letadla', 'Změřil ji provazem'],
    ['V jednom městě v poledne sloupy nevrhaly stín, ve druhém ano.'],
    'Eratosthenés zjistil, že v poledne stejného dne jsou stíny ve dvou městech různě dlouhé. Z rozdílu a vzdálenosti měst spočítal obvod Země docela přesně.'),
  q('beztize', 'Proč astronauti na vesmírné stanici volně plují vzduchem?', 'Padají spolu se stanicí kolem Země',
    ['Ve vesmíru není žádná přitažlivost', 'Stanice je plná vody', 'Mají lehké boty'],
    ['Země přitahuje i stanici. Proč tedy nespadne dolů?'],
    'I ve výšce stanice Země přitahuje skoro stejně silně. Stanice i astronauti ale pořád padají kolem Země – letí tak rychle, že míjejí její povrch. Proto se vznášejí.'),
  q('venuse-den', 'Která planeta se jednou otočí kolem své osy za delší dobu, než jednou oběhne Slunce?', 'Venuše',
    ['Země', 'Mars', 'Jupiter'],
    ['Tahle planeta se otáčí neuvěřitelně pomalu.'],
    'Venuše se otočí kolem své osy za 243 našich dní, ale Slunce oběhne už za 225 dní. Jedno otočení jí tedy trvá déle než celý oběh.'),
  q('jupiter-den', 'Která planeta se otáčí nejrychleji a má nejkratší den?', 'Jupiter',
    ['Venuše', 'Merkur', 'Země'],
    ['Den na ní trvá méně než polovinu našeho dne.'],
    'Jupiter se otočí kolem své osy asi za 10 hodin, i když je ze všech planet největší.'),
  q('galileo-dukaz', 'Který Galileův objev ukázal, že ne všechno obíhá kolem Země?', 'Měsíce obíhající Jupiter',
    ['Hory na Měsíci', 'Skvrny na Slunci', 'Mléčná dráha z hvězd'],
    ['Kolem čeho obíhala tělesa, která uviděl?'],
    'Galileo uviděl čtyři měsíce, které obíhají Jupiter. Bylo tak jasné, že ne všechno ve vesmíru obíhá Zemi.'),
  q('venuse-dukaz', 'Galileo viděl Venuši jednou skoro celou a jindy jako tenký srpek. Co z toho plyne?', 'Venuše obíhá kolem Slunce',
    ['Venuše obíhá kolem Země', 'Venuše je hvězda', 'Venuše je placatá'],
    ['Kdy bychom mohli vidět Venuši skoro celou osvětlenou?'],
    'Skoro celou osvětlenou Venuši vidíme, jen když je za Sluncem. To by nešlo, kdyby obíhala kolem Země. Proto obíhá Slunce.'),
  q('zatmeni-kazdy-mesic', 'Proč není zatmění Slunce při každém novu?', 'Dráha Měsíce je trochu nakloněná',
    ['Měsíc se někdy schová', 'Slunce je někdy moc malé', 'Zatmění je jen v zimě'],
    ['Prochází Měsíc při každém novu přesně před Sluncem?'],
    'Dráha Měsíce je vůči dráze Země trochu skloněná. Většinou při novu projde nad Sluncem nebo pod ním a zatmění nenastane.'),
  ord('zatmeni-slunce-rada', 'Při zatmění Slunce jsou tři tělesa v řadě. Seřaď je od Slunce.', ['Slunce', 'Měsíc', 'Země'],
    ['Kdo zakrývá Slunce?'],
    'Při zatmění Slunce je Měsíc mezi Sluncem a Zemí a vrhá na Zemi svůj stín. Do Slunce se ani tehdy nesmíme dívat bez speciálních brýlí.'),
  ord('zatmeni-mesice-rada', 'Při zatmění Měsíce jsou tři tělesa v řadě. Seřaď je od Slunce.', ['Slunce', 'Země', 'Měsíc'],
    ['Čí stín dopadá na Měsíc?'],
    'Při zatmění Měsíce je Země mezi Sluncem a Měsícem a Měsíc vstoupí do zemského stínu.'),
  q('polarka-osa', 'Proč se Polárka na obloze skoro nehýbe?', 'Míří k ní zemská osa',
    ['Je nejblíž Zemi', 'Je přišpendlená', 'Je největší hvězda'],
    ['Kolem čeho se Země otáčí?'],
    'Zemská osa míří skoro přesně k Polárce. Když se Země otáčí, všechny hvězdy se zdánlivě točí kolem ní a ona stojí.'),
  q('rychlost', 'Jak rychle letí Země kolem Slunce?', 'Asi 30 km za sekundu',
    ['Asi 30 km za hodinu', 'Stojí na místě', 'Asi 3 metry za sekundu'],
    ['Za rok musí uletět obrovský kruh kolem Slunce.'],
    'Země letí kolem Slunce rychlostí asi 30 km za sekundu. Necítíme to, protože letíme spolu s ní i se vzduchem.'),
  q('neptun', 'Jak byl objeven Neptun?', 'Nejdřív ho vypočítali, pak ho našli',
    ['Náhodou ho zahlédlo dítě', 'Spadl na Zemi', 'Vždy byl vidět pouhým okem'],
    ['Uran se pohyboval jinak, než měl.'],
    'Astronomové si všimli, že Uran se pohybuje trochu jinak, než by měl. Spočítali, kde musí být další planeta, a v roce 1846 ji tam dalekohledem našli.'),
];

export const vesmir = bankSkill({
  id: ID,
  island: 'svet',
  name: 'Země a vesmír',
  description: 'Země jako součást vesmíru: den a noc, rok, Měsíc a jeho fáze, planety, zatmění a jak lidé poznali, jak to ve vesmíru chodí.',
  rvp: {
    2: ['ČJS-3-4-01'],
    3: ['ČJS-5-4-02'],
    4: ['ČJS-5-4-02'],
    5: ['ČJS-5-4-02'],
  },
  ability: 'znalosti',
  testLike: 'vedomosti',
  showFact: true,
  banks: { 2: L2, 3: L3, 4: L4, 5: L5, 6: L6 },
  gen: {
    3: (rng) => {
      const r = rng.next();
      if (r < 0.4) return ntaPlaneta(rng);
      if (r < 0.7) return seradPlanety(4)(rng);
      return mezi(rng);
    },
    4: (rng) => (rng.chance(0.5) ? seradPlanety(5)(rng) : mezi(rng)),
    5: seradPlanety(6),
  },
  genShare: 0.4,
});

export const vesmirCards: KnowledgeCard[] = [
  {
    id: `${ID}.kulata-zeme`,
    skillId: ID,
    level: 3,
    emoji: '🌍',
    title: 'Země je koule',
    text: 'Když odplouvá loď, zmizí za obzorem nejdřív její trup a nakonec špička stěžně. Tak se to děje jen na kulaté Zemi.',
    fix: {
      before: 'Některé staré národy si představovaly Zemi jako placku, přes kterou se klene nebe.',
      evidence: 'Už řecký učenec Aristotelés si před více než 2 300 lety všiml, že stín Země na Měsíci je při zatmění vždycky kulatý. Dnes máme i fotky Země z vesmíru.',
    },
  },
  {
    id: `${ID}.pluto`,
    skillId: ID,
    level: 3,
    emoji: '🔭',
    title: 'Pluto je trpasličí planeta',
    text: 'Pluto je menší než náš Měsíc a obíhá daleko za Neptunem. Od roku 2006 patří mezi trpasličí planety.',
    fix: {
      before: 'Od objevu v roce 1930 se Pluto počítalo jako devátá planeta.',
      evidence: 'Astronomové za Neptunem našli další podobná tělesa, třeba Eris. V roce 2006 se sešli v Praze, přesně popsali, co je planeta, a Pluto zařadili mezi trpasličí planety.',
    },
  },
  {
    id: `${ID}.slunce-uprostred`,
    skillId: ID,
    level: 4,
    emoji: '☀️',
    title: 'Uprostřed je Slunce',
    text: 'Země i ostatní planety obíhají kolem Slunce. Země ho oběhne jednou za rok.',
    fix: {
      before: 'Dlouho se věřilo, že Země stojí uprostřed vesmíru a Slunce i planety obíhají kolem ní.',
      evidence: 'Mikuláš Koperník v roce 1543 popsal, že uprostřed je Slunce, a ukázal, že to sedí s pohyby planet. Galileo Galilei pak v roce 1610 dalekohledem uviděl měsíce obíhající Jupiter a fáze Venuše.',
    },
  },
  {
    id: `${ID}.svetlo`,
    skillId: ID,
    level: 6,
    emoji: '🌞',
    title: 'Osm minut do minulosti',
    text: 'Sluneční světlo k nám letí asi 8 minut. Slunce na obloze tedy vidíme takové, jaké bylo před osmi minutami.',
  },
];
