// Texty pro čtení s porozuměním – úroveň 3 (6–8 vět, otázka „Proč…?“).

import type { ReadingText } from './cteni-texty-1';

export const TEXTS_L3: ReadingText[] = [
  {
    id: 'ingrid-pristav',
    title: 'Zamrzlý přístav',
    text: 'Jednoho mrazivého rána zamrzl celý přístav. Rybáři nemohli vyplout a nevěděli si rady. Drak Hromík chtěl led rozbít ocasem, ale Ingrid ho zastavila. „Kdybys led rozbil, kry by mohly poškodit lodě,“ řekla. Místo toho poprosila dračici Jiskru, aby na led jemně foukala svým teplým dechem. Led pomalu roztával a lodě zůstaly celé. Rybáři pak Ingrid i oběma drakům přinesli koš čerstvých ryb.',
    questions: [
      {
        kind: 'proc',
        q: 'Proč rybáři nemohli vyplout?',
        a: 'Přístav zamrzl.',
        d: ['Byla bouřka.', 'Neměli sítě.', 'Byla tma.'],
        hint: 'Podívej se na úplný začátek textu.',
        why: 'Hned první věta říká, že jednoho mrazivého rána zamrzl celý přístav.',
      },
      {
        kind: 'proc',
        q: 'Proč Ingrid zastavila Hromíka?',
        a: 'Kry by mohly poškodit lodě.',
        d: ['Hromík byl moc malý.', 'Chtěla led rozbít sama.', 'Led byl moc tenký.'],
        hint: 'Přečti si, co Ingrid Hromíkovi řekla.',
        why: 'Ingrid řekla: „Kdybys led rozbil, kry by mohly poškodit lodě.“',
      },
      {
        kind: 'detail',
        q: 'Jak nakonec led zmizel?',
        a: 'Jiskra ho roztavila teplým dechem.',
        d: ['Hromík ho rozbil ocasem.', 'Rybáři ho rozsekali.', 'Odnesl ho vítr.'],
        hint: 'Koho Ingrid poprosila o pomoc?',
        why: 'Ingrid poprosila Jiskru, aby na led foukala teplým dechem, a led pomalu roztával.',
      },
    ],
  },
  {
    id: 'listi',
    title: 'Proč padá listí',
    text: 'Na podzim se listy mnoha stromů zbarví do žluta, oranžova a červena. Zelenou barvu dává listům látka, které se říká chlorofyl. Na podzim ji strom přestane vyrábět, a tak se ukážou jiné barvy. Potom listy opadají. Strom tím v zimě šetří vodu, protože ze zmrzlé země se voda nedá dobře nasát. Jehličnaté stromy, jako smrk nebo borovice, si jehličí většinou nechávají. Výjimkou je modřín, který jehličí na zimu shazuje.',
    questions: [
      {
        kind: 'detail',
        q: 'Co dává listům zelenou barvu?',
        a: 'chlorofyl',
        d: ['slunce', 'déšť', 'kůra'],
        hint: 'Hledej větu se slovem zelenou.',
        why: 'Ve druhé větě stojí, že zelenou barvu dává listům látka, které se říká chlorofyl.',
      },
      {
        kind: 'proc',
        q: 'Proč stromy na zimu shazují listí?',
        a: 'Aby šetřily vodu.',
        d: ['Aby jim nebyla zima.', 'Protože listy jsou moc těžké.', 'Aby v zimě rychleji rostly.'],
        hint: 'Najdi větu se slovem protože.',
        why: 'V textu stojí, že strom tím v zimě šetří vodu, protože ze zmrzlé země se voda nedá dobře nasát.',
      },
      {
        kind: 'detail',
        q: 'Který jehličnatý strom shazuje na zimu jehličí?',
        a: 'modřín',
        d: ['smrk', 'borovice', 'jedle'],
        hint: 'Podívej se na poslední větu.',
        why: 'Poslední věta říká: „Výjimkou je modřín, který jehličí na zimu shazuje.“',
      },
    ],
  },
  {
    id: 'knut-drak-z-papiru',
    title: 'Drak z papíru',
    text: 'Knut moc chtěl vlastního draka. Děda Olaf se usmál a řekl: „Tak si ho postav!“ Spolu vzali tenké tyčky, pevný papír a dlouhý provázek. Na ocas uvázali mašličky, aby drak ve vzduchu nepadal a držel směr. Pak vyšli na kopec, kde foukal vítr. Knut se rozběhl a papírový drak se vznesl vysoko k mrakům. Opravdoví draci z vesnice k němu hned přiletěli, aby si prohlédli nového kamaráda.',
    questions: [
      {
        kind: 'detail',
        q: 'Co potřebovali na stavbu draka?',
        a: 'tyčky, papír a provázek',
        d: ['kameny, hlínu a vodu', 'prkna a hřebíky', 'látku a jehlu'],
        hint: 'Najdi větu, která začíná slovem Spolu.',
        why: 'V textu stojí: „Spolu vzali tenké tyčky, pevný papír a dlouhý provázek.“',
      },
      {
        kind: 'proc',
        q: 'Proč šli s drakem na kopec?',
        a: 'Protože tam foukal vítr.',
        d: ['Aby viděli na moře.', 'Protože tam bydlí babička.', 'Aby se schovali před deštěm.'],
        hint: 'Co potřebuje papírový drak, aby letěl?',
        why: 'V textu stojí, že vyšli na kopec, kde foukal vítr. Bez větru papírový drak nevzlétne.',
      },
      {
        kind: 'proc',
        q: 'Proč uvázali drakovi na ocas mašličky?',
        a: 'Aby ve vzduchu nepadal.',
        d: ['Aby rychle spadl na zem.', 'Aby ho bylo slyšet.', 'Aby se vešel do kapsy.'],
        hint: 'Hledej větu se slovem mašličky.',
        why: 'V textu stojí, že mašličky uvázali, aby drak ve vzduchu nepadal a držel směr.',
      },
    ],
  },
  {
    id: 'netopyri',
    title: 'Netopýři',
    text: 'Netopýři jsou savci, kteří umějí létat. Přes den spí zavěšení hlavou dolů, třeba v jeskyni nebo na půdě. Za potravou vylétají za soumraku a v noci. Ve tmě se neztratí, protože vydávají velmi vysoké zvuky, které lidské ucho většinou neslyší. Ty se odrážejí od předmětů a vracejí se zpátky jako ozvěna. Podle ozvěny netopýr pozná, kde je překážka nebo létající hmyz. Naši netopýři se živí hmyzem, třeba komáry a můrami. V zimě spí v jeskyních, sklepích nebo na půdách.',
    questions: [
      {
        kind: 'detail',
        q: 'Kam patří netopýři?',
        a: 'mezi savce',
        d: ['mezi ptáky', 'mezi hmyz', 'mezi ryby'],
        hint: 'Odpověď najdeš v první větě.',
        why: 'Text začíná větou: „Netopýři jsou savci, kteří umějí létat.“',
      },
      {
        kind: 'proc',
        q: 'Proč se netopýr ve tmě neztratí?',
        a: 'Řídí se ozvěnou zvuků, které vydává.',
        d: ['Má velké svítící oči.', 'Létá jen tam, kde svítí lampy.', 'Pamatuje si cestu podle vůně.'],
        hint: 'Najdi větu se slovem ozvěna.',
        why: 'Netopýr vydává vysoké zvuky. Ty se odrazí a vrátí jako ozvěna a podle ní pozná, kde je překážka.',
      },
      {
        kind: 'detail',
        q: 'Co dělají naši netopýři v zimě?',
        a: 'spí v jeskyních nebo sklepích',
        d: ['hrají si ve sněhu', 'loví komáry', 'staví si hnízda'],
        hint: 'Podívej se na poslední větu.',
        why: 'Poslední věta říká: „V zimě spí v jeskyních, sklepích nebo na půdách.“',
      },
    ],
  },
  {
    id: 'frida-jablka',
    title: 'Záhada zmizelých jablek',
    text: 'Z Frídina sadu každou noc mizela jablka. Bjorn si myslel, že jablka potají jí dráček Plamínek. Frída ale chtěla mít nejdřív důkaz. Večer rozsypala pod stromy trochu mouky. Ráno v ní našla otisky malých kopýtek, a ne dračích drápů. Další noc se schovala za plot a čekala. O půlnoci se do sadu přikradla sousedova koza a chroupala jedno jablko za druhým. Bjorn se pak Plamínkovi omluvil a dal mu to nejčervenější jablko.',
    questions: [
      {
        kind: 'proc',
        q: 'Proč Frída rozsypala pod stromy mouku?',
        a: 'Aby v ní zůstaly stopy.',
        d: ['Aby upekla koláč.', 'Aby jablka rychleji rostla.', 'Aby odlákala ptáky.'],
        hint: 'Co Frída ráno v mouce našla?',
        why: 'Frída chtěla důkaz. V mouce zůstanou stopy každého, kdo v noci přijde – a ráno v ní našla otisky kopýtek, ne dračích drápů.',
      },
      {
        kind: 'detail',
        q: 'Kdo podle Bjorna jedl jablka?',
        a: 'Plamínek',
        d: ['koza', 'Frída', 'soused'],
        hint: 'Najdi větu se jménem Bjorn.',
        why: 'Ve druhé větě stojí, že si Bjorn myslel, že jablka potají jí dráček Plamínek.',
      },
      {
        kind: 'proc',
        q: 'Proč se Bjorn Plamínkovi omluvil?',
        a: 'Plamínek jablka vůbec nejedl.',
        d: ['Bjorn mu šlápl na ocas.', 'Bjorn zapomněl na jeho narozeniny.', 'Plamínek neuměl létat.'],
        hint: 'Kdo jablka doopravdy jedl?',
        why: 'Jablka jedla sousedova koza. Bjorn si o Plamínkovi myslel něco, co nebyla pravda.',
      },
    ],
  },
  {
    id: 'vltava',
    title: 'Vltava',
    text: 'Vltava je nejdelší řeka, která teče jen po českém území. Pramení na Šumavě. Cestou protéká Českým Krumlovem, Českými Budějovicemi a Prahou. U Mělníka se vlévá do Labe. Labe pak pokračuje do Německa a nakonec do Severního moře. Na Vltavě stojí několik přehrad, například Lipno nebo Orlík. Skladatel Bedřich Smetana o ní složil slavnou hudbu.',
    questions: [
      {
        kind: 'detail',
        q: 'Kde Vltava pramení?',
        a: 'na Šumavě',
        d: ['v Krkonoších', 'v Praze', 'u Mělníka'],
        hint: 'Podívej se na druhou větu.',
        why: 'Ve druhé větě stojí: „Pramení na Šumavě.“',
      },
      {
        kind: 'detail',
        q: 'Která přehrada stojí na Vltavě?',
        a: 'Lipno',
        d: ['Sněžka', 'Karlštejn', 'Říp'],
        hint: 'Hledej větu se slovem přehrad.',
        why: 'V textu stojí: „Na Vltavě stojí několik přehrad, například Lipno nebo Orlík.“',
      },
      {
        kind: 'detail',
        q: 'Po které řece se voda z Vltavy dostane do moře?',
        a: 'po Labi',
        d: ['po Dunaji', 'po Odře', 'po Moravě'],
        hint: 'Do které řeky se Vltava vlévá?',
        why: 'Vltava se u Mělníka vlévá do Labe a Labe teče až do Severního moře.',
      },
    ],
  },
  {
    id: 'liv-pristavani',
    title: 'Přistání jako holub',
    text: 'Dráček Mráček uměl skvěle létat, ale přistávání mu vůbec nešlo. Pokaždé se skutálel do sena nebo žbluňkl do rybníka. Liv si všimla, že Mráček před přistáním úplně složí křídla. „Zkus je nechat roztažená, jako když holub sedá na střechu,“ poradila mu. Mráček to zkusil a pomalu klouzal k zemi. Tentokrát dosedl přesně na všechny čtyři tlapky. Od té doby Liv říká, že nejlepší učitelé létání jsou holubi.',
    questions: [
      {
        kind: 'detail',
        q: 'Co Mráčkovi nešlo?',
        a: 'přistávání',
        d: ['létání', 'plavání', 'chrlení ohně'],
        hint: 'Odpověď najdeš v první větě.',
        why: 'V textu stojí: „Dráček Mráček uměl skvěle létat, ale přistávání mu vůbec nešlo.“',
      },
      {
        kind: 'proc',
        q: 'Proč Mráček špatně přistával?',
        a: 'Před přistáním složil křídla.',
        d: ['Byl moc těžký.', 'Neviděl na zem.', 'Měl malá křídla.'],
        hint: 'Čeho si Liv všimla?',
        why: 'Liv si všimla, že Mráček před přistáním úplně složí křídla.',
      },
      {
        kind: 'detail',
        q: 'Jak měl Mráček přistávat?',
        a: 'jako holub',
        d: ['jako kámen', 'jako žába', 'jako míč'],
        hint: 'Přečti si, co Liv Mráčkovi poradila.',
        why: 'Liv poradila: „Zkus je nechat roztažená, jako když holub sedá na střechu.“',
      },
    ],
  },
  {
    id: 'duha',
    title: 'Duha',
    text: 'Duha vzniká, když svítí slunce a zároveň prší. Sluneční světlo vypadá bíle, ale ve skutečnosti je v něm schováno mnoho barev. Když projde kapkami vody, rozloží se na barvy. Proto vidíme barevný oblouk: červenou, oranžovou, žlutou, zelenou, modrou a fialovou barvu. Duhu uvidíš, jen když máš slunce za zády. Někdy se objeví i dvojitá duha. Druhá duha je slabší a barvy má v obráceném pořadí.',
    questions: [
      {
        kind: 'detail',
        q: 'Kdy vzniká duha?',
        a: 'když svítí slunce a zároveň prší',
        d: ['když je noc', 'když sněží a je tma', 'když fouká vítr'],
        hint: 'Odpověď je hned v první větě.',
        why: 'Text začíná větou: „Duha vzniká, když svítí slunce a zároveň prší.“',
      },
      {
        kind: 'proc',
        q: 'Proč vidíme v duze barvy?',
        a: 'Světlo se v kapkách rozloží na barvy.',
        d: ['Někdo je namaloval na nebe.', 'Mraky jsou barevné.', 'Dešťové kapky jsou obarvené.'],
        hint: 'Co se stane se světlem, když projde kapkami vody?',
        why: 'V textu stojí, že když sluneční světlo projde kapkami vody, rozloží se na barvy.',
      },
      {
        kind: 'detail',
        q: 'Kde musí být slunce, když se díváš na duhu?',
        a: 'za tvými zády',
        d: ['přímo před tebou', 'pod tebou', 'hned vedle duhy'],
        hint: 'Hledej větu se slovem uvidíš.',
        why: 'V textu stojí: „Duhu uvidíš, jen když máš slunce za zády.“',
      },
    ],
  },
];
