// Texty pro čtení s porozuměním – úroveň 4 (8–12 vět: hlavní myšlenka,
// pořadí dějů, fakt × názor).

import type { ReadingText } from './cteni-texty-1';

export const TEXTS_L4: ReadingText[] = [
  {
    id: 'vceli-tanec',
    title: 'Jak si včely povídají',
    text: 'Včely medonosné si umějí navzájem sdělit, kde našly květy s nektarem. Když se včela vrátí do úlu, začne na plástu tančit. Pokud jsou květy blízko, krouží v malých kolečkách. Pokud jsou daleko, běží rovně a přitom vrtí zadečkem, pak se vrátí obloukem a běží znovu. Směr jejího běhu ukazuje ostatním včelám, kam mají letět vzhledem ke slunci. Čím déle včela při tanci vrtí zadečkem, tím dál jsou květy. V úlu je tma, a tak se ostatní včely tanečnice dotýkají tykadly a sledují ji. Tento včelí jazyk popsal rakouský vědec Karl von Frisch a dostal za to Nobelovu cenu. Podle mě je to jeden z nejkrásnějších objevů o zvířatech.',
    questions: [
      {
        kind: 'hlavni',
        q: 'O čem je hlavně tento text?',
        a: 'Jak si včely tancem ukazují cestu ke květům.',
        d: ['Jak včely vyrábějí vosk.', 'Kdo byl Karl von Frisch.', 'Proč je v úlu tma.'],
        hint: 'O čem mluví skoro všechny věty textu?',
        why: 'Skoro celý text popisuje, jak včela tancem ukazuje ostatním, kam letět za květy. Vědec i tma v úlu jsou jen podrobnosti.',
      },
      {
        kind: 'nazor',
        q: 'Která věta je názor, a ne fakt?',
        a: 'Je to jeden z nejkrásnějších objevů o zvířatech.',
        d: ['Včela tančí na plástu.', 'V úlu je tma.', 'Karl von Frisch dostal Nobelovu cenu.'],
        hint: 'Hledej větu, se kterou by někdo jiný mohl nesouhlasit.',
        why: 'Věta „Je to jeden z nejkrásnějších objevů“ říká, co si myslí pisatel (začíná slovy Podle mě). Ostatní věty se dají ověřit.',
      },
      {
        kind: 'detail',
        q: 'Jak včela ukáže, že jsou květy blízko?',
        a: 'Krouží v malých kolečkách.',
        d: ['Dlouho vrtí zadečkem.', 'Bzučí co nejhlasitěji.', 'Přinese jeden květ ukázat.'],
        hint: 'Najdi větu se slovem blízko.',
        why: 'V textu stojí: „Pokud jsou květy blízko, krouží v malých kolečkách.“ Vrtění zadečkem znamená, že jsou daleko.',
      },
    ],
  },
  {
    id: 'chytry-most',
    title: 'Chytrý most',
    text: 'Na jaře se rozvodnil potok za vesnicí a odnesl starou lávku. Děti se teď nemohly dostat na louku, kde pásly kozy. Sven navrhl, že je všechny přenese drak Hromík. Hromík byl ale moc lechtivý a každé dítě, které mu sedlo na krk, se smíchem shodil do měkké trávy. Sigrun se chvíli dívala na vodu a pak si všimla, že u břehu leží dlouhý padlý kmen. „Hromíku, zvedneš ten kmen?“ zeptala se. Hromík kmen zvedl a opatrně ho položil přes potok. Děti ho pak s Knutem zajistily kameny, aby se nekutálel. Nový most vydržel celé léto. Děti ho na počest Sigrun pojmenovaly Chytrý most.',
    questions: [
      {
        kind: 'poradi',
        q: 'Co se stalo nejdřív?',
        a: 'Potok odnesl starou lávku.',
        d: ['Hromík položil kmen přes potok.', 'Sigrun si všimla padlého kmene.', 'Děti zajistily kmen kameny.'],
        hint: 'Podívej se na úplný začátek příběhu.',
        why: 'Příběh začíná tím, že rozvodněný potok odnesl starou lávku. Všechno ostatní přišlo až potom.',
      },
      {
        kind: 'poradi',
        q: 'Co se stalo hned potom, co si Sigrun všimla kmene?',
        a: 'Zeptala se Hromíka, jestli ho zvedne.',
        d: ['Děti most pojmenovaly.', 'Sven navrhl, že je přenese Hromík.', 'Potok odnesl lávku.'],
        hint: 'Najdi větu s kmenem a přečti tu, která následuje.',
        why: 'Hned potom se Sigrun zeptala: „Hromíku, zvedneš ten kmen?“',
      },
      {
        kind: 'hlavni',
        q: 'O čem hlavně příběh vypráví?',
        a: 'Jak Sigrun vymyslela nový most.',
        d: ['Jak se pasou kozy.', 'Proč je Hromík lechtivý.', 'Jak se staví lodě.'],
        hint: 'Co se v příběhu vyřešilo a kdo na to přišel?',
        why: 'Příběh je hlavně o tom, jak Sigrun přemýšlela a vymyslela most z padlého kmene. Proto se mu říká Chytrý most.',
      },
    ],
  },
  {
    id: 'tucnaci',
    title: 'Tučňáci',
    text: 'Tučňáci jsou ptáci, kteří neumějí létat. Zato skvěle plavou a potápějí se. Křídla jim slouží jako ploutve. Skoro všichni tučňáci žijí na jižní polokouli. Největší z nich je tučňák císařský. U něj se o vejce stará hlavně tatínek. Samice snese vejce a předá ho samci. Samec ho pak celé týdny zahřívá na nohou pod kožním záhybem na břiše. Samci přitom stojí v mrazu těsně u sebe, aby se navzájem zahřáli. Samice se mezitím krmí v moři a pak se vrátí k mláděti. Myslím, že tučňáci patří k nejroztomilejším zvířatům na světě.',
    questions: [
      {
        kind: 'nazor',
        q: 'Která věta je názor, a ne fakt?',
        a: 'Tučňáci patří k nejroztomilejším zvířatům.',
        d: ['Tučňáci neumějí létat.', 'Křídla jim slouží jako ploutve.', 'Největší je tučňák císařský.'],
        hint: 'Hledej větu, o které by se lidé mohli přít, jestli platí.',
        why: 'To, jestli jsou tučňáci roztomilí, si myslí pisatel (začíná slovem Myslím). Ostatní věty jsou fakta, která se dají ověřit.',
      },
      {
        kind: 'poradi',
        q: 'Co udělá samice tučňáka císařského hned potom, co snese vejce?',
        a: 'Předá ho samci.',
        d: ['Odplave se krmit do moře.', 'Sama ho zahřívá na nohou.', 'Postaví z kamínků hnízdo.'],
        hint: 'Najdi větu, ve které samice snese vejce.',
        why: 'V textu stojí: „Samice snese vejce a předá ho samci.“ Do moře odplave až potom.',
      },
      {
        kind: 'proc',
        q: 'Proč stojí samci těsně u sebe?',
        a: 'Aby se navzájem zahřáli.',
        d: ['Aby si mohli povídat.', 'Protože je tam málo místa.', 'Aby je nikdo neviděl.'],
        hint: 'Hledej větu se slovy těsně u sebe.',
        why: 'V textu stojí, že samci stojí v mrazu těsně u sebe, aby se navzájem zahřáli.',
      },
    ],
  },
  {
    id: 'polarka',
    title: 'Hvězda, která ukazuje cestu',
    text: 'Ingrid a dračice Jiskra se vracely z výletu na vzdálený ostrov. Mezitím se setmělo a pod nimi bylo jen tmavé moře. Jiskra si nebyla jistá, kterým směrem letět. Ingrid se podívala na oblohu a hledala souhvězdí Velkého vozu. Spojnici jeho dvou zadních kol si v duchu prodloužila asi pětkrát, až došla k Polárce. „Polárka nám ukáže sever. Náš ostrov leží přesně tam,“ řekla. Jiskra zamířila k Polárce a za chvíli uviděly světla vesnice. Doma pak u ohně vyprávěly, jak je vedla hvězda. Knut prohlásil, že je to ten nejlepší příběh, jaký kdy slyšel. Od té doby se děti z vesnice učí najít Polárku dřív, než se vydají na noční let.',
    questions: [
      {
        kind: 'poradi',
        q: 'Co udělala Ingrid dřív, než našla Polárku?',
        a: 'Našla na obloze Velký vůz.',
        d: ['Uviděla světla vesnice.', 'Vyprávěla u ohně příběh.', 'Přistála na ostrově.'],
        hint: 'Od čeho Ingrid prodlužovala čáru?',
        why: 'Ingrid nejdřív hledala Velký vůz a teprve od jeho zadních kol došla k Polárce.',
      },
      {
        kind: 'nazor',
        q: 'Která věta vyjadřuje něčí názor?',
        a: 'Je to nejlepší příběh, jaký Knut kdy slyšel.',
        d: ['Polárka ukazuje na sever.', 'Jiskra zamířila k Polárce.', 'Pod nimi bylo tmavé moře.'],
        hint: 'Kdo v příběhu říká, co se mu líbí?',
        why: 'Že je to nejlepší příběh, si myslí Knut. Jiný posluchač by mohl mít jiný oblíbený příběh.',
      },
      {
        kind: 'proc',
        q: 'Proč Ingrid hledala Polárku?',
        a: 'Polárka ukazuje na sever.',
        d: ['Polárka je nejjasnější hvězda na nebi.', 'Chtěla si něco přát.', 'Polárka svítí jen nad jejich vesnicí.'],
        hint: 'Přečti si, co Ingrid řekla, když Polárku našla.',
        why: 'Ingrid řekla: „Polárka nám ukáže sever. Náš ostrov leží přesně tam.“ Nejjasnější hvězda na nebi Polárka není – najdeš ji podle Velkého vozu, jako to udělala Ingrid.',
      },
    ],
  },
  {
    id: 'karluv-most',
    title: 'Karlův most',
    text: 'Karlův most stojí v Praze a vede přes řeku Vltavu. Začal se stavět v roce 1357 za vlády Karla IV. Je postavený z pískovcových kvádrů a má šestnáct oblouků. Dlouho se mu říkalo jen Kamenný most. Jméno Karlův most dostal až zhruba před sto padesáti lety. Na mostě stojí asi třicet soch a sousoší. Dnes jsou to většinou kopie, mnohé originály jsou v muzeu. Po mostě nejezdí auta ani tramvaje, chodí po něm jen lidé. Říká se, že stavitelé přidávali do malty vejce, aby byl most pevnější. Podle mnoha lidí je to nejkrásnější most na světě.',
    questions: [
      {
        kind: 'nazor',
        q: 'Která věta je názor, a ne fakt?',
        a: 'Je to nejkrásnější most na světě.',
        d: ['Most má šestnáct oblouků.', 'Most vede přes Vltavu.', 'Most se začal stavět v roce 1357.'],
        hint: 'Počet oblouků se dá spočítat. Dá se spočítat i krása?',
        why: 'Že je most nejkrásnější, si myslí mnoho lidí, ale je to názor. Oblouky, řeka i rok stavby se dají ověřit.',
      },
      {
        kind: 'detail',
        q: 'Jak se mostu dlouho říkalo?',
        a: 'Kamenný most',
        d: ['Dřevěný most', 'Zlatý most', 'Královský most'],
        hint: 'Hledej větu se slovem dlouho.',
        why: 'V textu stojí: „Dlouho se mu říkalo jen Kamenný most.“',
      },
      {
        kind: 'hlavni',
        q: 'O čem je text hlavně?',
        a: 'o Karlově mostě',
        d: ['o řece Vltavě', 'o králi Karlovi IV.', 'o sochách v muzeu'],
        hint: 'Co je v textu skoro v každé větě?',
        why: 'Všechny věty mluví o Karlově mostě: kdy se stavěl, z čeho je a co na něm stojí.',
      },
    ],
  },
  {
    id: 'zavod',
    title: 'Závod kolem ostrova',
    text: 'Na ostrově se každé léto konají dračí závody. Letos se jich poprvé zúčastnila i Frída se svou dračicí Bublinkou. Bublinka neuměla létat tak rychle jako velcí draci, zato byla výborná plavkyně. Frída si proto před závodem pečlivě prohlédla trať i pravidla. Zjistila, že závod vede kolem celého ostrova a přes záliv se dá i přeplavat. V pravidlech totiž nikde nestálo, že se musí jen letět. Když ostatní draci obletovali záliv, Bublinka ho přeplavala rychle jako šipka. Do cíle doplula druhá, hned za rychlým drakem Hromíkem. Rozhodčí Olaf prohlásil, že to byl nejchytřejší závod, jaký kdy viděl. Hromík Bublince pogratuloval a pozval ji na koupání.',
    questions: [
      {
        kind: 'poradi',
        q: 'Co udělala Frída ještě před závodem?',
        a: 'Prohlédla si trať i pravidla.',
        d: ['Pogratulovala Hromíkovi.', 'Přeplavala záliv.', 'Šla se koupat s Hromíkem.'],
        hint: 'Najdi větu se slovy před závodem.',
        why: 'V textu stojí: „Frída si proto před závodem pečlivě prohlédla trať i pravidla.“',
      },
      {
        kind: 'nazor',
        q: 'Co je v příběhu něčí názor?',
        a: 'Byl to nejchytřejší závod, jaký Olaf viděl.',
        d: ['Bublinka doplula druhá.', 'Závod vedl kolem ostrova.', 'Hromík byl v cíli první.'],
        hint: 'Kdo v příběhu hodnotí, jaký závod byl?',
        why: 'Že to byl nejchytřejší závod, si myslí rozhodčí Olaf. Ostatní věty popisují, co se opravdu stalo.',
      },
      {
        kind: 'proc',
        q: 'Proč Frída zvolila cestu přes vodu?',
        a: 'Bublinka výborně plave.',
        d: ['Chtěla se cestou vykoupat.', 'Hromík jí to poradil.', 'Nad zálivem se nesmělo létat.'],
        hint: 'V čem byla Bublinka výborná?',
        why: 'Bublinka neuměla létat tak rychle jako velcí draci, zato byla výborná plavkyně. Frída toho chytře využila.',
      },
    ],
  },
  {
    id: 'den-a-noc',
    title: 'Proč se střídá den a noc',
    text: 'Země je obrovská koule, která se pořád otáčí kolem své osy. Jedna otočka trvá asi 24 hodin. Slunce vždycky osvětluje jen tu polovinu Země, která je k němu zrovna natočená. Na této polovině je den. Na druhé polovině, která je od Slunce odvrácená, je noc. Protože se Země otáčí, den a noc se na každém místě pravidelně střídají. Nám se zdá, že Slunce ráno vychází na východě a večer zapadá na západě. Ve skutečnosti se ale kolem nás nepohybuje Slunce, to se otáčí Země. Kromě toho Země obíhá kolem Slunce a jeden oběh jí trvá rok. Když je u nás poledne, v Austrálii je už večer nebo noc.',
    questions: [
      {
        kind: 'hlavni',
        q: 'O čem hlavně text vypráví?',
        a: 'Proč se střídá den a noc.',
        d: ['Jak daleko je Měsíc.', 'Jak horké je Slunce.', 'Kde leží Austrálie.'],
        hint: 'Podívej se i na nadpis textu.',
        why: 'Skoro všechny věty vysvětlují, proč je někde den a jinde noc a proč se to střídá.',
      },
      {
        kind: 'detail',
        q: 'Co se podle textu ve skutečnosti otáčí?',
        a: 'Země',
        d: ['Slunce', 'Měsíc', 'hvězdy'],
        hint: 'Najdi větu, která začíná slovy Ve skutečnosti.',
        why: 'V textu stojí: „Ve skutečnosti se ale kolem nás nepohybuje Slunce, to se otáčí Země.“',
      },
      {
        kind: 'proc',
        q: 'Proč je v Austrálii večer nebo noc, když je u nás poledne?',
        a: 'Je na jiném místě otáčející se Země.',
        d: ['V Austrálii nikdy nesvítí slunce.', 'V Austrálii chodí všichni brzy spát.', 'Austrálie je blíž Měsíci.'],
        hint: 'Slunce osvětluje vždycky jen jednu polovinu Země.',
        why: 'Slunce osvětluje jen polovinu Země. Když je k němu natočené Česko, Austrálie je na jiném místě koule a den tam už končí nebo skončil.',
      },
    ],
  },
  {
    id: 'vikingske-lode',
    title: 'Vikingské lodě',
    text: 'Vikingové byli zruční stavitelé lodí. Jejich dlouhé lodě byly štíhlé a lehké. Stavěli je hlavně z dubového dřeva. Prkna se na bocích lodi částečně překrývala jako šupiny, a proto byla loď pevná a zároveň pružná. Loď měla jednu velkou čtvercovou plachtu. Když nefoukal vítr, námořníci veslovali. Lodě byly ponořené jen málo, a tak mohly plout i po mělkých řekách a přistát přímo na pláži. Na přídi některých lodí byla vyřezaná hlava draka nebo hada. Několik vikingských lodí se zachovalo a dnes si je můžeme prohlédnout v muzeích. Podle mě byly vikingské lodě ty nejkrásnější lodě, jaké kdy lidé postavili.',
    questions: [
      {
        kind: 'proc',
        q: 'Proč mohly vikingské lodě plout i po mělkých řekách?',
        a: 'Byly ponořené jen málo.',
        d: ['Měly velkou plachtu.', 'Byly z dubového dřeva.', 'Měly na přídi hlavu draka.'],
        hint: 'Najdi větu se slovem mělkých.',
        why: 'V textu stojí: „Lodě byly ponořené jen málo, a tak mohly plout i po mělkých řekách.“',
      },
      {
        kind: 'nazor',
        q: 'Která věta je názor, a ne fakt?',
        a: 'Vikingské lodě byly ty nejkrásnější lodě.',
        d: ['Lodě měly čtvercovou plachtu.', 'Vikingové stavěli lodě hlavně z dubu.', 'Některé lodě jsou dnes v muzeích.'],
        hint: 'Která věta začíná v textu slovy Podle mě?',
        why: 'Věta o nejkrásnějších lodích říká, co si myslí pisatel. Plachta, dub i muzea jsou fakta.',
      },
      {
        kind: 'detail',
        q: 'Co dělali námořníci, když nefoukal vítr?',
        a: 'veslovali',
        d: ['čekali v přístavu', 'rybařili', 'spali na palubě'],
        hint: 'Hledej větu se slovem vítr.',
        why: 'V textu stojí: „Když nefoukal vítr, námořníci veslovali.“',
      },
    ],
  },
];
