// Oprav Hugina – mechanický havran z dílny tvrdí věci z počtů, přírody,
// jazyka a světa. Asi polovina tvrzení je schválně špatně (chyby jsou předem
// ověřené). Hráčka rozhoduje, jestli má pravdu, na vyšších úrovních hledá,
// kde se spletl, a vybírá, jak se tvrzení ověří. Vysvětlení vždy říká, jak
// to ověřit: spočítat, změřit, podívat se do atlasu nebo se zeptat odborníka.

import { bankSkill, type Spec } from '../../core/bank';
import type { ChoiceOption, KnowledgeCard } from '../../core/types';
import { fixed, q, speakMath } from './digitalni-common';

const ID = 'dilna.hugin';

export const PRAVDU = 'Hugin má pravdu';
export const PLETE = 'Hugin se plete';

/** Tvrzení Hugina: má pravdu, nebo se plete? Klíč `tvrzeni-…`. */
function claim(key: string, text: string, isTrue: boolean, hints: string[], explain: string, spoken?: string): Spec {
  const math = /[+−×=]| : /.test(text);
  const said = spoken ?? (math ? speakMath(text) : undefined);
  return fixed(`tvrzeni-${key}`, `Hugin říká: „${text}“ Má pravdu?`, [PRAVDU, PLETE], isTrue ? 0 : 1, hints, explain,
    said ? { speak: `Hugin říká: ${said} Má pravdu?` } : {});
}

/** Kde se Hugin spletl? Věty (nebo kroky) ve vizuálu, právě jedna je chybná. */
function kdeVeta(key: string, title: string, prompt: string, sentences: string[], wrongIndex: number, hints: string[], explain: string): Spec {
  return q(`kde-${key}`, prompt, sentences[wrongIndex], sentences.filter((_, i) => i !== wrongIndex), hints, explain, {
    visual: { type: 'steps', title, steps: sentences },
    difficulty: 0.2,
  });
}

/** Ve kterém kroku výpočtu se Hugin poprvé spletl? Klíč `kde-vypocet-…` =
 *  chyba je v počtech (test ji přepočítá), `kde-postup-…` = chyba v postupu. */
function kdeKrok(key: string, title: string, prompt: string, steps: string[], firstWrong: number, hints: string[], explain: string, speak?: string): Spec {
  const options: ChoiceOption[] = steps.map((_, i) => ({ label: `${i + 1}. krok`, speak: `${['první', 'druhý', 'třetí', 'čtvrtý'][i]} krok` }));
  return fixed(`kde-${key}`, prompt, options, firstWrong, hints, explain, {
    visual: { type: 'steps', title, steps },
    difficulty: 0.3,
    ...(speak ? { speak } : {}),
  });
}

/** Jak to ověříš? Klíč `overit-…`. */
function overit(key: string, prompt: string, correct: string, wrong: string[], hints: string[], explain: string): Spec {
  return q(`overit-${key}`, prompt, correct, wrong, hints, explain, { difficulty: 0.1 });
}

// ---------------------------------------------------------------------------
// L1 – počty do deseti, zvířata, kalendář, písmena

const L1: Spec[] = [
  claim('dva-a-tri', 'Dva a tři je pět.', true, ['Zkus to spočítat na prstech.'],
    'Dva a tři je opravdu pět. Ověříš to na prstech: dva prsty a tři prsty jsou dohromady pět prstů.'),
  claim('ctyri-a-ctyri', 'Čtyři a čtyři je devět.', false, ['Zkus to spočítat na prstech.'],
    'Čtyři a čtyři je osm, ne devět. Ověříš to na prstech: čtyři prsty na jedné ruce a čtyři na druhé.'),
  claim('trojuhelnik', 'Trojúhelník má tři rohy.', true, ['Nakresli si trojúhelník.'],
    'Trojúhelník má opravdu tři rohy. Ověříš to, když si ho nakreslíš a rohy spočítáš.'),
  claim('ctverec', 'Čtverec má pět stran.', false, ['Nakresli si čtverec a spočítej strany.'],
    'Čtverec má čtyři strany, ne pět. Ověříš to, když si ho nakreslíš a strany spočítáš.'),
  claim('prsty', 'Na jedné ruce máme šest prstů.', false, ['Podívej se na svou ruku.'],
    'Na jedné ruce máme pět prstů. Ověříš to hned: spočítej prsty na své ruce.'),
  claim('deset-a-sedm', 'Deset je víc než sedm.', true, ['Zkus si to ukázat na kamíncích.'],
    'Deset je opravdu víc než sedm. Ověříš to s kamínky: z deseti kamínků uděláš hromádku sedmi a ještě tři zbudou.'),
  claim('pet-a-tri', 'Pět je méně než tři.', false, ['Zkus si to ukázat na prstech.'],
    'Pět je víc než tři. Ověříš to na prstech: pět prstů je o dva víc než tři.'),
  claim('pavouk', 'Pavouk má osm nohou.', true, ['Kde se dá zjistit, jak vypadá pavouk?'],
    'Pavouk má opravdu osm nohou. Ověříš to v knize o zvířatech nebo když si pavouka opatrně prohlédneš.'),
  claim('krava', 'Kráva snáší vejce.', false, ['Která zvířata na statku snášejí vejce?'],
    'To není pravda. Kráva rodí telátka a dává mléko, vejce snáší třeba slepice. Ověříš to v knize o zvířatech nebo na statku.'),
  claim('vcely', 'Včely dělají med.', true, ['Kdo by to mohl vědět?'],
    'Včely opravdu dělají med z nektaru květů. Ověříš to u včelaře nebo v knize o hmyzu.'),
  claim('snih', 'Sníh je teplý.', false, ['Vzpomeň si, jak studí sníh na rukou.'],
    'Sníh je studený. Ověříš to v zimě: sáhni na sníh, nebo ho změř teploměrem.'),
  claim('listi', 'Na podzim padá z mnoha stromů listí.', true, ['Co vidíš venku na podzim?'],
    'Opravdu to tak je. Ověříš to pozorováním: na podzim se podívej na stromy v parku.'),
  claim('kapr', 'Kapr má čtyři nohy.', false, ['Jak se ryby pohybují ve vodě?'],
    'Kapr nemá nohy, plave pomocí ploutví. Ověříš to v atlasu ryb nebo u akvária.'),
  claim('kure', 'Kuře se vylíhne z vajíčka.', true, ['Kde se dá zjistit, odkud se berou kuřata?'],
    'Opravdu to tak je. Ověříš to v knize o zvířatech nebo se zeptáš někoho, kdo chová slepice.'),
  claim('tyden', 'Týden má sedm dní.', true, ['Podívej se do kalendáře.'],
    'Týden má opravdu sedm dní. Ověříš to v kalendáři: spočítej dny od pondělí do neděle.'),
  claim('po-pondeli', 'Po pondělí přijde čtvrtek.', false, ['Podívej se do kalendáře.'],
    'Po pondělí přijde úterý. Ověříš to v kalendáři.'),
  claim('rok', 'Rok má dvanáct měsíců.', true, ['Podívej se do kalendáře.'],
    'Rok má opravdu dvanáct měsíců. Ověříš to v kalendáři: spočítej měsíce od ledna do prosince.'),
  claim('zima', 'V zimě bývá tepleji než v létě.', false, ['Čím se dá změřit teplota?'],
    'V zimě bývá chladněji než v létě. Ověříš to teploměrem za oknem – v zimě i v létě.'),
  claim('slunce', 'Slunce vychází večer.', false, ['Kdy se Slunce objeví na obloze?'],
    'Slunce vychází ráno a zapadá večer. Ověříš to pozorováním: podívej se ráno a večer z okna.'),
  claim('pes-pismena', 'Slovo pes má tři písmena.', true, ['Spočítej písmena ve slově.'],
    'Slovo pes má opravdu tři písmena: p, e, s. Ověříš to, když si slovo napíšeš a písmena spočítáš.'),
  claim('dum-pismena', 'Slovo dům má čtyři písmena.', false, ['Napiš si slovo a spočítej písmena.'],
    'Slovo dům má tři písmena: d, ů, m. Ověříš to, když si ho napíšeš a písmena spočítáš.'),
  claim('auto', 'Slovo auto začíná písmenem A.', true, ['Řekni slovo nahlas a poslouchej první hlásku.'],
    'Opravdu to tak je. Ověříš to, když slovo řekneš pomalu nahlas nebo ho napíšeš.'),
  claim('mama', 'Slovo máma začíná písmenem T.', false, ['Řekni slovo nahlas a poslouchej první hlásku.'],
    'Slovo máma začíná písmenem M. Ověříš to, když ho řekneš pomalu nahlas: mmm-áma.'),
  claim('les-pes', 'Slova les a pes se rýmují.', true, ['Řekni obě slova nahlas.'],
    'Opravdu se rýmují. Ověříš to, když obě slova řekneš nahlas a posloucháš konec: les – pes.'),
];

// ---------------------------------------------------------------------------
// L2 – počty do sta a násobilka, zvířata a rostliny, slabiky, Česko

const L2: Spec[] = [
  claim('7-plus-8', '7 + 8 = 15.', true, ['Spočítej to přes desítku.'],
    'Opravdu to tak je: 7 + 3 = 10 a 10 + 5 = 15. Ověříš to výpočtem přes desítku nebo na počítadle.'),
  claim('6-plus-7', '6 + 7 = 12.', false, ['Spočítej to přes desítku.'],
    '6 + 7 = 13, ne 12. Ověříš to výpočtem: 6 + 4 = 10 a 10 + 3 = 13.'),
  claim('20-minus-6', '20 − 6 = 14.', true, ['Zkus to ověřit sčítáním.'],
    'Opravdu to tak je. Ověříš to zkouškou: 14 + 6 = 20.'),
  claim('35-plus-10', '35 + 10 = 55.', false, ['Kolik desítek přibude?'],
    '35 + 10 = 45 – přibude jen jedna desítka. Ověříš to na počítadle nebo zkouškou: 45 − 10 = 35.'),
  claim('5-krat-5', '5 × 5 = 25.', true, ['Vzpomeň si na násobilku pěti.'],
    'Opravdu to tak je. Ověříš to sčítáním: 5 + 5 + 5 + 5 + 5 = 25.'),
  claim('4-krat-3', '4 × 3 = 7.', false, ['Násobení je opakované sčítání.'],
    '4 × 3 = 12. Hugin místo násobení sčítal. Ověříš to sčítáním: 4 + 4 + 4 = 12.'),
  claim('hodina', 'Hodina má 60 minut.', true, ['Podívej se na hodiny s ručičkami.'],
    'Opravdu to tak je. Ověříš to na hodinách: velká ručička oběhne celý ciferník za 60 minut.'),
  claim('den-a-noc', 'Den a noc mají dohromady 12 hodin.', false, ['Kolikrát oběhne malá ručička ciferník od rána do rána?'],
    'Den a noc mají dohromady 24 hodin. Ověříš to na hodinách: malá ručička oběhne ciferník dvakrát a 2 × 12 = 24.'),
  claim('metr', 'Metr má 100 centimetrů.', true, ['Podívej se na svinovací metr.'],
    'Opravdu to tak je. Ověříš to na svinovacím metru: najdi na něm značku 100 cm.'),
  claim('kruh', 'Kruh má čtyři rohy.', false, ['Nakresli si kruh.'],
    'Kruh nemá žádné rohy. Ověříš to, když si ho nakreslíš nebo obkreslíš hrnek.'),
  claim('hmyz', 'Hmyz má šest nohou.', true, ['Kde se dá zjistit, jak vypadá hmyz?'],
    'Opravdu to tak je. Ověříš to v atlasu hmyzu nebo když berušce opatrně spočítáš nohy.'),
  claim('pavouk-hmyz', 'Pavouk je hmyz.', false, ['Kolik nohou má hmyz a kolik pavouk?'],
    'Pavouk není hmyz. Hmyz má šest nohou, pavouk osm. Ověříš to v atlasu zvířat.'),
  claim('jezek', 'Ježek přes zimu spí.', true, ['Kdo o zvířatech hodně ví?'],
    'Opravdu to tak je, ježek má zimní spánek. Ověříš to v knize o zvířatech nebo se zeptáš v záchranné stanici pro zvířata.'),
  claim('housenka', 'Z housenky se stane motýl.', true, ['Kde se dá zjistit, jak se rodí motýl?'],
    'Opravdu to tak je. Housenka se zakuklí a z kukly vylétne motýl. Ověříš to v atlasu hmyzu nebo pozorováním housenek.'),
  claim('jahody', 'Na zahradě v Česku dozrávají jahody v zimě.', false, ['Kdy jsi jedla jahody ze zahrady?'],
    'Jahody v Česku dozrávají hlavně v červnu. Ověříš to pozorováním na zahradě nebo v zahrádkářské knize.'),
  claim('slepice', 'Slepice dává mléko.', false, ['Co nám dává slepice?'],
    'Slepice mléko nedává, snáší vejce. Mléko dávají třeba krávy nebo kozy. Ověříš to v knize o zvířatech nebo na statku.'),
  claim('tulipany', 'Tulipány kvetou na jaře.', true, ['Kdy vidíš tulipány na zahrádkách?'],
    'Opravdu to tak je. Ověříš to pozorováním zahrádek na jaře nebo v knize o rostlinách.'),
  claim('kocka-slabiky', 'Slovo kočka má dvě slabiky.', true, ['Vytleskej si slovo.'],
    'Opravdu to tak je: koč-ka. Ověříš to, když slovo vytleskáš.'),
  claim('zmrzlina-slabiky', 'Slovo zmrzlina má dvě slabiky.', false, ['Vytleskej si slovo.'],
    'Slovo zmrzlina má tři slabiky: zmrz-li-na. Ověříš to, když ho vytleskáš.'),
  claim('po-z', 'Po písmenu ž píšeme měkké i.', true, ['Je ž tvrdá, nebo měkká souhláska?'],
    'Opravdu to tak je: ž je měkká souhláska a po ní píšeme i. Ověříš to v učebnici češtiny nebo u paní učitelky.'),
  claim('po-h', 'Po písmenu h píšeme vždycky měkké i.', false, ['Je h tvrdá, nebo měkká souhláska?'],
    'Písmeno h je tvrdá souhláska a v českých slovech po ní píšeme y, třeba ve slově hýbat. Ověříš to v učebnici češtiny.'),
  claim('velke-pismeno', 'Věta začíná velkým písmenem.', true, ['Podívej se do své čítanky.'],
    'Opravdu to tak je. Ověříš to v každé knize: první slovo věty začíná velkým písmenem.'),
  claim('abeceda', 'Abeceda začíná písmenem Z.', false, ['Zazpívej si abecedu od začátku.'],
    'Abeceda začíná písmenem A a končí písmenem Ž. Ověříš to v čítance nebo ve slovníku.'),
  claim('praha', 'Praha je hlavní město Česka.', true, ['Kde se dá najít hlavní město státu?'],
    'Opravdu to tak je. Ověříš to v atlasu nebo na mapě Česka – hlavní město bývá zvlášť označené.'),
  claim('brno', 'Hlavní město Česka je Brno.', false, ['Podívej se do atlasu.'],
    'Hlavní město Česka je Praha. Brno je druhé největší město. Ověříš to v atlasu.'),
  claim('vanoce', 'V Česku jsou Vánoce v létě.', false, ['Podívej se do kalendáře.'],
    'Vánoce jsou v prosinci, tedy v zimě. Ověříš to v kalendáři.'),
  overit('tuzka', 'Hugin říká: „Tahle tužka je dlouhá 30 centimetrů.“ Jak to ověříš?', 'Změřím ji pravítkem.',
    ['Zeptám se Hugina znovu.', 'Budu hádat.', 'Podívám se do kalendáře.'],
    ['Čím se měří délka?'],
    'Délku ověříš měřením. Přilož pravítko a přečti číslo. Obyčejná tužka bývá kratší než 30 centimetrů.'),
  overit('narozeniny', 'Hugin říká: „Tvoje narozeniny jsou za deset dní.“ Jak to ověříš?', 'Podívám se do kalendáře.',
    ['Změřím to pravítkem.', 'Zeptám se Hugina znovu.', 'Budu hádat.'],
    ['Kde najdeš dny a data?'],
    'V kalendáři najdeš dnešní den i den narozenin a dny mezi nimi spočítáš.'),
  overit('zidle', 'Hugin říká: „Ve třídě je 23 židlí.“ Jak to ověříš?', 'Spočítám je.',
    ['Zeptám se Hugina znovu.', 'Zvážím je.', 'Podívám se na hodiny.'],
    ['Jak se zjistí, kolik čeho je?'],
    'Počet ověříš počítáním. Židle spočítáš jednu po druhé.'),
  overit('teplota', 'Hugin říká: „Venku je teď 30 stupňů.“ Jak to ověříš?', 'Podívám se na teploměr.',
    ['Zeptám se Hugina znovu.', 'Spočítám mraky.', 'Budu hádat.'],
    ['Čím se měří teplota?'],
    'Teplotu ověříš teploměrem. Přečti, kolik stupňů ukazuje.'),
  overit('plejtvak', 'Hugin říká: „Plejtvák obrovský je největší zvíře na světě.“ Jak to ověříš?', 'Najdu to v knize o zvířatech.',
    ['Změřím ho pravítkem.', 'Zeptám se Hugina znovu.', 'Budu hádat.'],
    ['Kde se píše o zvířatech?'],
    'V knize o zvířatech nebo v encyklopedii se dočteš, že plejtvák obrovský je opravdu největší zvíře. Tentokrát měl Hugin pravdu.'),
];

// ---------------------------------------------------------------------------
// L3 – násobilka a jednotky, třídění živočichů, mapa Česka, slovní druhy

const L3: Spec[] = [
  claim('48-plus-27', '48 + 27 = 75.', true, ['Sečti zvlášť desítky a jednotky.'],
    'Opravdu to tak je: 40 + 20 = 60 a 8 + 7 = 15, dohromady 75. Ověříš to zkouškou: 75 − 27 = 48.'),
  claim('63-minus-28', '63 − 28 = 45.', false, ['Udělej zkoušku sčítáním.'],
    '63 − 28 = 35. Ověříš to zkouškou: 35 + 28 = 63, kdežto 45 + 28 = 73.'),
  claim('7-krat-8', '7 × 8 = 54.', false, ['Vzpomeň si na násobilku sedmi nebo osmi.'],
    '7 × 8 = 56. Ověříš to v násobilce: 7 × 7 = 49 a 49 + 7 = 56.'),
  claim('9-krat-6', '9 × 6 = 54.', true, ['Zkus 10 × 6 a pak jednu šestku uber.'],
    'Opravdu to tak je: 10 × 6 = 60 a 60 − 6 = 54. Ověříš to výpočtem nebo v násobilce.'),
  claim('ctvrthodina', 'Čtvrt hodiny je 15 minut.', true, ['Rozděl hodinu na čtyři stejné díly.'],
    'Opravdu to tak je: 60 : 4 = 15. Ověříš to na hodinách – velká ručička urazí čtvrtinu ciferníku za 15 minut.'),
  claim('pulhodina', 'Půl hodiny je 50 minut.', false, ['Kolik minut má celá hodina?'],
    'Půl hodiny je 30 minut, protože celá hodina má 60 minut. Ověříš to na hodinách s ručičkami.'),
  claim('kilometr', 'Kilometr má 1000 metrů.', true, ['Co znamená kilo?'],
    'Opravdu to tak je. Ověříš to v tabulce jednotek v učebnici: kilo znamená tisíc.'),
  claim('velryba', 'Velryba je ryba.', false, ['Jak dýchá velryba a čím krmí mláďata?'],
    'Velryba je savec: dýchá plícemi a mláďata kojí mlékem. Ověříš to v atlasu zvířat.'),
  claim('netopyr', 'Netopýr je pták.', false, ['Má netopýr peří?'],
    'Netopýr je savec. Nemá peří, ale srst, a mláďata kojí. Ověříš to v atlasu zvířat.'),
  claim('pulec', 'Žába se vyvíjí z pulce.', true, ['Co se líhne z žabích vajíček?'],
    'Opravdu to tak je. Z vajíčka se vylíhne pulec a z něj vyroste žába. Ověříš to pozorováním u rybníka na jaře nebo v atlasu zvířat.'),
  claim('tucnaci', 'Tučňáci žijí na severním pólu.', false, ['Podívej se do atlasu zvířat, kde tučňáci žijí.'],
    'Tučňáci žijí skoro jen na jižní polokouli, hodně jich je v Antarktidě. Na severním pólu žádní nejsou. Ověříš to v atlasu zvířat.'),
  claim('snezka', 'Nejvyšší hora Česka je Sněžka.', true, ['Kde najdeš výšky hor?'],
    'Opravdu to tak je, Sněžka měří asi 1603 metrů. Ověříš to v atlasu nebo na mapě Česka.'),
  claim('vltava', 'Vltava teče Prahou.', true, ['Podívej se na mapu Prahy.'],
    'Opravdu to tak je. Ověříš to na mapě: Vltava teče přímo středem Prahy.'),
  claim('bratislava', 'Hlavní město Slovenska je Brno.', false, ['Podívej se do atlasu na mapu Slovenska.'],
    'Hlavní město Slovenska je Bratislava. Brno leží v Česku. Ověříš to v atlasu.'),
  claim('mesic-sviti', 'Měsíc svítí vlastním světlem.', false, ['Proč je Měsíc někdy kulatý a jindy jen srpek?'],
    'Měsíc sám nesvítí, odráží světlo Slunce. Proto vidíme jeho fáze. Ověříš to v knize o vesmíru nebo se zeptáš na hvězdárně.'),
  claim('unor', 'Únor má méně dní než březen.', true, ['Podívej se do kalendáře.'],
    'Opravdu to tak je: únor má 28 dní, v přestupném roce 29, a březen 31. Ověříš to v kalendáři.'),
  claim('rok-dni', 'Rok má 300 dní.', false, ['Podívej se do kalendáře.'],
    'Rok má 365 dní, přestupný 366. Ověříš to v kalendáři, když sečteš dny všech měsíců.'),
  claim('pes-podstatne', 'Slovo pes je podstatné jméno.', true, ['Označuje to slovo osobu, zvíře nebo věc?'],
    'Opravdu to tak je, pes je podstatné jméno – označuje zvíře. Ověříš to v učebnici češtiny v kapitole o slovních druzích.'),
  claim('behat', 'Slovo běhat je podstatné jméno.', false, ['Co to slovo vyjadřuje – věc, nebo děj?'],
    'Běhat je sloveso, vyjadřuje děj. Ověříš to v učebnici češtiny v kapitole o slovních druzích.'),
  claim('byk', 'Slovo býk se píše s tvrdým ý.', true, ['Vzpomeň si na vyjmenovaná slova po b.'],
    'Opravdu to tak je, býk patří mezi vyjmenovaná slova po b. Ověříš to v seznamu vyjmenovaných slov.'),
  claim('mys', 'Slovo myš se píše s měkkým i.', false, ['Vzpomeň si na vyjmenovaná slova po m.'],
    'Myš se píše s tvrdým y, patří mezi vyjmenovaná slova po m. Ověříš to v seznamu vyjmenovaných slov.'),
  claim('led', 'Led je zmrzlá voda.', true, ['Co se stane s vodou v mrazáku?'],
    'Opravdu to tak je. Ověříš to pokusem: dej do mrazáku kelímek s vodou a druhý den v něm najdeš led.'),
  kdeVeta('pavouk', 'Hugin vypráví o pavoukovi', 'Hugin vypráví o pavoukovi. Kde se spletl?',
    ['Pavouk má osm nohou.', 'Mnoho pavouků tká sítě.', 'Pavouk je hmyz.'], 2,
    ['Dvě věty jsou pravdivé, jedna ne.', 'Kolik nohou má hmyz?'],
    'Pavouk není hmyz – hmyz má šest nohou, pavouk osm. Ostatní věty jsou pravdivé. Ověříš to v atlasu zvířat.'),
  kdeVeta('praha', 'Hugin vypráví o Praze', 'Hugin vypráví o Praze. Kde se spletl?',
    ['Praha je hlavní město Česka.', 'Prahou teče Vltava.', 'V Praze je moře.'], 2,
    ['Dvě věty jsou pravdivé, jedna ne.', 'Podívej se na mapu Evropy.'],
    'Česko nemá moře a Praha leží od moře hodně daleko. Ostatní věty jsou pravdivé. Ověříš to na mapě Evropy.'),
  kdeVeta('tyden', 'Hugin vypráví o týdnu', 'Hugin vypráví o týdnu. Kde se spletl?',
    ['Týden má sedm dní.', 'Po úterý přijde středa.', 'U nás je první den týdne sobota.'], 2,
    ['Dvě věty jsou pravdivé, jedna ne.', 'Podívej se do kalendáře.'],
    'V Česku je prvním dnem týdne pondělí. Ostatní věty jsou pravdivé. Ověříš to v kalendáři.'),
  kdeVeta('led', 'Hugin vypráví o ledu', 'Hugin vypráví o ledu. Kde se spletl?',
    ['Když voda zmrzne, je z ní led.', 'Led plave na vodě.', 'Led je teplejší než voda z kohoutku.'], 2,
    ['Dvě věty jsou pravdivé, jedna ne.', 'Čím se dá změřit teplota?'],
    'Led je studený, má nejvýš 0 stupňů. Voda z kohoutku je teplejší. Ověříš to teploměrem.'),
  kdeKrok('vypocet-soucty', 'Hugin počítá', 'Hugin počítá, kolik je 2 × 5 + 3 × 4. Ve kterém kroku se poprvé spletl?',
    ['2 krát 5 je 10.', '3 krát 4 je 12.', '10 plus 12 je 23.'], 2,
    ['Zkontroluj každý krok zvlášť.'],
    'Ve 3. kroku: 10 plus 12 je 22, ne 23. První dva kroky jsou správně. Ověříš to zkouškou: 22 minus 12 je 10.',
    'Hugin počítá, kolik je dvakrát pět plus třikrát čtyři. Ve kterém kroku se poprvé spletl?'),
  kdeKrok('vypocet-jablka', 'Hugin počítá jablka',
    'Ingrid má 4 košíky po 5 jablkách a 3 jablka rozdá. Hugin počítá, kolik jí zbude. Ve kterém kroku se poprvé spletl?',
    ['4 krát 5 je 25.', '25 minus 3 je 22.', 'Zbude 22 jablek.'], 0,
    ['Zkontroluj každý krok zvlášť.'],
    'Už v 1. kroku: 4 krát 5 je 20. Ingrid tedy zbude 20 minus 3, to je 17 jablek. Ověříš to sčítáním: 5 plus 5 plus 5 plus 5 je 20.'),
  overit('snezka', 'Hugin říká: „Sněžka je vysoká 1603 metrů.“ Jak to ověříš?', 'Najdu to v atlasu.',
    ['Změřím ji pravítkem.', 'Zeptám se Hugina znovu.', 'Budu hádat.'],
    ['Kde se píše, jak vysoké jsou hory?'],
    'Výšky hor najdeš v atlasu nebo na mapě. Sněžka měří asi 1603 metrů, takže Hugin má tentokrát pravdu.'),
  overit('aktovka', 'Hugin říká: „Tvoje aktovka váží 5 kilogramů.“ Jak to ověříš?', 'Zvážím ji na váze.',
    ['Změřím ji pravítkem.', 'Zeptám se Hugina znovu.', 'Spočítám v ní sešity.'],
    ['Čím se zjišťuje hmotnost?'],
    'Hmotnost ověříš vážením. Postav aktovku na váhu a přečti číslo.'),
  overit('vyr', 'Hugin říká: „Slovo výr se píše s ypsilonem.“ Jak to ověříš?', 'Podívám se do vyjmenovaných slov.',
    ['Změřím ho pravítkem.', 'Zvážím ho.', 'Zeptám se Hugina znovu.'],
    ['Kde najdeš slova, která se píšou s y?'],
    'Výr patří mezi vyjmenovaná slova po v, takže Hugin má pravdu. Ověříš to v seznamu vyjmenovaných slov.'),
  overit('stromy', 'Hugin říká: „Na školní zahradě roste 12 stromů.“ Jak to ověříš?', 'Půjdu je spočítat.',
    ['Zvážím je.', 'Zeptám se Hugina znovu.', 'Podívám se do kalendáře.'],
    ['Jak se zjistí, kolik čeho je?'],
    'Počet ověříš tak, že stromy spočítáš. Hugin vaši zahradu nikdy neviděl, takže to vědět nemůže.'),
];

// ---------------------------------------------------------------------------
// L4 – větší čísla, zlomky a jednotky, přírodověda, zeměpis, vyjmenovaná slova

const L4: Spec[] = [
  claim('456-plus-278', '456 + 278 = 734.', true, ['Sečti čísla pod sebou.'],
    'Opravdu to tak je. Ověříš to písemným sčítáním pod sebou nebo zkouškou: 734 − 278 = 456.'),
  claim('702-minus-45', '702 − 45 = 667.', false, ['Udělej zkoušku sčítáním.'],
    '702 − 45 = 657, Hugin se spletl o deset. Ověříš to zkouškou: 657 + 45 = 702.'),
  claim('12-krat-12', '12 × 12 = 144.', true, ['Zkus 10 × 12 a 2 × 12.'],
    'Opravdu to tak je: 10 × 12 = 120 a 2 × 12 = 24, dohromady 144. Ověříš to rozkladem nebo na kalkulačce.'),
  claim('72-deleno-8', '72 : 8 = 8.', false, ['Udělej zkoušku násobením.'],
    '72 : 8 = 9. Ověříš to zkouškou: 9 × 8 = 72, kdežto 8 × 8 = 64.'),
  claim('ctvrtina', 'Čtvrtina ze 100 je 25.', true, ['Rozděl 100 na čtyři stejné díly.'],
    'Opravdu to tak je: 100 : 4 = 25. Ověříš to zkouškou: 4 × 25 = 100.'),
  claim('tretina', 'Třetina z 12 je 3.', false, ['Rozděl 12 na tři stejné díly.'],
    'Třetina z 12 je 4, protože 12 : 3 = 4. Ověříš to, když 12 kamínků rozdělíš na tři stejné hromádky.'),
  claim('kilogram', 'Kilogram má 1000 gramů.', true, ['Co znamená kilo?'],
    'Opravdu to tak je, kilo znamená tisíc. Ověříš to v tabulce jednotek nebo na kuchyňské váze.'),
  claim('litr', 'Litr má 100 mililitrů.', false, ['Co znamená mili?'],
    'Litr má 1000 mililitrů. Ověříš to odměrkou: do litrové láhve se vejde deset odměrek po 100 mililitrech.'),
  claim('rostliny-svetlo', 'Zelené rostliny potřebují ke svému růstu světlo.', true, ['Jak by se to dalo vyzkoušet pokusem?'],
    'Opravdu to tak je. Ověříš to pokusem: zasej řeřichu do dvou misek, jednu dej na okno a druhou do tmavé skříně. Za týden bude řeřicha ve tmě bledá a slabá.'),
  claim('houby', 'Houby jsou rostliny.', false, ['Mají houby zelené listy?'],
    'Houby nejsou rostliny, vědci je řadí do samostatné říše. Nemají zelené barvivo a potravu si samy nevyrábějí. Ověříš to v učebnici přírodovědy.'),
  claim('delfin', 'Delfín je savec.', true, ['Jak dýchá delfín a čím krmí mládě?'],
    'Opravdu to tak je: delfín dýchá plícemi a mládě kojí mlékem. Ověříš to v atlasu zvířat.'),
  claim('had', 'Had je obojživelník.', false, ['Jakou kůži má had a jakou žába?'],
    'Had je plaz, má suchou šupinatou kůži. Obojživelníci jsou třeba žáby a mloci. Ověříš to v atlasu zvířat.'),
  claim('srdce', 'Srdce je sval.', true, ['Kde se dá zjistit, z čeho je srdce?'],
    'Opravdu to tak je, srdce je silný sval, který pumpuje krev. Ověříš to v atlasu lidského těla nebo se zeptáš lékařky.'),
  claim('slunce-obiha', 'Slunce obíhá kolem Země.', false, ['Co obíhá kolem čeho?'],
    'Je to naopak: Země obíhá kolem Slunce. Astronomové to zjistili přesným měřením pohybu planet. Ověříš to v knize o vesmíru.'),
  claim('obeh-zeme', 'Země oběhne Slunce zhruba za rok.', true, ['Kde se píše o pohybu Země?'],
    'Opravdu to tak je, jeden oběh trvá asi 365 dní. Ověříš to v knize o vesmíru.'),
  claim('labe', 'Labe se vlévá do Černého moře.', false, ['Podívej se na mapu Evropy.'],
    'Labe teče přes Německo do Severního moře. Ověříš to na mapě Evropy v atlasu.'),
  claim('ostrava', 'Ostrava leží na řece Odře.', true, ['Podívej se na mapu Česka.'],
    'Opravdu to tak je. Ověříš to na mapě Česka v atlasu.'),
  claim('snezka-sumava', 'Sněžka leží na Šumavě.', false, ['Podívej se na mapu Česka.'],
    'Sněžka leží v Krkonoších. Ověříš to na mapě Česka v atlasu.'),
  claim('pysk', 'Slovo pysk je vyjmenované slovo.', true, ['Vzpomeň si na vyjmenovaná slova po p.'],
    'Opravdu to tak je, pysk patří mezi vyjmenovaná slova po p. Ověříš to v seznamu vyjmenovaných slov.'),
  claim('liska', 'Slovo liška se píše s ypsilonem.', false, ['Vzpomeň si na vyjmenovaná slova po l.'],
    'Liška se píše s měkkým i, mezi vyjmenovaná slova nepatří. Ověříš to v seznamu vyjmenovaných slov po l.'),
  claim('vltava-velke', 'Jméno řeky Vltavy se píše s velkým V.', true, ['Je to vlastní jméno?'],
    'Opravdu to tak je, jména řek jsou vlastní jména. Ověříš to na mapě nebo v Pravidlech českého pravopisu.'),
  claim('krasny', 'Slovo krásný je sloveso.', false, ['Vyjadřuje to slovo děj, nebo vlastnost?'],
    'Krásný je přídavné jméno, říká, jaká věc je. Ověříš to v učebnici češtiny v kapitole o slovních druzích.'),
  kdeKrok('vypocet-susenky', 'Hugin počítá sušenky',
    'Knut má 3 balíčky po 6 sušenkách a 5 sušenek sní. Hugin počítá, kolik zbude. Ve kterém kroku se poprvé spletl?',
    ['3 krát 6 je 18.', '18 minus 5 je 12.', 'Zbude 12 sušenek.'], 1,
    ['Zkontroluj každý krok zvlášť.'],
    'Ve 2. kroku: 18 minus 5 je 13, ne 12. Zbude tedy 13 sušenek. Ověříš to zkouškou: 13 plus 5 je 18.'),
  kdeKrok('vypocet-sesity', 'Hugin počítá peníze',
    'Freja má 50 Kč a koupí 2 sešity po 12 Kč. Hugin počítá, kolik jí zbude. Ve kterém kroku se poprvé spletl?',
    ['2 krát 12 je 22.', '50 minus 22 je 28.', 'Zbude 28 korun.'], 0,
    ['Zkontroluj každý krok zvlášť.'],
    'Už v 1. kroku: 2 krát 12 je 24. Freji tedy zbude 50 minus 24, to je 26 Kč. Ověříš to sečtením: 12 plus 12 je 24.',
    'Freja má padesát korun a koupí dva sešity po dvanácti korunách. Hugin počítá, kolik jí zbude. Ve kterém kroku se poprvé spletl?'),
  kdeKrok('vypocet-nohy', 'Hugin počítá nohy',
    'Na dvoře jsou 4 psi a 3 slepice. Hugin počítá, kolik mají dohromady nohou. Ve kterém kroku se poprvé spletl?',
    ['4 psi mají 4 krát 4, tedy 16 nohou.', '3 slepice mají 3 krát 2, tedy 6 nohou.', '16 plus 6 je 20.'], 2,
    ['Zkontroluj každý krok zvlášť.'],
    'Ve 3. kroku: 16 plus 6 je 22, ne 20. Zvířata mají dohromady 22 nohou. Ověříš to, když nohy nakreslíš a spočítáš.'),
  kdeKrok('postup-obvod', 'Hugin počítá obvod čtverce',
    'Hugin počítá obvod čtverce se stranou 5 cm. Ve kterém kroku se poprvé spletl?',
    ['Čtverec má 4 stejně dlouhé strany.', 'Obvod je 5 krát 5, tedy 25.', 'Obvod je 25 centimetrů.'], 1,
    ['Obvod je délka všech stran dohromady.'],
    'Ve 2. kroku měl Hugin násobit 4 krát 5, protože čtverec má 4 strany. Obvod je 20 cm. Ověříš to, když všechny čtyři strany sečteš: 5 + 5 + 5 + 5 = 20.',
    'Hugin počítá obvod čtverce se stranou pět centimetrů. Ve kterém kroku se poprvé spletl?'),
  kdeVeta('vesmir', 'Hugin vypráví o vesmíru', 'Hugin vypráví o vesmíru. Kde se spletl?',
    ['Země obíhá kolem Slunce.', 'Měsíc obíhá kolem Země.', 'Slunce je planeta.'], 2,
    ['Dvě věty jsou pravdivé, jedna ne.', 'Je Slunce planeta, nebo hvězda?'],
    'Slunce je hvězda, ne planeta. Planety, jako je Země, obíhají kolem Slunce. Ověříš to v knize o vesmíru nebo na hvězdárně.'),
  overit('lek', 'Hugin říká: „Když máš horečku, pomůže ti každý lék z lékárničky.“ Jak to ověříš?', 'Zeptám se lékařky nebo lékárníka.',
    ['Vyberu lék podle barvy krabičky.', 'Zeptám se Hugina znovu.', 'Budu hádat.'],
    ['Kdo se vyzná v lécích?'],
    'Ověříš to u lékařky nebo lékárníka: každý lék je na něco jiného, takže Hugin se plete. O lécích vždycky rozhoduje dospělý.'),
  overit('praha-brno', 'Hugin říká: „Z Prahy do Brna je to asi 200 kilometrů.“ Jak to ověříš?', 'Změřím to na mapě podle měřítka.',
    ['Spočítám to na prstech.', 'Zeptám se Hugina znovu.', 'Podívám se do kalendáře.'],
    ['Kde se dají měřit vzdálenosti mezi městy?'],
    'Na mapě změříš vzdálenost pravítkem a podle měřítka ji převedeš na kilometry. Vzdušnou čarou vyjde asi 185 kilometrů a po dálnici je to asi 200 kilometrů, takže Hugin má zhruba pravdu.'),
  overit('led-na-slunci', 'Hugin říká: „Kostka ledu roztaje na slunci rychleji než ve stínu.“ Jak to ověříš?', 'Udělám pokus se dvěma kostkami.',
    ['Zeptám se Hugina znovu.', 'Zvážím jednu kostku.', 'Budu hádat.'],
    ['Jak se dá zkusit, co se stane?'],
    'Ověříš to pokusem: dej jednu kostku ledu na slunce a druhou do stínu a sleduj, která roztaje dřív. Hugin má pravdu.'),
  overit('dog', 'Hugin říká: „Anglické slovo dog znamená kočka.“ Jak to ověříš?', 'Podívám se do slovníku.',
    ['Změřím to pravítkem.', 'Zeptám se Hugina znovu.', 'Budu hádat.'],
    ['Kde se hledá, co znamenají cizí slova?'],
    'Ve slovníku najdeš, že dog znamená pes. Hugin se plete – kočka je anglicky cat.'),
  overit('dinosauri', 'Hugin ti řekne zajímavost o dinosaurech. Co je nejlepší udělat?', 'Ověřit ji v knize nebo u odborníka.',
    ['Hned ji všem říct jako jistotu.', 'Zeptat se Hugina, jestli si je jistý.', 'Nic, stroje se nepletou.'],
    ['Stačí, když to řekne stroj?'],
    'Zajímavost ověříš v knize o dinosaurech nebo se zeptáš v muzeu. Otázka „jsi si jistý?“ nic neověří – stroj se může splést znovu.'),
];

// ---------------------------------------------------------------------------
// L5 – omyly, které zní pravdivě, zlomky a obvody, Evropa, větné členy

const L5: Spec[] = [
  claim('milion', 'Milion je tisíc tisíců.', true, ['Kolik je 1000 × 1000?'],
    'Opravdu to tak je: 1000 × 1000 = 1 000 000. Ověříš to násobením nebo na kalkulačce.'),
  claim('zaokrouhleni', 'Číslo 4567 zaokrouhlené na stovky je 4500.', false, ['Je 4567 blíž k 4500, nebo k 4600?'],
    'Na stovky se 4567 zaokrouhlí na 4600, protože na místě desítek je 6 – to je 5 nebo víc. Ověříš to na číselné ose: 4567 je blíž k 4600.'),
  claim('polovina', 'Polovina je víc než třetina.', true, ['Rozděl v duchu dva stejné koláče.'],
    'Opravdu to tak je. Ověříš to, když rozdělíš dva stejné koláče: jeden na dva díly, druhý na tři. Kousek z prvního je větší.'),
  claim('ctvrtina', 'Jedna čtvrtina je víc než jedna třetina.', false, ['Na kolik dílů se celek dělí?'],
    'Je to naopak: třetina je víc než čtvrtina. Čím na víc dílů celek rozdělíš, tím menší díly jsou. Ověříš to na proužku papíru.'),
  claim('obsah', 'Obdélník se stranami 3 cm a 4 cm má obsah 12 čtverečních centimetrů.', true, ['Zkus to na čtverečkovaném papíře.'],
    'Opravdu to tak je: 3 × 4 = 12. Ověříš to na čtverečkovaném papíře: obdélník zakryje 12 čtverečků o straně 1 cm.',
    'Obdélník se stranami tři centimetry a čtyři centimetry má obsah dvanáct čtverečních centimetrů.'),
  claim('obvod', 'Obvod čtverce se stranou 6 cm je 36 cm.', false, ['Obvod je součet všech stran.'],
    'Obvod je 24 cm, protože 4 × 6 = 24. Hugin spočítal obsah, ne obvod. Ověříš to, když sečteš všechny čtyři strany.',
    'Obvod čtverce se stranou šest centimetrů je třicet šest centimetrů.'),
  claim('blesk', 'Blesk nikdy neudeří dvakrát do stejného místa.', false, ['Kam blesky nejčastěji udeří?'],
    'Blesk udeří i mnohokrát do stejného místa, hlavně do vysokých budov a věží. Vědci to změřili přístroji, které údery blesků zaznamenávají.'),
  claim('netopyri', 'Netopýři jsou slepí.', false, ['Jak se netopýři orientují ve tmě?'],
    'Netopýři vidí. Ve tmě se ale orientují hlavně sluchem: vydávají zvuky a poslouchají jejich ozvěnu. Vědci to ověřili pokusy.'),
  claim('pstros', 'Pštros strká hlavu do písku, když se bojí.', false, ['Kdo pštrosy zkoumá?'],
    'Pštros hlavu do písku nestrká. Vědci pštrosy dlouho pozorovali: hlavu skloní k zemi, když se stará o vejce v hnízdě.'),
  claim('svetlo-zvuk', 'Světlo se šíří rychleji než zvuk.', true, ['Vzpomeň si na bouřku.'],
    'Opravdu to tak je. Ověříš to při bouřce: nejdřív uvidíš blesk a až potom uslyšíš hrom.'),
  claim('rajce', 'Rajče je z pohledu botaniky plod.', true, ['Co najdeš uvnitř rajčete?'],
    'Opravdu to tak je, rajče je plod rostliny a uvnitř má semena. Ověříš to, když rajče rozkrojíš, nebo v knize o rostlinách.'),
  claim('mesic-obeh', 'Měsíc oběhne Zemi za jeden den.', false, ['Jak dlouho trvá od úplňku k úplňku?'],
    'Měsíc oběhne Zemi zhruba za měsíc, ne za den. Ověříš to pozorováním: od úplňku do dalšího úplňku uplyne asi 29 a půl dne.'),
  claim('otoceni-zeme', 'Země se otočí kolem své osy zhruba za 24 hodin.', true, ['Co se kvůli otáčení Země střídá?'],
    'Opravdu to tak je, proto se střídá den a noc. Ověříš to pozorováním Slunce: za 24 hodin je zase na stejném místě oblohy.'),
  claim('italie', 'Česko sousedí s Itálií.', false, ['Podívej se na mapu Evropy.'],
    'Česko s Itálií nesousedí. Sousedí s Německem, Polskem, Slovenskem a Rakouskem. Ověříš to na mapě Evropy.'),
  claim('sousede', 'Česko sousedí se čtyřmi státy.', true, ['Podívej se na mapu Evropy.'],
    'Opravdu to tak je: s Německem, Polskem, Slovenskem a Rakouskem. Ověříš to na mapě Evropy.'),
  claim('kraje', 'Česko má 20 krajů.', false, ['Podívej se na mapu krajů.'],
    'Česko má 14 krajů včetně hlavního města Prahy. Ověříš to na mapě krajů v atlasu.'),
  claim('mydlo', 'Ve slově mýdlo se píše ypsilon.', true, ['Vzpomeň si na vyjmenovaná slova po m.'],
    'Opravdu to tak je, mýdlo je příbuzné s vyjmenovaným slovem mýt. Ověříš to v seznamu vyjmenovaných slov po m.'),
  claim('rychle', 'Slovo rychle je přídavné jméno.', false, ['Říká to slovo, jaká věc je, nebo jak se něco děje?'],
    'Rychle je příslovce, říká, jak se něco děje. Přídavné jméno je rychlý. Ověříš to v učebnici češtiny.'),
  claim('podmet', 'Ve větě ‚Pes hlasitě štěká‘ je podmětem slovo pes.', true, ['Zeptej se: Kdo nebo co štěká?'],
    'Opravdu to tak je: kdo štěká? Pes. Ověříš to otázkou kdo nebo co – tak se podmět hledá.'),
  claim('rostliny-noc', 'Rostliny v noci vyrábějí kyslík stejně jako ve dne.', false, ['Co rostliny potřebují, aby vyráběly kyslík?'],
    'Kyslík rostliny vyrábějí jen na světle. V noci kyslík naopak spotřebovávají, protože dýchají. Vědci to změřili přístroji při pokusech s rostlinami.'),
  claim('srdce-krev', 'Srdce rozvádí krev po celém těle.', true, ['Co ucítíš, když si nahmatáš tep?'],
    'Opravdu to tak je, srdce krev pumpuje do cév. Ověříš to, když si nahmatáš tep na zápěstí – je to rytmus srdce.'),
  claim('jupiter', 'Jupiter je hvězda.', false, ['Kolik hvězd je ve Sluneční soustavě?'],
    'Jupiter je planeta, největší ve Sluneční soustavě. Ověříš to v knize o vesmíru nebo na hvězdárně.'),
  claim('dusik', 'Ve vzduchu je víc dusíku než kyslíku.', true, ['Kdo měří, z čeho je vzduch?'],
    'Opravdu to tak je: dusík tvoří asi čtyři pětiny vzduchu a kyslík asi pětinu. Vědci to zjistili měřením složení vzduchu.'),
  kdeKrok('vypocet-prevod', 'Hugin převádí jednotky',
    'Hugin převádí 2 m 5 cm na centimetry. Ve kterém kroku se poprvé spletl?',
    ['2 metry je 200 centimetrů.', '200 centimetrů a 5 centimetrů je 250 centimetrů.', 'Výsledek je 250 centimetrů.'], 1,
    ['Zkontroluj každý krok zvlášť.'],
    'Ve 2. kroku: 200 cm a 5 cm je 205 cm. Hugin přičetl 50 místo 5. Ověříš to na svinovacím metru.',
    'Hugin převádí dva metry pět centimetrů na centimetry. Ve kterém kroku se poprvé spletl?'),
  kdeKrok('vypocet-tretina', 'Hugin počítá třetinu',
    'Hugin počítá třetinu z 27 a k ní přičte 5. Ve kterém kroku se poprvé spletl?',
    ['27 děleno 3 je 8.', '8 plus 5 je 13.', 'Výsledek je 13.'], 0,
    ['Zkontroluj každý krok zvlášť.'],
    'Už v 1. kroku: 27 děleno 3 je 9. Správný výsledek je 9 plus 5, tedy 14. Ověříš to zkouškou: 3 krát 9 je 27.'),
  kdeKrok('postup-plot', 'Hugin počítá plot kolem zahrady',
    'Zahrada má tvar obdélníku se stranami 8 m a 5 m. Hugin počítá, jak dlouhý plot bude kolem ní. Ve kterém kroku se poprvé spletl?',
    ['Plot povede kolem celé zahrady.', 'Délka plotu je 8 krát 5, tedy 40.', 'Plot bude dlouhý 40 metrů.'], 1,
    ['Plot vede kolem – je to obvod, nebo obsah?'],
    'Ve 2. kroku Hugin spočítal obsah zahrady, ne obvod. Plot bude dlouhý 8 + 5 + 8 + 5 = 26 metrů. Ověříš to, když sečteš všechny strany.',
    'Zahrada má tvar obdélníku se stranami osm metrů a pět metrů. Hugin počítá, jak dlouhý plot bude kolem ní. Ve kterém kroku se poprvé spletl?'),
  kdeKrok('vypocet-vlak', 'Hugin počítá, jak dlouho jel vlak',
    'Vlak vyjel v 8:45 a do cíle dojel v 11:10. Hugin počítá, jak dlouho jel. Ve kterém kroku se poprvé spletl?',
    ['Od 8:45 do 9:00 je 15 minut.', 'Od 9:00 do 11:00 jsou 2 hodiny.', 'Od 11:00 do 11:10 je 10 minut.', 'Celkem 2 hodiny a 35 minut.'], 3,
    ['Zkontroluj každý krok zvlášť.'],
    'Ve 4. kroku: 15 minut a 10 minut je 25 minut. Vlak jel 2 hodiny a 25 minut. Ověříš to na hodinách s ručičkami.',
    'Vlak vyjel v osm hodin čtyřicet pět minut a do cíle dojel v jedenáct hodin deset minut. Hugin počítá, jak dlouho jel. Ve kterém kroku se poprvé spletl?'),
  kdeVeta('mesic', 'Hugin vypráví o Měsíci a Marsu', 'Hugin vypráví o Měsíci a Marsu. Kde se spletl?',
    ['Země má jeden Měsíc.', 'Marsu se kvůli barvě říká rudá planeta.', 'Na Měsíci se dá dýchat jako na Zemi.'], 2,
    ['Dvě věty jsou pravdivé, jedna ne.', 'Co si astronauti brali na Měsíc?'],
    'Na Měsíci skoro žádný vzduch není, astronauti tam museli mít skafandry s kyslíkem. Ostatní věty jsou pravdivé. Ověříš to v knize o vesmíru.'),
  overit('francie', 'Hugin napsal, že ve Francii se mluví hlavně německy. Jak to nejlépe ověříš?', 'Podívám se do encyklopedie.',
    ['Zeptám se Hugina, jestli si je jistý.', 'Uvěřím mu, protože to zní chytře.', 'Napíšu to do úkolu a uvidím.'],
    ['Stačí zeptat se znovu téhož stroje?'],
    'V encyklopedii nebo v atlasu zjistíš, že ve Francii se mluví francouzsky. Zeptat se znovu téhož stroje nestačí – může se splést znovu.'),
  overit('fazole', 'Hugin tvrdí, že fazole vyklíčí i úplně bez vody. Jak to ověříš?', 'Založím pokus s vodou a bez vody.',
    ['Zeptám se Hugina znovu.', 'Budu hádat.', 'Fazole zvážím.'],
    ['Jak se v přírodovědě zkouší, co se stane?'],
    'Pokus to ukáže: fazole ve vlhké vatě vyklíčí, v suché ne. Hugin se plete – semena potřebují ke klíčení vodu.'),
  overit('krok', 'Hugin tvrdí, že tvůj krok je dlouhý 2 metry. Jak to ověříš?', 'Změřím krok svinovacím metrem.',
    ['Spočítám své kroky.', 'Zeptám se Hugina znovu.', 'Podívám se do atlasu.'],
    ['Čím se měří délka?'],
    'Délku ověříš měřením. Dětský krok bývá dlouhý asi půl metru, takže Hugin se plete.'),
  overit('fotka', 'Hugin ukáže fotku kočky s křídly a tvrdí, že je skutečná. Co pomůže nejvíc?', 'Zjistit, odkud fotka pochází.',
    ['Podívat se, jestli je hezká.', 'Zeptat se Hugina znovu.', 'Podívat se, jestli je ostrá.'],
    ['Kdo mohl takovou fotku vyrobit?'],
    'Kočky křídla nemají a takovou fotku mohla vyrobit AI. Ověříš to tak, že zjistíš, kdo fotku vytvořil, a podíváš se do spolehlivých zdrojů.'),
  overit('pruzkum', 'Hugin tvrdí, že ve vaší třídě má psa většina dětí. Jak to ověříš?', 'Udělám ve třídě průzkum.',
    ['Zeptám se jen kamarádky.', 'Budu hádat.', 'Zeptám se Hugina znovu.'],
    ['Odkud se dají získat data o celé třídě?'],
    'Zeptáš se všech spolužáků, odpovědi zapíšeš do tabulky a spočítáš je. Tak z dat zjistíš, jestli má Hugin pravdu.'),
];

export const huginSkill = bankSkill({
  id: ID,
  island: 'dilna',
  name: 'Oprav Hugina',
  description: 'Dítě kriticky posuzuje tvrzení mechanického havrana Hugina z počtů, přírody, jazyka i světa a hledá, jak je ověřit počítáním, měřením nebo v důvěryhodném zdroji.',
  rvp: {
    1: ['ČJS-3-4-03'],
    2: ['ČJS-3-4-03'],
    3: ['ČJS-3-4-03'],
    4: ['I-5-2-04', 'ČJS-5-4-06'],
    5: ['I-5-2-04', 'ČJS-5-4-06'],
  },
  ability: 'usuzovani',
  banks: { 1: L1, 2: L2, 3: L3, 4: L4, 5: L5 },
});

export const huginCards: KnowledgeCard[] = [
  {
    id: 'dilna.hugin.vymysli',
    skillId: ID,
    level: 1,
    emoji: '🤖',
    title: 'Stroje si někdy vymýšlejí',
    text: 'AI občas napíše věc, která zní pravdivě, ale není. Říká se tomu halucinace. Proto se odpovědi strojů vyplatí ověřovat.',
  },
  {
    id: 'dilna.hugin.internet',
    skillId: ID,
    level: 2,
    emoji: '🌐',
    title: 'Co je na internetu, nemusí být pravda',
    text: 'Na internet může psát kdokoli a i počítač se může splést. Důležité zprávy proto ověřujeme v knize, u odborníka nebo měřením.',
    fix: {
      before: 'Co je napsané na internetu nebo co řekne počítač, je určitě pravda.',
      evidence: 'Lidé mnohokrát zjistili, že se po internetu šířily nepravdivé zprávy. Přišli na to, když je porovnali s knihami, měřením a slovy odborníků.',
    },
  },
  {
    id: 'dilna.hugin.tri-otazky',
    skillId: ID,
    level: 3,
    emoji: '🔎',
    title: 'Tři otázky badatelky',
    text: 'Když něco zní divně, zeptej se: Kdo to říká? Jak to ví? Najdu to i jinde? Takhle ověřují zprávy novináři i vědci.',
  },
];
