// Bezpečí a první pomoc – tísňová čísla, volání o pomoc, neznámí lidé,
// bezpečně na silnici, mimořádné události a ošetření drobných poranění.
// Vysvětlení je zajímavost: nejdřív co udělat a proč, pak navazující detail.

import { bankSkill, q, type ChoiceQ, type Spec } from './common';

const ID = 'telo.bezpeci';

/** Tísňová čísla v Česku. */
export const TISNOVA_CISLA = {
  zachranka: '155',
  hasici: '150',
  policie: '158',
  mestska: '156',
  evropske: '112',
} as const;

type Sluzba = keyof typeof TISNOVA_CISLA;

/** Otázka „které číslo?“. Klíč `tisnove-<služba>-…` kontrolují testy.
 *  Číslo 112 nikdy není distraktorem – funguje vždycky. */
function cislo(sluzba: Sluzba, key: string, prompt: string, wrong: Exclude<Sluzba, 'evropske'>[],
  hints: string[], explain: string): ChoiceQ {
  return q(`tisnove-${sluzba}-${key}`, prompt, TISNOVA_CISLA[sluzba], wrong.map((s) => TISNOVA_CISLA[s]), hints, explain);
}

/** Otázka „kdo se ozve na čísle…?“. Klíč `sluzba-<služba>-<číslo>`. */
function sluzba(s: Sluzba, prompt: string, correct: string, wrong: string[], hints: string[], explain: string): ChoiceQ {
  return q(`sluzba-${s}-${TISNOVA_CISLA[s]}`, prompt, correct, wrong, hints, explain);
}

// ---------------------------------------------------------------------------
// L1 – tísňová čísla, neznámí lidé, silnice, nebezpečné věci

const L1: Spec[] = [
  cislo('hasici', 'cislo', 'Které číslo mají hasiči?', ['zachranka', 'policie', 'mestska'],
    ['Všechna tato čísla začínají na 15.', 'Číslo hasičů je z nich nejmenší.'],
    'Hasiči mají číslo 150 a pomáhají při požárech, povodních a dalších nehodách. Profesionální hasiči vyjíždějí ze stanice do dvou minut od poplachu.'),
  cislo('zachranka', 'cislo', 'Které číslo má záchranka?', ['hasici', 'policie', 'mestska'],
    ['Začíná na 15.', 'Poslední dvě číslice jsou stejné.'],
    'Záchranka – zdravotnická záchranná služba – má číslo 155. Voláme ji, když je někdo vážně zraněný nebo nemocný, a operátor po telefonu poradí, jak pomáhat, než sanitka přijede.'),
  cislo('policie', 'cislo', 'Které číslo má policie?', ['hasici', 'zachranka'],
    ['Začíná na 15.', 'Je z těchto čísel největší.'],
    'Policie České republiky má číslo 158. Pomáhá, když je někdo v nebezpečí nebo když někdo krade či ubližuje – a hledá i ztracené děti.'),
  cislo('evropske', 'cislo', 'Které tísňové číslo platí v celé Evropské unii?', ['zachranka', 'hasici', 'policie'],
    ['Nezačíná na 15.'],
    'Číslo 112 je jednotné evropské číslo tísňového volání: platí v Česku i v dalších zemích Evropské unie a pošle hasiče, záchranku i policii. Operátoři u nás mluví i anglicky a německy.'),
  sluzba('hasici', 'Kdo ti pomůže, když zavoláš 150?', 'Hasiči',
    ['Záchranka', 'Policie České republiky', 'Městská policie'],
    ['Na 155 je záchranka a na 158 policie.'],
    'Na čísle 150 jsou hasiči. Nehasí jen požáry – pomáhají i při povodních nebo vyprošťují lidi z havarovaných aut.'),
  sluzba('zachranka', 'Kdo ti pomůže, když zavoláš 155?', 'Záchranka',
    ['Hasiči', 'Policie České republiky', 'Městská policie'],
    ['Na 150 jsou hasiči a na 158 policie.'],
    'Na čísle 155 je zdravotnická záchranná služba – záchranka. Přijede sanitkou se zdravotníky, kteří se o nemocného nebo zraněného postarají už cestou do nemocnice.'),
  sluzba('policie', 'Kdo ti pomůže, když zavoláš 158?', 'Policie České republiky',
    ['Hasiči', 'Záchranka', 'Městská policie'],
    ['Na 150 jsou hasiči a na 155 záchranka.'],
    'Na čísle 158 je Policie České republiky. Městská policie má 156.'),
  cislo('hasici', 'kulna', 'U sousedů hoří kůlna. Které číslo zavoláš?', ['zachranka', 'policie'],
    ['Kdo hasí oheň?'],
    'Oheň hasí hasiči – číslo 150. Drž se od ohně daleko a řekni to dospělému.'),
  cislo('zachranka', 'lezi', 'Na chodníku leží člověk a neodpovídá. Které číslo zavoláš?', ['hasici', 'policie'],
    ['Ten člověk potřebuje lékaře.'],
    'Když někdo leží a nereaguje, potřebuje lékařskou pomoc. Volej 155, nebo požádej dospělého, ať volá.'),

  q('cizi-auto', 'Neznámý člověk tě zve, ať s ním jdeš k autu podívat se na štěňátka. Co uděláš?', 'Řeknu ne, odejdu a řeknu to rodičům.',
    ['Půjdu se podívat, štěňátka jsou roztomilá.', 'Nasednu, když je milý.', 'Počkám s ním, až mi štěňata ukáže.'],
    ['Znáš toho člověka?'],
    'S neznámými lidmi nikam nechodíme, ani když jsou milí. Většina lidí je hodná, ale bezpečí je na prvním místě. Řekni to rodičům.'),
  q('cizi-bonbony', 'Neznámý člověk ti na ulici nabízí bonbony. Co uděláš?', 'Poděkuju, nevezmu si je a odejdu.',
    ['Vezmu si je a hned je sním.', 'Vezmu si je a půjdu s ním pro další.', 'Řeknu mu, kde bydlím.'],
    ['Od koho si můžeš něco vzít?'],
    'Od neznámých lidí si nic nebereme. Zdvořile odmítni, odejdi a řekni to dospělému, kterému věříš.'),
  q('zvonek', 'Jsi doma bez dospělých a zazvoní někdo neznámý. Co uděláš?', 'Neotevřu a zavolám rodičům.',
    ['Hned otevřu.', 'Pustím ho dovnitř, když řekne, že zná mámu.', 'Řeknu mu přes dveře, že tu nikdo dospělý není.'],
    ['Znáš toho člověka?'],
    'Když nejsou dospělí doma, neznámým lidem neotvíráme. Zavolej rodičům a řekni jim, co se stalo.'),
  q('ztraceni', 'Ztratíš se rodičům v obchodě. Co uděláš?', 'Požádám o pomoc prodavačku u pokladny.',
    ['Vyjdu z obchodu a půjdu domů.', 'Schovám se, aby mě nikdo nenašel.', 'Půjdu s prvním člověkem, který mě zavolá.'],
    ['Kdo v obchodě pracuje a může pomoct?'],
    'Když se ztratíš, zůstaň v obchodě a požádej o pomoc prodavačku nebo pokladní. Prodavačka může rodiče přivolat třeba obchodním rozhlasem.'),
  q('kdo-pomuze', 'Kdo ti může pomoct, když se ztratíš?', 'Policista nebo prodavač v obchodě',
    ['Neznámý člověk v autě', 'Nikdo, musím se schovat', 'Pes na ulici'],
    ['Kdo nosí uniformu nebo pracuje v obchodě?'],
    'Když se ztratíš, obrať se na policistu, prodavače nebo třeba maminku s dětmi. Řekni jim své jméno a telefon rodičů.'),
  q('telefon-rodicu', 'Co je dobré znát nazpaměť, kdyby ses {ztratila|ztratil}?', 'Své jméno a telefonní číslo rodičů',
    ['Jména všech zvířat v zoo', 'Barvu auta sousedů', 'Oblíbené jídlo paní učitelky'],
    ['Co pomůže dospělým zavolat tvým rodičům?'],
    'Když znáš své jméno, adresu a telefon rodičů, dospělí ti rychle pomohou dostat se domů. Telefonní číslo se dá naučit jako básnička.'),
  q('prechod-kde', 'Kde je nejbezpečnější přejít silnici?', 'Na přechodu pro chodce',
    ['Mezi zaparkovanými auty', 'V zatáčce', 'Kdekoli, kde zrovna jsem'],
    ['Je tam namalovaná „zebra“.'],
    'Nejbezpečnější je přecházet na přechodu pro chodce, nejlépe se semaforem. Řidiči tam chodce očekávají.'),
  q('rozhlednout', 'Co uděláš, než vstoupíš na přechod?', 'Zastavím se a rozhlédnu se vlevo, vpravo a znovu vlevo.',
    ['Rozběhnu se co nejrychleji.', 'Zavřu oči.', 'Budu se dívat do mobilu.'],
    ['Musíš vidět, jestli něco nejede.'],
    'U přechodu se zastav a rozhlédni: vlevo, vpravo a znovu vlevo. Přejdi, až nic nejede nebo až auta zastaví.'),
  q('cerveny-panacek', 'Na semaforu pro chodce svítí červený panáček. Co uděláš?', 'Stojím a čekám.',
    ['Přeběhnu.', 'Přejdu, když zrovna nic nejede.', 'Přejdu pozpátku.'],
    ['Co znamená červená?'],
    'Červená znamená stůj, a tak počkej, až se rozsvítí zelený panáček. Některé semafory pro nevidomé i pípají nebo tikají.'),
  q('zeleny-panacek', 'Na semaforu pro chodce svítí zelený panáček. Co uděláš?', 'Rozhlédnu se a přejdu.',
    ['Začnu si na přechodu hrát.', 'Budu čekat na červenou.', 'Přeběhnu se zavřenýma očima.'],
    ['Zelená znamená, že smíš jít. Na co ale nezapomeneš?'],
    'Zelená znamená, že můžeš jít. I tak se ale rozhlédni, jestli všechna auta zastavila.'),
  q('mic', 'Míč ti při hře vyletí na silnici. Co uděláš?', 'Nepoběžím za ním a požádám o pomoc dospělého.',
    ['Hned za ním skočím.', 'Poběžím za ním, když jede jen jedno auto.', 'Zavřu oči a poběžím.'],
    ['Co je důležitější – míč, nebo ty?'],
    'Za míčem na silnici nikdy neběž. Požádej dospělého – míč se dá koupit nový, ty jsi jen {jedna|jeden}.'),
  q('auto', 'Jak správně jezdíš v autě?', 'V autosedačce se zapnutým pásem',
    ['Na klíně u mámy', 'Vstoje mezi sedadly', 'Bez pásu, když je cesta krátká'],
    ['Co tě chrání, když auto prudce zabrzdí?'],
    'V autě jezdíme v autosedačce a vždycky připoutaní, protože pás a sedačka chrání při prudkém brzdění. Sedačka dítě nadzvedne, aby mu pás vedl přes rameno, a ne přes krk.'),
  q('prilba', 'Co si vždycky nasadíš, když jedeš na kole?', 'Přilbu',
    ['Sluneční brýle', 'Čepici s bambulí', 'Nic'],
    ['Chrání hlavu.'],
    'Přilba chrání hlavu při pádu, a tak ji nos na kole, koloběžce i bruslích. Na kole ji v Česku musí mít každý mladší 18 let.'),
  q('reflexy', 'Proč nosíme za tmy reflexní pásky?', 'Aby nás řidiči viděli.',
    ['Aby nám bylo tepleji.', 'Aby nás nikdo neviděl.', 'Aby se nám lépe četlo.'],
    ['Co se stane, když na pásku posvítí světla auta?'],
    'Reflexní pásky se ve světle aut rozzáří a řidič tě uvidí z velké dálky. Vracejí totiž světlo přímo zpátky k autu.'),
  q('led', 'Rybník je zamrzlý. Můžeš na něj jít bez dospělého?', 'Ne, led se může prolomit.',
    ['Ano, led je vždycky pevný.', 'Ano, když budu skákat opatrně.', 'Ano, když půjdu úplně {sama|sám}.'],
    ['Víš, jak je led silný?'],
    'Na zamrzlý rybník bez dospělého nechoď, protože led může být tenký a prolomit se. Pohledem se to pozná těžko – led může být na jednom místě pevný a kousek vedle tenký.'),
  q('pilulky', 'Najdeš doma pilulky, které vypadají jako bonbony. Co uděláš?', 'Nevezmu si je a řeknu to dospělému.',
    ['Ochutnám jednu.', 'Rozdám je kamarádům.', 'Schovám si je do kapsy.'],
    ['Jsou to opravdu bonbony?'],
    'Léky nejsou bonbony. Mohly by ti ublížit, proto je nikdy nejez a řekni to dospělému.'),
  q('zasuvka', 'Proč nestrkáme nic do elektrické zásuvky?', 'Mohl by nás zasáhnout elektrický proud.',
    ['Zásuvka by se urazila.', 'Zhasla by všechna světla ve městě.', 'Nic by se nestalo.'],
    ['Co je v zásuvce?'],
    'V zásuvce je elektrický proud. Mohl by nám vážně ublížit, proto do ní nikdy nic nestrkáme.'),
  q('hriste', 'Kde je bezpečné hrát si s míčem?', 'Na hřišti nebo na zahradě',
    ['Na silnici', 'U železniční trati', 'Na parkovišti'],
    ['Kde nejezdí auta ani vlaky?'],
    'S míčem si hrajeme na hřišti, na zahradě nebo v parku – daleko od silnice a kolejí.'),
  q('cizi-pes', 'Chceš pohladit cizího psa. Co uděláš nejdřív?', 'Zeptám se majitele, jestli smím.',
    ['Rychle k němu přiběhnu.', 'Obejmu ho kolem krku.', 'Vezmu mu misku s jídlem.'],
    ['Pes tě nezná.'],
    'Cizího psa hladíme, jen když to majitel dovolí, protože nás nezná a mohl by se leknout. Nejlepší je nechat ho nejdřív očichat ruku.'),
];

// ---------------------------------------------------------------------------
// L2 – další čísla a jak volat o pomoc, bezpečné chování venku i doma

const L2: Spec[] = [
  cislo('mestska', 'cislo', 'Které číslo má městská policie?', ['hasici', 'zachranka', 'policie'],
    ['Začíná na 15.', 'Je o jedna větší než číslo záchranky.'],
    'Městská policie má číslo 156 a stará se o pořádek ve městě. Na rozdíl od Policie České republiky ji zřizuje město nebo obec.'),
  sluzba('mestska', 'Kdo se ti ozve na čísle 156?', 'Městská policie',
    ['Hasiči', 'Záchranka', 'Policie České republiky'],
    ['Policie České republiky má 158.'],
    'Na čísle 156 je městská policie. Policie České republiky má 158.'),
  cislo('hasici', 'les', 'V lese hoří tráva a oheň se šíří. Které číslo zavoláš?', ['zachranka', 'policie', 'mestska'],
    ['Kdo hasí oheň?'],
    'Oheň hasí hasiči – číslo 150. Od ohně rychle odejdi do bezpečí.'),
  cislo('zachranka', 'dedecek', 'Dědeček upadl, nemůže vstát a moc ho bolí noha. Které číslo zavoláš?', ['hasici', 'policie', 'mestska'],
    ['Dědeček potřebuje lékařskou pomoc.'],
    'Když je někdo zraněný a sám si nepomůže, volá se záchranka – 155.'),
  cislo('policie', 'auto', 'Vidíš, jak někdo rozbíjí okno cizího auta a něco z něj bere. Které číslo zavoláš?', ['hasici', 'zachranka'],
    ['Kdo chytá zloděje?'],
    'Když někdo krade nebo ničí cizí věci, volá se policie – 158. Drž se v bezpečí a řekni to dospělému.'),
  cislo('evropske', 'italie', 'Jsi na dovolené v Itálii a potřebuješ pomoc. Které číslo platí i tam?', ['zachranka', 'hasici', 'policie'],
    ['Hledej číslo, které platí v celé Evropské unii.'],
    'V jiných zemích mají tísňové linky jiná čísla, ale 112 platí v celé Evropské unii. Funguje i v některých dalších zemích, třeba ve Švýcarsku nebo v Norsku.'),
  q('volani-co', 'Co řekneš, když voláš na tísňovou linku?', 'Kdo jsem, kde jsem a co se stalo.',
    ['Jakou mám oblíbenou barvu.', 'Jen své jméno a hned zavěsím.', 'Nic, jen budu poslouchat.'],
    ['Pomoc potřebuje vědět, kam jet a proč.'],
    'Řekni, kdo volá, kde to je a co se stalo. Pak odpovídej na otázky a poslouchej, co ti poradí.'),
  q('volani-zavesit', 'Kdy můžeš zavěsit, když voláš záchranku?', 'Až když mi to operátor řekne.',
    ['Hned, jak řeknu jméno.', 'Když se mi už nechce mluvit.', 'Když začne pršet.'],
    ['Operátor se může ještě na něco ptát.'],
    'Nezavěšuj jako první. Operátor se může ještě na něco zeptat nebo ti poradit, co dělat.'),
  q('volani-legrace', 'Proč se na tísňové linky nevolá pro legraci?', 'Linka musí být volná pro lidi, kteří potřebují pomoc.',
    ['Protože je to moc drahé.', 'Protože operátoři nemají rádi písničky.', 'Klidně se tam volat může.'],
    ['Co kdyby se zrovna někdo potřeboval dovolat?'],
    'Zatímco by operátor mluvil s vtipálkem, někdo jiný by se nemusel dovolat. Volání je zdarma, ale jen pro opravdovou pomoc.'),
  q('volani-kde', 'Co je při volání o pomoc nejdůležitější říct?', 'Kde přesně jsem',
    ['Kolik je mi let', 'Jak se jmenuje můj pes', 'Co jsem {měla|měl} k obědu'],
    ['Kam má pomoc přijet?'],
    'Pomoc musí vědět, kam má přijet, a tak řekni adresu nebo popiš, co je kolem. Operátor někdy místo zjistí i podle mobilu, ale jistější je to říct.'),
  q('volani-adresa', 'Nevíš přesnou adresu. Co pomůže operátorovi zjistit, kde jsi?', 'Popsat, co je kolem, třeba obchod nebo název ulice',
    ['Říct, že nevím, a zavěsit', 'Popsat, jaké mám boty', 'Zazpívat písničku'],
    ['Rozhlédni se kolem sebe.'],
    'Rozhlédni se a popiš, co vidíš: název ulice, číslo domu, obchod, zastávku nebo kostel.'),
  q('tajemstvi', 'Někdo ti dá dárek a řekne, ať to rodičům neříkáš. Co uděláš?', 'Řeknu to rodičům.',
    ['Nikomu nic neřeknu.', 'Budu chtít další dárky.', 'Řeknu to jen plyšákovi.'],
    ['Má po tobě cizí dospělý chtít tajemství před rodiči?'],
    'Dospělý nemá po dítěti chtít tajemství před rodiči. O takovém tajemství vždycky řekni rodičům nebo jinému dospělému, kterému věříš.'),
  q('internet-foto', 'Někdo neznámý ti na internetu píše a chce tvou fotku. Co uděláš?', 'Neodpovím a ukážu to rodičům.',
    ['Pošlu mu fotku.', 'Napíšu mu, kde bydlím.', 'Domluvím si s ním schůzku.'],
    ['Znáš ho doopravdy?'],
    'Neznámým lidem na internetu neposíláme fotky ani adresu. Ukaž zprávu rodičům – pomohou ti.'),
  q('nelibi', 'Kamarád tě pořád lechtá, i když chceš, aby přestal. Co můžeš udělat?', 'Říct jasně „Přestaň!“ a případně požádat dospělého o pomoc.',
    ['Nic, musím to vydržet.', 'Kousnout ho.', 'Smát se, i když se mi to nelíbí.'],
    ['Smíš říct ne?'],
    'Tvoje tělo patří tobě. Když se ti něco nelíbí, můžeš říct NE. Když to nepomůže, řekni to dospělému, kterému věříš.'),
  q('prejezd', 'U železničního přejezdu blikají červená světla a zvoní zvonek. Co uděláš?', 'Zastavím a počkám.',
    ['Rychle přeběhnu.', 'Podlezu závoru.', 'Přejdu, když vlak ještě není vidět.'],
    ['Co znamená červené světlo?'],
    'Blikající červená na přejezdu znamená, že jede vlak. Vlak nemůže rychle zastavit, proto počkej, až světla zhasnou.'),
  q('koleje', 'Proč si nehrajeme u železniční trati?', 'Vlak nemůže rychle zastavit.',
    ['Vlaky nemají rády hluk.', 'Koleje jsou studené.', 'Na kolejích se špatně běhá.'],
    ['Vlak je hodně těžký.'],
    'Vlak je těžký a na zastavení potřebuje hodně dlouhou dráhu, a proto si u kolejí nikdy nehrajeme. Rozjetý vlak brzdí i stovky metrů.'),
  q('chodnik', 'Kudy chodíš podél silnice, když je tam chodník?', 'Po chodníku',
    ['Po silnici', 'Po obrubníku', 'Mezi auty'],
    ['Kde jezdí auta a kde chodí lidé?'],
    'Chodec patří na chodník, na silnici jezdí auta. Když chodník chybí, jde se po levém okraji silnice.'),
  q('vystupovani', 'Na kterou stranu vystupuješ z auta?', 'Na stranu u chodníku',
    ['Na stranu, kde jezdí auta', 'Kterýmkoli oknem', 'Na tu, kde je víc místa'],
    ['Kde je bezpečno?'],
    'Z auta vystupujeme na stranu u chodníku. Na druhé straně mohou jezdit auta.'),
  q('sirky', 'Najdeš zapalovač nebo sirky. Co s nimi uděláš?', 'Nebudu si s nimi hrát a dám je dospělému.',
    ['Zkusím něco zapálit.', 'Schovám je pod postel.', 'Hodím je do koše k papírům.'],
    ['Oheň se může rychle rozšířit.'],
    'Se sirkami a zapalovačem si děti nehrají. Oheň se může rychle rozšířit.'),
  q('cistici', 'Lahev čisticího prostředku voní jako limonáda. Co s ní uděláš?', 'Nechám ji být a nepiju z ní.',
    ['Ochutnám.', 'Naliju si z ní do hrnku.', 'Dám ji mladšímu sourozenci.'],
    ['Je to opravdu pití?'],
    'Čisticí prostředky jsou jedovaté, i když hezky voní, a proto je nikdy nepijeme. Nikdy se také nepřelévají do lahví od pití.'),
  q('houby', 'V lese najdeš houbu. Co uděláš?', 'Nesním ji a ukážu ji dospělému.',
    ['Hned ji sním.', 'Ochutnám kousek.', 'Dám ji ochutnat kamarádovi.'],
    ['Některé houby jsou jedovaté.'],
    'Některé houby jsou jedovaté. Poznat je umí jen zkušený houbař, proto je sami nejíme.'),
  q('horky-caj', 'Na stole stojí hrnek s horkým čajem. Co uděláš?', 'Počkám, až trochu vychladne, a vezmu ho opatrně.',
    ['Rychle ho vypiju.', 'Strčím do něj prst.', 'Budu s ním běhat.'],
    ['Horký čaj může opařit.'],
    'Horký nápoj může opařit. Nech ho chvíli vychladnout a nes ho opatrně.'),
  q('strikacka', 'Na hřišti najdeš injekční stříkačku. Co uděláš?', 'Nesáhnu na ni a řeknu to dospělému.',
    ['Zvednu ji a prohlédnu si ji.', 'Vezmu ji domů.', 'Zahodím ji do křoví.'],
    ['Může být nebezpečná.'],
    'Stříkačky nalezené venku mohou být nebezpečné. Nikdy na ně nesahej a řekni to dospělému, který je bezpečně odstraní.'),
  q('pes-bezi', 'Proti tobě běží neznámý pes. Co je nejlepší udělat?', 'Zastavit se, stát klidně a nedívat se mu upřeně do očí.',
    ['Utíkat co nejrychleji.', 'Křičet a mávat rukama.', 'Hodit po něm klacek.'],
    ['Co dělá pes, když něco utíká?'],
    'Když se zastavíš a stojíš klidně jako strom, pes se většinou uklidní. Útěk by ho mohl vyprovokovat k honičce.'),
  q('bourka', 'Venku začne bouřka. Kam se schováš?', 'Do budovy',
    ['Pod osamělý strom', 'Na kopec', 'Do rybníka'],
    ['Kde tě blesk neohrozí?'],
    'Při bouřce jdi do budovy. Osamělý strom, kopec nebo voda jsou při blesku nebezpečné.'),
  q('pozarni-poplach', 'Ve škole zazní požární poplach. Co uděláš?', 'Poslechnu paní učitelku a v klidu odejdu se třídou ven.',
    ['Schovám se pod lavici.', 'Poběžím si pro aktovku.', 'Budu utíkat, kam mě napadne.'],
    ['Kdo ví, kudy jít?'],
    'Při poplachu poslouchej pokyny učitele. Třída odejde v klidu a spořádaně na bezpečné místo.'),
];

// ---------------------------------------------------------------------------
// L3 – mimořádné události, sirény, požár, neznámí lidé a internet

const L3: Spec[] = [
  cislo('policie', 'cr', 'Jaké číslo má Policie České republiky?', ['hasici', 'zachranka', 'mestska'],
    ['Městská policie má 156.'],
    'Policie České republiky má číslo 158, městská policie 156.'),
  sluzba('evropske', 'Kam se dovoláš na čísle 112?', 'Na tísňovou linku, která pošle hasiče, záchranku i policii',
    ['Jen do nemocnice na návštěvy', 'Na předpověď počasí', 'Do obchodu s hračkami'],
    ['Je to jednotné evropské číslo.'],
    'Číslo 112 je jednotné evropské číslo tísňového volání. Operátor podle potřeby pošle hasiče, záchranku i policii.'),
  q('mestska-policie', 'Kdo se ve městě stará hlavně o pořádek, třeba o správné parkování?', 'Městská policie',
    ['Hasiči', 'Záchranka'],
    ['Její číslo je 156.'],
    'Městská policie hlídá pořádek ve městě – třeba parkování, čistotu nebo klid v parku.'),
  q('strom-silnice', 'Po bouřce spadl strom přes silnici. Kdo ho pomůže odklidit?', 'Hasiči',
    ['Záchranka', 'Pošťák', 'Kominík'],
    ['Pomáhají i tam, kde nic nehoří.'],
    'Hasiči nehasí jen požáry. Pomáhají také při povodních, vichřicích nebo když je potřeba odklidit spadlý strom.'),
  q('zdarma', 'Kolik stojí zavolat na tísňovou linku?', 'Nic, je to zdarma',
    ['100 korun', 'Jednu zlatou minci', 'Záleží na počasí'],
    ['Pomoc musí být dostupná pro každého.'],
    'Volání na tísňové linky je zdarma a dovoláš se i z telefonu bez kreditu. Volá se ale jen tehdy, když je opravdu potřeba pomoc.'),
  q('operator', 'Jak se říká člověku, který na tísňové lince přijme hovor?', 'Operátor',
    ['Řidič', 'Pilot', 'Prodavač'],
    ['Sedí u telefonu a posílá pomoc.'],
    'Hovor přijme operátor. Vyptá se, co se stalo, a pošle pomoc.'),
  q('plyn', 'Doma je cítit plyn. Co uděláš?', 'Nerozsvítím, odejdu ven a řeknu to dospělému.',
    ['Rozsvítím, abych {viděla|viděl}, odkud to jde.', 'Zapálím svíčku.', 'Půjdu spát.'],
    ['Plyn může vzplanout od jiskry.'],
    'Plyn může vybuchnout od jiskry. Nerozsvěcuj, nezapaluj, rychle odejdi ven a řekni to dospělému. Ten zavolá hasiče nebo plynárenskou pohotovost.'),
  q('tajemstvi-dobre', 'Které tajemství je v pořádku nechat si pro sebe?', 'Dárek k narozeninám pro mámu',
    ['Když mi někdo ublížil', 'Když mi někdo řekl, ať rodičům něco nepovídám', 'Když se mi stalo něco, čeho se bojím'],
    ['Které tajemství je příjemné?'],
    'Příjemné tajemství, jako je překvapení k narozeninám, je v pořádku. Tajemství, ze kterého je ti smutno nebo úzko, řekni dospělému, kterému věříš.'),
  q('cizi-ve-skole', 'Pro tebe do školy přijde cizí člověk a říká, že ho poslala máma. Co uděláš?', 'Nepůjdu s ním a řeknu to paní učitelce.',
    ['Půjdu s ním, když zná moje jméno.', 'Půjdu s ním, když má hezké auto.', 'Rychle s ním odejdu, ať nečeká.'],
    ['Znáš ho?'],
    'S nikým, koho neznáš, nikam nechoď – ani když zná tvoje jméno. Paní učitelka rodičům zavolá a ověří si to.'),
  q('internet-adresa', 'Na internetu tě někdo neznámý žádá o adresu a jméno školy. Co uděláš?', 'Nic mu nenapíšu a řeknu to rodičům.',
    ['Napíšu mu všechno.', 'Napíšu mu jen adresu.', 'Pošlu mu i fotku našeho domu.'],
    ['Osobní údaje jsou jen pro lidi, které znáš.'],
    'Osobní údaje – adresu, školu nebo telefon – neznámým lidem nikdy nesdílíme. I na internetu platí, že neznámý je neznámý.'),
  q('pomoc-jinemu', 'Jiné dítě je v nebezpečí a potřebuje pomoc. Co uděláš?', 'Zavolám dospělého, a když nikdo není, tísňovou linku.',
    ['Budu dělat, že nic nevidím.', 'Utíkám domů a nic neřeknu.', 'Začnu se smát.'],
    ['Pomoc můžeš přivolat i pro někoho jiného.'],
    'Pomoc můžeš přivolat pro sebe i pro jiné dítě. Zavolej dospělého, a když nikdo není, tísňovou linku.'),
  q('posmivani', 'Spolužáci se pořád posmívají jinému dítěti. Co můžeš udělat?', 'Nepřidat se a říct to paní učitelce.',
    ['Přidat se k nim.', 'Smát se s nimi.', 'Nic, není to moje věc.'],
    ['Jak by ti bylo na jeho místě?'],
    'Když někomu ubližují, řekni to dospělému. Nejsi žalobníček – pomáháš.'),
  q('bez-chodniku', 'Silnice nemá chodník. Po které straně jdeš?', 'Po levé straně, proti jedoucím autům',
    ['Po pravé straně, zády k autům', 'Uprostřed silnice', 'Cik cak z jedné strany na druhou'],
    ['Je lepší auta vidět, nebo je mít za zády?'],
    'Když není chodník, jdeme po levém okraji silnice. Auta jedoucí proti nám tak vidíme přijíždět.'),
  q('vlevo-proc', 'Proč se na přechodu díváme nejdřív vlevo?', 'Auta v bližším pruhu přijíždějí zleva.',
    ['Protože vlevo je hezčí výhled.', 'Protože vpravo auta nejezdí.', 'Na tom vůbec nezáleží.'],
    ['V Česku se jezdí vpravo.'],
    'V Česku se jezdí vpravo, takže auta v pruhu blíž k tobě přijíždějí zleva. Proto vlevo, vpravo a znovu vlevo.'),
  q('autobus', 'Vystoupíš z autobusu a chceš přejít silnici. Kdy půjdeš?', 'Až autobus odjede a uvidím na silnici.',
    ['Hned těsně před autobusem.', 'Hned za autobusem.', 'Proběhnu, dokud autobus stojí.'],
    ['Stojící autobus zakrývá výhled.'],
    'Stojící autobus zakrývá výhled – ty nevidíš auta a řidiči nevidí tebe. Počkej, až autobus odjede.'),
  q('sluchatka', 'Proč nemít při přecházení v uších sluchátka s hudbou?', '{Nemusela|Nemusel} bych slyšet blížící se auto.',
    ['Sluchátka by se rozbila.', 'Hudba by se zastavila.', 'Auta nemají ráda hudbu.'],
    ['Který smysl ti u silnice pomáhá kromě zraku?'],
    'U silnice potřebuješ oči i uši. Se sluchátky bys {nemusela|nemusel} slyšet auto, kolo ani zvonění.'),
  q('tma-obleceni', 'Jaké oblečení je nejlepší, když jdeš za šera podél silnice?', 'Světlé, s reflexními prvky',
    ['Celé černé', 'Tmavě modré', 'Maskáčové'],
    ['Co řidič ve tmě uvidí nejlépe?'],
    'Světlé oblečení a reflexní prvky řidiči uvidí z dálky, tmavé oblečení ve tmě skoro splyne. S reflexními prvky tě řidič uvidí z mnohem větší vzdálenosti než bez nich.'),
  q('sirena-vystraha', 'Siréna dlouho kolísavě houká – nahoru a dolů. Co to znamená?', 'Všeobecnou výstrahu – je potřeba jít dovnitř a sledovat zprávy.',
    ['Že začaly prázdniny.', 'Že přijíždí cirkus.', 'Že někdo slaví narozeniny.'],
    ['Kolísavý tón sirény je varování.'],
    'Kolísavý tón sirény je signál Všeobecná výstraha. Jdi do nejbližší budovy, zavři okna a dveře a zapni rádio nebo televizi – dozvíš se, co dělat.'),
  q('sirena-zkouska', 'Kdy se v Česku pravidelně zkoušejí sirény?', 'Každou první středu v měsíci ve 12 hodin',
    ['Každý den o půlnoci', 'Jen na Vánoce', 'Každou neděli ráno'],
    ['Je to jednou za měsíc.'],
    'Každou první středu v měsíci v poledne se sirény zkoušejí. Zkušební tón je stejnoměrný, nekolísá.'),
  q('pozar-kour', 'V místnosti je kouř. Jak se dostaneš ven?', 'Nízko u země, kde je méně kouře',
    ['Vzpřímeně na špičkách', 'Vylezu na skříň', 'Schovám se pod postel'],
    ['Kouř stoupá nahoru.'],
    'Kouř stoupá nahoru. U země je čistší vzduch, proto se při odchodu drž nízko a jdi rychle ven.'),
  q('pozar-schovat', 'Kam se při požáru nikdy neschováváme?', 'Pod postel ani do skříně',
    ['Ven na bezpečné místo', 'K hasičům', 'K dospělým venku'],
    ['Kde by tě hasiči těžko hledali?'],
    'Při požáru se nikdy neschovávej pod postel ani do skříně. Odejdi ven a řekni dospělým, že jsi v bezpečí.'),
  q('vytah', 'Proč při požáru nepoužíváme výtah?', 'Může se zastavit a naplnit kouřem.',
    ['Výtah je moc pomalý.', 'Ve výtahu je tma.', 'Výtah jezdí jen nahoru.'],
    ['Co se stane s výtahem, když vypadne proud?'],
    'Při požáru může vypadnout proud a výtah se zastaví. Proto chodíme po schodech.'),
  q('povoden', 'Blíží se povodeň. Co uděláš?', 'Poslechnu dospělé a půjdu na vyšší místo.',
    ['Půjdu se podívat k řece.', 'Budu si hrát ve vodě.', 'Schovám se ve sklepě.'],
    ['Kam voda nedosáhne?'],
    'Při povodni jdi s dospělými na vyšší místo – do vyššího patra nebo na kopec. Do sklepa ani k řece nechoď.'),
  q('evakuacni-zavazadlo', 'Co patří do evakuačního zavazadla?', 'Doklady, léky, pití, jídlo, baterka a teplé oblečení',
    ['Televize a velké hračky', 'Jen sladkosti', 'Kolo a trampolína'],
    ['Co bys nutně {potřebovala|potřeboval}, kdybyste museli rychle odejít z domova?'],
    'Evakuační zavazadlo je batoh s nejnutnějšími věcmi: doklady, léky, jídlo, pití, baterka, hygiena a teplé oblečení. Malá oblíbená hračka se vejde taky.'),
  q('pokyny', 'Co je při mimořádné události nejdůležitější?', 'Zachovat klid a poslouchat pokyny dospělých.',
    ['Běhat a křičet.', 'Schovat se, aby mě nikdo nenašel.', 'Natáčet všechno na mobil.'],
    ['Kdo ví, co dělat?'],
    'Při mimořádné události poslouchej učitele, rodiče, hasiče nebo policisty. Klid pomáhá všem.'),
  q('bourka-strom', 'Proč se při bouřce neschováváme pod osamělý strom?', 'Blesk často uhodí do vysokých věcí.',
    ['Strom by se urazil.', 'Pod stromem je zima.', 'Pod stromem prší víc.'],
    ['Kam blesk nejčastěji udeří?'],
    'Blesk často udeří do nejvyššího místa v okolí, třeba do osamělého stromu. Bezpečnější je budova nebo auto.'),
];

// ---------------------------------------------------------------------------
// L4 – ošetření drobných poranění, kdy volat dospělého a lékaře

const L4: Spec[] = [
  q('odrenina', 'Kamarád si odřel koleno. Co uděláš jako první?', 'Opláchnu odřeninu čistou vodou.',
    ['Posypu ji pískem.', 'Přelepím ji bez umytí.', 'Budu do ní šťourat prstem.'],
    ['V odřenině je špína.'],
    'Odřeninu nejdřív opláchni čistou tekoucí vodou, aby se z ní dostala špína. Pak ji dospělý vydezinfikuje a přelepí.'),
  q('odrenina-dal', 'Odřenina je umytá. Co dál?', 'Vydezinfikovat ji a přelepit náplastí.',
    ['Namazat ji máslem.', 'Posypat ji solí.', 'Nechat ji otevřenou v blátě.'],
    ['Do rány se nemá dostat nečistota.'],
    'Po umytí se odřenina vydezinfikuje a překryje náplastí nebo obvazem, aby se do ní nedostala nečistota.'),
  q('nos-hlava', 'Kamarádce teče krev z nosu. Jak má držet hlavu?', 'Předkloněnou',
    ['Zakloněnou dozadu', 'Vzhůru nohama', 'Položenou vleže na polštáři'],
    ['Krev nemá stékat do krku.'],
    'Při krvácení z nosu se hlava předkloní. Kdyby se zaklonila, krev by stékala do krku.'),
  q('nos-stisk', 'Co ještě pomůže zastavit krvácení z nosu?', 'Stisknout nosní křídla na několik minut.',
    ['Smrkat co nejsilněji.', 'Skákat na jedné noze.', 'Strčit do nosu vatu namočenou v limonádě.'],
    ['Nosní křídla jsou měkká část nosu.'],
    'Nosní křídla stiskni prsty na několik minut a dýchej pusou. Pomoct může i studený obklad.'),
  q('nos-dlouho', 'Krev z nosu teče dlouho a nepřestává. Co uděláš?', 'Řeknu to dospělému, aby zajistil lékařskou pomoc.',
    ['Nic, samo to přestane za týden.', 'Půjdu si zaběhat.', 'Budu nos mnout.'],
    ['Když si nevíš rady, kdo pomůže?'],
    'Když krvácení dlouho nepřestává, dospělý zavolá lékaře nebo záchranku.'),
  q('popalenina', 'Kamarádka se spálila o horký hrnec. Co uděláš jako první?', 'Dám popálené místo pod studenou tekoucí vodu.',
    ['Namažu popáleninu máslem.', 'Posypu popáleninu moukou.', 'Přiložím na popáleninu led přímo z mrazáku.'],
    ['Popáleninu je potřeba zchladit.'],
    'Popáleninu hned chlaď čistou studenou vodou, klidně i dvacet minut. Máslo, mouka ani led na ni nepatří.'),
  q('popalenina-led', 'Proč se na popáleninu nedává led přímo z mrazáku?', 'Mohl by kůži ještě víc poškodit.',
    ['Led se moc rychle rozpustí.', 'Led je moc drahý.', 'Led by byl smutný.'],
    ['Mráz kůži také škodí.'],
    'Ledová věc přímo na kůži může popáleninu zhoršit. Nejlepší je chladit tekoucí studenou vodou.'),
  q('puchyr', 'Na popálenině se udělal puchýř. Co s ním?', 'Nepropichovat ho a nechat ho ošetřit.',
    ['Propíchnout ho jehlou.', 'Strhnout z něj kůži.', 'Posypat ho pískem.'],
    ['Puchýř chrání ránu pod sebou.'],
    'Puchýř chrání ránu pod ním. Nepropichuj ho – ošetří ho dospělý nebo lékař.'),
  q('popalenina-lekar', 'Kdy je potřeba jít s popáleninou k lékaři?', 'Když je velká nebo je na obličeji.',
    ['Nikdy, každá popálenina se zahojí sama.', 'Jen když je menší než mince.', 'Jen když prší.'],
    ['Na velikosti a místě záleží.'],
    'Velká popálenina, popálenina na obličeji nebo na rukou a popálenina malého dítěte patří k lékaři. Může být potřeba volat 155.'),
  q('riznuti', 'Kamarád se lehce řízl o papír a má malou ranku. Co pomůže?', 'Umýt ranku a přelepit ji náplastí.',
    ['Olíznout ji a jít si hrát do hlíny.', 'Nechat ji špinavou.', 'Posypat ji cukrem.'],
    ['Ranka má zůstat čistá.'],
    'Malé říznutí stačí umýt, vydezinfikovat a přelepit náplastí. Říznutí papírem bolí víc, než by člověk čekal, protože v konečcích prstů je hodně nervů.'),
  q('krvaceni', 'Z rány hodně teče krev. Co je potřeba udělat?', 'Přitlačit na ránu čistý obvaz a přivolat pomoc.',
    ['Nechat ránu volně krvácet.', 'Nic, krev se zastaví sama.', 'Strčit do rány prst.'],
    ['Tlak krvácení zpomalí.'],
    'Při silném krvácení se na ránu přitlačí čistý obvaz nebo látka. Dospělý nebo záchranka se postarají o další pomoc.'),
  q('rukavice', 'Proč si při ošetřování cizí rány nasazujeme rukavice?', 'Chrání nás i zraněného před bacily.',
    ['Aby nám nebyla zima.', 'Aby rána nebyla vidět.', 'Protože se to hezky nosí.'],
    ['V krvi mohou být bacily.'],
    'Rukavice z lékárničky chrání tebe i zraněného před přenosem bacilů.'),
  q('lekarnicka', 'Co najdeš v lékárničce?', 'Náplasti, obvazy, dezinfekci a rukavice',
    ['Bonbony a čokoládu', 'Hračky a pastelky', 'Klíče a mince'],
    ['Jsou to věci na ošetření.'],
    'V lékárničce jsou náplasti, obvazy, dezinfekce, nůžky a rukavice. Je dobré vědět, kde doma je.'),
  q('vcela', 'Kamarádku bodla včela do ruky. Co pomůže?', 'Chladit místo a říct to dospělému.',
    ['Místo mnout a škrábat.', 'Nic, jen se smát.', 'Zatřást rukou a pokračovat ve hře.'],
    ['Chlad zmenší otok.'],
    'Dospělý opatrně odstraní žihadlo a místo se chladí. Kdyby začal otékat obličej nebo se špatně dýchalo, volá se hned 155.'),
  q('kliste', 'Po procházce v lese najdeš na noze klíště. Co uděláš?', 'Řeknu to dospělému, který ho opatrně vytáhne.',
    ['Namažu ho olejem.', 'Nechám ho tam.', 'Zmáčknu ho prsty.'],
    ['Klíště je potřeba vytáhnout co nejdřív a správně.'],
    'Klíště vytáhne dospělý co nejdřív, třeba pinzetou, a místo vydezinfikuje. Nic se na klíště nemaže.'),
  q('kotnik', 'Kamarád si při běhu podvrtl kotník. Co pomůže?', 'Chladit ho a nechat nohu v klidu.',
    ['Běhat dál.', 'Kotník silně masírovat.', 'Skákat po té noze.'],
    ['Zraněná noha potřebuje klid.'],
    'Podvrtnutý kotník se chladí ledem zabaleným v utěrce, noha se nechá v klidu a dá se výš. Když hodně bolí, patří k lékaři.'),
  q('modrina', 'Kamarád se uhodil do nohy a dělá se mu modřina. Co pomůže?', 'Studený obklad',
    ['Horká láhev', 'Pepř', 'Škrábání'],
    ['Chlad zmenšuje otok.'],
    'Na modřinu pomáhá studený obklad, protože chlad zmírní otok i bolest. Jak se modřina hojí, mění barvu z modré přes zelenou až do žluta.'),
  q('zlomenina', 'Kamarád spadl, ruka ho moc bolí a vypadá divně. Co uděláš?', 'Nechám ruku v klidu a zavolám dospělého.',
    ['Zkusím ruku narovnat.', 'Budu s rukou hýbat, jestli to jde.', 'Řeknu mu, ať si dál hraje.'],
    ['Ruka může být zlomená.'],
    'Když je ruka možná zlomená, nehýbeme s ní a nenarovnáváme ji. Dospělý zajistí lékaře.'),
  q('hlava', 'Kamarád se praštil do hlavy, je mu zle a motá se mu hlava. Co uděláš?', 'Hned to řeknu dospělému.',
    ['Nechám ho jít samotného domů.', 'Pošlu ho točit se na kolotoči.', 'Nic, to přejde.'],
    ['Úraz hlavy je vážný.'],
    'Po úderu do hlavy a nevolnosti je potřeba lékař. Dospělý zajistí pomoc, případně zavolá 155.'),
  q('upal', 'Kamarádka byla dlouho na slunci, bolí ji hlava a je jí zle. Co uděláš?', 'Odvedu ji do stínu, dám jí napít a řeknu to dospělému.',
    ['Necháme ji dál na slunci.', 'Dám jí teplý čaj a deku.', 'Půjdeme si zaběhat.'],
    ['Může to být úpal.'],
    'To může být úpal. Pomáhá stín, pití a chladný obklad. Dospělý posoudí, jestli je potřeba lékař.'),
  q('oko-mydlo', 'Kamarádovi stříklo do oka mýdlo. Co pomůže?', 'Vyplachovat oko čistou vodou.',
    ['Mnout oko.', 'Kapat do oka mléko.', 'Foukat do oka písek.'],
    ['Mýdlo je potřeba z oka dostat.'],
    'Oko se vyplachuje čistou vlažnou vodou, dokud nepřestane pálit. Když pálí dál, je potřeba lékař.'),
  q('triska', 'Do prstu se ti zapíchla tříska. Co uděláš?', 'Požádám dospělého, aby ji opatrně vytáhl.',
    ['Nechám ji tam měsíc.', 'Budu ji kousat.', 'Zamáčknu ji hlouběji.'],
    ['Kdo má pinzetu?'],
    'Třísku opatrně vytáhne dospělý pinzetou a místo vydezinfikuje.'),
  q('kdy-155', 'Kdy voláme záchranku 155?', 'Když je někdo vážně zraněný nebo nereaguje',
    ['Když mám malou odřeninu', 'Když se mi nechce do školy', 'Když mě bolí zub od bonbonu'],
    ['Záchranka jezdí k vážným případům.'],
    'Záchranku voláme, když jde o život nebo o vážné zranění – třeba když někdo nereaguje nebo hodně krvácí. Malé ranky ošetříme sami.'),
  q('bezpeci-pomocnika', 'Než pomůžeš zraněnému, na co musíš myslet nejdřív?', 'Na svou vlastní bezpečnost',
    ['Na to, co bude k večeři', 'Na to, jestli mám čisté boty', 'Na nic, hned běžím, i když jedou auta'],
    ['Rozhlédni se kolem.'],
    'Nejdřív se rozhlédni, jestli ti nic nehrozí – třeba auta nebo oheň. Zraněný pomocník už nikomu nepomůže.'),
  q('uklidnit', 'Co můžeš dělat pro zraněného kamaráda, než přijde dospělý?', 'Zůstat u něj, mluvit s ním a uklidňovat ho.',
    ['Odejít domů.', 'Smát se mu.', 'Nutit ho, aby běhal.'],
    ['Jak by ti bylo, kdybys tam {ležela|ležel} {sama|sám}?'],
    'Když u zraněného zůstaneš a mluvíš s ním, cítí se bezpečněji. I to je důležitá první pomoc.'),
  q('dospely', 'Kdy je dobré zavolat dospělého, když si kamarád ublíží?', 'Vždycky, když si nevím rady nebo je zranění větší',
    ['Nikdy, musím to zvládnout {sama|sám}', 'Jen když se to stane v neděli', 'Až za týden'],
    ['Požádat o pomoc je chytré.'],
    'Dospělého zavolej pokaždé, když si nevíš rady. Požádat o pomoc je chytré.'),
];

// ---------------------------------------------------------------------------
// L5 – život ohrožující situace a přivolání lékařské pomoci

const L5: Spec[] = [
  cislo('zachranka', 'pad', 'Kamarád spadl z vysoké prolézačky a nemůže se hýbat. Které číslo zavoláš?', ['hasici', 'policie', 'mestska'],
    ['Potřebuje lékařskou pomoc.'],
    'Při vážném úrazu voláme záchranku – 155. Zraněný se nemá hýbat, dokud nepřijede pomoc.'),
  cislo('hasici', 'byt', 'V bytě hoří a všichni už jsou venku v bezpečí. Které číslo zavoláš?', ['zachranka', 'policie', 'mestska'],
    ['Kdo hasí požár?'],
    'Požár hlásíme hasičům na 150. Do hořícího bytu se nikdy nevracej.'),
  cislo('evropske', 'nehoda', 'Srazila se auta, někdo je zraněný a z auta se kouří. Které jedno číslo pošle hasiče, záchranku i policii najednou?', ['zachranka', 'hasici', 'policie'],
    ['Je to jednotné evropské číslo.'],
    'Na 112 operátor pošle všechny složky najednou. Samotné číslo 150, 155 nebo 158 by tě spojilo jen s jednou z nich.'),
  q('nereaguje', 'Někdo leží na zemi a neodpovídá, ani když na něj mluvíš a jemně s ním zatřeseš. Co uděláš?', 'Hned zavolám 155 nebo přivolám dospělého.',
    ['Nechám ho spát.', 'Dám mu napít.', 'Odejdu, určitě to nic není.'],
    ['Když někdo nereaguje, jde o život.'],
    'Když někdo nereaguje, jde o život. Hned volej 155 nebo zavolej dospělého. Operátor ti poradí, co dělat dál.'),
  q('dych', 'Jak poznáš, že člověk, který nereaguje, dýchá?', 'Podívám se, jestli se mu zvedá hrudník, a poslechnu si dech.',
    ['Změřím mu teplotu.', 'Podívám se na jeho boty.', 'Počkám, až sám promluví.'],
    ['Co se děje s hrudníkem, když dýcháme?'],
    'Dýchání poznáš podle toho, že se zvedá hrudník a u pusy je slyšet nebo cítit dech. Operátor záchranky ti pomůže.'),
  q('zotavovaci-poloha', 'Člověk nereaguje, ale normálně dýchá. Co s ním dospělí udělají, než přijede záchranka?', 'Otočí ho do polohy na boku.',
    ['Posadí ho a dají mu jíst.', 'Nechají ho ležet na zádech a odejdou.', 'Postaví ho na nohy.'],
    ['Jde o to, aby mohl volně dýchat.'],
    'Člověka, který nereaguje, ale dýchá, dáme do zotavovací polohy na boku. Jazyk mu pak nezapadne a dýchací cesty zůstanou volné.'),
  q('nedycha', 'Člověk nereaguje a nedýchá. Co je nejdůležitější?', 'Hned volat 155 – operátor poradí, jak pomáhat.',
    ['Čekat, jestli se to zlepší.', 'Dát mu napít vody.', 'Jít pro pomoc až zítra.'],
    ['Každá minuta je důležitá.'],
    'Když někdo nedýchá, každá minuta je důležitá. Volej 155 – operátor dospělé navede, jak dělat masáž srdce, než přijede záchranka.'),
  q('alergie', 'Kamaráda bodla vosa, začíná mu otékat obličej a špatně se mu dýchá. Co uděláš?', 'Hned volám 155 a řeknu to dospělému.',
    ['Počkám do zítřka.', 'Dám mu bonbon.', 'Nechám ho lehnout si a spát.'],
    ['Otok a potíže s dýcháním jsou vážné.'],
    'Otok obličeje a potíže s dýcháním po bodnutí jsou vážné. Hned volej 155 a řekni to dospělému.'),
  q('hlaseni', 'Co řekneš operátorovi záchranky?', 'Kde to je, co se stalo, kolik je zraněných a kdo volá',
    ['Jen své jméno', 'Jaké je venku počasí', 'Co dávali včera v televizi'],
    ['Pomoc potřebuje vědět, kam jet a co ji čeká.'],
    'Operátor potřebuje vědět, kde to je, co se stalo, kolik lidí je zraněných a kdo volá. Pak odpovídej na jeho otázky.'),
  q('ohrozuje-krvaceni', 'Které zranění ohrožuje život?', 'Silné krvácení, které nejde zastavit',
    ['Malá odřenina na koleni', 'Štípnutí od komára', 'Malá tříska v prstu'],
    ['Které zranění nejde zvládnout náplastí?'],
    'Silné krvácení, bezvědomí nebo potíže s dýcháním ohrožují život. Tehdy se hned volá 155.'),
  q('ohrozuje-dech', 'Který stav je vážný a potřebuje hned záchranku?', 'Člověk nemůže dýchat',
    ['Člověka svědí štípnutí od komára', 'Člověk má škytavku', 'Člověk kýchá'],
    ['Bez čeho tělo nevydrží ani pár minut?'],
    'Potíže s dýcháním jsou vážné, a proto volej 155 hned. Operátor ti poradí, co dělat, než záchranka přijede.'),
  q('krvaceni-tlak', 'Jak zastavit silné krvácení z rány na ruce?', 'Přitlačit na ránu čistý obvaz a držet.',
    ['Ránu pořád dokola omývat.', 'Nechat ruku volně viset a čekat.', 'Foukat do rány.'],
    ['Tlak krvácení zpomalí.'],
    'Tlak na ránu krvácení zpomalí. Přitlač čistý obvaz, ruku můžeš zvednout výš a mezitím někdo volá 155.'),
  q('obvaz-prosakuje', 'Obvaz na ráně prosákne krví. Co uděláš?', 'Přidám další obvaz navrch a dál tlačím.',
    ['Obvaz strhnu a začnu znovu.', 'Přestanu tlačit.', 'Ránu umyju mýdlem.'],
    ['První vrstvu nesundávej.'],
    'Prosáklý obvaz nesundávej – přidej další vrstvu a dál tlač, dokud nepřijede pomoc.'),
  q('otrava', 'Mladší sourozenec snědl neznámé léky. Co uděláš?', 'Hned to řeknu dospělému nebo zavolám 155 a obal od léků uschovám.',
    ['Počkám, jestli se něco stane.', 'Dám mu sníst ještě něco sladkého.', 'Nic nikomu neřeknu.'],
    ['Může to být otrava.'],
    'Při podezření na otravu jednej hned. Obal od léků pomůže lékařům zjistit, co sourozenec spolkl.'),
  q('podchlazeni', 'Kamarád je celý promrzlý a třese se zimou. Co pomůže?', 'Odvést ho do tepla a dát mu suché oblečení a teplý čaj.',
    ['Nechat ho venku v mokrém oblečení.', 'Dát mu studenou limonádu.', 'Posadit ho do sněhu.'],
    ['Tělo potřebuje teplo.'],
    'Promrzlého člověka odvedeme do tepla, převlékneme do suchého oblečení a dáme mu teplý, ne horký nápoj.'),
  q('nehoda', 'Vidíš dopravní nehodu. Co je pro tebe nejbezpečnější?', 'Zůstat mimo silnici a přivolat pomoc telefonem nebo dospělého.',
    ['Běžet doprostřed silnice.', 'Natáčet to na mobil.', 'Odejít a nikomu nic neříct.'],
    ['Nejdřív tvoje bezpečí.'],
    'Nejdřív tvoje bezpečí – na silnici nechoď. Pomoc přivoláš telefonem: číslo 112 pošle hasiče, záchranku i policii.'),
  q('pomoc-kazdy', 'Musíš pomoct, když se někdo zraní?', 'Ano, aspoň přivolat pomoc, ale bez ohrožení sebe.',
    ['Ne, je mi to jedno.', 'Jen když ho znám.', 'Jen když mi zaplatí.'],
    ['Pomoct může každý, i dítě.'],
    'Každý může pomoct – i dítě. Stačí přivolat dospělého nebo zavolat 155. Do nebezpečí se ale {sama|sám} nevrhej.'),
  q('voda', 'Kamarád ve vodě volá o pomoc a nemůže doplavat. Co uděláš?', 'Zavolám plavčíka nebo dospělého a hodím mu něco, co plave.',
    ['Skočím za ním, i když dobře neplavu.', 'Budu se dívat, co se stane.', 'Odejdu.'],
    ['Nesmíš se dostat do nebezpečí i ty.'],
    '{Sama|Sám} do vody neskákej – {mohla|mohl} by ses dostat do nebezpečí také. Zavolej plavčíka nebo dospělého a hoď kamarádovi něco, co plave, třeba kruh nebo míč.'),
  q('otres', 'Po pádu z kola kamaráda bolí hlava a zvrací. Co to může znamenat?', 'Otřes mozku – potřebuje lékaře.',
    ['Že má hlad.', 'Že je unavený ze školy.', 'Nic vážného, stačí se vyspat.'],
    ['Úder do hlavy může poranit mozek.'],
    'Bolest hlavy, zvracení nebo zmatenost po úderu do hlavy mohou znamenat otřes mozku. Je potřeba lékař.'),
  q('pater', 'Kamarád spadl z výšky a bolí ho záda. Co je správně?', 'Nechat ho ležet v klidu a volat pomoc.',
    ['Pomoct mu hned vstát.', 'Posadit ho a zatřást s ním.', 'Odnést ho na zádech domů.'],
    ['Může mít poraněnou páteř.'],
    'Při pádu z výšky a bolesti zad může být poraněná páteř. Zraněný se nemá hýbat a volá se 155.'),
  q('autolekarnicka', 'Proč má každé auto lékárničku?', 'Aby šlo ošetřit zraněné i na cestě.',
    ['Aby bylo auto těžší.', 'Aby se v ní vozily svačiny.', 'Je to jen ozdoba.'],
    ['Nehoda se může stát kdekoli.'],
    'Autolékárnička je povinná výbava auta. Jsou v ní obvazy, rukavice a další věci na první pomoc.'),
  q('vedet-predem', 'Proč je dobré vědět, kde je doma lékárnička a telefon na rodiče?', 'V nouzi pak neztrácím čas hledáním.',
    ['Aby se dalo hrát na schovávanou.', 'Kvůli úklidu.', 'Nemá to význam.'],
    ['V nouzi rozhodují minuty.'],
    'V nouzi rozhodují minuty. Když víš, kde je lékárnička a komu volat, pomůžeš rychleji.'),
  q('klid', 'Proč je při první pomoci důležitý klid?', 'S klidem lépe přemýšlím a zraněný se méně bojí.',
    ['Aby se nikdo nedozvěděl, co se stalo.', 'Aby zraněný usnul.', 'Klid není potřeba.'],
    ['Zkus se zhluboka nadechnout.'],
    'Když zůstaneš v klidu, lépe si vzpomeneš, co dělat, a zraněný se uklidní. Zhluboka se nadechni a jednej.'),
  q('cekani', '{Zavolala|Zavolal} jsi záchranku. Co můžeš dělat, než přijede?', 'Zůstat u zraněného a mít zapnutý telefon.',
    ['Odejít domů.', 'Vypnout telefon.', 'Jít si hrát.'],
    ['Operátor ti může zavolat zpátky.'],
    'Zůstaň u zraněného a měj zapnutý telefon – operátor ti může zavolat zpět. Když je vás víc, někdo může záchranku navigovat k místu.'),
  q('operator-rady', 'Proč je dobré poslouchat, co říká operátor záchranky?', 'Poradí mi, jak pomoct, než přijede záchranka.',
    ['Chce mi vyprávět pohádku.', 'Chce, abych hned {zavěsila|zavěsil}.', 'Nic důležitého neříká.'],
    ['Operátor je vyškolený.'],
    'Operátor je vyškolený a krok za krokem ti poradí, jak pomoct. Proto nezavěšuj a poslouchej.'),
];

export const bezpeci = bankSkill({
  id: ID,
  name: 'Bezpečí a první pomoc',
  description: 'Učí tísňová čísla, bezpečné chování na ulici, doma i s neznámými lidmi, reakce při mimořádných událostech a první pomoc.',
  rvp: {
    1: ['ČJS-3-5-02', 'ČJS-3-5-03', 'ČJS-3-5-04'],
    2: ['ČJS-3-5-02', 'ČJS-3-5-03', 'ČJS-3-5-04'],
    3: ['ČJS-3-5-02', 'ČJS-3-5-03', 'ČJS-3-5-04'],
    4: ['ČJS-5-5-07'],
    5: ['ČJS-5-5-07'],
  },
  ability: 'znalosti',
  showFact: true,
  banks: { 1: L1, 2: L2, 3: L3, 4: L4, 5: L5 },
});
