// Fakt, nebo pohádka? – třídění tvrzení: překvapivé, ale pravdivé věci o lidském
// těle proti pohádkovým a vymyšleným. Vysvětlení vždy říká, JAK to víme
// (pozorování, pokus, měření lékařů), nebo proč jde jen o příběh.

import { bankSkill, fact, type Spec } from './common';

const ID = 'telo.fakt-pohadka';

// ---------------------------------------------------------------------------
// L1 – jasná fakta o těle a jasné pohádky

const L1: Spec[] = [
  fact('srdce-spanek', 'Srdce tluče i ve spánku.', true,
    ['Potřebuje tělo krev i v noci?'],
    'Fakt. Lékaři to slyší fonendoskopem a měří přístroji: srdce tluče celý život, i když spíme.'),
  fact('kosti-rostou', 'Kosti rostou.', true,
    ['Jsi vyšší než loni?'],
    'Fakt. Když rosteš, rostou i kosti. Lékaři to vidí na rentgenu a ty to poznáš, když ti jsou boty malé.'),
  fact('nehty', 'Nehty pořád dorůstají, a proto je stříháme.', true,
    ['Podívej se na své nehty za pár týdnů.'],
    'Fakt. Můžeš to pozorovat sama: za pár týdnů jsou nehty zase dlouhé.'),
  fact('vlasy-strihani', 'Když se stříhají vlasy, nebolí to.', true,
    ['Vzpomeň si na kadeřníka.'],
    'Fakt. Ve vlasech nejsou nervy, které by cítily bolest. Znáš to od kadeřníka.'),
  fact('beh-srdce', 'Když běháš, srdce bije rychleji.', true,
    ['Dá se to vyzkoušet?'],
    'Fakt. Po běhu si polož ruku na hrudník – ucítíš, jak rychle buší.'),
  fact('mlecne-zuby', 'Dětem vypadávají mléčné zuby a rostou jim nové.', true,
    ['Podívej se na úsměvy spolužáků.'],
    'Fakt. Pozoruješ to u sebe i u spolužáků – na místě mléčného zubu vyroste stálý.'),
  fact('husi-kuze', 'Když je nám zima, naskočí nám husí kůže.', true,
    ['Vzpomeň si, jak vypadají ruce po vylezení z bazénu.'],
    'Fakt. Můžeš to pozorovat, když vylezeš z bazénu – chloupky na kůži se postaví.'),
  fact('kychnuti', 'Když kýchneme, vyletí nám z nosu drobné kapičky.', true,
    ['Proč kýcháme do kapesníku?'],
    'Fakt. Vědci to natáčeli rychlou kamerou. Proto kýcháme do kapesníku nebo do lokte.'),
  fact('dve-plice', 'Člověk má dvě plíce.', true,
    ['Jaký přístroj ukáže, co je uvnitř těla?'],
    'Fakt. Lékaři to vidí na rentgenovém snímku hrudníku: pravou a levou plíci.'),
  fact('slzy', 'Slzy oko čistí a zvlhčují.', true,
    ['Je oko suché, i když nepláčeš?'],
    'Fakt. Oko je pořád trochu vlhké díky slzám – i když zrovna nepláčeš.'),
  fact('sny', 'Když spíme, zdají se nám sny.', true,
    ['Pamatuješ si někdy ráno, co se ti zdálo?'],
    'Fakt. Sny si často pamatujeme po probuzení a vědci přístroji měří, co mozek ve spánku dělá.'),
  fact('zivani', 'Když někdo zívá, často začnou zívat i ostatní.', true,
    ['Dá se to vyzkoušet doma?'],
    'Fakt. Můžeš to vyzkoušet: zívni před rodinou a pozoruj, co se stane.'),
  fact('pes-cich', 'Pes cítí nosem mnohem víc vůní než člověk.', true,
    ['Proč pomáhají psi hledat ztracené lidi?'],
    'Fakt. Vědci to ověřili pokusy. Proto psi pomáhají hledat ztracené lidi.'),
  fact('drak-ohen', 'Drak chrlí oheň.', false,
    ['Viděl někdo skutečného draka?'],
    'Pohádka. Draci chrlí oheň v pohádkách a příbězích – třeba i v naší hře. Žádné skutečné zvíře oheň chrlit neumí.'),
  fact('drak-sedm-hlav', 'Drak má sedm hlav.', false,
    ['Kde se o dracích vypráví?'],
    'Pohádka. Sedmihlavý drak je z pohádek. Ve skutečnosti nemá sedm hlav žádné zvíře.'),
  fact('nos-lez', 'Když někdo zalže, vyroste mu nos.', false,
    ['Znáš někoho, komu by se to opravdu stalo?'],
    'Pohádka. Tak se to děje jen v pohádce o Pinocchiovi. Kdyby to byla pravda, lháře bychom poznali hned!'),
  fact('kouzelne-jablko', 'Kdo kousne do kouzelného jablka, usne na sto let.', false,
    ['Existují kouzelná jablka?'],
    'Pohádka. Kouzelná jablka a stoletý spánek známe jen z pohádek.'),
  fact('zlata-rybka', 'Zlatá rybka splní tři přání.', false,
    ['Co dělají zlaté rybky v akváriu?'],
    'Pohádka. Skutečné zlaté rybky plavou v akváriu, ale přání neplní.'),
  fact('proutek-ryma', 'Mávnutím kouzelného proutku zmizí rýma.', false,
    ['Jak se léčí rýma doopravdy?'],
    'Pohádka. Rýma se léčí odpočinkem, pitím a kapesníky. Kouzelné proutky jsou jen v pohádkách.'),
  fact('letani', 'Když člověk rychle mává rukama, vzlétne jako pták.', false,
    ['Zkoušela jsi to někdy?'],
    'Pohádka. Člověk nemá křídla a ruce ho neunesou. Létat může jen v letadle nebo třeba v balonu.'),
  fact('drak-jiskry', 'Když drak kýchne, vyletí mu z nosu jiskry.', false,
    ['Kde žijí draci?'],
    'Pohádka. Draci jsou z příběhů. Když kýchne člověk, vyletí mu z nosu jen drobné kapičky.'),
  fact('sedmimilove-boty', 'Kdo si obuje sedmimílové boty, přejde jedním krokem sedm mil.', false,
    ['Jak dlouhý je tvůj krok?'],
    'Pohádka. Sedmimílové boty jsou z pohádek. Skutečný krok měří jen kousek.'),
  fact('mluvici-dracek', 'Dráček se vylíhne z vejce a hned umí mluvit.', false,
    ['Kde se dráčci líhnou?'],
    'Pohádka. Mluvící dráčci jsou z příběhů. I lidská miminka se mluvit učí dlouho.'),
  fact('ziva-voda', 'Kdo se napije živé vody, uzdraví se z každé nemoci.', false,
    ['Kdo léčí nemoci doopravdy?'],
    'Pohádka. Živá voda je z pohádek. Nemoci léčí lékaři, léky a odpočinek.'),
  fact('neviditelna-cepice', 'Kdo si nasadí kouzelnou čepici, stane se neviditelným.', false,
    ['Dokáže nějaká čepice člověka opravdu schovat?'],
    'Pohádka. Neviditelnost je jen v pohádkách a příbězích.'),
];

// ---------------------------------------------------------------------------
// L2 – překvapivá fakta a nenápadnější pohádky

const L2: Spec[] = [
  fact('rano-vyssi', 'Ráno jsi o kousek vyšší než večer.', true,
    ['Vědci to měřili metrem. Co se přes den děje s páteří?'],
    'Fakt. Přes den se ploténky v páteři trochu stlačí a v noci se zase roztáhnou. Lékaři to změřili.'),
  fact('nejmensi-kost', 'Nejmenší kost v těle je v uchu.', true,
    ['Tahle kost pomáhá slyšet.'],
    'Fakt. Jmenuje se třmínek a je menší než zrnko rýže. Lékaři ho znají ze zkoumání lidského těla.'),
  fact('nejdelsi-kost', 'Nejdelší kost v těle je ve stehně.', true,
    ['Jak by se daly kosti změřit?'],
    'Fakt. Stehenní kost je nejdelší. Lékaři kosti měří třeba na rentgenových snímcích.'),
  fact('srdce-pest', 'Srdce je zhruba tak velké jako tvoje pěst.', true,
    ['Lékaři srdce měřili.'],
    'Fakt. Lékaři to vědí z měření: srdce je zhruba tak velké jako pěst svého majitele.'),
  fact('kuze-nejvetsi', 'Kůže je největší orgán lidského těla.', true,
    ['Který orgán pokrývá celé tělo?'],
    'Fakt. Kůže pokrývá celé tělo. Když vědci orgány změřili a zvážili, žádný nebyl větší.'),
  fact('miminko-kosti', 'Miminko má v těle víc kostí než dospělý.', true,
    ['Některé kosti mohou srůstat.'],
    'Fakt. Některé kosti miminka jsou ještě rozdělené na části a později srostou. Lékaři to vidí na rentgenu.'),
  fact('jazyk-sval', 'Jazyk je z velké části sval.', true,
    ['Jak pohyblivý je tvůj jazyk?'],
    'Fakt. Proto se umí hýbat do všech stran – vyzkoušej si to před zrcadlem.'),
  fact('otisky', 'Každý člověk má jiné otisky prstů.', true,
    ['Kdo porovnává otisky prstů?'],
    'Fakt. Vědci a policisté porovnali otisky mnoha lidí a nenašli dva stejné – ani u dvojčat.'),
  fact('lechtani', 'Sám sebe člověk skoro nepolechtá.', true,
    ['Dá se to vyzkoušet hned teď.'],
    'Fakt. Mozek předem ví, kam sáhneš, a tak lechtání skoro necítíš. Vyzkoušej to!'),
  fact('mrkani', 'Mrkáme mnohokrát za minutu, a ani o tom nevíme.', true,
    ['Zkus někomu počítat mrknutí.'],
    'Fakt. Když budeš kamarádovi minutu počítat mrknutí, napočítáš jich hodně.'),
  fact('vlasy-spanek', 'Vlasy rostou, i když spíme.', true,
    ['Rostou vlasy jen ve dne?'],
    'Fakt. Vlasy rostou pořád, ve dne i v noci – zhruba o centimetr za měsíc.'),
  fact('kolotoc', 'Za to, že se po kolotoči točí hlava, může ucho.', true,
    ['Kde máme smysl pro rovnováhu?'],
    'Fakt. Ve vnitřním uchu je ústrojí rovnováhy. Po točení se v něm ještě chvíli pohybuje tekutina.'),
  fact('sklovina', 'Zubní sklovina je nejtvrdší látka v lidském těle.', true,
    ['Vědci měřili tvrdost různých částí těla.'],
    'Fakt. Vědci změřili tvrdost různých částí těla a sklovina vyhrála.'),
  fact('drak-ctyri-srdce', 'Drak má čtyři srdce.', false,
    ['Jak by to kdo zjistil, kdyby draci nebyli skuteční?'],
    'Pohádka. Draci existují jen v příbězích, a tak si počet srdcí vymýšlí vypravěč. Člověk má jedno srdce se čtyřmi dutinami.'),
  fact('drak-pod-vodou', 'Drak dokáže dýchat pod vodou i v ohni.', false,
    ['Kde se o dracích vypráví?'],
    'Pohádka. Takové věci umějí jen draci z příběhů. Člověk pod vodou dýchat nemůže, a proto si potápěči berou láhev se vzduchem.'),
  fact('draci-supina', 'Kdo sní dračí šupinu, bude rozumět řeči ptáků.', false,
    ['Znáš to z nějaké pohádky?'],
    'Pohádka. Rozumět řeči zvířat umějí jen hrdinové pohádek. Chování zvířat se ve skutečnosti učíme pozorováním.'),
  fact('vila-kost', 'Víla umí mávnutím hůlky zahojit zlomenou kost.', false,
    ['Jak dlouho se hojí zlomená kost doopravdy?'],
    'Pohádka. Zlomená kost srůstá několik týdnů v sádře. Víly a kouzelné hůlky patří do pohádek.'),
  fact('obr-sopka', 'Obr má v břiše malou sopku, a proto chrlí oheň.', false,
    ['Co je doopravdy v břiše?'],
    'Pohádka. V břiše jsou žaludek a střeva, žádná sopka. Obři a ohniví tvorové jsou z příběhů.'),
  fact('lektvar', 'Po vypití kouzelného lektvaru vyroste člověk až do mraků.', false,
    ['Jak rychle rostou lidé doopravdy?'],
    'Pohádka. Člověk roste pomalu, celé dětství. Kouzelné lektvary jsou jen v příbězích.'),
  fact('drak-zlato', 'Drak spí sto let na hromadě zlata.', false,
    ['Kde se o dracích a pokladech vypráví?'],
    'Pohádka. Draci z pohádek a pověstí rádi hlídají poklady, ale skuteční draci neexistují.'),
  fact('pistalka', 'Když zapískáš na kouzelnou píšťalku, přiletí drak.', false,
    ['Kdo přiběhne na zapískání doopravdy?'],
    'Pohádka. Na píšťalku může přiběhnout vycvičený pes, ale drak nepřiletí – draci jsou z příběhů.'),
  fact('zkamenet', 'Kdo se podívá na zlou čarodějnici, zkamení.', false,
    ['Může se živé tělo proměnit v kámen?'],
    'Pohádka. Zkamenění je motiv z pohádek a bájí. Skutečné tělo se v kámen nepromění.'),
  fact('kouzelny-kolac', 'Kdo sní kouzelný koláč, zmenší se na velikost myšky.', false,
    ['Může se tělo najednou zmenšit?'],
    'Pohádka. Takové kouzlo známe z příběhů. Skutečné tělo se zmenšit nedá.'),
  fact('ohnivy-mechyr', 'Dráček má v břiše ohnivý měchýř.', false,
    ['Kdo by to mohl zjistit?'],
    'Pohádka. To si vymysleli vypravěči dračích příběhů. Člověk má v břiše močový měchýř – a ten je na moč, ne na oheň.'),
  fact('zlaty-vlas', 'Kdo získá zlatý vlas, tomu se splní každé přání.', false,
    ['Znáš pohádku o zlatých vlasech?'],
    'Pohádka. Tři zlaté vlasy děda Vševěda jsou z pohádky. Skutečné vlasy přání neplní.'),
  fact('kocour-v-botach', 'Kocour v botách umí mluvit a chodí po dvou.', false,
    ['Jak se chovají skutečné kočky?'],
    'Pohádka. Kocour v botách je pohádková postava. Skutečné kočky mňoukají a chodí po čtyřech.'),
];

// ---------------------------------------------------------------------------
// L3 – těžší: fakta, která zní neuvěřitelně, a povídačky, které zní skoro pravdivě

const L3: Spec[] = [
  fact('sitnice', 'Obraz v oku je na sítnici vzhůru nohama.', true,
    ['Oko funguje trochu jako fotoaparát.'],
    'Fakt. Vědci to pozorovali už před stovkami let na oku zvířete. Mozek si obraz otočí správně.'),
  fact('srdce-dutiny', 'Lidské srdce má uvnitř čtyři dutiny.', true,
    ['Jak se jmenují části srdce?'],
    'Fakt. Dvě síně a dvě komory. Lékaři je vidí třeba při ultrazvuku srdce.'),
  fact('svaly-600', 'Člověk má víc než šest set svalů.', true,
    ['Svalů je víc než kostí.'],
    'Fakt. Vědci svaly spočítali při zkoumání lidského těla. Kostí je asi 206, svalů mnohem víc.'),
  fact('zirafa', 'Žirafa má v krku stejný počet obratlů jako člověk.', true,
    ['Vědci srovnávali kostry.'],
    'Fakt. Obě mají sedm krčních obratlů – žirafí jsou jen mnohem delší. Vědci to zjistili srovnáním koster.'),
  fact('tenke-strevo', 'Tenké střevo je dlouhé několik metrů.', true,
    ['Jak se takové střevo vejde do břicha?'],
    'Fakt. Lékaři ho změřili. Aby se do břicha vešlo, je stočené.'),
  fact('kyselina', 'V žaludku je kyselina, která ničí mnoho bakterií.', true,
    ['Vědci měřili žaludeční šťávu.'],
    'Fakt. Vědci změřili, že žaludeční šťáva je velmi kyselá. Chrání nás tak před bacily z jídla.'),
  fact('kosti-zive', 'Kosti jsou živé a zlomená kost se umí zahojit.', true,
    ['Proč se nosí sádra?'],
    'Fakt. Lékaři na rentgenu pozorují, jak zlomenina během týdnů sroste.'),
  fact('mozek-energie', 'Mozek spotřebuje asi pětinu energie, kterou tělo v klidu potřebuje.', true,
    ['Mozek pracuje pořád, i ve spánku.'],
    'Fakt. Vědci to změřili. Mozek je poměrně malý, ale pracuje pořád – i ve spánku.'),
  fact('rostliny-oxid', 'Vydechujeme oxid uhličitý, který rostliny potřebují k růstu.', true,
    ['Co rostliny potřebují a co vyrábějí?'],
    'Fakt. Rostliny oxid uhličitý potřebují k růstu a samy vyrábějí kyslík. Vědci to ověřili pokusy.'),
  fact('chleba-sladky', 'Když dlouho žvýkáš chleba, začne chutnat nasládle.', true,
    ['Dá se to vyzkoušet u svačiny.'],
    'Fakt. Sliny začnou měnit škrob v chlebu na cukr. Můžeš si to vyzkoušet!'),
  fact('ucuknuti', 'Ruka ucukne od horkého dřív, než ucítíš bolest.', true,
    ['Kdo dává povel k ucuknutí?'],
    'Fakt. Povel k ucuknutí vydá už mícha. Vědci změřili, že zpráva o bolesti dorazí do mozku o chvilku později.'),
  fact('sklovina-nedoroste', 'Zubní sklovina zničená kazem už sama nedoroste.', true,
    ['Co dělá zubař s dírou v zubu?'],
    'Fakt. Proto zubař díru v zubu vyčistí a zaplní plombou. Lepší je zuby chránit čištěním.'),
  fact('spanek-pamet', 'Ve spánku si mozek ukládá, co ses přes den naučila.', true,
    ['Vědci to zkoumali pokusy.'],
    'Fakt. Vědci porovnávali lidi, kteří se něco naučili a pak spali, s těmi, kdo nespali. Ti vyspalí si pamatovali víc.'),
  fact('zacpany-nos', 'Když si zacpeš nos, jídlo chutná méně.', true,
    ['Dá se to vyzkoušet s kouskem jablka.'],
    'Fakt. Vyzkoušej to s kouskem jablka. Velkou část chuti jídla totiž cítíme nosem.'),
  fact('jaderko', 'Když spolkneš jadérko, vyroste ti v břiše strom.', false,
    ['Co potřebuje semínko, aby vyklíčilo?'],
    'Pohádka – taková povídačka. Semínko potřebuje hlínu a světlo. V břiše nevyklíčí a tělo ho prostě vyloučí.'),
  fact('mozek-desetina', 'Lidé používají jen desetinu mozku.', false,
    ['Vědci umějí přístroji sledovat, které části mozku pracují.'],
    'Pohádka – rozšířená povídačka. Vědci přístroji vidí, že během dne pracují všechny části mozku.'),
  fact('drak-tvrde-supiny', 'Drak má šupiny tvrdší než zubní sklovina.', false,
    ['Mohl někdo dračí šupiny změřit?'],
    'Pohádka. Draky nikdo nikdy nezměřil, protože existují jen v příbězích. Nejtvrdší opravdu změřená látka v lidském těle je sklovina.'),
  fact('drak-zlaza', 'Draci mají v krku ohnivou žlázu.', false,
    ['Prozkoumal někdy někdo skutečného draka?'],
    'Pohádka. Draci jsou z příběhů. Skutečné slinné žlázy v puse vyrábějí sliny, ne oheň.'),
  fact('silhani', 'Když šilháš a zafouká vítr, zůstaneš tak navždy.', false,
    ['Co se stane, když přestaneš šilhat?'],
    'Pohádka – povídačka, kterou dospělí občas straší děti. Oči se po šilhání samy vrátí zpátky.'),
  fact('draci-vejce', 'Dračí vejce se líhnou jen v horké sopce.', false,
    ['Existují dračí vejce doopravdy?'],
    'Pohádka. Draci jsou z příběhů. Skutečná vejce ptáků zahřívají rodiče vlastním tělem.'),
  fact('kouzelnik-kost', 'Kouzelník umí zaklínadlem přidat člověku kost navíc.', false,
    ['Mění se počet kostí kouzlem?'],
    'Pohádka. Počet kostí se kouzlem nezmění – dospělý má asi 206 kostí.'),
  fact('drak-horecka', 'Když má drak horečku, začne se mu v žaludku vařit voda.', false,
    ['Co je doopravdy horečka?'],
    'Pohádka. Draci jsou vymyšlení. U člověka je horečka zvýšená teplota, kterou tělo bojuje s nemocí – nic se v něm nevaří.'),
  fact('zvykacka', 'Spolknutá žvýkačka zůstane v břiše sedm let.', false,
    ['Co se děje se vším, co spolkneme?'],
    'Pohádka – povídačka. Lékaři vědí, že spolknutá žvýkačka projde trávicí trubicí a za pár dní tělo opustí. Polykat ji ale není dobré.'),
  fact('modra-krev', 'V žilách teče modrá krev.', false,
    ['Jakou barvu má krev z malé ranky?'],
    'Pohádka – povídačka. Krev je vždycky červená, v žilách jen tmavší. Žíly vypadají namodrale, protože se na ně díváme přes kůži.'),
  fact('kocka-zivoty', 'Kočka má devět životů.', false,
    ['Kolik životů má každé zvíře?'],
    'Pohádka – je to jen rčení. Kočky jsou mrštné a často dopadnou na nohy, ale život mají jeden.'),
  fact('rybka-pamet', 'Zlatá rybka si pamatuje jen tři vteřiny.', false,
    ['Vědci s rybkami dělali pokusy.'],
    'Pohádka. Vědci naučili zlaté rybky stisknout páčku, aby dostaly jídlo, a rybky si to pamatovaly aspoň tři měsíce.'),
];

export const faktPohadka = bankSkill({
  id: ID,
  name: 'Fakt, nebo pohádka?',
  description: 'Rozvíjí kritické myšlení: dítě odlišuje pravdivá tvrzení o těle od pohádek a povídaček a přemýšlí, jak to víme.',
  rvp: {
    1: ['ČJL-3-3-03', 'ČJS-3-5-01'],
    2: ['ČJL-3-3-03', 'ČJS-3-5-01'],
    3: ['ČJL-3-3-03', 'ČJS-3-5-01'],
  },
  ability: 'usuzovani',
  banks: { 1: L1, 2: L2, 3: L3 },
});
