// Kostra a svaly – kosti a jejich ochranná úloha, klouby, svaly, které jen
// táhnou, a proč kostem a svalům prospívá pohyb a vápník. Vysvětlení je
// zajímavost: nejdřív odpověď s důvodem, pak navazující detail.

import { bankSkill, q, type Spec } from './common';

const ID = 'telo.kostra';

// ---------------------------------------------------------------------------
// L2 – kostra drží a chrání, klouby, svaly hýbou kostmi

const L2: Spec[] = [
  q('lebka-chrani', 'Co chrání mozek?', 'Lebka',
    ['Žebra', 'Páteř', 'Pánev'],
    ['Chrání mozek jako přilba.'],
    'Lebka je pevná kostra hlavy a chrání mozek jako přilba. Skládá se z 22 kostí a všechny kromě dolní čelisti jsou pevně spojené.'),
  q('lebka-jmeno', 'Jak se jmenuje kostra hlavy?', 'Lebka',
    ['Pánev', 'Páteř', 'Čéška'],
    ['Je tvrdá a kulatá jako přilba.'],
    'Kostře hlavy říkáme lebka a uvnitř je schovaný mozek. Miminko má mezi kostmi lebky ještě měkká místa, aby hlava mohla růst.'),
  q('zebra-chrani', 'Co chrání srdce a plíce?', 'Žebra',
    ['Lebka', 'Čéška', 'Stehenní kost'],
    ['Tvoří v hrudníku ochranný koš.'],
    'Žebra tvoří kolem srdce a plic ochranný koš – hrudní koš. Většina lidí má dvanáct párů žeber.'),
  q('pater', 'Jak se jmenuje sloupec kostí v zádech, který nás drží zpříma?', 'Páteř',
    ['Lebka', 'Žebro', 'Čelist'],
    ['Nahmatáš ji vzadu uprostřed zad.'],
    'Páteř je v zádech, drží tělo zpříma a skládá se z mnoha malých kostí – obratlů. Uvnitř ní vede mícha, kterou páteř chrání.'),
  q('kloub', 'Jak se jmenuje místo, kde se dvě kosti pohyblivě spojují?', 'Kloub',
    ['Sval', 'Šlacha', 'Nehet'],
    ['Takové místo je třeba v koleni.'],
    'Kloub je místo, kde se kosti spojují tak, že se mohou pohybovat – třeba koleno nebo loket. Kloubů máme v těle stovky.'),
  q('ktery-kloub', 'Která z těchto částí těla je kloub?', 'Koleno',
    ['Nos', 'Ucho', 'Žaludek'],
    ['Kloub se umí ohnout.'],
    'Koleno je kloub, který spojuje kosti nohy a umožňuje nohu ohnout. Je to největší kloub v těle.'),
  q('loket', 'Jak se jmenuje kloub uprostřed ruky?', 'Loket',
    ['Koleno', 'Kotník', 'Rameno'],
    ['Ohneš ho, když si dáváš lžíci do pusy.'],
    'Loket je kloub uprostřed ruky, díky kterému ruku ohneš. Ohýbá se jen jedním směrem, jako dveře na pantech.'),
  q('koleno', 'Jak se jmenuje kloub uprostřed nohy?', 'Koleno',
    ['Loket', 'Zápěstí', 'Rameno'],
    ['Ohneš ho, když si sedáš.'],
    'Koleno je kloub uprostřed nohy a ohýbá se, když si sedáš, klečíš nebo skáčeš. Vpředu ho chrání malá kost – čéška.'),
  q('zapesti', 'Který kloub spojuje ruku s předloktím?', 'Zápěstí',
    ['Koleno', 'Kotník', 'Kyčel'],
    ['Nosí se na něm hodinky.'],
    'Zápěstí spojuje ruku s předloktím a díky němu můžeš ruku natočit a ohnout. Je v něm osm malých kůstek.'),
  q('kotnik', 'Který kloub spojuje nohu s chodidlem?', 'Kotník',
    ['Loket', 'Zápěstí', 'Rameno'],
    ['Je těsně nad chodidlem.'],
    'Kotník spojuje nohu s chodidlem a pomáhá nám chodit a skákat. Nahmatáš ho jako dva hrbolky – zevnitř i zvenku nohy.'),
  q('rameno', 'Který kloub spojuje ruku s tělem?', 'Rameno',
    ['Koleno', 'Kotník', 'Zápěstí'],
    ['Nosíš na něm batoh.'],
    'Rameno spojuje ruku s tělem a můžeš v něm rukou kroužit na všechny strany. Je to nejpohyblivější kloub v těle.'),
  q('hybe-kostmi', 'Co hýbe kostmi?', 'Svaly',
    ['Vlasy', 'Nehty', 'Slzy'],
    ['Jsou ke kostem připojené a umějí se stáhnout.'],
    'Kostmi hýbou svaly, které jsou ke kostem připojené a táhnou za ně. Svalů máme přes šest set.'),
  q('vyssi', 'Proč jsi každý rok o kousek vyšší?', 'Kosti rostou.',
    ['Natahuje se kůže.', 'Rostou vlasy.', 'Boty se zmenšují.'],
    ['Co je uvnitř nohou a drží tělo?'],
    'Když rosteš, rostou i kosti, hlavně v nohou a v páteři, a proto jsi každý rok o kousek vyšší. Kost roste do délky u svých konců, v růstových chrupavkách.'),
  q('kost-hoji', 'Může se zlomená kost zahojit?', 'Ano, kost je živá a sroste.',
    ['Ne, zlomená kost se nikdy nespraví.', 'Ano, ale jen u dospělých.', 'Jen když se na ni přilepí náplast.'],
    ['Kosti v těle rostou – jsou živé.'],
    'Kosti jsou živé. Když se zlomí, lékař je srovná a znehybní a kost za několik týdnů sroste.'),
  q('sadra', 'Proč dávají lékaři na zlomenou ruku sádru?', 'Aby kost zůstala v klidu a dobře srostla.',
    ['Aby ruka nebyla vidět.', 'Aby byla ruka těžší.', 'Aby ruka rychleji rostla.'],
    ['Zlomená kost se nesmí hýbat.'],
    'Sádra drží zlomenou kost v klidu a ve správné poloze, aby mohla dobře srůst. Dětem kosti srůstají rychleji než dospělým.'),
  q('jazyk-bez-kosti', 'Která z těchto částí těla nemá uvnitř žádnou kost?', 'Jazyk',
    ['Prst', 'Paže', 'Stehno'],
    ['Je to v puse a je to velmi ohebné.'],
    'Jazyk nemá kost – je z velké části ze svalů. Proto je tak ohebný.'),
  q('silne-kosti', 'Co potřebují kosti, aby byly silné?', 'Pohyb a jídlo s vápníkem',
    ['Hodně bonbonů', 'Celý den sedět', 'Sladké limonády'],
    ['Vápník je třeba v mléce.'],
    'Kostem prospívá pohyb a jídlo s vápníkem – mléko, jogurt, sýr nebo mák. Nejvíc si kosti vápníku uloží v dětství a v dospívání.'),
  q('ceska', 'Kde najdeš čéšku?', 'Na koleni',
    ['Na lokti', 'Na hlavě', 'Na zádech'],
    ['Je to malá kost na noze.'],
    'Čéška je malá kost vpředu na koleni a chrání kolenní kloub. Miminka ji mají ještě z měkké chrupavky.'),
  q('srdce-sval', 'Který sval pracuje pořád, i když spíš?', 'Srdce',
    ['Biceps', 'Sval na lýtku', 'Sval v prstu'],
    ['Tluče ve dne i v noci.'],
    'Srdce je sval, který pracuje celý život – ve dne i v noci. Odpočívá jen na chvilku mezi dvěma údery.'),
  q('usmev', 'Co pracuje, když se usměješ?', 'Svaly v obličeji',
    ['Kosti v noze', 'Nehty', 'Vlasy'],
    ['Něco musí zatáhnout koutky úst nahoru.'],
    'Úsměv dělají svaly v obličeji, které táhnou koutky úst nahoru. V obličeji máme desítky drobných svalů, a proto umíme tolik výrazů.'),
  q('vzprimene', 'Co drží tělo vzpřímené?', 'Kostra a svaly',
    ['Vlasy', 'Oblečení', 'Nehty'],
    ['Co je uvnitř těla pevné?'],
    'Tělo drží kostra a svaly. Kostra je jako lešení a svaly ji udrží ve správné poloze.'),
  q('kosti-jake', 'Jaké jsou kosti?', 'Tvrdé a pevné',
    ['Měkké jako vata', 'Průhledné jako sklo', 'Tekuté jako voda'],
    ['Nahmatej si kost na lokti nebo na koleni.'],
    'Kosti jsou tvrdé a pevné, a přesto trochu pružné. Obsahují hodně vápníku.'),
  q('kostra-co', 'Čemu říkáme kostra?', 'Všem kostem v těle dohromady',
    ['Jen lebce', 'Svalům', 'Kůži'],
    ['Patří do ní lebka, páteř i žebra.'],
    'Kostra jsou všechny kosti v těle dohromady – drží tělo a chrání orgány. Dospělý jich má asi 206.'),
  q('prsty', 'Proč můžeš ohýbat prsty?', 'Mají klouby.',
    ['Jsou z gumy.', 'Nemají kosti.', 'Jsou měkké jako vata.'],
    ['V prstech jsou malé kosti.'],
    'V každém prstu jsou malé kosti spojené klouby, a proto prsty ohneš. Palec má dva články a ostatní prsty tři.'),
  q('kostra-chrani', 'Co ještě dělá kostra kromě toho, že drží tělo?', 'Chrání orgány.',
    ['Tráví jídlo.', 'Vyrábí slzy.', 'Dýchá.'],
    ['Vzpomeň si na lebku a žebra.'],
    'Kostra chrání orgány: lebka mozek, žebra srdce a plíce a páteř míchu. A uvnitř kostí se v kostní dřeni dokonce vyrábí krev.'),
];

// ---------------------------------------------------------------------------
// L3 – počty a rekordy kostí, svaly jen táhnou, dvojice svalů

const L3: Spec[] = [
  q('kolik-kosti', 'Kolik kostí má dospělý člověk?', 'Asi 206',
    ['Asi 20', 'Asi 1000', 'Asi 60'],
    ['Kostí je víc než sto.', 'Je jich méně než tisíc.'],
    'Dospělý člověk má asi 206 kostí. Největší je stehenní kost, nejmenší je v uchu.'),
  q('miminko-kosti', 'Má miminko víc, nebo méně kostí než dospělý?', 'Víc – některé kosti později srostou.',
    ['Méně – kosti mu teprve narostou.', 'Úplně stejně.', 'Miminko nemá žádné kosti.'],
    ['Některé kosti jsou u miminka ještě rozdělené na několik částí.'],
    'Miminko má víc kostí, protože některé jsou zatím rozdělené na několik částí. Postupně srostou, a tak má dospělý kostí méně – asi 206.'),
  q('nejdelsi', 'Která kost je nejdelší?', 'Stehenní kost',
    ['Žebro', 'Kost v prstu', 'Třmínek'],
    ['Je v noze.'],
    'Nejdelší kost v těle je stehenní kost, v noze mezi kyčlí a kolenem. Měří asi čtvrtinu výšky člověka.'),
  q('nejmensi-kde', 'Kde je nejmenší kost v těle?', 'V uchu',
    ['V noze', 'V břiše', 'V palci'],
    ['Pomáhá nám slyšet.'],
    'Nejmenší kost, třmínek, je v uchu a pomáhá nám slyšet. Je menší než zrnko rýže.'),
  q('nejmensi-jmeno', 'Jak se jmenuje nejmenší kost v těle?', 'Třmínek',
    ['Stehenní kost', 'Lebka', 'Žebro'],
    ['Je schovaná v uchu.'],
    'Třmínek je v uchu a je menší než zrnko rýže. Spolu s kladívkem a kovadlinkou přenáší zvuk.'),
  q('nejvetsi-kloub', 'Který kloub je v těle největší?', 'Koleno',
    ['Loket', 'Zápěstí', 'Kloub v prstu'],
    ['Je na noze.'],
    'Největší kloub v těle je koleno a nese velkou část váhy těla. Při doskoku na něj působí i několikanásobek této váhy.'),
  q('sval-prace', 'Co dělá sval, když pracuje?', 'Stáhne se a zatáhne za kost.',
    ['Zatlačí do kosti.', 'Zmizí.', 'Nafoukne se vzduchem.'],
    ['Sval se umí zkrátit.'],
    'Sval se umí jen stáhnout a zkrátit, a tím zatáhne za kost. Ke kosti je připojený pevnou šlachou.'),
  q('sval-tlacit', 'Umí sval tlačit?', 'Ne, sval umí jen táhnout.',
    ['Ano, sval umí jen tlačit.', 'Ano, tlačí i táhne.', 'Sval nedělá nic.'],
    ['Co se stane, když se sval stáhne?'],
    'Svaly umějí jen táhnout. Proto pracují ve dvojicích – jeden ohýbá a druhý narovnává.'),
  q('dvojice', 'Proč svaly pracují ve dvojicích?', 'Jeden ohýbá a druhý narovnává.',
    ['Aby se nenudily.', 'Jeden je vždycky náhradní.', 'Aby bylo tělo těžší.'],
    ['Sval umí jen táhnout. Jak se pak ruka zase narovná?'],
    'Protože sval umí jen táhnout, potřebuje parťáka: jeden sval kloub ohne, druhý ho zase narovná. Takhle spolupracují třeba biceps a triceps v paži.'),
  q('biceps', 'Který sval ohýbá ruku v lokti?', 'Biceps',
    ['Triceps', 'Srdce', 'Bránice'],
    ['Je na přední straně paže.'],
    'Biceps je na přední straně paže, a když se stáhne, ohne ruku v lokti. Když ruku ohneš, nahmatáš, jak biceps ztvrdne.'),
  q('triceps', 'Který sval narovnává ruku v lokti?', 'Triceps',
    ['Biceps', 'Srdce', 'Bránice'],
    ['Je na zadní straně paže.'],
    'Triceps je na zadní straně paže, a když se stáhne, ruku v lokti narovná. Pracuje třeba při kliku, když se odtlačuješ od země.'),
  q('obratle', 'Z čeho se skládá páteř?', 'Z obratlů',
    ['Ze žeber', 'Ze zubů', 'Z nehtů'],
    ['Jsou to malé kosti naskládané na sobě.'],
    'Páteř se skládá z mnoha obratlů, které leží na sobě jako věž z kostek. Jen v krku je jich sedm.'),
  q('pater-ohyb', 'Proč se můžeš předklonit a ohnout záda?', 'Páteř je z mnoha obratlů.',
    ['Páteř je z jedné rovné kosti.', 'Záda nemají kosti.', 'Páteř je z gumy.'],
    ['Z kolika kostí je páteř?'],
    'Páteř není jedna kost, ale řada obratlů. Každý se pohne jen kousek, ale dohromady se páteř ohne hodně.'),
  q('svaly-kolik', 'Kolik svalů má člověk?', 'Víc než 600',
    ['Asi 10', 'Přesně 206', 'Jen 2'],
    ['Je jich víc než kostí.'],
    'Člověk má víc než 600 svalů, kostí jen asi 206. Nejmenší sval je v uchu a hýbe nejmenší kostí – třmínkem.'),
  q('ucho-chrupavka', 'Proč se dá ucho ohnout?', 'Je z chrupavky, ne z kosti.',
    ['Je z gumy.', 'Je z měkké kosti.', 'Uvnitř je jen vzduch.'],
    ['Ze stejné hmoty je i špička nosu.'],
    'Ucho i špička nosu jsou z chrupavky, která je pevná, ale ohebná. Proto se ucho po ohnutí zase narovná.'),
  q('srdce-vule', 'Srdce je sval. Můžeš ho ovládat, jak chceš?', 'Ne, pracuje samo.',
    ['Ano, můžu ho zastavit, kdy chci.', 'Ano, zrychlím ho mrknutím.', 'Ne, protože srdce není sval.'],
    ['Myslíš na srdce, když spíš?'],
    'Srdce pracuje samo, i když na něj nemyslíš. Svaly na rukou a nohou naopak ovládáme vůlí.'),
  q('vule', 'Kterými svaly můžeš pohnout, kdy chceš?', 'Svaly na rukou a nohou',
    ['Srdeční sval', 'Svaly v žaludku', 'Svaly ve střevech'],
    ['Zkus teď zvednout ruku.'],
    'Svaly na rukou a nohou ovládáme vůlí. Srdce, žaludek a střeva pracují samy.'),
  q('vapnik', 'Díky čemu jsou kosti tvrdé?', 'Díky vápníku',
    ['Díky cukru', 'Díky tuku', 'Díky vzduchu'],
    ['Najdeš ho třeba v mléce.'],
    'Kosti obsahují hodně vápníku a dalších minerálů, a proto jsou tvrdé a pevné. Je v nich uložená skoro všechna zásoba vápníku v těle.'),
  q('stehenni-kde', 'Kde je stehenní kost?', 'V noze nad kolenem',
    ['V noze pod kolenem', 'V paži', 'V hrudníku'],
    ['Stehno je horní část nohy.'],
    'Stehenní kost je v noze mezi kyčlí a kolenem. Je to nejdelší a zároveň nejpevnější kost v těle.'),
  q('ceska-co', 'Co je čéška?', 'Malá kost vpředu na koleni',
    ['Kloub v lokti', 'Sval na lýtku', 'Kost v uchu'],
    ['Nahmatáš ji, když si sáhneš na koleno.'],
    'Čéška je malá plochá kost vpředu na koleni a chrání kolenní kloub. Pomáhá také svalům stehna narovnávat nohu.'),
  q('hrudni-kost', 'Kde je hrudní kost?', 'Uprostřed hrudníku',
    ['V noze', 'V hlavě', 'V zádech'],
    ['Připojují se k ní žebra.'],
    'Hrudní kost je uprostřed hrudníku a připojují se k ní žebra. Spojuje je ohebná chrupavka, a proto hrudník při dýchání pruží.'),
  q('palec', 'Kolik článků má palec na ruce?', 'Dva',
    ['Jeden', 'Tři', 'Pět'],
    ['Podívej se na svou ruku a ohni palec.'],
    'Palec má dva články a ostatní prsty tři – podívej se na své ruce. Palec navíc stojí proti ostatním prstům, a tak jím umíme věci pevně uchopit.'),
  q('jazyk-sval', 'Z čeho je hlavně jazyk?', 'Ze svalů',
    ['Z kosti', 'Z chrupavky', 'Z tuku'],
    ['Jazyk se umí hýbat do všech stran.'],
    'Jazyk je z velké části ze svalů, proto je tak pohyblivý. Pomáhá nám mluvit, polykat a ochutnávat.'),
  q('kosti-zive', 'Jsou kosti živé?', 'Ano, rostou a umějí se zahojit.',
    ['Ne, jsou jako kameny.', 'Jen u zvířat.', 'Jen v zimě.'],
    ['Co se děje s kostmi, když rosteš?'],
    'Kosti jsou živé: mají cévy i nervy, rostou a po zlomení se umějí zahojit. Celý život se v nich stará kostní hmota mění na novou.'),
  q('protahnout', 'Proč je dobré se po dlouhém sezení protáhnout?', 'Svaly a klouby potřebují pohyb.',
    ['Aby rostly vlasy.', 'Aby se kosti zmenšily.', 'Protahování škodí.'],
    ['Jak se cítíš po hodině bez hnutí?'],
    'Svaly a klouby mají rády pohyb. Po dlouhém sezení se protáhni, projdi nebo si zaskákej.'),
];

// ---------------------------------------------------------------------------
// L4 – šlachy, chrupavky, druhy kloubů, stavba páteře a lebky

const L4: Spec[] = [
  q('slacha', 'Co spojuje sval s kostí?', 'Šlacha',
    ['Nerv', 'Céva', 'Nehet'],
    ['Je to pevný „provaz“.'],
    'Šlacha je pevný provaz, který připojuje sval ke kosti – když se sval stáhne, šlacha zatáhne za kost. Šlachy uvidíš třeba na hřbetu ruky, když hýbeš prsty.'),
  q('achillova', 'Jak se jmenuje silná šlacha nad patou?', 'Achillova šlacha',
    ['Biceps', 'Čéška', 'Bránice'],
    ['Je pojmenovaná po hrdinovi ze starých řeckých bájí.'],
    'Achillova šlacha spojuje lýtkový sval s patní kostí a je to nejsilnější šlacha v těle. Jmenuje se po řeckém hrdinovi Achillovi, kterého podle báje šlo zranit jen do paty.'),
  q('chrupavka', 'Co je chrupavka?', 'Pevná, ale ohebná tkáň – třeba v uchu',
    ['Tvrdá kost v lebce', 'Sval, který pumpuje krev', 'Tekutina v kloubu'],
    ['Ohni si ucho.'],
    'Chrupavka je pevná, ale ohebná. Najdeš ji v uchu, ve špičce nosu a na koncích kostí v kloubech.'),
  q('kloubni-chrupavka', 'Proč mají kosti v kloubech na koncích chrupavku?', 'Aby po sobě hladce klouzaly.',
    ['Aby byly delší.', 'Aby kloub nešel ohnout.', 'Aby byly barevné.'],
    ['Chrupavka je hladká a pružná.'],
    'Hladká chrupavka na koncích kostí a kloubní tekutina pomáhají, aby se kosti v kloubu pohybovaly lehce a neodíraly se. Klouzají po sobě dokonce lépe než led po ledu.'),
  q('celist', 'Která kost lebky se může hýbat?', 'Dolní čelist',
    ['Čelní kost', 'Temenní kost', 'Nosní kost'],
    ['Pohneš s ní, když mluvíš nebo jíš.'],
    'Dolní čelist se hýbe v čelistním kloubu. Kosti, které chrání mozek, jsou naopak pevně spojené.'),
  q('zvykani', 'Který kloub nám umožňuje žvýkat?', 'Čelistní kloub',
    ['Kolenní kloub', 'Ramenní kloub', 'Kyčelní kloub'],
    ['Je kousek před uchem.'],
    'Čelistní kloub je kousek před uchem, a když žvýkáš, můžeš si ho tam nahmatat. Žvýkací svaly patří na svou velikost k nejsilnějším v těle.'),
  q('micha', 'Co chrání páteř?', 'Míchu',
    ['Žaludek', 'Srdce', 'Oči'],
    ['Vede zprávy mezi mozkem a tělem.'],
    'Uvnitř páteře vede mícha. Obratle ji chrání jako pevný tunel.'),
  q('polovina', 'Kde je víc než polovina všech kostí v těle?', 'V rukou a chodidlech',
    ['V hlavě', 'V hrudníku', 'V páteři'],
    ['Tyto části těla umějí velmi jemné pohyby.'],
    'Jen v rukou a chodidlech je víc než polovina všech kostí těla. Proto s nimi umíme tak jemné pohyby.'),
  q('krcni-obratle', 'Kolik krčních obratlů má člověk?', 'Sedm',
    ['Dva', 'Dvacet', 'Sto'],
    ['Stejně jich má i žirafa.'],
    'Člověk má sedm krčních obratlů. Žirafa jich má taky sedm – jen jsou mnohem delší.'),
  q('zebra-pary', 'Kolik párů žeber má většina lidí?', 'Dvanáct',
    ['Pět', 'Třicet', 'Tři'],
    ['Je jich víc než deset.', 'Je to stejné číslo jako počet měsíců v roce.'],
    'Většina lidí má 12 párů žeber, tedy 24 žeber, a tvoří hrudní koš. Někomu ale roste o žebro víc nebo míň.'),
  q('hrudni-kos', 'Jak se jmenuje kostěný koš kolem srdce a plic?', 'Hrudní koš',
    ['Pánev', 'Lebka', 'Páteř'],
    ['Tvoří ho žebra.'],
    'Hrudní koš tvoří žebra, hrudní kost a část páteře a chrání srdce a plíce. Při nádechu se žebra zvednou a koš se rozšíří.'),
  q('panev', 'Jak se jmenují kosti, ke kterým se připojují nohy a které nesou páteř?', 'Pánev',
    ['Lebka', 'Hrudní koš', 'Lopatky'],
    ['Je to velká kostěná mísa dole v trupu.'],
    'Pánev je velká kostěná mísa dole v trupu, připojují se k ní nohy a nese páteř. Jmenuje se stejně jako kuchyňská pánev – obě připomínají mísu.'),
  q('lopatky', 'Kde máš lopatky?', 'Nahoře na zádech',
    ['Na kolenou', 'V hlavě', 'Na chodidlech'],
    ['Připojují se k nim paže.'],
    'Lopatky jsou ploché kosti nahoře na zádech a připojují se k nim paže. Jméno mají podle tvaru – připomínají malou lopatu.'),
  q('pazni-kost', 'Jak se jmenuje kost v paži?', 'Pažní kost',
    ['Stehenní kost', 'Hrudní kost', 'Čelní kost'],
    ['Jmenuje se podle části ruky, ve které je.'],
    'V paži je pažní kost, která vede od ramene k lokti. V předloktí pod loktem jsou kosti dvě – loketní a vřetenní.'),
  q('kycel', 'Který kloub spojuje nohu s pánví?', 'Kyčelní kloub',
    ['Loketní kloub', 'Ramenní kloub', 'Čelistní kloub'],
    ['Je nahoře u stehna.'],
    'Kyčelní kloub spojuje stehenní kost s pánví. Díky němu můžeš zvednout nohu dopředu, dozadu i do strany.'),
  q('mlynek', 'Ve kterém kloubu můžeš rukou kroužit jako mlýnek?', 'V rameni',
    ['V lokti', 'V koleni', 'V prstu'],
    ['Je to kloub, kde se ruka připojuje k tělu.'],
    'Rameno je kulovitý kloub – hlavice kosti sedí v jamce jako kulička. Proto v něm můžeš rukou kroužit.'),
  q('panty', 'Jak se ohýbá loket nebo koleno?', 'Hlavně jedním směrem, jako dveře na pantech',
    ['Na všechny strany jako mlýnek', 'Vůbec se neohýbají', 'Dokola jako kolotoč'],
    ['Zkus ohnout loket různými směry.'],
    'Loket i koleno se ohýbají hlavně jedním směrem, podobně jako se otvírají dveře na pantech. Proto třeba koleno dopředu neohneš.'),
  q('plotenky', 'Co je mezi obratli, aby páteř pružila?', 'Meziobratlové ploténky',
    ['Zuby', 'Nehty', 'Vlasy'],
    ['Jsou pružné jako polštářky.'],
    'Mezi obratli jsou pružné ploténky, které tlumí nárazy, když skáčeš nebo běháš. Přes den se trochu stlačí, a proto jsi večer o kousek menší než ráno.'),
  q('rano-vyssi', 'Proč jsi ráno o trochu vyšší než večer?', 'Ploténky v páteři se v noci zase roztáhnou.',
    ['Ráno máš na nohou jiné boty.', 'Večer se kosti zmenšují.', 'Ráno máš delší vlasy.'],
    ['Přes den tě tlačí váha těla, v noci ležíš.'],
    'Přes den se ploténky mezi obratli trochu stlačí a v noci vleže se zase roztáhnou, a proto jsi ráno o kousek vyšší. Rozdíl bývá kolem jednoho centimetru.'),
  q('pater-tvar', 'Jaký tvar má páteř, když se na ni podíváš z boku?', 'Je prohnutá jako dvojité písmeno S',
    ['Je úplně rovná jako tyč', 'Je kulatá jako kruh', 'Má tvar písmene V'],
    ['Není úplně rovná.'],
    'Z boku je páteř prohnutá do tvaru dvojitého písmene S. Díky tomu pruží a tlumí nárazy.'),
  q('nejvetsi-sval', 'Kde je největší sval v těle?', 'Na zadečku',
    ['Na malíčku', 'V uchu', 'Na čele'],
    ['Sedíš na něm.'],
    'Největší sval je velký hýžďový sval. Pomáhá nám vstát, chodit do schodů a běhat.'),
  q('tres', 'Proč se třeseme zimou?', 'Svaly se chvějí a vyrábějí teplo.',
    ['Kosti o sebe cvakají.', 'Tělo se tak ochlazuje.', 'Kůže se zmenšuje.'],
    ['Při práci svalů vzniká teplo.'],
    'Když je nám zima, svaly se rychle chvějí. Při té práci vzniká teplo, které nás zahřeje.'),
  q('rozcvicka', 'Proč se před sportem rozcvičujeme?', 'Zahřáté svaly a klouby jsou připravené na pohyb.',
    ['Aby nás sport víc bolel.', 'Aby se svaly zmenšily.', 'Rozcvička je jen pro zábavu.'],
    ['Co se stane se svaly, když se hýbou?'],
    'Rozcvička zahřeje svaly a připraví klouby na pohyb. Tělo pak lépe zvládne námahu.'),
  q('hojeni', 'Jak dlouho se obvykle hojí zlomená kost?', 'Několik týdnů',
    ['Jednu minutu', 'Jeden den', 'Sto let'],
    ['Sádra se nosí docela dlouho.'],
    'Zlomená kost se obvykle hojí několik týdnů, a proto se sádra nosí tak dlouho. Nová kost přitom přeroste místo zlomu jako most.'),
  q('rust-konec', 'Do kdy rostou kosti do délky?', 'Zhruba do konce dospívání',
    ['Jen do prvních narozenin', 'Jen do pěti let', 'Celý život bez přestání'],
    ['Dospělí už nerostou.'],
    'Kosti rostou do délky zhruba do konce dospívání, pak už člověk do výšky neroste. Lékař to pozná na rentgenu podle růstových chrupavek u konců kostí.'),
];

// ---------------------------------------------------------------------------
// L5 – proč kostem a svalům prospívá pohyb, vápník a spánek; druhy svalů

const L5: Spec[] = [
  q('pohyb-kosti', 'Proč kostem prospívá běhání a skákání?', 'Kosti se zatěžováním zpevňují.',
    ['Kosti se při skákání zmenšují.', 'Kostem pohyb škodí.', 'Kosti potřebují jen spánek.'],
    ['Co se děje se svaly, když trénuješ? S kostmi je to podobné.'],
    'Když kosti při běhu a skákání pracují, zpevňují se. Pohyb v dětství pomáhá mít pevné kosti na celý život.'),
  q('skakani', 'Který pohyb nejvíc posiluje kosti?', 'Běhání a skákání',
    ['Ležení na gauči', 'Sledování televize', 'Spaní'],
    ['Kosti posiluje, když nesou váhu těla.'],
    'Kosti nejvíc posiluje pohyb, při kterém nesou váhu těla – běhání, skákání, tanec nebo míčové hry. Plavání prospívá srdci a svalům, kosti ale posiluje méně, protože voda tělo nadnáší.'),
  q('mlecne', 'Proč jsou pro kosti dobré mléčné výrobky?', 'Obsahují vápník.',
    ['Obsahují hodně cukru.', 'Jsou studené.', 'Jsou bílé.'],
    ['Z čeho jsou kosti tvrdé?'],
    'Mléko, jogurt a sýr obsahují vápník. Z vápníku si tělo staví pevné kosti a zuby.'),
  q('mak', 'Která surovina obsahuje hodně vápníku?', 'Mák',
    ['Cukr', 'Bílá mouka', 'Máslo'],
    ['Je to maličké tmavé semínko.'],
    'Mák obsahuje hodně vápníku. Vápník najdeš také v mléce, sýru, brokolici nebo v ořeších.'),
  q('vitamin-d', 'Který vitamin pomáhá tělu využít vápník?', 'Vitamin D',
    ['Vitamin C', 'Cukr', 'Sůl'],
    ['Tělo si ho umí vyrobit na slunci.'],
    'Vitamin D pomáhá tělu dostat vápník z jídla do kostí. Tělo si ho vyrobí i v kůži na slunci.'),
  q('vitamin-d-slunce', 'Jak si tělo samo vyrobí vitamin D?', 'V kůži, když na ni svítí slunce',
    ['V žaludku ze sladkostí', 'Ve vlasech při česání', 'V kostech ve tmě'],
    ['Potřebuje k tomu světlo.'],
    'Když sluneční světlo dopadne na kůži, vyrobí si v ní tělo vitamin D. Na opalovací krém ale nezapomínej.'),
  q('trenink', 'Co se stane se svaly, když je pravidelně procvičuješ?', 'Zesílí.',
    ['Zeslábnou.', 'Zmizí.', 'Promění se v kosti.'],
    ['Proč sportovci trénují?'],
    'Svaly, které pravidelně pracují, sílí, a proto se sportovci tréninkem zlepšují. Posiluje se i srdce – je to taky sval.'),
  q('sadra-svaly', 'Co se stane se svaly, když se dlouho nehýbou, třeba noha v sádře?', 'Zeslábnou.',
    ['Zesílí.', 'Vyrostou.', 'Promění se v kost.'],
    ['Svaly potřebují práci.'],
    'Svaly, které dlouho nepracují, zeslábnou. Po sundání sádry je ale cvičením zase posílíš.'),
  q('bilkoviny', 'Z čeho si tělo staví svaly?', 'Hlavně z bílkovin',
    ['Hlavně z cukru', 'Z vody z kohoutku', 'Ze vzduchu'],
    ['Najdeš je třeba ve vejcích a fazolích.'],
    'Svaly se staví hlavně z bílkovin. Jsou třeba v mase, rybách, vejcích, luštěninách nebo mléčných výrobcích.'),
  q('spanek-rust', 'Proč je spánek důležitý pro růst?', 'Ve spánku se uvolňuje hodně růstového hormonu.',
    ['Ve spánku kosti přestanou růst.', 'Spánek s růstem nesouvisí.', 'Ve spánku se kosti zkracují.'],
    ['Říká se, že děti rostou ve spánku.'],
    'Hodně růstového hormonu se uvolňuje v hlubokém spánku. Proto děti, které rostou, potřebují spát dost.'),
  q('rustove-chrupavky', 'Díky čemu rostou dlouhé kosti do délky?', 'Díky růstovým chrupavkám u konců kostí',
    ['Díky nehtům', 'Díky vlasům', 'Díky kůži'],
    ['Je to pružná tkáň u konců kostí.'],
    'U konců dlouhých kostí jsou růstové chrupavky, ve kterých kost roste do délky, dokud člověk nedospěje. Na rentgenu jsou vidět jako tenké tmavé proužky.'),
  q('houbovita', 'Proč nejsou kosti moc těžké, i když jsou pevné?', 'Uvnitř mají houbovitou kost s dutinkami.',
    ['Jsou uvnitř úplně prázdné.', 'Jsou nafouknuté vzduchem jako balon.', 'Jsou z chrupavky.'],
    ['Kost uvnitř není celá plná.'],
    'Kosti mají pevný povrch, ale uvnitř je houbovitá kost s mnoha dutinkami. Díky tomu jsou pevné a přitom nejsou moc těžké.'),
  q('kostni-dren', 'Co vzniká v červené kostní dřeni?', 'Krvinky',
    ['Sliny', 'Žluč', 'Vlasy'],
    ['Najdeš je v krvi.'],
    'Uvnitř některých kostí je červená kostní dřeň a vznikají v ní krvinky. Každou vteřinu jich vzniknou miliony.'),
  q('druhy-svalu', 'Jaké druhy svalů máme?', 'Kosterní, hladké a srdeční',
    ['Jen kosterní', 'Tvrdé, měkké a kostěné', 'Horní, dolní a prostřední'],
    ['Jeden druh tvoří srdce.'],
    'Kosterní svaly hýbou kostmi a ovládáme je vůlí. Hladké svaly jsou ve stěnách orgánů a srdeční sval tvoří srdce.'),
  q('hladke', 'Kde najdeš hladké svaly?', 'Ve stěnách orgánů, třeba žaludku a střev',
    ['Jen v prstech', 'V nehtech', 'Ve vlasech'],
    ['Tyto svaly pracují samy, bez přemýšlení.'],
    'Hladké svaly jsou ve stěnách žaludku, střev nebo cév a pracují samy, bez našeho přemýšlení. Díky nim se jídlo posouvá střevy, i když spíme.'),
  q('kosterni', 'Jak se jmenují svaly připojené ke kostem, které ovládáme vůlí?', 'Kosterní svaly',
    ['Hladké svaly', 'Srdeční sval', 'Chrupavky'],
    ['Jméno napovídá, k čemu jsou připojené.'],
    'Kosterní svaly jsou připojené ke kostem šlachami. Ovládáme je vůlí – třeba když se rozhodneš skočit.'),
  q('sedeni', 'Proč je dobré sedět rovně?', 'Páteř tak není zbytečně namáhaná.',
    ['Aby rostly vlasy.', 'Aby se lépe slyšelo.', 'Aby kosti zmizely.'],
    ['Co drží záda zpříma?'],
    'Když sedíš rovně s oporou zad, páteř a svaly na zádech se tolik nenamáhají. Pomáhají také časté přestávky.'),
  q('tablet', 'Na co myslet, když se díváš dlouho do tabletu?', 'Sedět rovně a dělat přestávky',
    ['Sklonit hlavu co nejníž', 'Nehýbat se několik hodin'],
    ['Co se namáhá, když se dlouho díváš dolů?'],
    'Při dlouhém koukání dolů do tabletu se namáhá krk a záda, a proto pomáhá rovné sezení a přestávky s protažením. Hlava je těžká, a čím víc ji skloníš, tím víc musí krk pracovat.'),
  q('aktovka', 'Jak správně nosit školní aktovku?', 'Na obou ramenou',
    ['Na jednom rameni', 'Na hlavě'],
    ['Váha by se měla rozložit rovnoměrně.'],
    'Aktovku nos na obou ramenou – váha se rozloží a páteř se nekřiví na jednu stranu. Těžké věci patří do aktovky nejblíž k zádům.'),
  q('zvedani', 'Jak správně zvednout těžší věc ze země?', 'Pokrčit kolena a zvedat s rovnými zády.',
    ['Ohnout se v zádech a prudce škubnout.', 'Zvedat s nataženýma nohama a kulatými zády.', 'Zvedat co nejrychleji jednou rukou.'],
    ['Silné svaly máme v nohou.'],
    'Těžší věc zvedáme z podřepu s rovnými zády – pracují silné svaly nohou a záda se nepřetíží. Moc těžké věci nech dospělým.'),
  q('zlomenina', 'Co je zlomenina?', 'Prasklá nebo zlomená kost',
    ['Natažený sval', 'Odřená kůže', 'Vymknutý kotník'],
    ['Týká se to kosti.'],
    'Zlomenina znamená, že kost praskla nebo se zlomila, a lékař ji uvidí na rentgenu. Dětské kosti se často jen nalomí, podobně jako mladá zelená větvička.'),
  q('rentgen', 'Jak lékař pozná, že je kost zlomená?', 'Podívá se na rentgenový snímek.',
    ['Poslechne si kost.', 'Ochutná sádru.', 'Změří horečku.'],
    ['Existuje přístroj, který ukáže kosti uvnitř těla.'],
    'Rentgen ukáže kosti uvnitř těla a lékař na snímku uvidí, jestli je kost zlomená. Paprsky objevil v roce 1895 Wilhelm Röntgen – po něm se jmenují.'),
  q('ruka-kosti', 'Kolik kostí je v jedné ruce i se zápěstím?', '27',
    ['5', '12', '100'],
    ['Jen v prstech je jich 14.'],
    'Jedna ruka i se zápěstím má 27 kostí: 8 v zápěstí, 5 v dlani a 14 v prstech.'),
  q('chodidlo-kosti', 'Kolik kostí je v jednom chodidle?', '26',
    ['3', '10', '60'],
    ['Je jich skoro stejně jako v ruce.'],
    'Jedno chodidlo má 26 kostí. Spolu s klouby a šlachami dělají z nohy pružnou oporu.'),
  q('klouby-pohyb', 'Proč je pohyb dobrý i pro klouby?', 'Kloubní chrupavka díky němu dostává výživu.',
    ['Klouby se pohybem zmenšují.', 'Klouby pohyb vůbec nepotřebují.', 'Pohybem se klouby mění v kosti.'],
    ['Chrupavka nemá vlastní cévy.'],
    'Chrupavka v kloubech nemá vlastní cévy. Výživu dostává z kloubní tekutiny a pohyb jí v tom pomáhá.'),
];

export const kostra = bankSkill({
  id: ID,
  name: 'Kostra a svaly',
  description: 'Učí, jak kostra drží a chrání tělo, jak svaly a klouby umožňují pohyb a co kostem a svalům prospívá.',
  rvp: {
    2: ['ČJS-3-5-01'],
    3: ['ČJS-3-5-01'],
    4: ['ČJS-5-5-01'],
    5: ['ČJS-5-5-01'],
  },
  ability: 'znalosti',
  testLike: 'vedomosti',
  showFact: true,
  banks: { 2: L2, 3: L3, 4: L4, 5: L5 },
});
