// K čemu slouží orgány – práce orgánů, orgánové soustavy a jejich spolupráce.
// Vysvětlení je zajímavost: nejdřív odpověď s důvodem, pak navazující detail.

import { bankSkill, path, q, type ChoiceQ, type Spec } from './common';

const ID = 'telo.organy';

// ---------------------------------------------------------------------------
// L2 – srdce, plíce, žaludek, mozek

const L2: Spec[] = [
  q('srdce-prace', 'Co dělá srdce?', 'Pumpuje krev do celého těla.',
    ['Tráví jídlo.', 'Dýchá vzduch.', 'Přemýšlí a pamatuje si věci.', 'Vyrábí slzy.'],
    ['Srdce je silný sval v hrudníku.', 'Přemýšlej, co proudí v cévách po celém těle.'],
    'Srdce je silný sval, který pumpuje krev do celého těla, a krev roznáší kyslík a živiny. Za den srdce udeří zhruba stotisíckrát.'),
  q('plice-k-cemu', 'K čemu máme plíce?', 'K dýchání',
    ['K trávení jídla', 'K pumpování krve', 'K přemýšlení', 'K chůzi'],
    ['Plíce jsou v hrudníku a při nádechu se naplní.'],
    'Plícemi dýcháme: při nádechu se naplní vzduchem a kyslík z něj přejde do krve. Uvnitř jsou měkké jako houba, plné drobných váčků se vzduchem.'),
  q('jidlo-kam', 'Kam doputuje jídlo, když ho spolkneš?', 'Do žaludku',
    ['Do plic', 'Do srdce', 'Do mozku'],
    ['Je to orgán v břiše.', 'Je to takový vak na jídlo.'],
    'Spolknuté jídlo jde jícnem do žaludku a tam se mísí s trávicími šťávami. Jícnem projde za pár vteřin, v žaludku ale zůstane několik hodin.'),
  q('ridi-telo', 'Který orgán řídí celé tělo?', 'Mozek',
    ['Žaludek', 'Plíce', 'Srdce'],
    ['Je schovaný v hlavě.'],
    'Mozek řídí celé tělo – posílá povely svalům a dostává zprávy od očí, uší i kůže. Zprávy mu nosí nervy, které vedou do každého kousku těla.'),
  q('cim-premyslis', 'Čím přemýšlíš?', 'Mozkem',
    ['Žaludkem', 'Srdcem', 'Plícemi'],
    ['Je to v hlavě.'],
    'Přemýšlíme mozkem, který si také pamatuje a učí se nové věci. Jsou v něm desítky miliard nervových buněk – víc, než je lidí na celé Zemi.'),
  q('zavod', 'Který orgán ti bije rychleji, když závodíš?', 'Srdce',
    ['Žaludek', 'Mozek', 'Ledviny'],
    ['Můžeš ho nahmatat na hrudníku.'],
    'Při běhu srdce bije rychleji, aby svaly dostaly víc krve s kyslíkem. Po závodě se za pár minut zase zklidní – můžeš si to změřit na zápěstí.'),
  q('traveni-kde', 'Ve kterém z těchto orgánů se tráví jídlo?', 'V žaludku',
    ['V plicích', 'V srdci', 'V mozku'],
    ['Tento orgán je v břiše.'],
    'V žaludku se jídlo mísí s trávicími šťávami a rozkládá se, pak trávení pokračuje ve střevech. Začíná ale už v puse, kde jídlo rozkoušeme a promícháme se slinami.'),
  q('plice-pocet', 'Kolik plic má člověk?', 'Dvě',
    ['Jednu', 'Tři', 'Pět'],
    ['Jsou po obou stranách srdce.'],
    'Člověk má dvě plíce – pravou a levou. Levá je o trochu menší, protože vedle ní je srdce.'),
  q('srdce-kde', 'Kde je srdce?', 'V hrudníku',
    ['V hlavě', 'V noze', 'V břiše'],
    ['Chrání ho žebra.'],
    'Srdce je v hrudníku mezi plícemi, trochu vlevo, a chrání ho žebra. Tlukot, který slyšíme, dělají chlopně, když se v srdci zavírají.'),
  q('vdech', 'Co vdechujeme do plic?', 'Vzduch',
    ['Vodu', 'Jídlo', 'Krev'],
    ['Dělá se to nosem nebo pusou.'],
    'Do plic vdechujeme vzduch a v něm kyslík, který tělo potřebuje. Kyslík tvoří asi pětinu vzduchu – zbytek je hlavně dusík.'),
  q('srdce-z-ceho', 'Z čeho je hlavně srdce?', 'Ze svalu',
    ['Z kosti', 'Z vlasů', 'Z chrupavky'],
    ['Srdce se pořád stahuje a zase povoluje.'],
    'Srdce je sval, který se pořád stahuje a povoluje, a tím pumpuje krev. Na rozdíl od svalů na rukou ho neovládáme vůlí – pracuje samo.'),
  q('srdce-spanek', 'Tluče srdce i ve spánku?', 'Ano, tluče pořád.',
    ['Ne, v noci se zastaví.', 'Jen když se nám něco zdá.', 'Jen když chrápeme.'],
    ['Tělo potřebuje krev i v noci.'],
    'Srdce tluče pořád – ve dne i v noci, celý život. Ve spánku jen trochu pomaleji.'),
  q('nadech-hrudnik', 'Proč se ti při nádechu zvedne hrudník?', 'Plíce se naplní vzduchem.',
    ['Srdce se nafoukne.', 'Žaludek se naplní jídlem.', 'Kosti se prodlouží.'],
    ['Co se při nádechu děje se vzduchem?'],
    'Při nádechu se plíce naplní vzduchem a zvětší se, a proto se hrudník zvedne. Plíce přitom roztahují dýchací svaly, hlavně bránice pod nimi.'),
  q('zaludek-prace', 'Co dělá žaludek s jídlem?', 'Míchá ho s trávicími šťávami.',
    ['Posílá ho do plic.', 'Mění ho na kosti.', 'Vyfoukne ho nosem.'],
    ['Žaludek je jako vak, který se hýbe.'],
    'Žaludek jídlo promíchá s trávicími šťávami, až z něj vznikne kaše, a ta pak pokračuje do střev. Prázdný žaludek je malý, ale po jídle se umí hodně roztáhnout.'),
  q('basnicka', 'Který orgán ti pomáhá zapamatovat si básničku?', 'Mozek',
    ['Žaludek', 'Srdce', 'Plíce'],
    ['Je v hlavě.'],
    'Básničku si pamatuješ díky mozku. Když ji opakuješ, posilují se v něm spojení mezi nervovými buňkami – a ve spánku si ji mozek ještě upevní.'),
  // Distraktor „začne bít pomaleji“ vyřazen: při úleku se srdce na chvilku
  // opravdu může zpomalit, takže by nebyl jasně chybný.
  q('lek', 'Co udělá srdce, když se lekneš?', 'Začne bít rychleji.',
    ['Zastaví se.', 'Přesune se do břicha.', 'Zmenší se na polovinu.'],
    ['Vzpomeň si, jak ti buší, když se něčeho lekneš.'],
    'Když se lekneš, tělo se připraví utíkat nebo se bránit, a srdce proto bije rychleji. Pomáhá mu v tom adrenalin – látka, kterou tělo při leknutí rychle vyrobí.'),
  q('vzduch-kudy', 'Kudy jde vzduch do plic?', 'Nosem nebo pusou',
    ['Ušima', 'Očima', 'Pupíkem'],
    ['Zkus se zhluboka nadechnout. Kudy vzduch vchází?'],
    'Vzduch vdechujeme nosem nebo pusou. Nos ho navíc ohřeje, zvlhčí a chloupky v něm zachytí prach.'),
  q('mozek-kde', 'Kde je mozek?', 'V hlavě',
    ['V břiše', 'V hrudníku', 'V noze'],
    ['Chrání ho lebka.'],
    'Mozek je v hlavě a chrání ho pevná lebka. U dospělého váží asi 1,4 kilogramu.'),
  q('prilba', 'Proč nosíme na kole přilbu?', 'Chrání hlavu a mozek.',
    ['Aby kolo jelo rychleji.', 'Aby nám nerostly vlasy.', 'Aby nás nikdo nepoznal.'],
    ['Který orgán je schovaný v hlavě?'],
    'Přilba chrání hlavu při pádu, a tím i mozek, který řídí celé tělo. Pěnová vrstva uvnitř se při nárazu zmáčkne a pohltí velkou část rány.'),
  q('krev-kam', 'Kam pumpuje srdce krev?', 'Do celého těla',
    ['Jen do nohou', 'Jen do hlavy', 'Jen do žaludku'],
    ['Krev potřebuje každá část těla.'],
    'Srdce pumpuje krev do celého těla – od hlavy až po prsty u nohou. Krev tělo oběhne a vrátí se do srdce zhruba za minutu.'),
  q('nos-dychani', 'Proč je dobré dýchat nosem?', 'Nos vzduch ohřeje a očistí.',
    ['Nos vzduch obarví.', 'Nos vzduch promění ve vodu.', 'Nos vzduch zmenší.'],
    ['V nose jsou chloupky a je tam vlhko.'],
    'V nose se vzduch ohřeje a zvlhčí a chloupky zachytí prach. Do plic pak jde čistší a teplejší vzduch.'),
  q('mozek-spanek', 'Co dělá mozek, když spíš?', 'Pracuje dál – řídí třeba dýchání.',
    ['Úplně se vypne jako lampička.', 'Zmenší se na polovinu.', 'Přestane řídit tělo.'],
    ['Dýcháš, i když spíš. Kdo to řídí?'],
    'Mozek pracuje i ve spánku: řídí dýchání a ukládá si, co ses přes den {naučila|naučil}. Proto si po dobrém spánku pamatuješ víc.'),
  q('organy-co-jsou', 'Čemu říkáme orgány?', 'Částem těla, které mají svou práci',
    ['Jen vlasům a nehtům', 'Jen kostem v nohou', 'Jen oblečení a botám'],
    ['Srdce, plíce i žaludek mají v těle každý svou práci.'],
    'Orgány jsou části těla, které mají svou práci: srdce pumpuje krev, plíce dýchají a žaludek tráví. Největší orgán máme navrchu – je to kůže.'),
  q('zaludek-kde', 'Kde je žaludek?', 'V břiše',
    ['V hlavě', 'V krku', 'V noze'],
    ['Jídlo tam putuje z pusy dolů.'],
    'Žaludek je nahoře v břiše, pod plícemi, víc vlevo. Když se najíš, jídlo v něm zůstane obvykle několik hodin.'),
  q('dech-beh', 'Co se stane s dechem, když rychle běžíš?', 'Dýcháš rychleji.',
    ['Přestaneš dýchat.', 'Dýcháš pomaleji.', 'Dýcháš ušima.'],
    ['Vzpomeň si na honičku na hřišti.'],
    'Při běhu potřebují svaly víc kyslíku, a proto dýcháš rychleji a srdce bije rychleji. Po chvíli odpočinku se dech zase zklidní.'),
];

// ---------------------------------------------------------------------------
// L3 – játra, ledviny, střeva, kůže; svaly a kosti

const L3: Spec[] = [
  q('ledviny-prace', 'Co dělají ledviny?', 'Čistí krev a vyrábějí moč.',
    ['Pumpují krev.', 'Vyrábějí sliny.', 'Ukládají vzpomínky.'],
    ['Ledviny jsou dvě a mají tvar fazole.', 'Souvisí to s chozením na záchod.'],
    'Ledviny čistí krev – odpadní látky, které tělo nepotřebuje, odvedou s vodou jako moč. Za den celou krev přečistí mnohokrát dokola.'),
  q('ledviny-pocet', 'Kolik ledvin má většina lidí?', 'Dvě',
    ['Jednu', 'Čtyři', 'Deset'],
    ['Jsou po obou stranách páteře.'],
    'Většina lidí má dvě ledviny, vzadu v břiše po obou stranách páteře. Zdravě se ale dá žít i s jedinou.'),
  q('moc-kde-ceka', 'Kde se v těle hromadí moč, než jdeme na záchod?', 'V močovém měchýři',
    ['V žaludku', 'V plicích', 'V srdci'],
    ['Je to orgán úplně dole v břiše.'],
    'Moč teče z ledvin do močového měchýře. Když se měchýř naplní a roztáhne, pošle mozku zprávu – a chce se nám na záchod.'),
  q('moc-kde-vznika', 'Kde v těle vzniká moč?', 'V ledvinách',
    ['V močovém měchýři', 'V žaludku', 'V plicích'],
    ['Moč vzniká tam, kde se čistí krev.'],
    'Moč vzniká v ledvinách, do močového měchýře jen stéká a čeká tam. Vede ji tam dvojice tenkých trubiček – močovodů.'),
  q('jatra-nejvetsi', 'Který z těchto vnitřních orgánů je největší?', 'Játra',
    ['Srdce', 'Ledviny', 'Žaludek'],
    ['Je nahoře v břiše, pod plícemi.'],
    'Játra jsou největší vnitřní orgán. U dospělého váží asi jeden a půl kilogramu.'),
  q('jatra-prace', 'Co dělají játra?', 'Zpracovávají živiny a zbavují krev škodlivých látek.',
    ['Pumpují krev do těla.', 'Vyrábějí moč.', 'Posílají zprávy svalům.'],
    ['Jsou jako chemická továrna těla.'],
    'Játra zpracovávají živiny z jídla, ukládají zásoby, zbavují krev škodlivých látek a vyrábějí žluč. Když se jejich kus ztratí, umějí zase dorůst.'),
  q('jatra-kde', 'Kde jsou játra?', 'Nahoře v břiše, pod plícemi',
    ['V hlavě', 'V noze', 'V krku'],
    ['Patří k trávení.'],
    'Játra jsou nahoře v břiše, hlavně na pravé straně, hned pod plícemi. Spodní žebra je tak zčásti chrání.'),
  q('ledviny-kde', 'Kde jsou ledviny?', 'Vzadu v břiše, po stranách páteře',
    ['V hlavě', 'V chodidlech', 'V krku'],
    ['Jsou blízko zad.'],
    'Ledviny jsou vzadu v břiše po obou stranách páteře, zhruba ve výšce pasu. Pravá je o kousek níž, protože nad ní jsou velká játra.'),
  q('tenke-strevo', 'Co se děje s jídlem v tenkém střevě?', 'Živiny z něj přecházejí do krve.',
    ['Mění se na vzduch.', 'Vrací se zpátky do pusy.', 'Mění se na kosti.'],
    ['Tělo potřebuje z jídla dostat to užitečné.'],
    'V tenkém střevě se jídlo dotráví a živiny přejdou do krve, která je roznese po těle. Stěna střeva je pokrytá drobnými výběžky, a proto má obrovskou plochu.'),
  q('strevo-delsi', 'Které střevo je delší?', 'Tenké střevo',
    ['Tlusté střevo', 'Obě jsou stejně dlouhá'],
    ['Pozor, jméno může mást!'],
    'Tenké střevo měří několik metrů, tlusté je kratší, ale širší. Jména tedy mluví o šířce, ne o délce.'),
  q('tluste-strevo', 'Co dělá hlavně tlusté střevo?', 'Vstřebává ze zbytků jídla vodu.',
    ['Pumpuje krev.', 'Vyrábí žluč.', 'Dýchá.'],
    ['Zbytky jídla v něm postupně houstnou.'],
    'Tlusté střevo vstřebává ze zbytků jídla vodu, a co tělo nepotřebuje, odchází na záchodě. Žijí v něm i miliardy užitečných bakterií.'),
  q('zaludek-dal', 'Kam pokračuje jídlo ze žaludku?', 'Do střev',
    ['Do plic', 'Do ledvin', 'Do srdce'],
    ['Jsou dlouhá a stočená v břiše.'],
    'Ze žaludku jde natrávené jídlo do tenkého střeva a pak do tlustého. Žaludek ho tam pouští postupně, po malých dávkách.'),
  q('kuze-nejvetsi', 'Který orgán je největší ze všech?', 'Kůže',
    ['Játra', 'Srdce', 'Žaludek'],
    ['Pokrývá celé tělo.'],
    'Největší orgán je kůže – pokrývá celé tělo a chrání ho. U dospělého má plochu asi jako velká plážová osuška.'),
  q('kuze-k-cemu', 'K čemu je kůže?', 'Chrání tělo a cítí dotek.',
    ['Pumpuje krev.', 'Tráví jídlo.', 'Vyrábí moč.'],
    ['Pokrývá celé tělo jako obal.'],
    'Kůže chrání tělo před špínou, bacily i sluncem a cítíme jí dotek, teplo, chlad i bolest. Její svrchní vrstva se pořád obnovuje – drobné šupinky kůže nám odpadávají každý den.'),
  q('pot', 'Proč se v horku potíme?', 'Pot na kůži tělo ochlazuje.',
    ['Pot tělo zahřívá.', 'Aby nám rychleji rostly vlasy.', 'Aby se nám lépe dýchalo.'],
    ['Co se děje s vodou, která se odpařuje?'],
    'Když se pot na kůži odpařuje, ochlazuje tělo, a proto se potíme v horku a při sportu. Potních žláz máme v kůži miliony.'),
  q('husi-kuze', 'Co se může stát s kůží, když je ti zima?', 'Naskočí husí kůže.',
    ['Zezelená.', 'Začne svítit.', 'Zmizí z ní chloupky.'],
    ['Podívej se na ruce, když vylezeš z bazénu.'],
    'Když je nám zima, chloupky na kůži se napřímí a naskočí husí kůže. Zvířatům s hustou srstí to pomáhá zahřát se, nám už jen trochu.'),
  q('kuze-vitamin', 'Co si umí kůže vyrobit, když na ni svítí slunce?', 'Vitamin D',
    ['Vitamin C', 'Cukr', 'Kyslík'],
    ['Tento vitamin potřebují kosti.'],
    'Na slunci si kůže vyrobí vitamin D, který pomáhá, aby byly kosti pevné. Opalovací krém ale nevynechávej!'),
  q('nehty-vlasy', 'Z čeho jsou nehty a vlasy?', 'Z rohoviny',
    ['Z kosti', 'Ze svalu', 'Z chrupavky'],
    ['Ze stejné látky mají zvířata kopyta.'],
    'Nehty i vlasy jsou z rohoviny, stejně jako kopyta nebo rohy zvířat. Stříhání nebolí, protože v odstřižené části nejsou nervy.'),
  q('kosti-svaly', 'Čím se liší kosti a svaly?', 'Kosti tělo drží, svaly jím hýbou.',
    ['Kosti jsou měkké, svaly tvrdé.', 'Svaly tělo drží, kosti jím hýbou.', 'Kosti a svaly jsou úplně stejné.'],
    ['Co je tvrdé a co se umí stáhnout?'],
    'Kosti tvoří pevnou kostru, která tělo drží, a svaly jsou ke kostem připojené a táhnou za ně, takže se hýbeme. Svalů máme přes šest set.'),
  q('bez-kosti', 'Co by se stalo, kdybychom neměli kosti?', 'Tělo by nemělo oporu.',
    ['Běhali bychom rychleji.', 'Byli bychom vyšší.', 'Nic, kosti nejsou potřeba.'],
    ['Kostra je jako lešení domu.'],
    'Kostra je opora těla – bez ní bychom se neudrželi vzpřímeně a orgány by nebyly chráněné. Třeba chobotnice kosti nemá, a proto proleze i úzkou škvírou.'),
  q('hybe-kostmi', 'Co pohybuje kostmi?', 'Svaly',
    ['Kůže', 'Nehty', 'Krev'],
    ['Umějí se stáhnout a zatáhnout.'],
    'Kostmi hýbou svaly: když se sval stáhne, zatáhne za kost a část těla se pohne. Tlačit sval neumí – umí jen táhnout.'),
  q('srdce-nikdy', 'Který orgán je sval, který pracuje celý život bez přestávky?', 'Srdce',
    ['Žaludek', 'Mozek', 'Játra'],
    ['Tluče ve dne i v noci.'],
    'Srdce je sval, který pracuje celý život bez dlouhé pauzy. Odpočívá jen na chvilku mezi dvěma údery.'),
  q('tep-kde', 'Kde si můžeš nahmatat tep?', 'Na zápěstí nebo na krku',
    ['Na nehtu', 'Na vlasech', 'Na špičce nosu'],
    ['Tep je cítit tam, kde je céva blízko pod kůží.'],
    'Tep nahmatáš na vnitřní straně zápěstí nebo na krku – cítíš, jak srdce posílá krev do tepen. Měř ho prsty, ne palcem: palec má vlastní tep.'),
  q('jicen', 'Jak se jmenuje trubice, která vede jídlo z pusy do žaludku?', 'Jícen',
    ['Průdušnice', 'Močovod', 'Tepna'],
    ['Polykáš jím každé sousto.'],
    'Jícen vede jídlo z krku do žaludku a vedle něj vede průdušnice vzduch do plic. Když polykáš, zakryje průdušnici malá chlopeň, aby jídlo nezaskočilo.'),
  q('prudusnice', 'Kudy jde vzduch z krku do plic?', 'Průdušnicí',
    ['Jícnem', 'Žaludkem', 'Míchou'],
    ['Je to trubice vedle jícnu.'],
    'Vzduch jde z krku průdušnicí, která se v hrudníku rozvětví do obou plic. Otevřenou ji drží kroužky z chrupavky.'),
  q('krev-nese', 'Co roznáší krev po těle?', 'Kyslík a živiny',
    ['Kosti', 'Vlasy', 'Myšlenky'],
    ['Tělo to dostává z dechu a z jídla.'],
    'Krev roznáší po těle kyslík z plic a živiny ze střev a odpad odnáší třeba k ledvinám. Dospělý má krve asi pět litrů.'),
];

// ---------------------------------------------------------------------------
// L4 – orgánové soustavy a jejich spolupráce

const SOUSTAVY = [
  'Oběhová soustava',
  'Dýchací soustava',
  'Trávicí soustava',
  'Opěrná soustava',
  'Pohybová soustava',
  'Nervová soustava',
  'Vylučovací soustava',
] as const;

type Soustava = (typeof SOUSTAVY)[number];

/** Opěrná a pohybová soustava se v některých učebnicích spojují
 *  („opěrná a pohybová soustava“), a proto nejsou navzájem distraktory. */
const PARTNER: Partial<Record<Soustava, Soustava>> = {
  'Opěrná soustava': 'Pohybová soustava',
  'Pohybová soustava': 'Opěrná soustava',
};

function sys(key: string, prompt: string, correct: Soustava, hints: string[], explain: string): ChoiceQ {
  return q(key, prompt, correct, SOUSTAVY.filter((s) => s !== correct && s !== PARTNER[correct]), hints, explain);
}

const L4: Spec[] = [
  sys('patri-srdce', 'Do které soustavy patří srdce a cévy?', 'Oběhová soustava',
    ['Srdce a cévy dopravují krev.'],
    'Srdce, cévy a krev tvoří oběhovou soustavu, která rozvádí krev po celém těle. Kdyby se všechny cévy jednoho člověka natáhly za sebe, měřily by tisíce kilometrů.'),
  sys('patri-plice', 'Do které soustavy patří plíce?', 'Dýchací soustava',
    ['Plícemi se dýchá.'],
    'Plíce patří do dýchací soustavy spolu s nosem, hrtanem a průdušnicí. V hrtanu jsou hlasivky, takže nám dýchací soustava pomáhá i mluvit.'),
  sys('patri-zaludek', 'Do které soustavy patří žaludek a střeva?', 'Trávicí soustava',
    ['Zpracovávají jídlo.'],
    'Žaludek, střeva, jícen i játra patří do trávicí soustavy, která zpracovává jídlo. Trávicí trubice od pusy dál měří u dospělého několik metrů.'),
  sys('patri-kosti', 'Do které soustavy patří kosti?', 'Opěrná soustava',
    ['Kosti tělo drží, jsou mu oporou.'],
    'Kosti tvoří kostru – opěrnou soustavu, která drží tělo a chrání orgány. Dospělý člověk má asi 206 kostí.'),
  sys('patri-svaly', 'Do které soustavy patří svaly, kterými hýbeme rukama a nohama?', 'Pohybová soustava',
    ['Díky těmto svalům se hýbeme.'],
    'Svaly tvoří pohybovou soustavu: táhnou za kosti, a tak se hýbeme. Svalů máme přes šest set.'),
  sys('patri-mozek', 'Do které soustavy patří mozek, mícha a nervy?', 'Nervová soustava',
    ['Po nervech běží zprávy.'],
    'Mozek, mícha a nervy tvoří nervovou soustavu, která řídí celé tělo. Mícha vede páteří jako kabel mezi mozkem a tělem.'),
  sys('patri-ledviny', 'Do které soustavy patří ledviny a močový měchýř?', 'Vylučovací soustava',
    ['Tyto orgány odvádějí z těla moč.'],
    'Ledviny a močový měchýř patří do vylučovací soustavy, která odvádí z těla odpadní látky. Něco odpadu ale odchází i potem a při výdechu.'),
  sys('patri-jatra', 'Do které soustavy patří játra?', 'Trávicí soustava',
    ['Játra vyrábějí žluč, která pomáhá zpracovat jídlo.'],
    'Játra patří do trávicí soustavy – vyrábějí žluč, která pomáhá trávit tuky. Jsou to největší vnitřní orgán.'),
  sys('soustava-kyslik', 'Která soustava přivádí do těla kyslík?', 'Dýchací soustava',
    ['Kyslík je ve vzduchu.'],
    'Dýchací soustava přivádí do plic vzduch s kyslíkem a odvádí oxid uhličitý. Kyslík pak krev roznese do celého těla.'),
  sys('soustava-krev', 'Která soustava rozvádí krev po celém těle?', 'Oběhová soustava',
    ['Krev koluje dokola – obíhá.'],
    'Oběhová soustava rozvádí krev: srdce ji pumpuje a cévy ji vedou do celého těla. Celé kolečko krev oběhne zhruba za minutu.'),
  sys('soustava-ridi', 'Která soustava řídí celé tělo?', 'Nervová soustava',
    ['Patří do ní mozek.'],
    'Nervová soustava řídí celé tělo: mozek posílá po nervech povely a dostává zprávy od smyslů. Nejrychlejší zprávy běží po nervech rychleji, než jede auto po dálnici.'),
  sys('soustava-jidlo', 'Která soustava zpracovává jídlo?', 'Trávicí soustava',
    ['Patří do ní žaludek.'],
    'Trávicí soustava rozloží jídlo na živiny, které tělo využije. Trávení začíná už v puse, kde se jídlo potká se slinami.'),
  sys('soustava-opora', 'Která soustava drží tělo a chrání orgány?', 'Opěrná soustava',
    ['Tvoří ji kosti.'],
    'Opěrná soustava je kostra: drží tělo a chrání orgány, třeba lebka mozek. Nejdelší kost je stehenní kost.'),
  sys('soustava-pohyb', 'Která soustava táhne za kosti, abychom mohli běhat a skákat?', 'Pohybová soustava',
    ['Umí se stáhnout a zase povolit.'],
    'Pohybová soustava jsou svaly, které táhnou za kosti, a tak můžeme běhat a skákat. Největší sval máme na zadečku.'),
  sys('soustava-odpad', 'Která soustava odvádí z těla odpadní látky v moči?', 'Vylučovací soustava',
    ['Patří do ní ledviny.'],
    'Vylučovací soustava – ledviny a močový měchýř – odvádí z těla odpad v moči. Ledviny přitom celou krev přečistí mnohokrát za den.'),
  sys('soustava-uloha', 'Která soustava nejvíc pracuje, když přemýšlíš nad úlohou?', 'Nervová soustava',
    ['Přemýšlí se v hlavě.'],
    'Když přemýšlíš, pracuje hlavně mozek – řídicí centrum nervové soustavy. Spotřebuje aspoň pětinu energie celého těla.'),
  q('beh-soustavy', 'Při běhu potřebují svaly víc kyslíku. Které dvě soustavy musí pracovat rychleji?', 'Dýchací a oběhová',
    ['Trávicí a vylučovací', 'Opěrná a trávicí', 'Vylučovací a opěrná'],
    ['Kyslík se musí dostat do těla a pak ke svalům.'],
    'Dýchací soustava přivede víc kyslíku do plic a oběhová soustava ho krví rychleji dopraví ke svalům. Proto se při běhu zadýcháš a srdce ti buší.'),
  q('zvednout-ruku', 'Chceš zvednout ruku. Co pošle svalům povel?', 'Mozek po nervech',
    ['Žaludek po střevech', 'Srdce po kostech', 'Ledviny po žilách'],
    ['Povely putují po nervech.'],
    'Mozek pošle po nervech zprávu svalům, ty se stáhnou a zvednou kosti ruky. Pravou ruku přitom řídí levá polovina mozku a levou ruku pravá.'),
  q('ziviny-cesta', 'Jak se živiny z jídla dostanou do celého těla?', 'Ze střev přejdou do krve a krev je roznese.',
    ['Ze žaludku jdou rovnou do kostí.', 'Vydechneme je plícemi.', 'Zůstanou navždy v žaludku.'],
    ['Spolupracuje trávicí a oběhová soustava.'],
    'Trávicí soustava jídlo rozloží a ve střevech předá živiny krvi. Oběhová soustava je pak roznese po těle.'),
  q('hrudni-kos', 'Které orgány chrání hrudní koš?', 'Srdce a plíce',
    ['Střeva a močový měchýř', 'Mozek a oči', 'Kolena a lokty'],
    ['Hrudní koš tvoří žebra.'],
    'Žebra, hrudní kost a páteř tvoří hrudní koš, který chrání srdce a plíce. Není to pevná klec – při nádechu se žebra zvedají.'),
  q('micha', 'K čemu slouží mícha?', 'Vede zprávy mezi mozkem a tělem.',
    ['Pumpuje krev.', 'Tráví jídlo.', 'Vyrábí moč.'],
    ['Je schovaná v páteři.'],
    'Mícha je schovaná v páteři a vede zprávy z mozku do těla a z těla do mozku. Některé bleskové reakce, třeba ucuknutí od horkého, řídí dokonce sama.'),
  q('srdce-a-svaly', 'Co mají společného srdce a svaly na noze?', 'Obojí jsou svaly.',
    ['Obojí jsou kosti.', 'Obojí je v hlavě.', 'Obojí vyrábí moč.'],
    ['Obojí se umí stáhnout.'],
    'Srdce je taky sval. Na rozdíl od svalů na noze ho ale neovládáme vůlí – pracuje samo.'),
  q('kyslik-kam', 'Kam jde kyslík z plic?', 'Do krve',
    ['Do žaludku', 'Do kostí', 'Do močového měchýře'],
    ['Kyslík potřebuje celé tělo. Co ho roznese?'],
    'V plicích přejde kyslík do krve a krev ho roznese do celého těla. Nesou ho červené krvinky – a právě díky nim je krev červená.'),
  q('tep-sport', 'Co se stane s tepem, když sportuješ?', 'Zrychlí se.',
    ['Zpomalí se.', 'Zastaví se.', 'Nic se nestane.'],
    ['Srdce musí svalům dodat víc krve.'],
    'Při sportu srdce bije rychleji, aby svaly dostaly víc kyslíku a živin. Dětem bije srdce i v klidu rychleji než dospělým.'),
  q('kuze-organ', 'Kůže chrání tělo, pomáhá mu udržet teplotu a cítí dotek. Je kůže orgán?', 'Ano, je to největší orgán těla.',
    ['Ne, je to jen obal.', 'Ne, orgány jsou jen uvnitř těla.', 'Ano, ale je to nejmenší orgán.'],
    ['Orgán je část těla, která má svou práci.'],
    'Kůže je orgán, a dokonce ten největší – chrání, cítí i chladí. U dospělého váží několik kilogramů.'),
];

// ---------------------------------------------------------------------------
// L5 – krevní oběh, dýchání a trávení podrobněji

const L5: Spec[] = [
  q('tepny', 'Jak se jmenují cévy, které vedou krev ze srdce do těla?', 'Tepny',
    ['Žíly', 'Nervy', 'Šlachy'],
    ['Na zápěstí v nich nahmatáš tep.'],
    'Tepny vedou krev ze srdce do těla a nahmatáš v nich tep. Mají silné pružné stěny, protože krev v nich proudí pod velkým tlakem.'),
  q('zily', 'Jak se jmenují cévy, které vedou krev zpátky do srdce?', 'Žíly',
    ['Tepny', 'Průdušky', 'Močovody'],
    ['Na hřbetu ruky je někdy vidíš jako namodralé čárky.'],
    'Žíly vedou krev zpátky do srdce a na hřbetu ruky je vidíš jako namodralé čárky. Krev v nich je ale tmavě červená – modrá se jen zdá přes kůži.'),
  q('vlasecnice', 'Jak se jmenují nejtenčí cévy, ze kterých se kyslík dostane až k buňkám?', 'Vlásečnice',
    ['Tepny', 'Žíly', 'Obratle'],
    ['Jsou tenké jako vlásek.'],
    'Vlásečnice jsou tenčí než vlas a přes jejich stěnu přechází kyslík a živiny do buněk. Jsou tak úzké, že jimi krvinky projdou jen jedna za druhou.'),
  q('sklipky', 'Co se děje v plicních sklípcích?', 'Kyslík přechází do krve a oxid uhličitý z krve ven.',
    ['Jídlo se mění na kaši.', 'Vzniká tam moč.', 'Rostou tam kosti.'],
    ['Sklípky jsou malinké váčky na konci průdušek.'],
    'Plicní sklípky jsou drobné váčky obalené vlásečnicemi: kyslík z nich přechází do krve a oxid uhličitý z krve ven. V plicích jsou jich stovky milionů.'),
  q('oxid-odpad', 'Který plyn vydechujeme jako odpad?', 'Oxid uhličitý',
    ['Kyslík', 'Helium', 'Vodík'],
    ['Vzniká v buňkách, když spotřebují kyslík.'],
    'Buňky spotřebují kyslík a vzniká oxid uhličitý, který krev donese do plic a my ho vydechneme. Rostliny ho pak využijí k růstu.'),
  q('oxid-proc', 'Proč musí oxid uhličitý z těla ven?', 'Je to odpad, který by tělu škodil.',
    ['Je to vlastně kyslík.', 'Aby nám rostly vlasy.', 'Aby se nám nechtělo spát.'],
    ['Vzniká v buňkách jako zbytek.'],
    'Oxid uhličitý je odpad z buněk – kdyby se hromadil, tělu by škodil, a proto ho vydechujeme. Právě jeho přibývání v krvi nás nutí znovu se nadechnout.'),
  q('dech-proc', 'Proč se ti při běhu zrychlí dech?', 'Svaly potřebují víc kyslíku.',
    ['Plíce se zmenšily.', 'Svaly potřebují méně kyslíku.', 'Žaludek se naplnil vzduchem.'],
    ['Co svaly potřebují, aby mohly pracovat?'],
    'Pracující svaly spotřebují víc kyslíku a vyrábějí víc oxidu uhličitého. Proto dýcháš rychleji a hlouběji.'),
  q('tep-proc', 'Proč ti při běhu buší srdce rychleji?', 'Musí svalům rychleji dodávat kyslík a živiny.',
    ['Srdce je unavené a chce odpočívat.', 'Svaly potřebují méně krve.', 'Krev se změnila ve vodu.'],
    ['Kyslík z plic ke svalům dopravuje krev.'],
    'Srdce při běhu pumpuje rychleji, aby krev dopravila ke svalům víc kyslíku a živin a odnesla oxid uhličitý. Pravidelným pohybem srdce sílí.'),
  q('sliny', 'Co dělají sliny?', 'Zvlhčují sousta a začínají trávit škrob.',
    ['Bělí zuby.', 'Vyrábějí kyslík.', 'Chladí mozek.'],
    ['Zkus chvíli žvýkat kousek chleba. Začne chutnat nasládle.'],
    'Sliny zvlhčí sousto, aby se dalo spolknout. Obsahují látku, která začne trávit škrob – proto chléb po chvíli žvýkání chutná nasládle.'),
  q('traveni-zacina', 'Kde začíná trávení?', 'Už v ústech',
    ['Až v tlustém střevě', 'V plicích', 'V ledvinách'],
    ['Kde se jídlo poprvé potká se slinami?'],
    'Trávení začíná v ústech: zuby jídlo rozkoušou a sliny ho začnou trávit. Za den vyrobíme zhruba litr slin.'),
  q('cervene-krvinky', 'K čemu jsou červené krvinky?', 'Roznášejí kyslík.',
    ['Bojují s bacily.', 'Tvoří kosti.', 'Vyrábějí žluč.'],
    ['Je jich v krvi nejvíc a dávají jí barvu.'],
    'Červené krvinky roznášejí kyslík z plic do celého těla a díky nim je krev červená. V jediné kapce krve jich jsou miliony.'),
  q('bile-krvinky', 'K čemu jsou bílé krvinky?', 'Bojují s bacily.',
    ['Roznášejí kyslík.', 'Barví krev na červeno.', 'Vyrábějí sliny.'],
    ['Jsou to strážci těla.'],
    'Bílé krvinky chrání tělo – vyhledávají a ničí bakterie a viry. Když jsme nemocní, tělo jich vyrobí víc.'),
  q('desticky', 'Co pomáhá zastavit krvácení a vytvořit strup?', 'Krevní destičky',
    ['Bílé krvinky', 'Žluč', 'Sliny'],
    ['Jsou v krvi a shluknou se, když se céva poraní.'],
    'Krevní destičky se v ranách shluknou a pomáhají krev srazit, a z toho pak vznikne strup. Pod strupem se hojí nová kůže, a proto ho nestrhávej.'),
  q('srdce-dutiny', 'Srdce má uvnitř čtyři dutiny. Jak se jmenují?', 'Dvě síně a dvě komory',
    ['Čtyři žaludky', 'Dvě plíce a dvě ledviny', 'Čtyři obratle'],
    ['Dvě jsou nahoře a dvě dole.'],
    'Srdce má dvě síně a dvě komory: do síní krev přitéká a komory ji pumpují do tepen. Chlopně mezi nimi pouštějí krev jen jedním směrem a jejich klapání slyšíme jako tlukot.'),
  q('leva-plice', 'Proč je levá plíce trochu menší než pravá?', 'Vedle ní je srdce.',
    ['Protože jíme levou rukou.', 'Protože je starší.', 'Protože v ní je žaludek.'],
    ['Co leží v hrudníku trochu vlevo?'],
    'Srdce leží v hrudníku trochu vlevo, a tak mu levá plíce dělá místo a je o něco menší. Pravá plíce má tři laloky, levá jen dva.'),
  q('branice', 'Jak se jmenuje sval pod plícemi, který nám pomáhá dýchat?', 'Bránice',
    ['Biceps', 'Jazyk', 'Hýžďový sval'],
    ['Odděluje hrudník od břicha.'],
    'Bránice je plochý sval pod plícemi: když se stáhne, plíce se roztáhnou a nasají vzduch. Když se nečekaně stahuje sama od sebe, máme škytavku.'),
  q('skytavka', 'Co se děje, když máme škytavku?', 'Bránice se nečekaně stahuje.',
    ['Kosti se posouvají.', 'Žaludek se převrací.', 'Plíce se zmenšují.'],
    ['Je to sval, který nám pomáhá dýchat.'],
    'Při škytavce se bránice nečekaně stáhne a hlasivky se rychle zavřou. Tak vznikne známé „hik“.'),
  q('ziviny-kde', 'Kde se vstřebává většina živin?', 'V tenkém střevě',
    ['V tlustém střevě', 'V jícnu', 'V ústech'],
    ['Je to nejdelší část trávicí trubice.'],
    'Většina živin přejde do krve v tenkém střevě. Jeho stěna je zvrásněná a má obrovskou plochu.'),
  q('tluste-voda', 'Co ze zbytků jídla vstřebává hlavně tlusté střevo?', 'Vodu',
    ['Kyslík', 'Žluč', 'Krev'],
    ['Zbytky jídla v něm postupně houstnou.'],
    'Tlusté střevo vstřebává ze zbytků jídla vodu, a co zbude, tělo vyloučí. Žijí v něm miliardy užitečných bakterií, které tělu vyrábějí i některé vitaminy.'),
  q('zluc', 'Co dělá žluč?', 'Pomáhá trávit tuky.',
    ['Roznáší kyslík.', 'Zpevňuje kosti.', 'Chrání oči.'],
    ['Vyrábějí ji játra a posílají ji do střeva.'],
    'Žluč vyrábějí játra. Ve střevě rozbije tuky na drobné kapičky, aby se lépe strávily – podobně jako prostředek na nádobí na mastném talíři.'),
  q('zluc-kde', 'Kde se vyrábí žluč?', 'V játrech',
    ['V žaludku', 'V ledvinách', 'V srdci'],
    ['Je to největší vnitřní orgán.'],
    'Žluč vyrábějí játra. Než ji střevo potřebuje, čeká její zásoba v malém váčku – žlučníku.'),
  q('kyselina', 'Proč je v žaludku kyselá šťáva?', 'Pomáhá trávit a ničí mnoho bakterií.',
    ['Aby jídlo chutnalo sladce.', 'Aby žaludek svítil.', 'Aby se jídlo změnilo na vzduch.'],
    ['Spolu s jídlem spolkneme i drobné bacily.'],
    'Žaludeční šťáva je velmi kyselá: pomáhá rozkládat jídlo a ničí mnoho bakterií, které spolkneme. Žaludek sám sebe chrání vrstvou hlenu.'),
  q('krev-litry', 'Kolik krve má v těle dospělý člověk?', 'Asi 5 litrů',
    ['Asi půl litru', 'Asi 50 litrů', 'Asi jednu lžíci'],
    ['Je to víc než jedna láhev, ale méně než kbelík.'],
    'Dospělý má asi 5 litrů krve, děti méně, protože jsou menší – prvňák necelé dva litry.'),
  q('cesta-vzduchu', 'Kudy jde vzduch do plic?', path('nos', 'hrtan', 'průdušnice', 'průdušky', 'plíce'),
    [path('nos', 'jícen', 'žaludek', 'plíce'), path('pusa', 'průdušky', 'hrtan', 'nos'), path('nos', 'průdušnice', 'srdce', 'plíce')],
    ['Jícen vede jídlo, ne vzduch.'],
    'Vzduch jde nosem do hrtanu, pak průdušnicí a průduškami až do plic. Průdušky se v plicích větví jako koruna stromu, až do drobných sklípků.'),
  q('cesta-jidla', 'Kudy putuje jídlo?', path('ústa', 'jícen', 'žaludek', 'tenké střevo', 'tlusté střevo'),
    [path('ústa', 'průdušnice', 'plíce', 'žaludek'), path('ústa', 'žaludek', 'jícen', 'tlusté střevo', 'tenké střevo'), path('ústa', 'jícen', 'srdce', 'střevo')],
    ['Průdušnice vede vzduch, ne jídlo.', 'Tenké střevo je na řadě dřív než tlusté.'],
    'Jídlo jde z úst jícnem do žaludku, pak do tenkého střeva a nakonec do tlustého. Celá cesta trvá obvykle jeden až tři dny.'),
  q('svaly-teplo', 'Co v těle vyrábí nejvíc tepla, když sportuješ?', 'Svaly',
    ['Vlasy', 'Nehty', 'Kosti'],
    ['Co při sportu nejvíc pracuje?'],
    'Pracující svaly vyrábějí hodně tepla, a proto je ti při sportu horko a potíš se. Teplem nás svaly zahřívají i v zimě, když se třeseme.'),
  q('cervene-tvare', 'Proč máš po běhu červené tváře?', 'Ke kůži proudí víc krve, aby se tělo ochladilo.',
    ['Kůže se opálila.', 'Srdce se přesunulo do hlavy.', 'Tváře se nafoukly vzduchem.'],
    ['Tělo se při běhu zahřeje a potřebuje se zbavit tepla.'],
    'Když se tělo zahřeje, cévy v kůži se rozšíří a proudí jimi víc krve. Kůže pak teplo odevzdá do okolí.'),
  q('tep-co-je', 'Co cítíš, když na zápěstí nahmatáš tep?', 'Nárazy krve, kterou srdce posílá do tepen',
    ['Jak roste kost', 'Jak dýchají plíce', 'Jak se tráví jídlo'],
    ['Tep bije stejně rychle jako srdce.'],
    'Při každém stahu pošle srdce do tepen dávku krve a tu cítíš na zápěstí jako tep. Kolik tepů napočítáš za minutu, tolikrát srdce udeřilo.'),
];

export const organy = bankSkill({
  id: ID,
  name: 'K čemu slouží orgány',
  description: 'Rozvíjí porozumění tomu, co dělají jednotlivé orgány a orgánové soustavy a jak spolu spolupracují.',
  rvp: {
    2: ['ČJS-3-5-01'],
    3: ['ČJS-3-5-01'],
    4: ['ČJS-5-5-01'],
    5: ['ČJS-5-5-01'],
  },
  ability: 'znalosti',
  testLike: 'vedomosti',
  showFact: true,
  banks: { 2: L2, 3: L3, 4: L4, 5: L5 },
});
