// K čemu slouží orgány – práce orgánů, orgánové soustavy a jejich spolupráce.

import { bankSkill, path, q, type ChoiceQ, type Spec } from './common';

const ID = 'telo.organy';

// ---------------------------------------------------------------------------
// L2 – srdce, plíce, žaludek, mozek

const L2: Spec[] = [
  q('srdce-prace', 'Co dělá srdce?', 'Pumpuje krev do celého těla.',
    ['Tráví jídlo.', 'Dýchá vzduch.', 'Přemýšlí a pamatuje si věci.', 'Vyrábí slzy.'],
    ['Srdce je silný sval v hrudníku.', 'Přemýšlej, co proudí v cévách po celém těle.'],
    'Srdce je silný sval, který pumpuje krev do celého těla. Krev roznáší kyslík a živiny.'),
  q('plice-k-cemu', 'K čemu máme plíce?', 'K dýchání',
    ['K trávení jídla', 'K pumpování krve', 'K přemýšlení', 'K chůzi'],
    ['Plíce jsou v hrudníku a při nádechu se naplní.'],
    'Plícemi dýcháme. Při nádechu se naplní vzduchem a do krve se z nich dostane kyslík.'),
  q('jidlo-kam', 'Kam doputuje jídlo, když ho spolkneš?', 'Do žaludku',
    ['Do plic', 'Do srdce', 'Do mozku'],
    ['Je to orgán v břiše.', 'Je to takový vak na jídlo.'],
    'Spolknuté jídlo jde jícnem do žaludku. Tam se mísí s trávicími šťávami.'),
  q('ridi-telo', 'Který orgán řídí celé tělo?', 'Mozek',
    ['Žaludek', 'Plíce', 'Srdce'],
    ['Je schovaný v hlavě.'],
    'Mozek řídí celé tělo. Posílá povely svalům a dostává zprávy od očí, uší i kůže.'),
  q('cim-premyslis', 'Čím přemýšlíš?', 'Mozkem',
    ['Žaludkem', 'Srdcem', 'Plícemi'],
    ['Je to v hlavě.'],
    'Přemýšlíme mozkem. Mozek si také pamatuje a učí se nové věci.'),
  q('zavod', 'Který orgán ti bije rychleji, když závodíš?', 'Srdce',
    ['Žaludek', 'Mozek', 'Ledviny'],
    ['Můžeš ho nahmatat na hrudníku.'],
    'Při běhu srdce bije rychleji, aby svaly dostaly víc krve s kyslíkem.'),
  q('traveni-kde', 'Ve kterém z těchto orgánů se tráví jídlo?', 'V žaludku',
    ['V plicích', 'V srdci', 'V mozku'],
    ['Tento orgán je v břiše.'],
    'V žaludku se jídlo mísí s trávicími šťávami a rozkládá se. Trávení pak pokračuje ve střevech.'),
  q('plice-pocet', 'Kolik plic má člověk?', 'Dvě',
    ['Jednu', 'Tři', 'Pět'],
    ['Jsou po obou stranách srdce.'],
    'Člověk má dvě plíce – pravou a levou. Levá je o trochu menší, protože vedle ní je srdce.'),
  q('srdce-kde', 'Kde je srdce?', 'V hrudníku',
    ['V hlavě', 'V noze', 'V břiše'],
    ['Chrání ho žebra.'],
    'Srdce je v hrudníku mezi plícemi, trochu vlevo. Chrání ho žebra.'),
  q('vdech', 'Co vdechujeme do plic?', 'Vzduch',
    ['Vodu', 'Jídlo', 'Krev'],
    ['Dělá se to nosem nebo pusou.'],
    'Do plic vdechujeme vzduch. Je v něm kyslík, který tělo potřebuje.'),
  q('srdce-z-ceho', 'Z čeho je hlavně srdce?', 'Ze svalu',
    ['Z kosti', 'Z vlasů', 'Z chrupavky'],
    ['Srdce se pořád stahuje a zase povoluje.'],
    'Srdce je sval. Pořád se stahuje a povoluje, a tím pumpuje krev.'),
  q('srdce-spanek', 'Tluče srdce i ve spánku?', 'Ano, tluče pořád.',
    ['Ne, v noci se zastaví.', 'Jen když se nám něco zdá.', 'Jen když chrápeme.'],
    ['Tělo potřebuje krev i v noci.'],
    'Srdce tluče pořád – ve dne i v noci, celý život. Ve spánku jen trochu pomaleji.'),
  q('nadech-hrudnik', 'Proč se ti při nádechu zvedne hrudník?', 'Plíce se naplní vzduchem.',
    ['Srdce se nafoukne.', 'Žaludek se naplní jídlem.', 'Kosti se prodlouží.'],
    ['Co se při nádechu děje se vzduchem?'],
    'Při nádechu se plíce naplní vzduchem a zvětší se. Hrudník se proto zvedne.'),
  q('zaludek-prace', 'Co dělá žaludek s jídlem?', 'Míchá ho s trávicími šťávami.',
    ['Posílá ho do plic.', 'Mění ho na kosti.', 'Vyfoukne ho nosem.'],
    ['Žaludek je jako vak, který se hýbe.'],
    'Žaludek jídlo promíchá s trávicími šťávami, až z něj vznikne kaše. Ta pak pokračuje do střev.'),
  q('basnicka', 'Který orgán ti pomáhá zapamatovat si básničku?', 'Mozek',
    ['Žaludek', 'Srdce', 'Plíce'],
    ['Je v hlavě.'],
    'Básničku si pamatuješ díky mozku. Čím častěji ji opakuješ, tím lépe si ji mozek zapamatuje.'),
  q('lek', 'Co udělá srdce, když se lekneš?', 'Začne bít rychleji.',
    ['Zastaví se.', 'Přesune se do břicha.', 'Začne bít pomaleji.'],
    ['Vzpomeň si, jak ti buší, když se něčeho lekneš.'],
    'Když se lekneš, tělo se připraví utíkat nebo se bránit. Srdce proto bije rychleji.'),
  q('vzduch-kudy', 'Kudy jde vzduch do plic?', 'Nosem nebo pusou',
    ['Ušima', 'Očima', 'Pupíkem'],
    ['Zkus se zhluboka nadechnout. Kudy vzduch vchází?'],
    'Vzduch vdechujeme nosem nebo pusou. Nos vzduch navíc ohřeje a očistí.'),
  q('mozek-kde', 'Kde je mozek?', 'V hlavě',
    ['V břiše', 'V hrudníku', 'V noze'],
    ['Chrání ho lebka.'],
    'Mozek je v hlavě. Chrání ho pevná lebka.'),
  q('prilba', 'Proč nosíme na kole přilbu?', 'Chrání hlavu a mozek.',
    ['Aby kolo jelo rychleji.', 'Aby nám nerostly vlasy.', 'Aby nás nikdo nepoznal.'],
    ['Který orgán je schovaný v hlavě?'],
    'Přilba chrání hlavu při pádu. V hlavě je mozek, který řídí celé tělo.'),
  q('krev-kam', 'Kam pumpuje srdce krev?', 'Do celého těla',
    ['Jen do nohou', 'Jen do hlavy', 'Jen do žaludku'],
    ['Krev potřebuje každá část těla.'],
    'Srdce pumpuje krev do celého těla – od hlavy až po prsty u nohou.'),
  q('nos-dychani', 'Proč je dobré dýchat nosem?', 'Nos vzduch ohřeje a očistí.',
    ['Nos vzduch obarví.', 'Nos vzduch promění ve vodu.', 'Nos vzduch zmenší.'],
    ['V nose jsou chloupky a je tam vlhko.'],
    'V nose se vzduch ohřeje a zvlhčí a chloupky zachytí prach. Do plic pak jde čistší vzduch.'),
  q('mozek-spanek', 'Co dělá mozek, když spíš?', 'Pracuje dál – řídí třeba dýchání.',
    ['Úplně se vypne jako lampička.', 'Zmenší se na polovinu.', 'Přestane řídit tělo.'],
    ['Dýcháš, i když spíš. Kdo to řídí?'],
    'Mozek pracuje i ve spánku. Řídí dýchání a ukládá si, co ses přes den naučila.'),
  q('organy-co-jsou', 'Čemu říkáme orgány?', 'Částem těla, které mají svou práci',
    ['Jen vlasům a nehtům', 'Jen kostem v nohou', 'Jen oblečení a botám'],
    ['Srdce, plíce i žaludek mají v těle každý svou práci.'],
    'Orgány jsou části těla, které mají svou práci. Srdce pumpuje krev, plíce dýchají a žaludek tráví.'),
  q('zaludek-kde', 'Kde je žaludek?', 'V břiše',
    ['V hlavě', 'V krku', 'V noze'],
    ['Jídlo tam putuje z pusy dolů.'],
    'Žaludek je nahoře v břiše, pod plícemi.'),
  q('dech-beh', 'Co se stane s dechem, když rychle běžíš?', 'Dýcháš rychleji.',
    ['Přestaneš dýchat.', 'Dýcháš pomaleji.', 'Dýcháš ušima.'],
    ['Vzpomeň si na honičku na hřišti.'],
    'Při běhu potřebují svaly víc kyslíku. Proto dýcháš rychleji a srdce bije rychleji.'),
];

// ---------------------------------------------------------------------------
// L3 – játra, ledviny, střeva, kůže; svaly a kosti

const L3: Spec[] = [
  q('ledviny-prace', 'Co dělají ledviny?', 'Čistí krev a vyrábějí moč.',
    ['Pumpují krev.', 'Vyrábějí sliny.', 'Ukládají vzpomínky.'],
    ['Ledviny jsou dvě a mají tvar fazole.', 'Souvisí to s chozením na záchod.'],
    'Ledviny čistí krev. Odpadní látky, které tělo nepotřebuje, odvedou s vodou jako moč.'),
  q('ledviny-pocet', 'Kolik ledvin má většina lidí?', 'Dvě',
    ['Jednu', 'Čtyři', 'Deset'],
    ['Jsou po obou stranách páteře.'],
    'Většina lidí má dvě ledviny. Jsou vzadu v břiše po obou stranách páteře.'),
  q('moc-kde-ceka', 'Kde se v těle hromadí moč, než jdeme na záchod?', 'V močovém měchýři',
    ['V žaludku', 'V plicích', 'V srdci'],
    ['Je to orgán úplně dole v břiše.'],
    'Moč teče z ledvin do močového měchýře. Když je měchýř plný, chce se nám na záchod.'),
  q('moc-kde-vznika', 'Kde v těle vzniká moč?', 'V ledvinách',
    ['V močovém měchýři', 'V žaludku', 'V plicích'],
    ['Moč vzniká tam, kde se čistí krev.'],
    'Moč vzniká v ledvinách. Do močového měchýře jen stéká a čeká tam.'),
  q('jatra-nejvetsi', 'Který z těchto vnitřních orgánů je největší?', 'Játra',
    ['Srdce', 'Ledviny', 'Žaludek'],
    ['Je nahoře v břiše, pod plícemi.'],
    'Játra jsou největší vnitřní orgán. U dospělého váží asi jeden a půl kilogramu.'),
  q('jatra-prace', 'Co dělají játra?', 'Zpracovávají živiny a zbavují krev škodlivých látek.',
    ['Pumpují krev do těla.', 'Vyrábějí moč.', 'Posílají zprávy svalům.'],
    ['Jsou jako chemická továrna těla.'],
    'Játra zpracovávají živiny z jídla, ukládají zásoby a zbavují krev škodlivých látek. Vyrábějí také žluč.'),
  q('jatra-kde', 'Kde jsou játra?', 'Nahoře v břiše, pod plícemi',
    ['V hlavě', 'V noze', 'V krku'],
    ['Patří k trávení.'],
    'Játra jsou nahoře v břiše, hlavně na pravé straně, hned pod plícemi.'),
  q('ledviny-kde', 'Kde jsou ledviny?', 'Vzadu v břiše, po stranách páteře',
    ['V hlavě', 'V chodidlech', 'V krku'],
    ['Jsou blízko zad.'],
    'Ledviny jsou vzadu v břiše po obou stranách páteře, zhruba ve výšce pasu.'),
  q('tenke-strevo', 'Co se děje s jídlem v tenkém střevě?', 'Živiny z něj přecházejí do krve.',
    ['Mění se na vzduch.', 'Vrací se zpátky do pusy.', 'Mění se na kosti.'],
    ['Tělo potřebuje z jídla dostat to užitečné.'],
    'V tenkém střevě se jídlo dotráví a živiny přejdou do krve. Krev je pak roznese po celém těle.'),
  q('strevo-delsi', 'Které střevo je delší?', 'Tenké střevo',
    ['Tlusté střevo', 'Obě jsou stejně dlouhá'],
    ['Pozor, jméno může mást!'],
    'Tenké střevo je mnohem delší – měří několik metrů. Tlusté střevo je kratší, ale širší.'),
  q('tluste-strevo', 'Co dělá hlavně tlusté střevo?', 'Vstřebává ze zbytků jídla vodu.',
    ['Pumpuje krev.', 'Vyrábí žluč.', 'Dýchá.'],
    ['Zbytky jídla v něm postupně houstnou.'],
    'Tlusté střevo vstřebává ze zbytků jídla vodu. Co tělo nepotřebuje, odchází pak na záchodě.'),
  q('zaludek-dal', 'Kam pokračuje jídlo ze žaludku?', 'Do střev',
    ['Do plic', 'Do ledvin', 'Do srdce'],
    ['Jsou dlouhá a stočená v břiše.'],
    'Ze žaludku jde natrávené jídlo do tenkého střeva a pak do tlustého střeva.'),
  q('kuze-nejvetsi', 'Který orgán je největší ze všech?', 'Kůže',
    ['Játra', 'Srdce', 'Žaludek'],
    ['Pokrývá celé tělo.'],
    'Největší orgán je kůže. Pokrývá celé tělo a chrání ho.'),
  q('kuze-k-cemu', 'K čemu je kůže?', 'Chrání tělo a cítí dotek.',
    ['Pumpuje krev.', 'Tráví jídlo.', 'Vyrábí moč.'],
    ['Pokrývá celé tělo jako obal.'],
    'Kůže chrání tělo před špínou, bacily i sluncem. Cítíme jí dotek, teplo, chlad i bolest.'),
  q('pot', 'Proč se v horku potíme?', 'Pot na kůži tělo ochlazuje.',
    ['Pot tělo zahřívá.', 'Aby nám rychleji rostly vlasy.', 'Aby se nám lépe dýchalo.'],
    ['Co se děje s vodou, která se odpařuje?'],
    'Když se pot na kůži odpařuje, ochlazuje tělo. Proto se potíme v horku a při sportu.'),
  q('husi-kuze', 'Co se může stát s kůží, když je ti zima?', 'Naskočí husí kůže.',
    ['Zezelená.', 'Začne svítit.', 'Zmizí z ní chloupky.'],
    ['Podívej se na ruce, když vylezeš z bazénu.'],
    'Když je nám zima, chloupky na kůži se napřímí a naskočí husí kůže.'),
  q('kuze-vitamin', 'Co si umí kůže vyrobit, když na ni svítí slunce?', 'Vitamin D',
    ['Vitamin C', 'Cukr', 'Kyslík'],
    ['Tento vitamin potřebují kosti.'],
    'Na slunci si kůže vyrobí vitamin D, který pomáhá, aby byly kosti pevné. Opalovací krém ale nevynechávej!'),
  q('nehty-vlasy', 'Z čeho jsou nehty a vlasy?', 'Z rohoviny',
    ['Z kosti', 'Ze svalu', 'Z chrupavky'],
    ['Ze stejné látky mají zvířata kopyta.'],
    'Nehty i vlasy jsou z rohoviny. Proto nebolí, když je stříháme.'),
  q('kosti-svaly', 'Čím se liší kosti a svaly?', 'Kosti tělo drží, svaly jím hýbou.',
    ['Kosti jsou měkké, svaly tvrdé.', 'Svaly tělo drží, kosti jím hýbou.', 'Kosti a svaly jsou úplně stejné.'],
    ['Co je tvrdé a co se umí stáhnout?'],
    'Kosti tvoří pevnou kostru, která tělo drží. Svaly jsou připojené ke kostem a táhnou za ně, takže se hýbeme.'),
  q('bez-kosti', 'Co by se stalo, kdybychom neměli kosti?', 'Tělo by nemělo oporu.',
    ['Běhali bychom rychleji.', 'Byli bychom vyšší.', 'Nic, kosti nejsou potřeba.'],
    ['Kostra je jako lešení domu.'],
    'Kostra je opora těla. Bez ní bychom se neudrželi vzpřímeně a orgány by nebyly chráněné.'),
  q('hybe-kostmi', 'Co pohybuje kostmi?', 'Svaly',
    ['Kůže', 'Nehty', 'Krev'],
    ['Umějí se stáhnout a zatáhnout.'],
    'Kostmi hýbou svaly. Když se sval stáhne, zatáhne za kost a část těla se pohne.'),
  q('srdce-nikdy', 'Který orgán je sval, který pracuje celý život bez přestávky?', 'Srdce',
    ['Žaludek', 'Mozek', 'Játra'],
    ['Tluče ve dne i v noci.'],
    'Srdce je sval, který pracuje celý život. Nikdy si neudělá dlouhou pauzu.'),
  q('tep-kde', 'Kde si můžeš nahmatat tep?', 'Na zápěstí nebo na krku',
    ['Na nehtu', 'Na vlasech', 'Na špičce nosu'],
    ['Tep je cítit tam, kde je céva blízko pod kůží.'],
    'Tep nahmatáš na vnitřní straně zápěstí nebo na krku. Cítíš, jak srdce posílá krev do tepen.'),
  q('jicen', 'Jak se jmenuje trubice, která vede jídlo z pusy do žaludku?', 'Jícen',
    ['Průdušnice', 'Močovod', 'Tepna'],
    ['Polykáš jím každé sousto.'],
    'Jícen vede jídlo z krku do žaludku. Průdušnice vedle něj vede vzduch do plic.'),
  q('prudusnice', 'Kudy jde vzduch z krku do plic?', 'Průdušnicí',
    ['Jícnem', 'Žaludkem', 'Míchou'],
    ['Je to trubice vedle jícnu.'],
    'Vzduch jde z krku průdušnicí. Ta se v hrudníku rozvětví do obou plic.'),
  q('krev-nese', 'Co roznáší krev po těle?', 'Kyslík a živiny',
    ['Kosti', 'Vlasy', 'Myšlenky'],
    ['Tělo to dostává z dechu a z jídla.'],
    'Krev roznáší po těle kyslík z plic a živiny ze střev. Odnáší také odpad, třeba k ledvinám.'),
];

// ---------------------------------------------------------------------------
// L4 – orgánové soustavy a jejich spolupráce

const SOUSTAVY = [
  'Oběhová soustava',
  'Dýchací soustava',
  'Trávicí soustava',
  'Opěrná soustava',
  'Pohybová soustava',
  'Nervová soustava',
  'Vylučovací soustava',
] as const;

type Soustava = (typeof SOUSTAVY)[number];

function sys(key: string, prompt: string, correct: Soustava, hints: string[], explain: string): ChoiceQ {
  return q(key, prompt, correct, SOUSTAVY.filter((s) => s !== correct), hints, explain);
}

const L4: Spec[] = [
  sys('patri-srdce', 'Do které soustavy patří srdce a cévy?', 'Oběhová soustava',
    ['Srdce a cévy dopravují krev.'],
    'Srdce, cévy a krev tvoří oběhovou soustavu. Ta rozvádí krev po celém těle.'),
  sys('patri-plice', 'Do které soustavy patří plíce?', 'Dýchací soustava',
    ['Plícemi se dýchá.'],
    'Plíce patří do dýchací soustavy spolu s nosem, hrtanem a průdušnicí.'),
  sys('patri-zaludek', 'Do které soustavy patří žaludek a střeva?', 'Trávicí soustava',
    ['Zpracovávají jídlo.'],
    'Žaludek, střeva, jícen i játra patří do trávicí soustavy. Ta zpracovává jídlo.'),
  sys('patri-kosti', 'Do které soustavy patří kosti?', 'Opěrná soustava',
    ['Kosti tělo drží, jsou mu oporou.'],
    'Kosti tvoří kostru – opěrnou soustavu. Drží tělo a chrání orgány.'),
  sys('patri-svaly', 'Do které soustavy patří svaly, kterými hýbeme rukama a nohama?', 'Pohybová soustava',
    ['Díky těmto svalům se hýbeme.'],
    'Svaly tvoří pohybovou soustavu. Táhnou za kosti, a tak se hýbeme.'),
  sys('patri-mozek', 'Do které soustavy patří mozek, mícha a nervy?', 'Nervová soustava',
    ['Po nervech běží zprávy.'],
    'Mozek, mícha a nervy tvoří nervovou soustavu. Řídí celé tělo.'),
  sys('patri-ledviny', 'Do které soustavy patří ledviny a močový měchýř?', 'Vylučovací soustava',
    ['Tyto orgány odvádějí z těla moč.'],
    'Ledviny a močový měchýř patří do vylučovací soustavy. Ta odvádí z těla odpadní látky.'),
  sys('patri-jatra', 'Do které soustavy patří játra?', 'Trávicí soustava',
    ['Játra vyrábějí žluč, která pomáhá zpracovat jídlo.'],
    'Játra patří do trávicí soustavy. Vyrábějí žluč, která pomáhá trávit tuky.'),
  sys('soustava-kyslik', 'Která soustava přivádí do těla kyslík?', 'Dýchací soustava',
    ['Kyslík je ve vzduchu.'],
    'Dýchací soustava přivádí do plic vzduch s kyslíkem.'),
  sys('soustava-krev', 'Která soustava rozvádí krev po celém těle?', 'Oběhová soustava',
    ['Krev koluje dokola – obíhá.'],
    'Oběhová soustava rozvádí krev. Srdce ji pumpuje a cévy ji vedou do celého těla.'),
  sys('soustava-ridi', 'Která soustava řídí celé tělo?', 'Nervová soustava',
    ['Patří do ní mozek.'],
    'Nervová soustava řídí celé tělo. Mozek posílá po nervech povely a dostává zprávy od smyslů.'),
  sys('soustava-jidlo', 'Která soustava zpracovává jídlo?', 'Trávicí soustava',
    ['Patří do ní žaludek.'],
    'Trávicí soustava rozloží jídlo na živiny, které tělo využije.'),
  sys('soustava-opora', 'Která soustava drží tělo a chrání orgány?', 'Opěrná soustava',
    ['Tvoří ji kosti.'],
    'Opěrná soustava je kostra. Drží tělo a chrání orgány, třeba lebka mozek.'),
  sys('soustava-pohyb', 'Která soustava táhne za kosti, abychom mohli běhat a skákat?', 'Pohybová soustava',
    ['Umí se stáhnout a zase povolit.'],
    'Pohybová soustava jsou svaly. Táhnou za kosti, a tak můžeme běhat a skákat.'),
  sys('soustava-odpad', 'Která soustava odvádí z těla odpadní látky v moči?', 'Vylučovací soustava',
    ['Patří do ní ledviny.'],
    'Vylučovací soustava – ledviny a močový měchýř – odvádí z těla odpad v moči.'),
  sys('soustava-uloha', 'Která soustava nejvíc pracuje, když přemýšlíš nad úlohou?', 'Nervová soustava',
    ['Přemýšlí se v hlavě.'],
    'Když přemýšlíš, pracuje hlavně mozek – řídicí centrum nervové soustavy.'),
  q('beh-soustavy', 'Při běhu potřebují svaly víc kyslíku. Které dvě soustavy musí pracovat rychleji?', 'Dýchací a oběhová',
    ['Trávicí a vylučovací', 'Opěrná a trávicí', 'Vylučovací a opěrná'],
    ['Kyslík se musí dostat do těla a pak ke svalům.'],
    'Dýchací soustava přivede víc kyslíku do plic a oběhová soustava ho krví rychleji dopraví ke svalům.'),
  q('zvednout-ruku', 'Chceš zvednout ruku. Co pošle svalům povel?', 'Mozek po nervech',
    ['Žaludek po střevech', 'Srdce po kostech', 'Ledviny po žilách'],
    ['Povely putují po nervech.'],
    'Mozek pošle po nervech zprávu svalům. Svaly se stáhnou a zvednou kosti ruky.'),
  q('ziviny-cesta', 'Jak se živiny z jídla dostanou do celého těla?', 'Ze střev přejdou do krve a krev je roznese.',
    ['Ze žaludku jdou rovnou do kostí.', 'Vydechneme je plícemi.', 'Zůstanou navždy v žaludku.'],
    ['Spolupracuje trávicí a oběhová soustava.'],
    'Trávicí soustava jídlo rozloží a ve střevech předá živiny krvi. Oběhová soustava je pak roznese po těle.'),
  q('hrudni-kos', 'Které orgány chrání hrudní koš?', 'Srdce a plíce',
    ['Střeva a močový měchýř', 'Mozek a oči', 'Kolena a lokty'],
    ['Hrudní koš tvoří žebra.'],
    'Žebra, hrudní kost a páteř tvoří hrudní koš. Chrání srdce a plíce.'),
  q('micha', 'K čemu slouží mícha?', 'Vede zprávy mezi mozkem a tělem.',
    ['Pumpuje krev.', 'Tráví jídlo.', 'Vyrábí moč.'],
    ['Je schovaná v páteři.'],
    'Mícha je schovaná v páteři. Vede zprávy z mozku do těla a z těla do mozku.'),
  q('srdce-a-svaly', 'Co mají společného srdce a svaly na noze?', 'Obojí jsou svaly.',
    ['Obojí jsou kosti.', 'Obojí je v hlavě.', 'Obojí vyrábí moč.'],
    ['Obojí se umí stáhnout.'],
    'Srdce je taky sval. Na rozdíl od svalů na noze ho ale neovládáme vůlí – pracuje samo.'),
  q('kyslik-kam', 'Kam jde kyslík z plic?', 'Do krve',
    ['Do žaludku', 'Do kostí', 'Do močového měchýře'],
    ['Kyslík potřebuje celé tělo. Co ho roznese?'],
    'V plicích přejde kyslík do krve. Krev ho pak roznese do celého těla.'),
  q('tep-sport', 'Co se stane s tepem, když sportuješ?', 'Zrychlí se.',
    ['Zpomalí se.', 'Zastaví se.', 'Nic se nestane.'],
    ['Srdce musí svalům dodat víc krve.'],
    'Při sportu srdce bije rychleji, aby svaly dostaly víc kyslíku a živin.'),
  q('kuze-organ', 'Kůže chrání tělo, pomáhá mu udržet teplotu a cítí dotek. Je kůže orgán?', 'Ano, je to největší orgán těla.',
    ['Ne, je to jen obal.', 'Ne, orgány jsou jen uvnitř těla.', 'Ano, ale je to nejmenší orgán.'],
    ['Orgán je část těla, která má svou práci.'],
    'Kůže je orgán, a dokonce ten největší. Má hodně práce: chrání, cítí i chladí.'),
];

// ---------------------------------------------------------------------------
// L5 – krevní oběh, dýchání a trávení podrobněji

const L5: Spec[] = [
  q('tepny', 'Jak se jmenují cévy, které vedou krev ze srdce do těla?', 'Tepny',
    ['Žíly', 'Nervy', 'Šlachy'],
    ['Na zápěstí v nich nahmatáš tep.'],
    'Tepny vedou krev ze srdce do těla. V tepnách nahmatáš tep.'),
  q('zily', 'Jak se jmenují cévy, které vedou krev zpátky do srdce?', 'Žíly',
    ['Tepny', 'Průdušky', 'Močovody'],
    ['Na hřbetu ruky je někdy vidíš jako namodralé čárky.'],
    'Žíly vedou krev zpátky do srdce. Na hřbetu ruky je někdy vidíš jako namodralé čárky.'),
  q('vlasecnice', 'Jak se jmenují nejtenčí cévy, ze kterých se kyslík dostane až k buňkám?', 'Vlásečnice',
    ['Tepny', 'Žíly', 'Obratle'],
    ['Jsou tenké jako vlásek.'],
    'Vlásečnice jsou tenčí než vlas. Přes jejich stěnu přechází kyslík a živiny do buněk.'),
  q('sklipky', 'Co se děje v plicních sklípcích?', 'Kyslík přechází do krve a oxid uhličitý z krve ven.',
    ['Jídlo se mění na kaši.', 'Vzniká tam moč.', 'Rostou tam kosti.'],
    ['Sklípky jsou malinké váčky na konci průdušek.'],
    'Plicní sklípky jsou drobné váčky obalené vlásečnicemi. Kyslík z nich přechází do krve a oxid uhličitý z krve do vzduchu, který vydechneme.'),
  q('oxid-odpad', 'Který plyn vydechujeme jako odpad?', 'Oxid uhličitý',
    ['Kyslík', 'Helium', 'Vodík'],
    ['Vzniká v buňkách, když spotřebují kyslík.'],
    'Buňky spotřebují kyslík a vzniká oxid uhličitý. Krev ho donese do plic a my ho vydechneme.'),
  q('oxid-proc', 'Proč musí oxid uhličitý z těla ven?', 'Je to odpad, který by tělu škodil.',
    ['Je to vlastně kyslík.', 'Aby nám rostly vlasy.', 'Aby se nám nechtělo spát.'],
    ['Vzniká v buňkách jako zbytek.'],
    'Oxid uhličitý je odpad, který vzniká v buňkách. Kdyby se hromadil, tělu by škodil, a proto ho vydechujeme.'),
  q('dech-proc', 'Proč se ti při běhu zrychlí dech?', 'Svaly potřebují víc kyslíku.',
    ['Plíce se zmenšily.', 'Svaly potřebují méně kyslíku.', 'Žaludek se naplnil vzduchem.'],
    ['Co svaly potřebují, aby mohly pracovat?'],
    'Pracující svaly spotřebují víc kyslíku a vyrábějí víc oxidu uhličitého. Proto dýcháš rychleji a hlouběji.'),
  q('tep-proc', 'Proč ti při běhu buší srdce rychleji?', 'Musí svalům rychleji dodávat kyslík a živiny.',
    ['Srdce je unavené a chce odpočívat.', 'Svaly potřebují méně krve.', 'Krev se změnila ve vodu.'],
    ['Kyslík z plic ke svalům dopravuje krev.'],
    'Srdce při běhu pumpuje rychleji, aby krev dopravila ke svalům víc kyslíku a živin a odnesla oxid uhličitý.'),
  q('sliny', 'Co dělají sliny?', 'Zvlhčují sousta a začínají trávit škrob.',
    ['Bělí zuby.', 'Vyrábějí kyslík.', 'Chladí mozek.'],
    ['Zkus chvíli žvýkat kousek chleba. Začne chutnat nasládle.'],
    'Sliny zvlhčí sousto, aby se dalo spolknout. Obsahují látku, která začne trávit škrob – proto chléb po chvíli žvýkání chutná nasládle.'),
  q('traveni-zacina', 'Kde začíná trávení?', 'Už v ústech',
    ['Až v tlustém střevě', 'V plicích', 'V ledvinách'],
    ['Kde se jídlo poprvé potká se slinami?'],
    'Trávení začíná v ústech. Zuby jídlo rozkoušou a sliny ho začnou trávit.'),
  q('cervene-krvinky', 'K čemu jsou červené krvinky?', 'Roznášejí kyslík.',
    ['Bojují s bacily.', 'Tvoří kosti.', 'Vyrábějí žluč.'],
    ['Je jich v krvi nejvíc a dávají jí barvu.'],
    'Červené krvinky roznášejí kyslík z plic do celého těla. Díky nim je krev červená.'),
  q('bile-krvinky', 'K čemu jsou bílé krvinky?', 'Bojují s bacily.',
    ['Roznášejí kyslík.', 'Barví krev na červeno.', 'Vyrábějí sliny.'],
    ['Jsou to strážci těla.'],
    'Bílé krvinky chrání tělo. Vyhledávají a ničí bakterie a viry.'),
  q('desticky', 'Co pomáhá zastavit krvácení a vytvořit strup?', 'Krevní destičky',
    ['Bílé krvinky', 'Žluč', 'Sliny'],
    ['Jsou v krvi a shluknou se, když se céva poraní.'],
    'Krevní destičky se v ranách shluknou a pomáhají krev srazit. Z toho pak vznikne strup.'),
  q('srdce-dutiny', 'Srdce má uvnitř čtyři dutiny. Jak se jmenují?', 'Dvě síně a dvě komory',
    ['Čtyři žaludky', 'Dvě plíce a dvě ledviny', 'Čtyři obratle'],
    ['Dvě jsou nahoře a dvě dole.'],
    'Srdce má dvě síně a dvě komory. Do síní krev přitéká a komory ji pumpují do tepen.'),
  q('leva-plice', 'Proč je levá plíce trochu menší než pravá?', 'Vedle ní je srdce.',
    ['Protože jíme levou rukou.', 'Protože je starší.', 'Protože v ní je žaludek.'],
    ['Co leží v hrudníku trochu vlevo?'],
    'Srdce leží v hrudníku trochu vlevo, a tak mu levá plíce dělá místo. Je proto o něco menší.'),
  q('branice', 'Jak se jmenuje sval pod plícemi, který nám pomáhá dýchat?', 'Bránice',
    ['Biceps', 'Jazyk', 'Hýžďový sval'],
    ['Odděluje hrudník od břicha.'],
    'Bránice je plochý sval pod plícemi. Když se stáhne, plíce se roztáhnou a nasají vzduch.'),
  q('skytavka', 'Co se děje, když máme škytavku?', 'Bránice se nečekaně stahuje.',
    ['Kosti se posouvají.', 'Žaludek se převrací.', 'Plíce se zmenšují.'],
    ['Je to sval, který nám pomáhá dýchat.'],
    'Při škytavce se bránice nečekaně stáhne a hlasivky se rychle zavřou. Tak vznikne známé „hik“.'),
  q('ziviny-kde', 'Kde se vstřebává většina živin?', 'V tenkém střevě',
    ['V tlustém střevě', 'V jícnu', 'V ústech'],
    ['Je to nejdelší část trávicí trubice.'],
    'Většina živin přejde do krve v tenkém střevě. Jeho stěna je zvrásněná a má obrovskou plochu.'),
  q('tluste-voda', 'Co ze zbytků jídla vstřebává hlavně tlusté střevo?', 'Vodu',
    ['Kyslík', 'Žluč', 'Krev'],
    ['Zbytky jídla v něm postupně houstnou.'],
    'Tlusté střevo vstřebává ze zbytků jídla vodu. Co zbude, tělo vyloučí.'),
  q('zluc', 'Co dělá žluč?', 'Pomáhá trávit tuky.',
    ['Roznáší kyslík.', 'Zpevňuje kosti.', 'Chrání oči.'],
    ['Vyrábějí ji játra a posílají ji do střeva.'],
    'Žluč vyrábějí játra. Ve střevě rozbije tuky na drobné kapičky, aby se lépe strávily.'),
  q('zluc-kde', 'Kde se vyrábí žluč?', 'V játrech',
    ['V žaludku', 'V ledvinách', 'V srdci'],
    ['Je to největší vnitřní orgán.'],
    'Žluč vyrábějí játra. Zásoba žluči čeká ve žlučníku, dokud ji střevo nepotřebuje.'),
  q('kyselina', 'Proč je v žaludku kyselá šťáva?', 'Pomáhá trávit a ničí mnoho bakterií.',
    ['Aby jídlo chutnalo sladce.', 'Aby žaludek svítil.', 'Aby se jídlo změnilo na vzduch.'],
    ['Spolu s jídlem spolkneme i drobné bacily.'],
    'Žaludeční šťáva je velmi kyselá. Pomáhá rozkládat jídlo a ničí mnoho bakterií, které spolkneme.'),
  q('krev-litry', 'Kolik krve má v těle dospělý člověk?', 'Asi 5 litrů',
    ['Asi půl litru', 'Asi 50 litrů', 'Asi jednu lžíci'],
    ['Je to víc než jedna láhev, ale méně než kbelík.'],
    'Dospělý má asi 5 litrů krve. Děti mají krve méně, protože jsou menší.'),
  q('cesta-vzduchu', 'Kudy jde vzduch do plic?', path('nos', 'hrtan', 'průdušnice', 'průdušky', 'plíce'),
    [path('nos', 'jícen', 'žaludek', 'plíce'), path('pusa', 'průdušky', 'hrtan', 'nos'), path('nos', 'průdušnice', 'srdce', 'plíce')],
    ['Jícen vede jídlo, ne vzduch.'],
    'Vzduch jde nosem do hrtanu, pak průdušnicí a průduškami až do plic.'),
  q('cesta-jidla', 'Kudy putuje jídlo?', path('ústa', 'jícen', 'žaludek', 'tenké střevo', 'tlusté střevo'),
    [path('ústa', 'průdušnice', 'plíce', 'žaludek'), path('ústa', 'žaludek', 'jícen', 'tlusté střevo', 'tenké střevo'), path('ústa', 'jícen', 'srdce', 'střevo')],
    ['Průdušnice vede vzduch, ne jídlo.', 'Tenké střevo je na řadě dřív než tlusté.'],
    'Jídlo jde z úst jícnem do žaludku, pak do tenkého střeva a nakonec do tlustého střeva.'),
  q('svaly-teplo', 'Co v těle vyrábí nejvíc tepla, když sportuješ?', 'Svaly',
    ['Vlasy', 'Nehty', 'Kosti'],
    ['Co při sportu nejvíc pracuje?'],
    'Pracující svaly vyrábějí hodně tepla. Proto je ti při sportu horko a potíš se.'),
  q('cervene-tvare', 'Proč máš po běhu červené tváře?', 'Ke kůži proudí víc krve, aby se tělo ochladilo.',
    ['Kůže se opálila.', 'Srdce se přesunulo do hlavy.', 'Tváře se nafoukly vzduchem.'],
    ['Tělo se při běhu zahřeje a potřebuje se zbavit tepla.'],
    'Když se tělo zahřeje, cévy v kůži se rozšíří a proudí jimi víc krve. Kůže pak teplo odevzdá do okolí.'),
  q('tep-co-je', 'Co cítíš, když na zápěstí nahmatáš tep?', 'Nárazy krve, kterou srdce posílá do tepen',
    ['Jak roste kost', 'Jak dýchají plíce', 'Jak se tráví jídlo'],
    ['Tep bije stejně rychle jako srdce.'],
    'Při každém stahu pošle srdce do tepen dávku krve. Tu cítíš na zápěstí jako tep.'),
];

export const organy = bankSkill({
  id: ID,
  name: 'K čemu slouží orgány',
  description: 'Rozvíjí porozumění tomu, co dělají jednotlivé orgány a orgánové soustavy a jak spolu spolupracují.',
  rvp: {
    2: ['ČJS-3-5-01'],
    3: ['ČJS-3-5-01'],
    4: ['ČJS-5-5-01'],
    5: ['ČJS-5-5-01'],
  },
  ability: 'znalosti',
  testLike: 'vedomosti',
  banks: { 2: L2, 3: L3, 4: L4, 5: L5 },
});
