// Smysly – pět základních smyslů a jejich orgány, ochrana očí a uší,
// spolupráce smyslů a reflexy.

import { bankSkill, q, type Spec } from './common';

const ID = 'telo.smysly';

const SMYSLY = ['Zrak', 'Sluch', 'Čich', 'Chuť', 'Hmat'];
const others = (correct: string) => SMYSLY.filter((s) => s !== correct);

// ---------------------------------------------------------------------------
// L1 – pět smyslů a jejich orgány

const L1: Spec[] = [
  q('cim-vidis', 'Čím vidíš?', 'Očima',
    ['Ušima', 'Nosem', 'Jazykem'],
    ['Když je zavřeš, je tma.'],
    'Vidíme očima. Smysl, kterým vidíme, se jmenuje zrak.'),
  q('cim-slysis', 'Čím slyšíš?', 'Ušima',
    ['Očima', 'Nosem', 'Kolenem'],
    ['Když si je zakryješ, je skoro ticho.'],
    'Slyšíme ušima. Tomuto smyslu říkáme sluch.'),
  q('cim-vune', 'Čím cítíš vůni květiny?', 'Nosem',
    ['Ušima', 'Očima', 'Loktem'],
    ['Když máš rýmu, moc to nefunguje.'],
    'Vůně cítíme nosem. Tomuto smyslu říkáme čich.'),
  q('cim-sladke', 'Čím poznáš, že je jídlo sladké?', 'Jazykem',
    ['Ušima', 'Loktem', 'Vlasy'],
    ['Je to v puse.'],
    'Chuť jídla poznáváme jazykem. Tomuto smyslu říkáme chuť.'),
  q('cim-tepla-voda', 'Čím poznáš, že je voda ve vaně teplá?', 'Kůží',
    ['Ušima', 'Nosem', 'Vlasy'],
    ['Stačí do vody strčit ruku.'],
    'Teplo a chlad cítíme kůží. Kůže patří k hmatu.'),
  q('kolik-smyslu', 'Kolik základních smyslů má člověk?', 'Pět',
    ['Dva', 'Deset', 'Sto'],
    ['Vzpomeň si: zrak, sluch, čich… a ještě další.'],
    'Pět základních smyslů je zrak, sluch, čich, chuť a hmat. Vědci znají i další, třeba smysl pro rovnováhu.'),
  q('zvonek', 'Kterým smyslem poznáš, že zvoní zvonek?', 'Sluchem',
    ['Čichem', 'Chutí', 'Hmatem'],
    ['Zvonění je zvuk.'],
    'Zvuky vnímáme sluchem – ušima.'),
  q('buchta', 'Z kuchyně voní pečená buchta. Kterým smyslem to poznáš?', 'Čichem',
    ['Sluchem', 'Hmatem', 'Chutí'],
    ['Čím cítíš vůni?'],
    'Vůně cítíme čichem. Čichovým orgánem je nos.'),
  q('barvy', 'Kterým smyslem poznáš barvy?', 'Zrakem',
    ['Sluchem', 'Čichem', 'Chutí'],
    ['Barvy nejde slyšet ani ochutnat.'],
    'Barvy vidíme očima – zrakem.'),
  q('citron', 'Kterým smyslem poznáš, že je citron kyselý?', 'Chutí',
    ['Sluchem', 'Zrakem', 'Hmatem'],
    ['Musíš ho ochutnat.'],
    'Kyselou chuť citronu poznáš chutí – jazykem.'),
  q('kote', 'Kterým smyslem poznáš, že je kotě hebké?', 'Hmatem',
    ['Sluchem', 'Čichem', 'Chutí'],
    ['Musíš ho pohladit.'],
    'Hebkost cítíme hmatem – kůží, hlavně na prstech.'),
  q('smysl-zrak', 'Jak se jmenuje smysl, kterým vidíme?', 'Zrak', others('Zrak'),
    ['Tento smysl patří k očím.'],
    'Smysl, kterým vidíme, je zrak. Orgánem zraku jsou oči.'),
  q('smysl-sluch', 'Jak se jmenuje smysl, kterým slyšíme?', 'Sluch', others('Sluch'),
    ['Tento smysl patří k uším.'],
    'Smysl, kterým slyšíme, je sluch. Orgánem sluchu jsou uši.'),
  q('smysl-cich', 'Jak se jmenuje smysl, kterým cítíme vůně?', 'Čich', others('Čich'),
    ['Tento smysl patří k nosu.'],
    'Smysl, kterým cítíme vůně a pachy, je čich. Orgánem čichu je nos.'),
  q('smysl-chut', 'Jak se jmenuje smysl, kterým poznáme, že je jídlo sladké nebo slané?', 'Chuť', others('Chuť'),
    ['Tento smysl patří k jazyku.'],
    'Smysl, kterým poznáváme sladké, slané, kyselé a hořké, je chuť. Pracuje hlavně jazyk.'),
  q('smysl-hmat', 'Jak se jmenuje smysl, kterým cítíme dotek?', 'Hmat', others('Hmat'),
    ['Tento smysl patří ke kůži.'],
    'Smysl, kterým cítíme dotek, je hmat. Orgánem hmatu je kůže.'),
  q('analogie-usi', 'Oči patří ke zraku. K čemu patří uši?', 'Ke sluchu',
    ['K čichu', 'K chuti', 'K hmatu'],
    ['Čím posloucháš písničku?'],
    'Uši jsou orgán sluchu, stejně jako oči jsou orgán zraku.'),
  q('analogie-nos', 'Jazyk patří k chuti. K čemu patří nos?', 'K čichu',
    ['Ke zraku', 'Ke sluchu', 'K hmatu'],
    ['Čím cítíš, jak voní květina?'],
    'Nos je orgán čichu, stejně jako jazyk je orgán chuti.'),
  q('rasy', 'Co chrání oči před prachem?', 'Řasy a víčka',
    ['Uši', 'Vlasy na hlavě', 'Nos'],
    ['Když mrkneš, zavřou se.'],
    'Víčka a řasy chrání oči před prachem. Když něco letí k oku, rychle mrkneme.'),
  q('slunce-oci', 'Co je pro oči nebezpečné?', 'Dívat se přímo do slunce',
    ['Mrkat', 'Dívat se na zelenou trávu', 'Spát se zavřenýma očima'],
    ['Slunce je velmi jasné.'],
    'Do slunce se nikdy nedívej přímo, ani přes sluneční brýle. Mohlo by to oči vážně poškodit.'),
  q('usi-chranime', 'Jak chráníme uši?', 'Neposloucháme moc hlasitou hudbu.',
    ['Strkáme do nich tužky.', 'Křičíme kamarádům do ucha.', 'Pouštíme si hudbu co nejhlasitěji.'],
    ['Uším škodí příliš silné zvuky.'],
    'Uším škodí hodně hlasité zvuky a strkání věcí do ucha. Pouštěj si hudbu potichu.'),
  q('smitko', 'Do oka ti spadlo smítko. Co uděláš?', 'Nebudu oko mnout a řeknu to dospělému.',
    ['Budu oko silně mnout.', 'Sáhnu si do oka špinavým prstem.'],
    ['Oko je velmi jemné.'],
    'Oko nemni, smítko by ho mohlo poškrábat. Zamrkej, a když smítko nevyjde, dospělý ti oko opatrně vypláchne čistou vodou.'),
  q('kuze-organ', 'Který orgán cítí teplo, zimu a dotek?', 'Kůže',
    ['Oko', 'Ucho', 'Nos'],
    ['Pokrývá celé tělo.'],
    'Kůže je orgán hmatu. Cítí dotek, teplo, chlad i bolest.'),
  q('slunecni-bryle', 'Proč nosíme v létě sluneční brýle?', 'Chrání oči před ostrým sluncem.',
    ['Aby nám bylo tepleji.', 'Abychom lépe slyšeli.', 'Aby nám rostly řasy.'],
    ['V létě svítí slunce hodně ostře.'],
    'Sluneční brýle chrání oči před ostrým světlem a škodlivým zářením ze slunce.'),
  q('cepice-usi', 'Proč v zimě nosíme čepici přes uši?', 'Aby uši neprochladly.',
    ['Abychom lépe slyšeli.', 'Aby nám rostly vlasy.', 'Aby nám bylo horko.'],
    ['Uši jsou tenké a trčí z hlavy.'],
    'Uši rychle prochladnou. Čepice je chrání před zimou a větrem.'),
  q('cteni-svetlo', 'Co potřebují oči, když čteš?', 'Dost světla',
    ['Úplnou tmu', 'Hlasitou hudbu', 'Silný vítr'],
    ['Jde ti čtení ve tmě?'],
    'Při čtení potřebují oči dost světla. Ve tmě se namáhají a rychle se unaví.'),
  q('ohnostroj', 'Co můžeš udělat, když je nějaký zvuk moc hlasitý, třeba ohňostroj?', 'Zakrýt si uši.',
    ['Dát si uši blíž.', 'Křičet ještě hlasitěji.', 'Strčit si do uší tužky.'],
    ['Jak zvuk k uším nepustíš?'],
    'Když je něco moc hlasité, zakryj si uši nebo odejdi dál. Uši se tak nepoškodí.'),
];

// ---------------------------------------------------------------------------
// L2 – jak jsou smyslové orgány stavěné a jak je chránit

const CHUTI = ['Sladkou', 'Slanou', 'Kyselou', 'Hořkou'];
const chut = (correct: string) => CHUTI.filter((c) => c !== correct);

const L2: Spec[] = [
  q('duhovka', 'Jak se jmenuje barevná část oka?', 'Duhovka',
    ['Zornice', 'Víčko', 'Řasa'],
    ['Podle ní říkáme, že má někdo modré nebo hnědé oči.'],
    'Duhovka je barevná část oka. Podle ní říkáme, jestli má někdo oči modré, zelené, nebo hnědé.'),
  q('zornice', 'Jak se jmenuje černý kroužek uprostřed oka?', 'Zornice',
    ['Duhovka', 'Obočí', 'Víčko'],
    ['Tudy do oka vchází světlo.'],
    'Zornice je otvor uprostřed duhovky. Tudy vchází do oka světlo, a proto vypadá černě.'),
  q('zornice-svetlo', 'Co se stane se zornicí, když je hodně světla?', 'Zmenší se.',
    ['Zvětší se.', 'Zezelená.', 'Zmizí.'],
    ['Oko se chrání, aby do něj nešlo moc světla.'],
    'Na světle se zornice zmenší, aby do oka nešlo příliš mnoho světla.'),
  q('zornice-tma', 'Co se stane se zornicí ve tmě?', 'Zvětší se.',
    ['Zmenší se.', 'Zčervená.', 'Zmizí.'],
    ['Ve tmě potřebuje oko nachytat co nejvíc světla.'],
    'Ve tmě se zornice zvětší, aby do oka pustila co nejvíc světla.'),
  q('slzy', 'K čemu jsou slzy?', 'Zvlhčují a čistí oko.',
    ['Barví oči.', 'Pomáhají slyšet.', 'Chladí nos.'],
    ['Oko musí být pořád trochu vlhké.'],
    'Slzy oko pořád zvlhčují a oplachují z něj prach. Nejen když pláčeme.'),
  q('mrkani', 'Proč mrkáme?', 'Aby se oko zvlhčilo a očistilo.',
    ['Aby oko rostlo.', 'Abychom lépe slyšeli.', 'Abychom usnuli.'],
    ['Víčko při mrknutí přejede přes oko.'],
    'Při každém mrknutí víčko roztáhne po oku slzy. Oko je pak vlhké a čisté.'),
  q('oboci', 'K čemu je obočí?', 'Zadržuje pot, aby nestékal do očí.',
    ['Pomáhá slyšet.', 'Zahřívá nos.', 'Je jen na ozdobu.'],
    ['Je nad očima jako stříška.'],
    'Obočí je jako malá stříška nad očima. Zadržuje pot a vodu, aby nestékaly do očí.'),
  q('boltec', 'Jak se jmenuje část ucha, kterou vidíme zvenku?', 'Boltec',
    ['Bubínek', 'Zornice', 'Nosní dírka'],
    ['Zachytává zvuky jako trychtýř.'],
    'Boltec je vnější část ucha. Zachytává zvuky jako trychtýř.'),
  q('bubinek', 'Jak se jmenuje tenká blána v uchu, která se chvěje, když slyšíme zvuk?', 'Bubínek',
    ['Boltec', 'Víčko', 'Duhovka'],
    ['Jmenuje se podobně jako hudební nástroj.'],
    'Bubínek je tenká blána uvnitř ucha. Zvuk ji rozechvěje a ucho pošle zprávu do mozku.'),
  q('nic-do-ucha', 'Proč si nestrkáme do ucha žádné předměty?', 'Mohli bychom si poškodit bubínek.',
    ['Ucho by se zvětšilo.', 'Začali bychom hůř vidět.', 'Vypadaly by nám vlasy.'],
    ['Uvnitř ucha je něco velmi jemného.'],
    'Uvnitř ucha je jemný bubínek. Mohl by se snadno poškodit, a proto do ucha nic nestrkáme.'),
  q('usni-maz', 'K čemu je ušní maz?', 'Chrání ucho před prachem a bacily.',
    ['Pomáhá slyšet hudbu.', 'Je to zbytek jídla.', 'Barví uši.'],
    ['Zachytává to, co do ucha nepatří.'],
    'Ušní maz chrání ucho před prachem a bacily. Ucho se samo čistí, proto do něj nestrkáme ani vatové tyčinky.'),
  q('ryma-chut', 'Proč jídlo při rýmě tolik nechutná?', 'Nos je ucpaný a chuť potřebuje i čich.',
    ['Jazyk při rýmě spí.', 'Jídlo se při rýmě zkazí.', 'Uši jsou ucpané.'],
    ['Který orgán je při rýmě ucpaný?'],
    'Chuť jídla poznáváme jazykem i nosem. Když je nos ucpaný, jídlo chutná méně.'),
  q('poharky', 'Kde najdeš chuťové pohárky?', 'Hlavně na jazyku',
    ['Na nose', 'V uších', 'Na lokti'],
    ['Díky nim poznáš chuť jídla.'],
    'Chuťové pohárky jsou drobná místa hlavně na jazyku. Díky nim poznáme chuť jídla.'),
  q('chut-cukr', 'Jakou chuť má cukr?', 'Sladkou', chut('Sladkou'),
    ['Stejnou chuť má med.'],
    'Cukr je sladký. Sladkou chuť cítíme jazykem.'),
  q('chut-citron', 'Jakou chuť má citron?', 'Kyselou', chut('Kyselou'),
    ['Po kousnutí se většinou zašklebíš.'],
    'Citron je kyselý. Kyselou chuť mají i nezralá jablka nebo rybíz.'),
  q('chut-more', 'Jakou chuť má mořská voda?', 'Slanou', chut('Slanou'),
    ['V moři je rozpuštěná sůl.'],
    'Mořská voda je slaná, protože je v ní rozpuštěná sůl. Pít se nedá.'),
  q('chut-kakao', 'Jakou chuť má kakaový prášek bez cukru?', 'Hořkou', chut('Hořkou'),
    ['Proto se do kakaa dává cukr.'],
    'Kakao bez cukru je hořké. Hořkou chuť mají také třeba některé bylinky.'),
  q('citlive-prsty', 'Které místo je na dotek nejcitlivější?', 'Konečky prstů',
    ['Záda', 'Pata', 'Loket'],
    ['Čím si osaháváš drobné věci?'],
    'Na konečcích prstů je velmi mnoho drobných nervových zakončení, která cítí dotek. Proto jimi poznáme i jemné věci.'),
  q('kuze-co-citi', 'Co všechno cítí kůže?', 'Dotek, teplo, chlad i bolest',
    ['Jen barvy', 'Jen zvuky', 'Jen vůně'],
    ['Vzpomeň si, co cítíš, když sáhneš na sníh.'],
    'Kůže je orgán hmatu. Cítí dotek, tlak, teplo, chlad i bolest.'),
  q('braillovo-pismo', 'Jak čtou nevidomí lidé?', 'Prsty – nahmatají vystouplé tečky.',
    ['Ušima – poslouchají papír.', 'Nosem – čichají písmena.', 'Nevidomí číst nemohou.'],
    ['Používají smysl, kterým cítíme dotek.'],
    'Nevidomí čtou Braillovo písmo. Písmena jsou z vystouplých teček, které nahmatají prsty.'),
  q('vodici-pes', 'Kdo pomáhá nevidomému člověku bezpečně chodit po ulici?', 'Vodicí pes',
    ['Kočka', 'Papoušek', 'Zlatá rybka'],
    ['Je speciálně vycvičený.'],
    'Vodicí pes je vycvičený, aby nevidomého člověka bezpečně provedl ulicí. Pomáhá také bílá hůl.'),
  q('znakovy-jazyk', 'Jak si mohou povídat lidé, kteří neslyší?', 'Znakovým jazykem',
    ['Jen šeptem', 'Pískáním', 'Nemohou si povídat'],
    ['Mluví rukama.'],
    'Neslyšící lidé často mluví znakovým jazykem. Slova ukazují rukama, prsty a výrazem obličeje.'),
  q('bryle', 'Co pomáhá lidem, kteří špatně vidí?', 'Brýle nebo kontaktní čočky',
    ['Naslouchátko', 'Čepice', 'Rukavice'],
    ['Nosí se na očích nebo přímo v nich.'],
    'Brýle a kontaktní čočky pomáhají lidem vidět ostře.'),
  q('naslouchatko', 'Co pomáhá lidem, kteří špatně slyší?', 'Naslouchátko',
    ['Brýle', 'Kapesník', 'Šála'],
    ['Nosí se u ucha.'],
    'Naslouchátko zesílí zvuky, aby je člověk lépe slyšel.'),
  q('mleko-pachne', 'Mléko v lednici divně páchne. Který smysl tě varoval?', 'Čich',
    ['Sluch', 'Hmat', 'Zrak'],
    ['Pach cítíme nosem.'],
    'Zkažené jídlo často poznáme čichem. Čich nás chrání, abychom nesnědli něco zkaženého.'),
];

// ---------------------------------------------------------------------------
// L3 – spolupráce smyslů, reflexy, rovnováha

const L3: Spec[] = [
  q('reflex-jmeno', 'Sáhneš na horký hrnek a ruka hned ucukne. Jak se tomu říká?', 'Reflex',
    ['Plán', 'Zvyk', 'Sen'],
    ['Stane se to samo, bez přemýšlení.'],
    'Ucuknutí je reflex – rychlá reakce, na kterou nemusíš myslet. Chrání tě před popálením.'),
  q('reflex-zkratka', 'Proč ruka ucukne od horkého dřív, než ucítíš, že to pálí?', 'Povel k ucuknutí vydá už mícha.',
    ['Ruka má vlastní mozek.', 'Horko ruku samo odstrčí.', 'Je to náhoda.'],
    ['Mícha je v páteři a vede zprávy mezi tělem a mozkem.'],
    'U reflexu vydá povel k ucuknutí už mícha. Do mozku dorazí zpráva o chvilku později, a proto bolest ucítíš až po ucuknutí.'),
  q('reflex-k-cemu', 'K čemu jsou reflexy?', 'Rychle nás chrání před nebezpečím.',
    ['Pomáhají nám usnout.', 'Učí nás číst.', 'Barví nám kůži.'],
    ['Jsou rychlejší než přemýšlení.'],
    'Reflexy jsou bleskové reakce těla. Chrání nás dřív, než stihneme přemýšlet.'),
  q('ktery-reflex', 'Který z těchto pohybů je reflex?', 'Mrknutí, když ti něco letí k oku',
    ['Kreslení obrázku', 'Psaní úkolu', 'Zavazování tkaniček'],
    ['Který pohyb se stane sám, bez přemýšlení?'],
    'Mrknutí je reflex – oko se zavře samo, dřív než stihneš přemýšlet.'),
  q('kladivko', 'Proč lékař ťukne kladívkem pod koleno?', 'Zkouší reflex – noha sama vyskočí.',
    ['Chce koleno spravit.', 'Zkouší, jestli je koleno tvrdé.', 'Chce tě polechtat.'],
    ['Noha se pohne, i když nechceš.'],
    'Lékař zkouší kolenní reflex. Když noha sama vyskočí, nervy a mícha fungují dobře.'),
  q('kychnuti', 'Kýchnutí je taky reflex. Co jím tělo dělá?', 'Vyfukuje z nosu prach a bacily.',
    ['Ohřívá si uši.', 'Zrychluje si růst.', 'Čistí si zuby.'],
    ['Kýchnutí přichází, když nás něco zašimrá v nose.'],
    'Kýchnutím se nos zbavuje prachu, pylu a bacilů. Kýchej proto do kapesníku nebo do lokte.'),
  q('kasel', 'K čemu je kašel?', 'Čistí dýchací cesty.',
    ['Čistí žaludek.', 'Pomáhá lépe vidět.', 'Zahřívá ruce.'],
    ['Kašlem něco vyháníme z krku a průdušek.'],
    'Kašlem tělo vyhání z dýchacích cest hlen, prach nebo drobek, který zaskočil.'),
  q('jahoda', 'Když jíš jahodu, které smysly používáš?', 'Chuť, čich, zrak i hmat',
    ['Jen chuť', 'Jen sluch', 'Jen zrak'],
    ['Zkus si při jídle všimnout, co všechno o jahodě víš.'],
    'Při jídle pracuje víc smyslů najednou: vidíme barvu, cítíme vůni, jazykem chuť a v puse, jestli je jahoda měkká.'),
  q('zacpany-nos', 'Co se stane, když si při jídle zacpeš nos?', 'Jídlo chutná méně výrazně.',
    ['Jídlo chutná víc.', 'Přestaneš vidět.', 'Jídlo začneš slyšet.'],
    ['Vzpomeň si, jak chutná jídlo při rýmě.'],
    'Velkou část chuti jídla tvoří vůně, kterou cítí nos. Se zacpaným nosem je chuť slabší – můžeš si to vyzkoušet.'),
  q('kolotoc', 'Proč se ti po jízdě na kolotoči točí hlava?', 'Ústrojí rovnováhy v uchu je zmatené.',
    ['Oči se unavily.', 'Mozek se otočil.', 'Nos je ucpaný.'],
    ['Smysl pro rovnováhu je schovaný v hlavě u sluchu.'],
    'Ve vnitřním uchu je ústrojí rovnováhy s tekutinou. Po točení se tekutina ještě chvíli pohybuje, a proto se nám točí hlava.'),
  q('rovnovaha-kde', 'Kde máme ústrojí rovnováhy?', 'Ve vnitřním uchu',
    ['V koleni', 'V žaludku', 'V nose'],
    ['Je schované hluboko v hlavě.'],
    'Ústrojí rovnováhy je ve vnitřním uchu. Pomáhá nám stát, chodit a nespadnout.'),
  q('hlavou-dolu', 'Kterým smyslem poznáš, že jsi hlavou dolů, i když máš zavřené oči?', 'Smyslem pro rovnováhu',
    ['Čichem', 'Chutí', 'Hmatem na prstech'],
    ['Ten smysl ti pomáhá nespadnout.'],
    'Smysl pro rovnováhu ve vnitřním uchu pozná, jak je hlava natočená, i když máš zavřené oči.'),
  q('zpravy-kam', 'Kam posílají smysly své zprávy?', 'Po nervech do mozku',
    ['Do žaludku', 'Do kostí', 'Do vlasů'],
    ['Který orgán řídí celé tělo?'],
    'Oči, uši, nos, jazyk i kůže posílají zprávy po nervech do mozku. Teprve mozek pozná, co vidíme nebo slyšíme.'),
  q('mozek-smysly', 'Který orgán dostává zprávy ze všech smyslů?', 'Mozek',
    ['Srdce', 'Žaludek', 'Játra'],
    ['Je v hlavě.'],
    'Všechny smysly posílají zprávy do mozku. Mozek je poskládá dohromady.'),
  q('sitnice', 'Jaký je obraz, který vzniká v oku na sítnici?', 'Je vzhůru nohama a mozek ho otočí.',
    ['Je vždycky černobílý.', 'Vzniká jen v noci.', 'Je obrovský jako strom.'],
    ['Oko funguje trochu jako fotoaparát.'],
    'Oko funguje trochu jako fotoaparát. Obraz na sítnici je vzhůru nohama a mozek si ho otočí správně.'),
  q('tma-zvykani', 'Po zhasnutí za chvíli vidíš ve tmě o něco lépe. Proč?', 'Zornice se zvětší a oko si na tmu zvykne.',
    ['Oči začnou svítit.', 'Tma sama zesvětlá.', 'Uši začnou vidět.'],
    ['Vzpomeň si, co dělá zornice ve tmě.'],
    'Ve tmě se zornice zvětší a oko se postupně přizpůsobí. Proto po chvíli vidíš víc.'),
  q('bolest', 'Proč je bolest užitečná?', 'Varuje nás, že se tělu něco děje.',
    ['Aby nás zlobila.', 'Aby nás bavila.', 'Užitečná není vůbec.'],
    ['Co bys dělala, kdyby tě nic nebolelo?'],
    'Bolest je varování. Díky ní víme, že máme přestat a něco s tím udělat.'),
  q('cich-chrani', 'Jak nás chrání čich?', 'Ucítíme kouř nebo zkažené jídlo.',
    ['Uslyšíme blížící se auto.', 'Uvidíme barvy.', 'Ochrání nás před sluncem.'],
    ['Co dělá nos?'],
    'Čich nás varuje před kouřem, unikajícím plynem nebo zkaženým jídlem.'),
  q('prechod', 'Proč se na přechodu díváme i posloucháme?', 'Některá vozidla, třeba kola, skoro neslyšíme.',
    ['Auta jsou vidět jen v noci.', 'Oči na ulici nefungují.', 'Na přechodu se rozhlížet nemusíme.'],
    ['Jezdí všechno hlučně?'],
    'Kolo nebo elektromobil může jet skoro potichu. Proto se na přechodu vždycky díváme i posloucháme.'),
  q('kolo-smysly', 'Proč při jízdě na kole potřebuješ zrak, sluch i rovnováhu najednou?', 'Každý smysl hlídá něco jiného.',
    ['Stačí jeden smysl, ostatní odpočívají.', 'Na kole smysly nepotřebujeme.', 'Protože kolo nemá brzdy.'],
    ['Co by se stalo, kdyby jeden z nich chyběl?'],
    'Zrak hlídá cestu, sluch slyší auta a zvonky a rovnováha tě drží na kole. Smysly spolupracují.'),
  q('psi-cich', 'Který smysl mají psi mnohem lepší než lidé?', 'Čich',
    ['Chuť', 'Zrak na barvy'],
    ['Psi při procházce pořád čenichají.'],
    'Psi mají mnohem citlivější čich než lidé. Proto dokážou najít ztracené lidi nebo vystopovat zvíře.'),
  q('pytlik', 'Hráč má zavázané oči a poznává věci v pytlíku jen rukama. Který smysl používá?', 'Hmat',
    ['Zrak', 'Čich', 'Sluch'],
    ['Pracují prsty.'],
    'Bez očí poznáváme tvar a povrch věcí hmatem. Prsty cítí, jestli je věc hladká, hrbolatá, měkká, nebo tvrdá.'),
  q('hlas', 'Poznáš kamaráda podle hlasu, i když ho nevidíš. Který smysl pracuje?', 'Sluch',
    ['Zrak', 'Čich', 'Chuť'],
    ['Hlas je zvuk.'],
    'Hlas slyšíme ušima – sluchem. Mozek si pamatuje, jak kamarád mluví.'),
  q('dve-usi', 'Proč je dobré, že máme dvě uši?', 'Lépe poznáme, odkud zvuk přichází.',
    ['Jedno ucho je náhradní.', 'Jedním slyšíme ráno a druhým večer.', 'Aby na hlavě držela čepice.'],
    ['Zvuk zleva dorazí dřív k levému uchu.'],
    'Zvuk dorazí k jednomu uchu o kousek dřív a silněji. Mozek z toho pozná, odkud přichází.'),
  q('dve-oci', 'Proč je dobré, že máme dvě oči?', 'Lépe odhadneme vzdálenost.',
    ['Jedno oko je náhradní.', 'Jedním okem vidíme barvy a druhým tvary.', 'Aby nám nepadaly brýle.'],
    ['Zkus zavřít jedno oko a chytit míč.'],
    'Každé oko vidí svět z trochu jiného místa. Mozek oba obrázky spojí a pozná, co je blízko a co daleko.'),
  q('uv-filtr', 'Proč by sluneční brýle měly mít UV filtr?', 'Chrání oči před neviditelným ultrafialovým zářením.',
    ['Aby byly hezčí.', 'Aby v nich bylo líp slyšet.', 'Aby se nerozbily.'],
    ['Slunce vysílá i záření, které nevidíme.'],
    'Slunce vysílá i ultrafialové (UV) záření, které nevidíme, ale očím škodí. Dobré sluneční brýle ho zachytí.'),
];

export const smysly = bankSkill({
  id: ID,
  name: 'Smysly',
  description: 'Seznamuje s pěti základními smysly, jejich orgány a ochranou, se spoluprací smyslů a s reflexy.',
  rvp: {
    1: ['ČJS-3-5-01'],
    2: ['ČJS-3-5-01'],
    3: ['ČJS-3-5-01'],
  },
  ability: 'znalosti',
  testLike: 'vedomosti',
  banks: { 1: L1, 2: L2, 3: L3 },
});
