// Zdraví a denní režim – hygiena, spánek, pití, pestré jídlo, pohyb,
// přestávky od obrazovky, prevence a plánování dne. Vysvětlení je zajímavost:
// nejdřív odpověď s důvodem, pak navazující detail.

import { form } from '../../core/czech';
import type { ChoiceOption } from '../../core/types';
import { bankSkill, q, type Spec } from './common';

const ID = 'telo.zdravi';

/** Čas jako možnost: „15:40“, předčítá se „15 hodin 40 minut“. */
function cas(h: number, m: number): ChoiceOption {
  const hodin = `${h} ${form(h, ['hodina', 'hodiny', 'hodin'])}`;
  return {
    label: `${h}:${String(m).padStart(2, '0')}`,
    speak: m === 0 ? hodin : `${hodin} ${m} ${form(m, ['minuta', 'minuty', 'minut'])}`,
  };
}

// ---------------------------------------------------------------------------
// L1 – základní hygiena a zdravé návyky

const L1: Spec[] = [
  q('ruce-kdy', 'Kdy si myjeme ruce?', 'Po záchodě a před jídlem',
    ['Jen v neděli', 'Jen když jsou vidět špinavé', 'Jen o prázdninách'],
    ['Bacily nejsou vidět.'],
    'Ruce si myjeme po záchodě, před jídlem a po příchodu domů. Bacily nejsou vidět, ale na rukou být můžou.'),
  q('ruce-cim', 'Čím si myjeme ruce?', 'Mýdlem a vodou',
    ['Jen studeným větrem', 'Pískem', 'Limonádou'],
    ['Pění to.'],
    'Mýdlo a voda smyjí z rukou špínu i bacily. Mýdlo uvolní mastnotu, ve které se bacily drží, a voda je pak spláchne.'),
  q('ruce-proc', 'Proč si myjeme ruce?', 'Smyjeme bacily, které nejsou vidět.',
    ['Aby ruce voněly jako limonáda.', 'Aby nám rostly nehty.', 'Aby ruce byly studené.'],
    ['Na rukou může být něco, co nevidíme.'],
    'Na rukou mohou být drobné bacily – bakterie a viry. Jsou tak malé, že je nevidíme, a mýdlo s vodou je smyjí.'),
  q('pred-obedem', 'Co uděláš, než si sedneš k obědu?', 'Umyju si ruce.',
    ['Pohladím psa a hned začnu jíst.', 'Olížu si prsty.', 'Nic.'],
    ['Rukama budeš brát jídlo.'],
    'Před jídlem si myjeme ruce, aby se bacily z rukou nedostaly do pusy. Na pusu a nos si totiž sahají lidé mnohokrát za hodinu, aniž by si toho všimli.'),
  q('pisek', 'Po hraní na pískovišti máš špinavé ruce. Co uděláš?', 'Umyju si je mýdlem.',
    ['Olížu si je.', 'Utřu si je do trička a jdu jíst.', 'Nic, špína se ztratí sama.'],
    ['Ve špíně mohou být bacily.'],
    'Po hraní venku si umyj ruce mýdlem, protože ve špíně mohou být bacily. Nezapomeň na nehty – pod nimi se špína drží nejdéle.'),
  q('zuby-kolikrat', 'Kolikrát denně si čistíme zuby?', 'Dvakrát – ráno a večer',
    ['Jednou za týden', 'Jen o Vánocích', 'Jen když bolí'],
    ['Jednou po probuzení a jednou před spaním.'],
    'Zuby si čistíme dvakrát denně – ráno a večer před spaním. Na zubech se totiž pořád tvoří lepkavý povlak plný bakterií.'),
  q('zuby-jak-dlouho', 'Jak dlouho si čistíme zuby?', 'Asi dvě minuty',
    ['Dvě vteřiny', 'Dvě hodiny', 'Půl dne'],
    ['Kartáček se musí dostat ke každému zubu.'],
    'Zuby čistíme asi dvě minuty, aby se kartáček dostal ke každému zubu. Dvě minuty jsou delší, než se zdá – pomohou přesýpací hodiny nebo písnička.'),
  q('pasta', 'Kolik zubní pasty dáváš na kartáček?', 'Asi jako hrášek',
    ['Celou tubu', 'Plný kartáček a ještě víc', 'Vůbec žádnou'],
    ['Stačí jen trochu.'],
    'Stačí kousek pasty velký asi jako hrášek a pastu pak nepolykáme, ale vyplivneme. Fluor v ní zpevňuje zubní sklovinu.'),
  q('po-cisteni', 'Večer sis {vyčistila|vyčistil} zuby a ještě máš chuť něco zobnout. Co uděláš?', 'Už nic nejím, jen se napiju vody.',
    ['Dám si ještě bonbon.', 'Vypiju sladký čaj.', 'Sním v posteli sušenku.'],
    ['Zuby mají zůstat přes noc čisté.'],
    'Po večerním čištění už nejíme a pijeme jen vodu, aby zuby zůstaly přes noc čisté. V noci máme v puse málo slin, které zuby jinak oplachují.'),
  q('kartacek', 'Proč má každý svůj kartáček na zuby?', 'Aby se nepřenášely bacily.',
    ['Aby byl barevnější.', 'Aby se kartáček neztratil.', 'Aby se rychleji opotřeboval.'],
    ['Kartáček se dotýká pusy.'],
    'Na kartáčku zůstávají bacily z pusy, a proto má každý svůj a nepůjčujeme si ho. Po čištění má kartáček uschnout, nejlépe hlavou nahoru.'),
  q('zizen', 'Co je nejlepší pít, když máš žízeň?', 'Vodu',
    ['Limonádu', 'Sladký sirup', 'Energetický nápoj'],
    ['Je to nejobyčejnější pití.'],
    'Nejlepší na žízeň je čistá voda, sladké pití jen občas. Tělo dítěte je víc než z poloviny z vody.'),
  q('spanek-kolik', 'Kolik spánku potřebují děti?', 'Hodně – zhruba 9 až 12 hodin',
    ['Asi 2 hodiny', 'Asi 5 hodin', 'Žádný'],
    ['Děti potřebují spát déle než dospělí.'],
    'Školní děti potřebují spát zhruba 9 až 12 hodin, protože ve spánku tělo odpočívá a roste. Novorozená miminka prospí dokonce víc než půl dne.'),
  q('spat-vcas', 'Proč chodíme spát včas?', 'Abychom byli ráno odpočatí.',
    ['Abychom ráno zaspali.', 'Aby nás bolela hlava.', 'Aby byla noc kratší.'],
    ['Jak se ti vstává, když jdeš spát pozdě?'],
    'Když jdeš spát včas, tělo i mozek si odpočinou a ráno máš víc síly. Mozek si ve spánku navíc ukládá vzpomínky z celého dne.'),
  q('kychnuti', 'Co uděláš, když potřebuješ kýchnout a nemáš kapesník?', 'Kýchnu do lokte.',
    ['Kýchnu do dlaně a pak podám ruku.', 'Kýchnu kamarádovi do obličeje.', 'Kýchnu na jídlo.'],
    ['Bacily nemají zůstat na ruce.'],
    'Kýchni do lokte. Bacily pak nezůstanou na dlani a nerozneseš je na všechno, na co sáhneš.'),
  q('kapesnik', 'Co uděláš s použitým papírovým kapesníkem?', 'Vyhodím ho do koše.',
    ['Dám ho kamarádovi.', 'Nechám ho na lavici.', 'Schovám si ho pod polštář.'],
    ['Jsou na něm bacily.'],
    'Použitý papírový kapesník patří hned do koše a pak si umyj ruce. Z odloženého kapesníku by se bacily snadno dostaly na další věci.'),
  q('kasel', 'Když kašleš, co uděláš?', 'Zakryju si pusu kapesníkem nebo loktem.',
    ['Zakašlu na ostatní.', 'Otevřu pusu co nejvíc.', 'Zakašlu do jídla.'],
    ['S kašlem létají vzduchem bacily.'],
    'Při kašli si zakryj pusu kapesníkem nebo loktem, aby se bacily nešířily. Kapičky z kašle doletí až metr i dál.'),
  q('svacina', 'Co je nejlepší dát si ke svačině každý den?', 'Jablko nebo mrkev',
    ['Lízátko', 'Bonbony', 'Chipsy'],
    ['Co má hodně vitaminů?'],
    'Ovoce a zelenina dodají tělu vitaminy, sladkosti a chipsy jen občas. Z mrkve si tělo vyrobí vitamin A, který oči potřebují k vidění za šera.'),
  q('sladkosti', 'Kdy můžeme jíst sladkosti?', 'Jen občas',
    ['Ke každému jídlu', 'Místo oběda', 'Pořád'],
    ['Cukr škodí zubům.'],
    'Sladkosti jsou dobré jen občas, protože cukr škodí zubům. Bakterie v puse z něj vyrábějí kyselinu, která narušuje sklovinu.'),
  q('zelenina', 'Co z toho je zelenina?', 'Mrkev',
    ['Jablko', 'Banán', 'Jahoda'],
    ['Roste v zemi a má zelenou nať.'],
    'Mrkev je zelenina – jíme její kořen. Jablko, banán i jahoda jsou ovoce.'),
  q('ovoce', 'Co z toho je ovoce?', 'Hruška',
    ['Mrkev', 'Brambora', 'Rohlík'],
    ['Roste na stromě.'],
    'Hruška je ovoce, které roste na stromě. Mrkev je zelenina, brambora hlíza a rohlík pečivo.'),
  q('pohyb', 'Proč je dobré hodně se hýbat a hrát si venku?', 'Tělo je pak silné a zdravé.',
    ['Aby nás bolelo břicho.', 'Aby se nám hůř spalo.', 'Pohyb tělu škodí.'],
    ['Co se děje se svaly, když je používáš?'],
    'Pohyb posiluje svaly, kosti i srdce. Venku navíc dýcháme čerstvý vzduch.'),
  q('horecka', 'Co uděláš, když ti je zle a máš horečku?', 'Řeknu to dospělému a budu odpočívat.',
    ['Půjdu hrát fotbal.', 'Nikomu nic neřeknu.', 'Sním hodně bonbonů.'],
    ['Kdo se o tebe postará?'],
    'Když je ti zle, řekni to dospělému – nemoc se nejlépe léčí odpočinkem, pitím a péčí. Horečka je znamení, že tělo bojuje s bacily.'),
  q('snih', 'Co si vezmeš na sebe, když venku sněží?', 'Teplou bundu, čepici a rukavice',
    ['Plavky', 'Tričko a kraťasy', 'Sandály'],
    ['Venku je zima.'],
    'V zimě se oblékáme teple, aby tělo neprochladlo. Víc tenkých vrstev hřeje lépe než jedna tlustá, protože mezi nimi zůstává teplý vzduch.'),
  q('slunce-hlava', 'Co si dáš na hlavu, když silně svítí slunce?', 'Čepici nebo klobouk',
    ['Nic, hlava slunce vydrží', 'Rukavice', 'Šálu'],
    ['Hlavu je potřeba chránit před úpalem.'],
    'Pokrývka hlavy chrání před úpalem. V horku se také schovej do stínu a pij.'),
  q('opalovaci-krem', 'Čím si chráníš kůži před sluncem?', 'Opalovacím krémem',
    ['Zubní pastou', 'Mýdlem', 'Vodou z louže'],
    ['Maže se to na kůži před koupáním i na výletě.'],
    'Opalovací krém chrání kůži před spálením od slunce. Slunce pálí i přes mraky, a tak se krém hodí, i když je zataženo.'),
  q('tablet-oci', 'Dlouho se díváš na tablet a pálí tě oči. Co uděláš?', 'Udělám přestávku a podívám se z okna do dálky.',
    ['Přiblížím si tablet k očím.', 'Budu se dívat ještě déle.', 'Zhasnu a budu se dívat potmě.'],
    ['Oči potřebují odpočinek.'],
    'Oči potřebují pauzu: podívej se do dálky, zamrkej a jdi se protáhnout. U obrazovky totiž mrkáme mnohem méně než jindy.'),
];

// ---------------------------------------------------------------------------
// L2 – proč to děláme: bacily, spánek, pestré jídlo, pitný režim

const L2: Spec[] = [
  q('snidane', 'Proč je dobré snídat?', 'Snídaně dodá energii na dopoledne.',
    ['Po snídani se nesmí pít.', 'Snídaně je jen pro dospělé.', 'Snídaně nás uspí.'],
    ['Kolik hodin v noci tělo nic nejí?'],
    'Ráno je tělo po dlouhé noci bez jídla a snídaně mu dodá energii na učení i hraní. Hodně energie spotřebuje i mozek, i když jen sedíme v lavici.'),
  q('bacily-co', 'Co jsou bacily?', 'Drobné bakterie a viry, které mohou způsobit nemoc',
    ['Malí brouci, které vidíme na listech', 'Druh ovoce', 'Barevné kamínky'],
    ['Jsou tak malé, že je nevidíme.'],
    'Bacily jsou maličké bakterie a viry – uvidíme je jen mikroskopem a některé mohou způsobit nemoc. Většina bakterií je ale neškodná a spousta nám dokonce pomáhá, třeba ve střevech.'),
  q('lahev', 'Proč se nenapijeme z lahve kamaráda, který má rýmu?', 'Bacily by mohly přejít na nás.',
    ['Lahev by se rozbila.', 'Pití by zmizelo.', 'Kamarád by hned přestal mít rýmu.'],
    ['Na lahvi zůstávají sliny.'],
    'Na lahvi mohou zůstat bacily, a proto každý pije ze svého hrnku nebo lahve. Rýma se šíří i slinami a kapičkami z nosu.'),
  q('ruce-jak', 'Jak si správně umyjeme ruce?', 'Namydlíme je i mezi prsty a pod nehty a opláchneme.',
    ['Jen je namočíme.', 'Jen si je utřeme do kalhot.', 'Jen si foukneme do dlaní.'],
    ['Bacily se schovávají i mezi prsty.'],
    'Ruce namydlíme ze všech stran, i mezi prsty a pod nehty, a pak je opláchneme a utřeme. Nejčastěji zapomínáme na palce a konečky prstů.'),
  q('ruce-jak-dlouho', 'Jak dlouho si mydlíme ruce?', 'Asi jako dvakrát zazpívat Hodně štěstí, zdraví',
    ['Jen jedno mrknutí', 'Celou hodinu', 'Vůbec, stačí je otřít'],
    ['Mýdlo potřebuje chvilku, aby bacily smylo.'],
    'Mydlit se má aspoň 20 sekund – to je zhruba jako dvakrát zazpívat Hodně štěstí, zdraví.'),
  q('spanek-proc', 'Proč potřebujeme dost spát?', 'Tělo odpočívá a roste a mozek si ukládá, co se naučil.',
    ['Abychom měli méně času na hraní.', 'Spánek tělo unavuje.', 'Abychom ráno měli hlad.'],
    ['Co se děje s tělem v noci?'],
    'Ve spánku tělo odpočívá a roste a mozek si ukládá, co se přes den naučil. Hodně růstového hormonu se uvolňuje právě v hlubokém spánku.'),
  q('usnout', 'Co pomáhá dobře usnout?', 'Klid a ztlumené světlo před spaním',
    ['Hraní na tabletu v posteli', 'Sladká limonáda', 'Hlasitá hudba'],
    ['Mozek se potřebuje zklidnit.'],
    'Před spaním pomáhá klid, ztlumené světlo a třeba pohádka. Tablet a hlasitá hudba mozek spíš povzbudí.'),
  q('talir', 'Jak vypadá zdravý talíř?', 'Pestře – zelenina, příloha i bílkoviny',
    ['Jen sladkosti', 'Jen maso', 'Jen rohlíky'],
    ['Tělo potřebuje různé látky z různých jídel.'],
    'Zdravé jídlo je pestré: hodně zeleniny a ovoce, k tomu pečivo nebo příloha a bílkoviny, třeba vejce, maso, ryba nebo luštěniny.'),
  q('bilkoviny', 'Kde najdeš hodně bílkovin?', 'Ve vejcích a fazolích',
    ['V limonádě', 'V bonbonech', 'V ledu'],
    ['Tělo z nich staví svaly.'],
    'Bílkoviny jsou ve vejcích, mase, rybách, mléčných výrobcích a luštěninách. Tělo z nich staví svaly.'),
  q('lusteniny', 'Co jsou luštěniny?', 'Čočka, fazole a hrách',
    ['Jablka a hrušky', 'Rohlíky a chleba', 'Bonbony a lízátka'],
    ['Rostou v luscích.'],
    'Luštěniny jsou semena rostlin, která rostou v luscích – čočka, fazole nebo hrách. Mají hodně bílkovin.'),
  q('pecivo', 'Co z toho je pečivo?', 'Rohlík',
    ['Mrkev', 'Sýr', 'Hruška'],
    ['Peče se to v pekárně z mouky.'],
    'Rohlík je pečivo a pečivo i obiloviny dodávají tělu energii. Nejvíc živin má celozrnné pečivo.'),
  q('zelenina-proc', 'Proč jíme zeleninu?', 'Má vitaminy a vlákninu.',
    ['Aby nám zezelenala kůže.', 'Je sladká jako bonbony.', 'Nemá to žádný důvod.'],
    ['Co tělo potřebuje, aby bylo zdravé?'],
    'Zelenina obsahuje vitaminy a vlákninu. Pomáhá tělu být zdravé a střevům dobře pracovat.'),
  q('kolikrat-jist', 'Jak často je dobré během dne jíst?', 'Pravidelně – asi pětkrát denně',
    ['Jednou za den', 'Jen o svátcích', 'Pořád, bez přestávky'],
    ['Vzpomeň si: snídaně, přesnídávka, oběd…'],
    'Dětem prospívá jíst pravidelně: snídaně, přesnídávka, oběd, svačina a večeře. Menší porce častěji dodávají energii rovnoměrně celý den.'),
  q('sport-piti', 'Co je nejlepší pít při sportu?', 'Vodu',
    ['Energetický nápoj', 'Kolu', 'Nic'],
    ['Při sportu se potíš.'],
    'Při sportu se potíme a tělo potřebuje doplnit vodu. Nejlepší je obyčejná voda.'),
  q('horko-piti', 'Proč v horku pijeme víc?', 'Tělo se víc potí a ztrácí vodu.',
    ['Voda v horku chutná jinak.', 'V horku tělo vodu nepotřebuje.', 'Abychom se zahřáli.'],
    ['Co dělá tělo, když je mu horko?'],
    'V horku se víc potíme, a aby tělo neztratilo příliš vody, musíme ji doplňovat. Nejlepší je napít se dřív, než přijde velká žízeň.'),
  q('kartacek-vymena', 'Jak často se mění kartáček na zuby?', 'Asi jednou za tři měsíce',
    ['Jednou za deset let', 'Každý den', 'Nikdy'],
    ['Štětiny se časem rozcuchají.'],
    'Kartáček se mění zhruba každé tři měsíce, nebo dřív, když má rozcuchané štětiny. Rozcuchaný kartáček už zuby tak dobře nečistí.'),
  q('zuby-vecer', 'Proč si čistíme zuby i večer?', 'Aby na nich přes noc nezůstaly zbytky jídla.',
    ['Aby zuby svítily ve tmě.', 'Aby se nám zdály hezčí sny.', 'Večer si zuby čistit nemusíme.'],
    ['Přes noc jsou zuby dlouho bez čištění.'],
    'Přes noc by zbytky jídla a bacily škodily zubům, a proto je večerní čištění tak důležité. Bakterie totiž z cukru vyrábějí kyselinu, která narušuje sklovinu.'),
  q('zubar', 'Co potřebují zuby kromě čištění?', 'Pravidelné prohlídky u zubaře',
    ['Hodně bonbonů', 'Kousání tužek', 'Otvírání lahví zuby'],
    ['Kdo se stará o zdravé zuby?'],
    'Zubař při prohlídce zkontroluje, jestli jsou zuby zdravé. Malý problém se tak dá opravit včas.'),
  q('obrazovka', 'Co dělat, když se dlouho díváš do obrazovky?', 'Dělat přestávky a dívat se do dálky.',
    ['Dívat se co nejblíž.', 'Nemrkat.', 'Dívat se potmě.'],
    ['Oči se při dlouhém koukání unaví.'],
    'Oči potřebují přestávky: pomáhá podívat se z okna do dálky, zamrkat a protáhnout se. Při pohledu do dálky si svaly v oku odpočinou.'),
  q('venku', 'Proč je dobré chodit ven na čerstvý vzduch?', 'Hýbeme se a dýcháme čerstvý vzduch.',
    ['Venku se nedá hýbat.', 'Čerstvý vzduch škodí.', 'Abychom se nemuseli mýt.'],
    ['Co děláš venku nejčastěji?'],
    'Venku se víc hýbeme a dýcháme čerstvý vzduch, a to prospívá tělu i náladě. Denní světlo navíc seřizuje vnitřní hodiny těla, takže se pak lépe spí.'),
  q('sladkosti-proc', 'Proč jíme sladkosti jen občas?', 'Cukr škodí zubům.',
    ['Sladkosti jsou kyselé.', 'Sladkosti nás uspí.', 'Sladkosti jsou jen pro psy.'],
    ['Co mají rády bakterie v puse?'],
    'Z cukru si bakterie v puse dělají kyselinu, která škodí zubům. Proto jsou sladkosti jen občas.'),
  q('nemoc-doma', 'Kdy je lepší zůstat doma ze školy?', 'Když mám horečku',
    ['Když mám nové boty', 'Když prší', 'Když je pondělí'],
    ['Kdy by ses {mohla|mohl} ve škole cítit špatně a nakazit ostatní?'],
    'S horečkou patříš do postele. Doma se rychleji uzdravíš a nenakazíš ostatní.'),
  q('loket-proc', 'Proč kýcháme do lokte, a ne do dlaně?', 'Z dlaně bychom bacily roznesli všude, kam sáhneme.',
    ['Loket je teplejší.', 'Do dlaně se kýchat nedá.', 'Loket bacily sní.'],
    ['Čím se dotýkáš klik a hraček?'],
    'Dlaní se dotýkáme klik, hraček i kamarádů. Proto kýcháme do lokte nebo do kapesníku.'),
  q('rucnik', 'Proč má každý svůj ručník?', 'Aby se nepřenášely bacily.',
    ['Aby se ručníky nepomíchaly barvou.', 'Protože ručníky jsou těžké.', 'Aby se ručník rychleji ušpinil.'],
    ['Ručníkem si utíráme obličej i ruce.'],
    'Na ručníku mohou zůstat bacily, a když má každý svůj, nemoci se tak snadno nešíří. Ručník má také dobře uschnout – ve vlhku se bacilům daří.'),
  q('pohyb-denne', 'Jaký pohyb je pro děti dobrý každý den?', 'Hraní venku, běhání nebo jízda na kole',
    ['Celý den sezení na gauči', 'Jen pohyb prstů po tabletu', 'Žádný pohyb'],
    ['Při čem se zadýcháš?'],
    'Děti by se měly hýbat každý den – běhat, skákat, jezdit na kole nebo tancovat. Lékaři doporučují aspoň hodinu pohybu denně.'),
];

// ---------------------------------------------------------------------------
// L3 – zuby, spánek, vitaminy, obranyschopnost, pitný režim

const L3: Spec[] = [
  q('kaz', 'Jak vzniká zubní kaz?', 'Bakterie z cukru vyrábějí kyselinu, která narušuje zuby.',
    ['Zuby se unaví od mluvení.', 'Zuby se rozpustí ve vodě.', 'Kaz vzniká z čištění zubů.'],
    ['Souvisí to se sladkostmi.'],
    'Bakterie na zubech se živí cukrem a vyrábějí kyselinu. Ta narušuje sklovinu a vznikne díra – zubní kaz.'),
  q('sklovina', 'Co je nejtvrdší látka v lidském těle?', 'Zubní sklovina',
    ['Kost', 'Nehet', 'Vlas'],
    ['Je to bílý povrch zubů.'],
    'Nejtvrdší látka v těle je zubní sklovina. I tu ale dokáže kyselina od bakterií narušit.'),
  q('zubar-kolikrat', 'Jak často chodí děti na preventivní prohlídku k zubaři?', 'Dvakrát do roka',
    ['Jednou za deset let', 'Každý den', 'Jen když zub vypadne'],
    ['Je to častěji než jednou za rok.'],
    'Děti chodí na preventivní prohlídku k zubaři dvakrát do roka. Zubař tak včas uvidí, jestli zuby něco nepotřebují.'),
  q('nit', 'Čím vyčistíme místa mezi zuby, kam kartáček nedosáhne?', 'Zubní nití nebo mezizubním kartáčkem',
    ['Tužkou', 'Nehtem', 'Vidličkou'],
    ['Je to tenké a vejde se to mezi zuby.'],
    'Mezi zuby se dostane zubní nit nebo mezizubní kartáček a ze začátku pomáhá dospělý. Obyčejný kartáček mezery mezi zuby nevyčistí.'),
  q('spanek-skolak', 'Kolik hodin spánku potřebuje školák?', 'Zhruba 9 až 12 hodin',
    ['Zhruba 3 až 4 hodiny', 'Zhruba 6 až 7 hodin', 'Zhruba 15 až 18 hodin'],
    ['Je to víc, než potřebují dospělí.'],
    'Školní děti potřebují zhruba 9 až 12 hodin spánku. Každý je trochu jiný, ale spánek je pro růst i učení velmi důležitý.'),
  q('pohyb-hodina', 'Kolik pohybu denně potřebují děti?', 'Aspoň hodinu',
    ['Pět minut za týden', 'Vůbec žádný', 'Deset minut za měsíc'],
    ['Počítá se běhání, hraní i cesta pěšky.'],
    'Lékaři doporučují, aby se děti hýbaly aspoň hodinu denně. Počítá se běhání, hraní, tanec i cesta do školy pěšky.'),
  q('vitaminy', 'Co jsou vitaminy?', 'Látky, které tělo potřebuje, aby bylo zdravé',
    ['Druh bonbonů', 'Malí brouci', 'Kůstky v rybách'],
    ['Je jich hodně v ovoci a zelenině.'],
    'Vitaminy jsou látky, které tělo potřebuje v malém množství, a najdeme je hlavně v ovoci a zelenině. Vitamin D si ale tělo umí vyrobit samo – na slunci.'),
  q('vitamin-c', 'Kde najdeš hodně vitaminu C?', 'V paprice a citronu',
    ['V cukru', 'V soli', 'V bílém rohlíku'],
    ['Je to v ovoci a zelenině.'],
    'Hodně vitaminu C má paprika, šípky, citrusy nebo kiwi. Červená paprika ho má dokonce víc než citron.'),
  q('pestra-strava', 'Proč je dobré jíst pestře?', 'Každá potravina obsahuje jiné užitečné látky.',
    ['Aby talíř vypadal hezky na fotce.', 'Pestré jídlo je méně zdravé.', 'Aby se nemuselo pít.'],
    ['Najdeš všechny vitaminy v jedné potravině?'],
    'Každá potravina má jiné živiny a vitaminy. Když jíme pestře, tělo dostane všechno, co potřebuje.'),
  q('vlaknina', 'Kde najdeš hodně vlákniny?', 'V zelenině, ovoci a luštěninách',
    ['V limonádě', 'V bonbonech', 'Ve vodě'],
    ['Je v rostlinné potravě.'],
    'Vláknina je v zelenině, ovoci, luštěninách a celozrnném pečivu a pomáhá střevům dobře pracovat. Tělo ji skoro nestráví, ale živí se jí užitečné bakterie ve střevech.'),
  q('nejvic', 'Čeho z toho by mělo být v jídle během dne nejvíc?', 'Zeleniny a ovoce',
    ['Sladkostí', 'Chipsů', 'Sladkých limonád'],
    ['Má to hodně vitaminů a vlákniny.'],
    'Zelenina a ovoce by měly být v jídle každý den a v dostatku – klidně ať zaberou polovinu talíře. Sladkosti jen občas.'),
  q('pitny-rezim', 'Kdy je nejlepší pít?', 'Průběžně během celého dne',
    ['Jen jednou večer', 'Až když je hrozná žízeň', 'Jen o víkendu'],
    ['Tělo potřebuje vodu pořád.'],
    'Pít je dobré průběžně během dne, ne až když máme velkou žízeň. Nejlepší je voda.'),
  q('ockovani', 'Proč se děti očkují?', 'Očkování naučí tělo bránit se některým nemocem.',
    ['Aby rychleji rostly.', 'Aby nemusely spát.', 'Aby měly silnější zuby.'],
    ['Souvisí to s nemocemi.'],
    'Očkování ukáže tělu, jak poznat určitou nemoc a bránit se jí. Když pak na tu nemoc narazí, je připravené.'),
  q('horecka-proc', 'Proč máme při nemoci horečku?', 'Tělo tak bojuje s nemocí.',
    ['Tělo se chce opálit.', 'Horečka vzniká z jídla.', 'Aby nás bolely vlasy.'],
    ['Je to jedna ze zbraní těla.'],
    'Horečka je jeden ze způsobů, jak tělo bojuje s bacily. Když je vysoká, pomůže dospělý nebo lékař.'),
  q('imunita', 'Jak se jmenuje schopnost těla bránit se nemocem?', 'Imunita',
    ['Rovnováha', 'Trávení', 'Dýchání'],
    ['Říká se jí také obranyschopnost.'],
    'Imunita neboli obranyschopnost je schopnost těla bránit se bacilům. Pomáhají jí bílé krvinky.'),
  q('imunita-pomaha', 'Co pomáhá tělu, aby se bránilo nemocem?', 'Spánek, pohyb a pestré jídlo',
    ['Celý den u obrazovky', 'Hodně sladkostí', 'Málo spánku'],
    ['Co dělá tělo silné?'],
    'Obranyschopnosti pomáhá dost spánku, pohyb, pobyt venku a pestré jídlo.'),
  q('nemocny', 'Proč nechodíme nemocní mezi ostatní?', 'Abychom nenakazili ostatní a sami se uzdravili.',
    ['Aby se ostatní nenudili.', 'Aby nám nikdo nesnědl svačinu.', 'Protože venku prší.'],
    ['Bacily se šíří z člověka na člověka.'],
    'Když jsme nemocní, bacily se snadno šíří na ostatní. Doma se navíc lépe uzdravíme.'),
  q('prenos', 'Jak se nejčastěji šíří rýma?', 'Kapénkami při kýchání a kašli a přes ruce',
    ['Pohledem do očí', 'Zvukem hlasu', 'Barvou oblečení'],
    ['Co vylétá z nosu při kýchnutí?'],
    'Při kýchání a kašli létají vzduchem drobné kapénky s viry. Další se dostanou na ruce a z nich do nosu nebo pusy.'),
  q('vetrani', 'Proč se ve třídě větrá?', 'Přivedeme čerstvý vzduch.',
    ['Aby vyletěly sešity.', 'Aby se ve třídě zhasla světla.', 'Aby se nemusela mýt tabule.'],
    ['Ve třídě dýchá hodně lidí.'],
    'Větráním se do místnosti dostane čerstvý vzduch a odvětrá se ten vydýchaný. Líp se pak přemýšlí.'),
  q('vrstvy', 'Proč se v zimě oblékáme do vrstev?', 'Mezi vrstvami se drží teplý vzduch.',
    ['Aby oblečení vydrželo déle.', 'Aby bylo vidět víc barev.', 'Aby se nám hůř chodilo.'],
    ['Co hřeje mezi dvěma tričky?'],
    'Mezi vrstvami oblečení zůstává teplý vzduch, který tělo hřeje. Když je teplo, jednu vrstvu sundáš.'),
  q('horko', 'Co je dobré dělat, když je venku velké horko?', 'Pít, být ve stínu a nosit pokrývku hlavy.',
    ['Běhat v poledne na slunci bez čepice.', 'Nepít, aby se nemuselo na záchod.', 'Obléct si zimní bundu.'],
    ['Jak předejít úpalu?'],
    'V horku je důležité pít, schovat se do stínu a nosit čepici nebo klobouk. Tak předejdeš úpalu.'),
  q('odpocinek', 'Proč je důležité odpočívat?', 'Tělo i mozek potřebují nabrat síly.',
    ['Odpočinek není vůbec potřeba.', 'Odpočinek tělo unaví.', 'Aby se zapomnělo, co jsme se naučili.'],
    ['Jak se cítíš po velkém výletě?'],
    'Po učení a sportu potřebuje tělo i mozek odpočinek, aby zase nabraly síly.'),
  q('po-sezeni', 'Co je dobré udělat po dlouhém sezení při učení?', 'Protáhnout se a projít.',
    ['Sedět ještě dvě hodiny bez hnutí.', 'Sníst sáček bonbonů.', 'Lehnout si s tabletem.'],
    ['Svaly potřebují pohyb.'],
    'Po delším sezení se protáhni a projdi. Svaly se uvolní a mozek se pak lépe soustředí.'),
  q('obrazovka-spani', 'Proč není dobré koukat do obrazovky těsně před spaním?', 'Obrazovka mozek povzbudí a hůř se usíná.',
    ['Obrazovka ve tmě zhasne.', 'Z obrazovky se kazí zuby.', 'Po obrazovce se spí déle.'],
    ['Mozek se před spaním potřebuje zklidnit.'],
    'Světlo z obrazovky a napínavé hry mozek povzbudí, a proto je lepší obrazovky před spaním vypnout. Světlo obrazovky mate vnitřní hodiny těla, jako by byl ještě den.'),
  q('nehty', 'Proč není dobré kousat si nehty?', 'Pod nehty jsou bacily, které by se dostaly do pusy.',
    ['Nehty jsou sladké.', 'Nehty pak rychleji rostou.', 'Zuby by se zlomily.'],
    ['Co se schovává pod nehty?'],
    'Pod nehty se schovává špína a bacily. Když nehty koušeš, dostanou se do pusy.'),
];

// ---------------------------------------------------------------------------
// L4 – denní režim, plánování času a prevence

const L4: Spec[] = [
  q('rezim-co', 'Co je denní režim?', 'Pravidelný plán dne – spánek, jídlo, učení, pohyb i odpočinek',
    ['Seznam hraček', 'Jídelní lístek v restauraci', 'Program v televizi'],
    ['Pomáhá, aby den měl řád.'],
    'Denní režim je pravidelný plán dne. Tělo si zvykne, kdy jí, kdy se učí, kdy si hraje a kdy spí.'),
  q('rezim-proc', 'Proč je dobré chodit spát a vstávat každý den zhruba ve stejnou dobu?', 'Tělo si zvykne a lépe spí.',
    ['Aby byl den kratší.', 'Aby se nám nechtělo snídat.', 'Na tom vůbec nezáleží.'],
    ['Tělo má své vnitřní hodiny.'],
    'Tělo má své vnitřní hodiny. Když chodíš spát pravidelně, snáz usneš a ráno se lépe probudíš.'),
  q('kdy-spat', 'Vstáváš v 7 hodin a chceš spát 10 hodin. V kolik hodin je dobré jít spát?', cas(21, 0),
    [cas(23, 0), cas(18, 0), cas(22, 30)],
    ['Počítej od 7 hodin ráno zpátky.', 'Kolik hodin je od večera do půlnoci a kolik od půlnoci do rána?'],
    'Od 21 do 24 hodin jsou 3 hodiny a od půlnoci do 7 hodin je 7 hodin, dohromady 10 hodin spánku. To je tak akorát – školáci potřebují zhruba 9 až 12 hodin.'),
  q('trenink', 'Trénink začíná v 16 hodin a cesta trvá 20 minut. Kdy musíš nejpozději vyrazit?', cas(15, 40),
    [cas(16, 20), cas(16, 0), cas(15, 20)],
    ['Musíš vyrazit dřív, než trénink začne.', 'Od 16 hodin odečti 20 minut.'],
    'Od začátku tréninku odečteme cestu: 16 hodin bez 20 minut je 15:40. V 15:40 přijdeš přesně včas – kdo vyrazí o pár minut dřív, stihne se v klidu i převléknout.'),
  q('ukol', 'Začneš psát úkol ve 14:30 a trvá ti půl hodiny. Kdy budeš mít hotovo?', cas(15, 0),
    [cas(14, 0), cas(15, 30), cas(16, 0)],
    ['Půl hodiny je 30 minut.'],
    'Ke 14:30 přičteme 30 minut a je 15:00. Po úkolu se hodí krátká přestávka s pohybem – mozek si odpočine a pak se zase lépe soustředí.',
    { speak: 'Začneš psát úkol ve 14 hodin 30 minut a trvá ti půl hodiny. Kdy budeš mít hotovo?' }),
  q('rano', 'Škola začíná v 8 hodin. Snídaně trvá 20 minut a cesta 15 minut. Kdy nejpozději musíš začít snídat?', cas(7, 25),
    [cas(7, 45), cas(7, 40), cas(8, 0)],
    ['Sečti, jak dlouho trvá snídaně a cesta dohromady.', 'Tolik minut odečti od 8 hodin.'],
    'Snídaně a cesta dohromady trvají 35 minut a 8 hodin bez 35 minut je 7:25. S pár minutami rezervy se ráno nemusí spěchat.'),
  q('volno', 'Máš volno od 14 do 17 hodin. Úkoly ti zaberou hodinu. Kolik času ti zbude na hraní a odpočinek?', '2 hodiny',
    ['3 hodiny', '1 hodina', '4 hodiny'],
    ['Kolik hodin je od 14 do 17?'],
    'Od 14 do 17 hodin jsou 3 hodiny, a když hodinu zaberou úkoly, zbudou 2 hodiny. Aspoň hodinu z nich stojí za to strávit pohybem – lékaři ho dětem doporučují každý den.'),
  q('den-plan', 'Který den je naplánovaný nejzdravěji?', 'Škola, oběd, hraní venku, úkoly, večeře, spánek',
    ['Škola, tablet až do noci, spánek po půlnoci', 'Škola, jen sladkosti, žádný pohyb', 'Celý den bez jídla a bez odpočinku'],
    ['Zdravý den má jídlo, pohyb, učení i spánek.'],
    'Zdravý den má pravidelné jídlo, učení, pohyb, odpočinek i dost spánku.'),
  q('prestavky', 'Proč je dobré při učení dělat krátké přestávky?', 'Mozek si odpočine a pak se lépe soustředí.',
    ['Aby učení trvalo do noci.', 'Přestávky mozku škodí.', 'Aby se zapomnělo, co jsme se naučili.'],
    ['Jak dlouho vydržíš dávat pozor bez přestávky?'],
    'Po chvíli soustředění se pozornost unaví. Krátká přestávka s trochou pohybu pomůže mozku, aby se zase dobře soustředil.'),
  q('uceni-po-kouskach', 'Na test máš tři dny. Jak se učit nejlépe?', 'Každý den kousek a pak si to zopakovat.',
    ['Všechno až poslední večer.', 'Vůbec se neučit.', 'Učit se jen ve spánku.'],
    ['Mozek si lépe pamatuje to, co opakuje víckrát.'],
    'Mozek si lépe zapamatuje, co opakuje několik dní po kouscích, než když se všechno učí najednou.'),
  q('test-spanek', 'Zítra píšeš test. Co ti pomůže nejvíc?', 'Zopakovat si učivo a jít včas spát.',
    ['Učit se až do půlnoci.', 'Nespat vůbec.', 'Hrát celou noc hry.'],
    ['Kdy si mozek ukládá, co ses {naučila|naučil}?'],
    'Mozek si ve spánku ukládá, co ses {naučila|naučil}. Po dobrém spánku si to lépe vybavíš.'),
  q('unava', 'Jak poznáš, že potřebuješ víc spánku?', 'Ráno se těžko probouzím a přes den jsem {unavená|unavený}.',
    ['Mám chuť na ovoce.', 'Rostou mi nehty.', 'Chce se mi zpívat.'],
    ['Jak se cítíš po krátké noci?'],
    'Když se ráno těžko probouzíš a přes den jsi {unavená|unavený}, tělo možná potřebuje víc spánku. Zkus chodit spát dřív.'),
  q('pohyb-plan', 'Proč má být v denním plánu i pohyb?', 'Posiluje srdce, svaly i kosti a pomáhá dobře spát.',
    ['Pohyb je potřeba jen o prázdninách.', 'Pohyb tělu škodí.', 'Aby zbylo méně času na jídlo.'],
    ['Co pohyb dělá se svaly a srdcem?'],
    'Pohyb každý den posiluje srdce, svaly i kosti. Po pohybu se také lépe usíná.'),
  q('krouzky', 'Proč by v týdnu neměl být každý den úplně plný kroužků?', 'Děti potřebují i volný čas a odpočinek.',
    ['Kroužky jsou zakázané.', 'Volný čas je zbytečný.', 'Aby zbylo víc času na tablet.'],
    ['Co ještě kromě kroužků potřebuješ?'],
    'Kroužky jsou fajn, ale tělo i hlava potřebují také volno – na hraní, odpočinek a rodinu.'),
  q('priprava', 'Proč je dobré si večer připravit věci do školy?', 'Ráno je pak méně spěchu.',
    ['Aby se aktovka nenudila.', 'Aby se ve škole dalo spát.', 'Nemá to žádný smysl.'],
    ['Jak vypadá ráno, když všechno hledáš?'],
    'Když si věci připravíš večer, ráno nemusíš spěchat a na nic nezapomeneš.'),
  q('vecer', 'Co je dobré udělat večer před spaním?', 'Vyčistit si zuby a chvíli si číst.',
    ['Hrát napínavou hru na tabletu.', 'Sníst velkou porci sladkostí.', 'Vypít kolu.'],
    ['Před spaním se hodí klid.'],
    'Před spaním pomáhá klid: vyčistit zuby, připravit si věci na ráno a chvíli si číst.'),
  q('obrazovka-cas', 'Jak rozumně plánovat čas u obrazovky?', 'Domluvit se s rodiči na čase a dělat přestávky',
    ['Dívat se, dokud se tablet nevybije', 'Dívat se místo spánku', 'Dívat se při jídle i při úkolech'],
    ['Na co dalšího musí zbýt čas?'],
    'Je dobré mít čas u obrazovky domluvený s rodiči a dělat přestávky. Zbyde tak čas na pohyb, hraní i spánek.'),
  q('prevence-co', 'Co znamená prevence?', 'Předcházet nemocem a úrazům',
    ['Léčit se až po úrazu', 'Nikdy nechodit k lékaři', 'Jíst jen sladkosti'],
    ['Děláme to dřív, než se něco stane.'],
    'Prevence je předcházení nemocem a úrazům: mytí rukou, přilba na kole, očkování nebo pestré jídlo.'),
  q('prevence-priklad', 'Co z toho je prevence?', 'Nosit na kole přilbu',
    ['Jezdit na kole bez přilby', 'Nemýt si ruce před jídlem', 'Chodit spát pozdě v noci'],
    ['Co chrání dřív, než se něco stane?'],
    'Přilba chrání hlavu dřív, než se něco stane. To je prevence – předcházení úrazům.'),
  q('prevence-ruce', 'Který zvyk nejvíc pomáhá, aby se nešířily nemoci?', 'Mytí rukou',
    ['Nošení barevných ponožek', 'Hraní na flétnu', 'Česání vlasů'],
    ['Čím se dotýkáme všeho kolem?'],
    'Mytí rukou mýdlem patří k nejlepším způsobům, jak zabránit šíření nemocí.'),
  q('chranice', 'Jak můžeš předejít úrazu na bruslích nebo koloběžce?', 'Nosit přilbu a chrániče.',
    ['Jezdit co nejrychleji z kopce.', 'Poslouchat při jízdě hlasitou hudbu ve sluchátkách.', 'Jezdit potmě bez světla.'],
    ['Co chrání hlavu, kolena a lokty?'],
    'Přilba a chrániče na kolena, lokty a zápěstí chrání při pádu. To je prevence úrazů.'),
  q('slunce', 'Jak předejdeš spálení od slunce?', 'Opalovací krém, pokrývka hlavy a v poledne stín',
    ['Opalovat se celé poledne', 'Namazat se jen jednou za léto', 'Chodit na slunce bez čepice'],
    ['Kdy slunce pálí nejvíc?'],
    'Kůži chrání opalovací krém, oblečení a pokrývka hlavy. Kolem poledne, kdy slunce pálí nejvíc, je nejlepší stín.'),
  q('prohlidka', 'Proč chodíme na preventivní prohlídky k dětskému lékaři, i když nejsme nemocní?', 'Lékař zkontroluje, jestli dobře rosteme a jsme zdraví.',
    ['Aby nám dal bonbon.', 'Protože nemáme co dělat.', 'Aby nás naučil počítat.'],
    ['Slovo „preventivní“ znamená „aby se předešlo potížím“.'],
    'Při preventivní prohlídce lékař zkontroluje růst, zrak, sluch i srdce. Případný problém tak zachytí včas.'),
  q('antibiotika', 'Pomohou antibiotika na nemoc, kterou způsobil virus?', 'Ne, antibiotika působí na bakterie, ne na viry.',
    ['Ano, antibiotika zničí všechny bacily.', 'Ano, ale jen v zimě.', 'Ano, když se jich vezme hodně.'],
    ['Viry a bakterie jsou různé bacily.'],
    'Antibiotika ničí bakterie, na viry nepůsobí, a proto je předepisuje jen lékař, když jsou opravdu potřeba. První antibiotikum, penicilin, objevil Alexander Fleming v obyčejné plísni.'),
  q('leky-kdo', 'Od koho si smíš vzít lék?', 'Od rodiče nebo od lékaře',
    ['Od kamaráda ze třídy', 'Od kohokoli, kdo ho nabízí', '{Sama|Sám} z lékárničky'],
    ['Kdo ví, jaký lék a kolik ho potřebuješ?'],
    'Léky bereš jen od rodiče, jiného dospělého, který se o tebe stará, nebo od lékaře. Každý lék má svou správnou dávku.'),
  q('lek-kamarada', 'Proč si nebereme léky kamaráda?', 'Každý lék je určený pro jiného člověka a jinou nemoc.',
    ['Protože by se kamarád zlobil.', 'Protože léky jsou vždycky hořké.', 'Klidně si je vzít můžeme.'],
    ['Kdo vybírá, jaký lék kdo dostane?'],
    'Lék a jeho dávku vybírá lékař pro konkrétního člověka. Cizí lék by mohl uškodit.'),
];

export const zdravi = bankSkill({
  id: ID,
  name: 'Zdraví a denní režim',
  description: 'Vede k hygienickým a zdravým návykům, rozumnému dennímu režimu, plánování času a prevenci nemocí.',
  rvp: {
    1: ['ČJS-3-5-01'],
    2: ['ČJS-3-5-01'],
    3: ['ČJS-3-5-01'],
    4: ['ČJS-5-5-01', 'ČJS-5-5-03', 'ČJS-5-5-06'],
  },
  ability: 'znalosti',
  showFact: true,
  banks: { 1: L1, 2: L2, 3: L3, 4: L4 },
});
