// Jak rosteme – období lidského života a co se v nich mění: růst, zuby,
// nové dovednosti, dospívání a stáří. Bez podrobností o rozmnožování.

import { bankSkill, path, q, type Spec } from './common';

const ID = 'telo.zivot';

// ---------------------------------------------------------------------------
// L3 – období života a jejich pořadí, zuby, první dovednosti

const L3: Spec[] = [
  q('po-miminku', 'Které období přichází hned po miminku?', 'Batole',
    ['Školák', 'Senior', 'Dospívající'],
    ['Je to malé dítě, které se učí chodit.'],
    'Po miminku přichází batole – malé dítě, které se učí chodit a mluvit.'),
  q('mezi', 'Které období je mezi batoletem a školákem?', 'Předškolák',
    ['Miminko', 'Dospělý', 'Senior'],
    ['Chodí do školky.'],
    'Mezi batoletem a školákem je předškolák – dítě, které chodí do školky.'),
  q('po-skolakovi', 'Které období přichází po školákovi?', 'Dospívající',
    ['Batole', 'Miminko', 'Předškolák'],
    ['Z dítěte se pomalu stává dospělý.'],
    'Po školním věku přichází dospívání. Z dítěte se postupně stává dospělý.'),
  q('po-dospelosti', 'Které období života přichází po dospělosti?', 'Stáří',
    ['Batolecí věk', 'Školní věk', 'Předškolní věk'],
    ['Lidem v tomto věku říkáme senioři.'],
    'Po dospělosti přichází stáří. Starším lidem říkáme senioři.'),
  q('poradi', 'Které pořadí je správné?', path('miminko', 'batole', 'předškolák', 'školák'),
    [path('batole', 'miminko', 'školák', 'předškolák'), path('školák', 'předškolák', 'batole', 'miminko'), path('miminko', 'školák', 'batole', 'předškolák')],
    ['Začni od nejmenšího.', 'Do školky se chodí před školou.'],
    'Nejdřív je miminko, pak batole, předškolák a školák. Potom přijde dospívání, dospělost a stáří.'),
  q('kdo-mleko', 'Kdo v prvních měsících života pije jen mléko?', 'Miminko', ['Školák', 'Dospívající', 'Dospělý', 'Senior'],
    ['Nemá ještě zoubky.'],
    'Miminka v prvních měsících pijí jen mléko. Až později ochutnávají kašičky a další jídlo.'),
  q('kdo-chodit', 'Kdo se právě učí chodit?', 'Batole',
    ['Školák', 'Dospělý', 'Senior'],
    ['Říká se, že se „batolí“.'],
    'Kolem prvních narozenin začínají děti chodit. Batole se ještě trochu kolébá – odtud jeho jméno.'),
  q('kdo-skolka', 'Kdo chodí do mateřské školy?', 'Předškolák',
    ['Miminko', 'Dospívající', 'Senior'],
    ['Je to dítě, které ještě nechodí do školy.'],
    'Předškoláci chodí do mateřské školy. Hrají si, zpívají a připravují se na školu.'),
  q('kdo-cte', 'Kdo se ve škole učí číst, psát a počítat?', 'Školák',
    ['Batole', 'Miminko', 'Senior'],
    ['To teď děláš i ty.'],
    'Školáci se učí číst, psát a počítat. To teď děláš i ty!'),
  q('kdo-prace', 'Kdo obvykle chodí do práce a stará se o domácnost?', 'Dospělý',
    ['Batole', 'Miminko', 'Předškolák'],
    ['Mohou to být třeba tvoji rodiče.'],
    'Dospělí většinou pracují a starají se o domácnost a o děti.'),
  q('kdo-duchod', 'Kdo už často nechodí do práce a je v důchodu?', 'Senior',
    ['Školák', 'Předškolák', 'Batole'],
    ['Může to být třeba tvoje babička nebo děda.'],
    'Senioři jsou často v důchodu. Mají víc času na vnoučata, zahradu nebo koníčky.'),
  q('kdo-spi', 'Kdo spí ze všech nejvíc?', 'Miminko',
    ['Školák', 'Dospělý', 'Senior'],
    ['Je ze všech nejmenší.'],
    'Novorozená miminka prospí většinu dne i noci. Ve spánku rychle rostou.'),
  q('uci-se-prvni', 'Co se miminko učí jako jedno z prvních?', 'Držet hlavičku',
    ['Číst knihy', 'Jezdit na kole', 'Psát úkoly'],
    ['Než se naučí sedět, musí unést hlavu.'],
    'Miminko se nejdřív učí držet hlavičku, pak se přetáčet, sedět, lézt a nakonec chodit.'),
  q('poradi-pohybu', 'V jakém pořadí se miminko obvykle učí pohyby?', path('držet hlavičku', 'sedět', 'lézt', 'chodit'),
    [path('chodit', 'lézt', 'sedět', 'držet hlavičku'), path('sedět', 'chodit', 'držet hlavičku', 'lézt'), path('lézt', 'držet hlavičku', 'chodit', 'sedět')],
    ['Chůze přijde až nakonec.'],
    'Nejdřív miminko udrží hlavičku, pak se naučí sedět, lézt a nakonec chodit. Každé dítě ale svým tempem.'),
  q('prvni-slova', 'Kdy děti obvykle říkají první slova?', 'Kolem prvních narozenin',
    ['Hned po narození', 'Až v deseti letech', 'Až ve škole'],
    ['Je to zhruba ve stejné době, kdy se učí chodit.'],
    'První slova, třeba máma nebo táta, děti obvykle řeknou kolem prvního roku.'),
  q('skola', 'V kolika letech začínají děti v Česku obvykle chodit do školy?', 'V šesti letech',
    ['Ve dvou letech', 'V deseti letech', 'V patnácti letech'],
    ['Kolik ti bylo, když jsi šla do první třídy?'],
    'Povinná školní docházka začíná v Česku obvykle v šesti letech. Někdo jde do školy o rok později.'),
  q('zuby-vypadavaji', 'Kdy začínají dětem vypadávat mléčné zuby?', 'Zhruba v šesti letech',
    ['Hned po narození', 'Ve dvou letech', 'Ve třiceti letech'],
    ['Je to zhruba v době, kdy se jde do školy.'],
    'Mléčné zuby začínají vypadávat zhruba v šesti letech. Na jejich místo rostou zuby stálé.'),
  q('stale-zuby', 'Co roste na místě vypadlého mléčného zubu?', 'Stálý zub',
    ['Další mléčný zub', 'Nic, zůstane díra', 'Zub moudrosti'],
    ['Tento zub už ti vydrží celý život.'],
    'Pod mléčnými zuby čekají zuby stálé. Ty už nám vydrží celý život, proto se o ně dobře starej.'),
  q('mlecne-pocet', 'Kolik mléčných zubů má dítě?', '20',
    ['10', '32', '100'],
    ['Mléčných zubů je méně než stálých.'],
    'Dítě má 20 mléčných zubů. Stálých zubů má dospělý víc – až 32.'),
  q('rust-nejrychleji', 'Kdy člověk roste nejrychleji?', 'V prvním roce života',
    ['Ve stáří', 'V dospělosti', 'Po šedesátce'],
    ['Vzpomeň si, jak malá jsou novorozená miminka.'],
    'Nejrychleji rosteme v prvním roce života. Další velký růst přichází v dospívání.'),
  q('kazdy-jinak', 'Kamarádka je menší než ty, i když je stejně stará. Je to v pořádku?', 'Ano, každý roste jinak rychle.',
    ['Ne, všichni stejně staří musí být stejně velcí.', 'Ne, menší děti nemůžou do školy.', 'Ne, výška se dá změnit kouzlem.'],
    ['Jsou všichni lidé stejně velcí?'],
    'Každé dítě roste svým tempem. Někdo vyroste dřív, někdo později – obojí je v pořádku.'),
  q('dospivani', 'Co se děje v dospívání?', 'Tělo roste a mění se z dětského na dospělé.',
    ['Člověk se zmenšuje.', 'Vypadají všechny stálé zuby.', 'Člověk se znovu učí chodit.'],
    ['Z dítěte se stává dospělý.'],
    'V dospívání člověk rychle roste a jeho tělo se postupně mění na dospělé. U každého to začne trochu jindy.'),
  q('senior-sluch', 'Co pomáhá mnoha seniorům, kteří hůř slyší?', 'Naslouchátko',
    ['Dudlík', 'Kočárek', 'Aktovka'],
    ['Nosí se u ucha.'],
    'Ve stáří se sluch i zrak mohou zhoršovat. Pomáhají naslouchátka a brýle.'),
  q('senior-vlasy', 'Co se ve stáří často děje s vlasy?', 'Šediví nebo bělají.',
    ['Zezelenají.', 'Začnou svítit.', 'Samy se ostříhají.'],
    ['Podívej se na vlasy babičky nebo dědy.'],
    'Ve stáří vlasy často šediví nebo bělají, protože v nich přestává vznikat barvivo.'),
  q('babicka', 'Proč je dobré povídat si s babičkou a dědou?', 'Mají hodně zkušeností a vzpomínek.',
    ['Protože nic nevědí.', 'Protože nemají čas.', 'Protože neumějí mluvit.'],
    ['Zažili už hodně let.'],
    'Senioři toho hodně zažili. Od babičky a dědy se můžeš dozvědět, jak se žilo dřív, a naučit se spoustu věcí.'),
];

// ---------------------------------------------------------------------------
// L4 – přesnější názvy období, zuby, dovednosti, rodina a ohleduplnost

const L4: Spec[] = [
  q('novorozenec', 'Jak se říká miminku v prvních týdnech po narození?', 'Novorozenec',
    ['Batole', 'Předškolák', 'Senior'],
    ['Je úplně „nový“ na světě.'],
    'Novorozenec je miminko v prvních čtyřech týdnech po narození.'),
  q('kojenec', 'Jak se říká miminku do jednoho roku?', 'Kojenec',
    ['Dospívající', 'Školák', 'Senior'],
    ['Pije hlavně mléko.'],
    'Dítě do prvních narozenin se nazývá kojenec. Pak se z něj stává batole.'),
  q('batole-vek', 'Kolik let je obvykle batoleti?', 'Zhruba jeden až tři roky',
    ['Zhruba deset až dvanáct let', 'Zhruba dvacet let', 'Zhruba šedesát let'],
    ['Batole už chodí, ale do školky ještě většinou nechodí.'],
    'Batoletem je dítě zhruba od prvních do třetích narozenin.'),
  q('predskolak-vek', 'Kolik let je obvykle předškolákovi?', 'Zhruba tři až šest let',
    ['Zhruba jeden rok', 'Zhruba patnáct let', 'Zhruba čtyřicet let'],
    ['Je to doba školky.'],
    'Předškolní věk je zhruba od tří do šesti let – to je doba školky.'),
  q('povinna-skolka', 'Který rok ve školce je v Česku povinný?', 'Poslední rok před školou',
    ['Žádný', 'Jen první rok', 'Všechny roky od narození'],
    ['Je to příprava na první třídu.'],
    'V Česku je povinný poslední rok předškolního vzdělávání, tedy rok před nástupem do školy.'),
  q('prvni-zoubky', 'Kdy obvykle miminku vyrostou první zoubky?', 'Kolem půl roku',
    ['Hned při narození', 'Ve dvou letech', 'V šesti letech'],
    ['Většina miminek se rodí bez zubů.'],
    'První zoubky se obvykle objeví kolem půl roku, u každého dítěte trochu jindy.'),
  q('sestileta-stolicka', 'Který stálý zub roste kolem šesti let vzadu za mléčnými zuby?', 'Šestiletá stolička',
    ['Zub moudrosti', 'Mléčný řezák', 'Mléčný špičák'],
    ['Jmenuje se podle věku, kdy roste.'],
    'Kolem šesti let roste vzadu za mléčnými zuby první stálá stolička – šestiletá stolička. Nic kvůli ní nevypadne, proto si jí nemusíš všimnout. Čisti ji pečlivě!'),
  q('stale-pocet', 'Kolik stálých zubů může mít dospělý?', 'Až 32',
    ['Jen 10', 'Přesně 20', 'Až 100'],
    ['Je jich víc než mléčných zubů.'],
    'Dospělý může mít až 32 stálých zubů, včetně zubů moudrosti. Mléčných zubů je 20.'),
  q('zuby-moudrosti', 'Kdy rostou zuby moudrosti?', 'Až v dospělosti, a někomu vůbec',
    ['U miminek', 'V pěti letech', 'Až po osmdesátce'],
    ['Jsou to poslední zuby, které rostou.'],
    'Zuby moudrosti rostou nejčastěji mezi 17 a 25 lety. Někomu nevyrostou vůbec.'),
  q('konec-rustu', 'Kdy člověk obvykle přestane růst do výšky?', 'Na konci dospívání',
    ['V pěti letech', 'Nikdy', 'V osmdesáti letech'],
    ['Dospělí už nerostou.'],
    'Do výšky rosteme zhruba do konce dospívání. Potom kosti přestanou růst do délky.'),
  q('dospivani-kdy', 'Kdy začíná dospívání?', 'U každého trochu jindy',
    ['Všem přesně v den desátých narozenin', 'Hned po narození', 'Až v důchodu'],
    ['Rostou všichni stejně rychle?'],
    'Dospívání začíná u každého trochu jindy – u někoho dřív, u někoho později. Obojí je normální.'),
  q('dospivani-zmeny', 'Co se v dospívání mění?', 'Člověk rychle roste, mění se tělo i hlas.',
    ['Člověk se zmenšuje.', 'Vypadávají stálé zuby.', 'Člověk zapomene mluvit.'],
    ['Z dětského těla se stává dospělé.'],
    'V dospívání člověk rychle roste, tělo se mění na dospělé a hlas se prohlubuje, hlavně u kluků. Dospívající jsou také samostatnější.'),
  q('miminko-potrebuje', 'Co potřebuje miminko, aby dobře prospívalo?', 'Mléko, spánek, čistotu a hodně lásky',
    ['Tablet a sladkosti', 'Tvrdé jídlo a běhání', 'Samotu a ticho celý den'],
    ['Co potřebuje ten nejmenší člověk?'],
    'Miminko potřebuje mléko, spánek, čistotu, teplo a hodně mazlení a lásky.'),
  q('fontanela', 'Proč mají miminka na hlavě měkké místo?', 'Kosti lebky tam ještě nesrostly, aby hlava mohla růst.',
    ['Mají tam schovaný zub.', 'Je to místo pro čepici.', 'Nemají vůbec žádnou lebku.'],
    ['Mozek miminka rychle roste.'],
    'Měkkému místu na hlavě miminka se říká fontanela. Kosti lebky tam ještě nesrostly, aby mozek mohl růst. Během prvních let se zavře.'),
  q('batole-mluvi', 'Co batole obvykle zvládne kolem dvou let?', 'Mluvit v krátkých větách',
    ['Přečíst knihu', 'Napsat dopis', 'Jezdit samo na kole'],
    ['Učí se hodně nových slov.'],
    'Kolem druhého roku batolata mluví v krátkých větách, třeba „Tam auto“. Rychle se učí nová slova.'),
  q('predskolak-umi', 'Co už obvykle zvládne předškolák?', 'Obléknout se, kreslit a vyprávět',
    ['Řídit auto', 'Chodit do práce', 'Nic, jen spí'],
    ['Vzpomeň si, co jsi uměla ve školce.'],
    'Předškolák se obleče, nakreslí obrázek, zazpívá písničku a vypráví, co zažil.'),
  q('skolak-uci', 'Co se ve školním věku učíme kromě čtení a počítání?', 'Kamarádit a spolupracovat s ostatními',
    ['Chodit a lézt', 'Pít z lahve s dudlíkem', 'Řídit autobus'],
    ['Ve třídě je hodně dětí.'],
    'Ve školním věku se učíme číst, psát a počítat, ale i kamarádit, spolupracovat a řešit spory.'),
  q('dospely-dela', 'Co obvykle dělá dospělý?', 'Pracuje a stará se o domácnost',
    ['Chodí do školky', 'Učí se chodit', 'Pije jen mléko'],
    ['Mohou to být tvoji rodiče.'],
    'Dospělí obvykle pracují a starají se o domácnost. Mnozí se starají i o své děti nebo rodiče.'),
  q('senior-zdravi', 'Co pomáhá seniorům zůstat zdraví?', 'Pohyb, pestré jídlo a setkávání s lidmi',
    ['Celý den ležet', 'Nikam nechodit', 'S nikým nemluvit'],
    ['Co pomáhá zdraví v každém věku?'],
    'I ve stáří pomáhá pohyb, pestré jídlo, dobrý spánek a setkávání s rodinou a přáteli.'),
  q('tramvaj', 'Jak můžeš pomoct starší paní v tramvaji?', 'Pustit ji sednout',
    ['Předběhnout ji', 'Sednout si na její místo', 'Nevšímat si jí'],
    ['Pro koho je těžší stát, když se tramvaj rozjede?'],
    'Starší lidé se hůř udrží, když tramvaj zabrzdí nebo se rozjede. Pustit je sednout je ohleduplné a milé.'),
  q('rodokmen', 'Jak se jmenuje obrázek, na kterém je zakreslená celá rodina – prarodiče, rodiče i děti?', 'Rodokmen',
    ['Rozvrh', 'Mapa', 'Jídelníček'],
    ['Vypadá jako strom.'],
    'Rodokmen je jako strom rodiny. Ukazuje, kdo je čí rodič, dítě nebo sourozenec.'),
  q('generace', 'Kolik generací je v rodině, kde žije babička, maminka a dcera?', 'Tři',
    ['Jedna', 'Dvě', 'Pět'],
    ['Každá generace je o stupeň mladší.'],
    'Babička, maminka a dcera jsou tři generace. Každá další je o stupeň mladší.'),
  q('vnucka', 'Babička má dceru a ta má také dceru. Kým je ta nejmladší pro babičku?', 'Vnučkou',
    ['Sestrou', 'Tetou', 'Maminkou'],
    ['Je to dítě babiččina dítěte.'],
    'Dítě babiččina dítěte je její vnouče – vnučka nebo vnuk.'),
  q('rust-pomaha', 'Co pomáhá dětem dobře růst?', 'Dost spánku, pestré jídlo a pohyb',
    ['Hodně sladkostí', 'Málo spánku', 'Celý den u tabletu'],
    ['Kdy se uvolňuje růstový hormon?'],
    'Pro růst je důležitý dostatek spánku, pestré jídlo a pohyb – a také klid a láska doma.'),
  q('doziti', 'Kolika let se lidé v Česku dožívají v průměru?', 'Zhruba 80 let',
    ['Zhruba 20 let', 'Zhruba 200 let', 'Zhruba 1000 let'],
    ['Je to méně než sto let.'],
    'Lidé v Česku se v průměru dožívají zhruba 80 let. Někteří senioři se dožijí i sta let.'),
];

// ---------------------------------------------------------------------------
// L5 – vývoj podrobněji: kojenecký věk, puberta, stáří, dědičnost

const L5: Spec[] = [
  q('poradi-vse', 'Které pořadí období života je správné?',
    path('kojenec', 'batole', 'předškolák', 'školák', 'dospívající', 'dospělý', 'senior'),
    [
      path('batole', 'kojenec', 'předškolák', 'školák', 'dospělý', 'dospívající', 'senior'),
      path('kojenec', 'předškolák', 'batole', 'dospívající', 'školák', 'dospělý', 'senior'),
      path('kojenec', 'batole', 'školák', 'předškolák', 'dospívající', 'senior', 'dospělý'),
    ],
    ['Kojenec je miminko do jednoho roku.', 'Dospívání je mezi školním věkem a dospělostí.'],
    'Život má tato období: kojenec, batole, předškolák, školák, dospívající, dospělý a senior.'),
  q('mladsi-skolni', 'Jak se jmenuje období zhruba od šesti do jedenácti let?', 'Mladší školní věk',
    ['Kojenecký věk', 'Stáří', 'Dospělost'],
    ['Je to doba prvního stupně základní školy.'],
    'Období od nástupu do školy zhruba do jedenácti let je mladší školní věk. Pak přichází dospívání.'),
  q('novorozenec-doba', 'Jak dlouho je miminko novorozencem?', 'Zhruba první měsíc po narození',
    ['Celý první rok', 'Do tří let', 'Jen jeden den'],
    ['Je to jen krátká doba.'],
    'Novorozenecké období trvá první čtyři týdny po narození. Potom je z miminka kojenec až do prvních narozenin.'),
  q('kojenec-pije', 'Co nejčastěji pije kojenec v prvním půlroce?', 'Mateřské mléko nebo kojeneckou výživu',
    ['Kakao', 'Limonádu', 'Kávu'],
    ['Miminko ještě nemá zuby.'],
    'V prvních měsících kojenec pije mateřské mléko nebo speciální kojeneckou výživu. Další jídlo přichází postupně.'),
  q('prikrmy', 'Kdy obvykle začínají miminka ochutnávat kašičky a jiné jídlo?', 'Zhruba kolem půl roku',
    ['Hned první den', 'Ve třech letech', 'V deseti letech'],
    ['Je to ještě během kojeneckého věku.'],
    'Kolem půl roku miminko začíná ochutnávat kašičky a pyré. Mléko ale pije dál.'),
  q('prvni-zuby-ktere', 'Které zuby vyrostou miminku obvykle jako první?', 'Dolní přední zoubky',
    ['Stoličky vzadu', 'Zuby moudrosti', 'Horní špičáky'],
    ['Jsou vpředu.'],
    'Jako první obvykle vyrostou dolní přední zoubky – řezáky. Stoličky přicházejí později.'),
  q('novorozenec-zrak', 'Jak dobře vidí novorozenec?', 'Nejlépe na krátkou vzdálenost',
    ['Ostře až k obzoru', 'Vůbec nic, dokud nemá rok', 'Jen ve tmě'],
    ['Nejlépe vidí toho, kdo ho chová v náruči.'],
    'Novorozenec vidí nejostřeji na krátkou vzdálenost – zhruba na obličej toho, kdo ho chová. Zrak se pak rychle zlepšuje.'),
  q('fontanela-zavre', 'Kdy se miminku obvykle zavře měkké místo na hlavě – fontanela?', 'Většinou do dvou let',
    ['Hned po narození', 'Až v deseti letech', 'Nikdy'],
    ['Stane se to během batolecího věku nebo dřív.'],
    'Velká fontanela se většinou zavře mezi prvním a druhým rokem. Kosti lebky pak srostou.'),
  q('kosti-deti', 'Proč jsou kosti malých dětí pružnější než kosti dospělých?', 'Obsahují víc chrupavky.',
    ['Jsou z gumy.', 'Jsou úplně duté.', 'Nemají v sobě žádný vápník.'],
    ['Z chrupavky jsou i uši.'],
    'Kosti malých dětí obsahují víc chrupavky, a proto jsou pružnější. S věkem postupně zpevňují.'),
  q('batole-samo', 'Proč batolata často říkají „ne“ a „já sám“?', 'Učí se samostatnosti.',
    ['Nemají rády rodiče.', 'Neumějí jiná slova.', 'Jsou unavená z práce.'],
    ['Chtějí zkoušet, co zvládnou.'],
    'Kolem dvou až tří let chtějí děti dělat věci samy. Je to důležitý krok k samostatnosti.'),
  q('mozek-vyvoj', 'Kdy se mozek vyvíjí nejrychleji?', 'V prvních letech života',
    ['Ve stáří', 'Až v dospělosti', 'Mozek se nevyvíjí'],
    ['Malé děti se učí neuvěřitelně rychle.'],
    'Mozek roste a vyvíjí se nejrychleji v prvních letech života. Učit se ale můžeme celý život.'),
  q('uceni-zivot', 'Do kdy se může člověk učit nové věci?', 'Celý život',
    ['Jen do šesti let', 'Jen do konce školy', 'Jen v pondělí'],
    ['I dospělí chodí na kurzy.'],
    'Mozek se umí učit celý život. I babička se může naučit hrát na kytaru nebo nový jazyk.'),
  q('puberta', 'Jak se říká období, kdy se tělo mění z dětského na dospělé?', 'Puberta',
    ['Batolecí věk', 'Stáří', 'Kojenecký věk'],
    ['Je to část dospívání.'],
    'Puberta je část dospívání, kdy se tělo mění z dětského na dospělé. Člověk rychle roste a mění se mu i hlas.'),
  q('nalada', 'Proč mívají dospívající někdy proměnlivou náladu?', 'Tělo i mozek se v dospívání hodně mění.',
    ['Málo jedí bonbony.', 'Jsou už staří.', 'Nechodí do školky.'],
    ['V dospívání se mění víc než jen výška.'],
    'V dospívání se mění tělo i mozek a přibývá nových pocitů. Proměnlivá nálada k tomu někdy patří.'),
  q('dospivajici-spanek', 'Proč dospívající často usínají později?', 'Jejich vnitřní hodiny se posunou.',
    ['Nepotřebují spát.', 'Bojí se tmy.', 'Jsou senioři.'],
    ['Tělo má vnitřní hodiny, které se s věkem mění.'],
    'V dospívání se vnitřní hodiny těla posunou a usíná se později. Spánku ale dospívající potřebují pořád hodně – zhruba 8 až 10 hodin.'),
  q('rustovy-hormon', 'Co v těle hlavně řídí růst?', 'Růstový hormon',
    ['Žluč', 'Sliny', 'Ušní maz'],
    ['Hodně se ho uvolňuje ve spánku.'],
    'Růst řídí hlavně růstový hormon. Hodně se ho uvolňuje v hlubokém spánku.'),
  q('vyska', 'Na čem hlavně záleží, jak vysoký člověk vyroste?', 'Na výšce rodičů a také na spánku a jídle',
    ['Na barvě očí', 'Na oblíbené písničce', 'Na barvě pokoje'],
    ['Něco dědíme po rodičích.'],
    'Výška se hodně dědí po rodičích. Pomáhá ale i dostatek spánku, pestré jídlo a pohyb.'),
  q('podobnost', 'Proč se děti často podobají rodičům?', 'Dědí po nich vlohy, třeba barvu očí.',
    ['Nosí stejné oblečení.', 'Jedí stejné jídlo.', 'Spí ve stejném domě.'],
    ['Něco si neseme od narození.'],
    'Každý dostane od obou rodičů „návod“ na stavbu těla. Proto se děti podobají mámě i tátovi, ale každé je jedinečné.'),
  q('dvojcata', 'Jednovaječná dvojčata vypadají skoro stejně. Mají i stejné otisky prstů?', 'Ne, otisky prstů má každý jiné.',
    ['Ano, úplně stejné.', 'Ano, ale jen na palci.', 'Dvojčata otisky prstů nemají.'],
    ['Otisky prstů jsou jedinečné.'],
    'I jednovaječná dvojčata mají různé otisky prstů. Otisky se tvoří ještě před narozením a u každého jsou jedinečné.'),
  q('jedinecny', 'Proč každý člověk vypadá trochu jinak?', 'Každý zdědí jinou kombinaci vloh a žije jinak.',
    ['Rozhodne se tak každé ráno.', 'Má jiné boty.', 'Všichni lidé vypadají úplně stejně.'],
    ['Co dostáváme od rodičů?'],
    'Každý člověk je jedinečný – zdědí jinou kombinaci vloh od rodičů a každý žije trochu jinak.'),
  q('stari-telo', 'Co se ve stáří často děje s tělem?', 'Kůže je méně pružná, vlasy šediví a síla ubývá.',
    ['Rostou nové mléčné zuby.', 'Člověk rychle roste do výšky.', 'Vrací se dětský hlas.'],
    ['Podívej se na ruce babičky nebo dědy.'],
    'Ve stáří je kůže méně pružná, vlasy šediví a svaly slábnou. Pohyb a zdravý život pomáhají zůstat svěží.'),
  q('stari-kosti', 'Proč by se měli senioři chránit před pády?', 'Jejich kosti bývají křehčí.',
    ['Jejich kosti jsou z gumy.', 'Nemají žádné kosti.', 'Pád jim nevadí.'],
    ['Co se děje s kostmi ve stáří?'],
    'Ve stáří mohou být kosti křehčí a snáz se zlomí. Pomáhají pevná madla, dobré světlo a pohodlné boty.'),
  q('stari-mozek', 'Co pomáhá udržet mozek v kondici i ve stáří?', 'Učení, čtení, hry a setkávání s lidmi',
    ['Celý den nic nedělat', 'Nikdy nečíst', 'S nikým nemluvit'],
    ['Mozek je trochu jako sval.'],
    'Mozek je trochu jako sval – když ho používáme, zůstává v kondici. Pomáhají čtení, hry, učení i povídání s lidmi.'),
  q('plnoletost', 'V kolika letech je člověk v Česku plnoletý?', 'V 18 letech',
    ['V 10 letech', 'V 15 letech', 'Ve 30 letech'],
    ['Je to na konci dospívání.'],
    'Plnoletost začíná v 18 letech. Člověk pak může třeba volit.'),
  q('obcanka', 'Od kolika let musí mít každý občan Česka občanský průkaz?', 'Od 15 let',
    ['Od 6 let', 'Od 60 let', 'Hned od narození'],
    ['Je to ještě před plnoletostí.'],
    'Od 15 let musí mít každý občan Česka občanský průkaz. Mladší děti ho mít mohou, ale nemusí.'),
];

export const zivot = bankSkill({
  id: ID,
  name: 'Jak rosteme',
  description: 'Seznamuje s obdobími lidského života, s tím, jak se člověk mění a co se v jednotlivých obdobích učí.',
  rvp: {
    3: ['ČJS-5-5-02'],
    4: ['ČJS-5-5-02'],
    5: ['ČJS-5-5-02'],
  },
  ability: 'znalosti',
  banks: { 3: L3, 4: L4, 5: L5 },
});
